compucorp/civihr

hrabsence/CRM/HRAbsence/Form/AbsenceRequest.php
**Issue:**
Dates were not formatted right in date input fields on absence edit page in CiviCRM because the format was statically defined in php code and it was not respecting the format chosen by admin in CiviCRM localization settings.
**Solution:**
Removed static date format and added a logic to change format in php specific date formats.
=> UY-29: Correct input date formats

hrabsence/js/models.js
**Issue:**
When a leave is Rejected/Cancelled, the count is displayed as -1 on list tab under Absences tab of a contact in CiviCRM admin.
**Solution:**
Check if the status is "Cancelled" (numerical value for cancelled leave is 3) and return 0.
=> PCHR-764: Cacelled leave shows 0 now

hrjobcontract/CRM/Hrjobcontract/BAO/HRJobContract.php, hrjobcontract/CRM/Hrjobcontract/Import/Form/MapFieldBaseClass.php, hrjobcontract/CRM/Hrjobcontract/Import/Parser/Api.php
Fixing issues with import of job contracts and roles:
1. Non-existants values for pseudocontant fields cause errors (now they're simply ignored, just like in Civi's importers)
2. Date/time format setting is ignored
3. Mandatory fields aren't correctly marked as mandatory
=> Pchr 784 contracts import

com.civicrm.hrjobroles/CRM/Hrjobroles/BAO/HrJobRoles.php, com.civicrm.hrjobroles/CRM/Hrjobroles/DAO/HrJobRoles.php, com.civicrm.hrjobroles/CRM/Hrjobroles/Upgrader.php, hrjobcontract/CRM/Hrjobcontract/BAO/HRJobContractRevision.php, hrjobcontract/CRM/Hrjobcontract/Import/Form/MapFieldBaseClass.php, hrjobcontract/CRM/Hrjobcontract/Import/Parser.php, hrjobcontract/CRM/Hrjobcontract/Import/Parser/Api.php, hrjobcontract/CRM/Hrjobcontract/Import/Parser/BaseClass.php, hrjobcontract/templates/CRM/Hrjobcontract/Import/Form/MapField.tpl
Job role couldn't be imported before.
1. Changed type of job role's `start_date` and `end_date` from `TIMESTAMP` to `DATETIME`
2. Import now uses HrJobRole instead of the (not used anymore) HrJobContractRole
3. All fields appear on the list of fields to import (before, if there were fields with the same name in different entities, only one of them would appear)
=> PCHR-800 - Matching job contract and job role at import 

hrjobcontract/CRM/Hrjobcontract/Import/EntityHandler/HRJobHealth.php
A fix for a bug introduced in my fix for PCHR-805. Life Insurance Provider ID was not normalised correctly.
=> PCHR-805: Fixed normalisation of Life Insurance Providers

hrjobcontract/CRM/Hrjobcontract/BAO/HRJobDetails.php, hrjobcontract/CRM/Hrjobcontract/ExportImportValuesConverter.php, hrjobcontract/CRM/Hrjobcontract/Import/Parser/Api.php
Fixed some warnings occurring on import of a hrjobcontract. 
Some of them were caused by invalid handling of date fields (too much fields were considered to be date/time, and therefore they were converted to the start of Unix epoch).
Others were caused by invalid array lookups.
=> PCHR-804: Fixed PHP warnings in hrjobcontract import

hrjobcontract/CRM/Hrjobcontract/DAO/HRJobDetails.php, hrjobcontract/CRM/Hrjobcontract/Page/JobContractTab.php, hrjobcontract/CRM/Hrjobcontract/Report/Form/Summary.php, hrjobcontract/CRM/Hrjobcontract/Upgrader.php, hrjobcontract/hrjobcontract.php, hrjobcontract/js/src/job-contract/controllers/contract.js, hrjobcontract/js/src/job-contract/controllers/form/form-general.js, hrjobcontract/views/contractList.html, hrjobcontract/views/contractSummary.html, hrjobcontract/views/modalForm.html
- Adding new 'end_reason' field for HRJobContract Details entity.
- Creating new 'hrjc_contract_end_reason' Option Group containing three Contract End reasons.
- Adding the 'hrjc_contract_end_reason' Option Group to the CiviCRM Administration menu (under Dropdown Options).
Job Contract Summary page (before):
Job Contract Summary page (after) - notice there is a new 'End reason' label under 'Contract Dates' section:
Job Contract Details page (before):
Job Contract Details page (after) - notice there is a new 'Contract End Reason' dropdown field after setting Contract End Date:
=> PCHR-841: Job contract reason for end

hrjobcontract/CRM/Hrjobcontract/BAO/HRJobContract.php, hrjobcontract/CRM/Hrjobcontract/BAO/HRJobDetails.php, hrjobcontract/CRM/Hrjobcontract/Upgrader.php, hrjobcontract/api/v3/HRJobContract.php, hrjobcontract/hrjobcontract.php, hrjobcontract/xml/length_of_service.xml
Implementing 'length of service' Custom Field for Contact entity and creating three custom API calls on HRJobContract CiviCRM entity.
Custom Length of Service API calls:
**Update the Length of Service value(s)**
entity: HRJobContract
action: updatelengthofservice
params: contact_id (optional)
description: automatically updates Length of Service value for specific Contact ID or Length of Service for all Contacts if no 'contact_id' is provided.
example:
```
CRM.api3('HRJobContract', 'updatelengthofservice', {
"sequential": 1,
"contact_id": 49 // optional
}).done(function(result) {
// do something
});
```
// response:
```
{
"is_error":0,
"version":3,
"count":1,
"values":true
}
```
**Calculate the Length of Service for specified Contact**
entity: HRJobContract
action: getlengthofservice …
=> PCHR-846 - Length of Service

hrabsence/CRM/HRAbsence/BAO/HRAbsenceType.php
When you add new absence type with spaces , and then you visit "my absences" or any other contact "absences tab" . the name ( which contains underscores ) of the absence type appears instead of the title  . 
I've changed the logic that retrieve absence types list to use "title" field instead of "name".
=> PCHR-860: Fix bug in my absences to use title instead of name

com.civicrm.hrjobroles/CRM/Hrjobroles/BAO/HrJobRoles.php, com.civicrm.hrjobroles/CRM/Hrjobroles/DAO/HrJobRoles.php, com.civicrm.hrjobroles/CRM/Hrjobroles/Import/Controller.php, com.civicrm.hrjobroles/CRM/Hrjobroles/Import/Field.php, com.civicrm.hrjobroles/CRM/Hrjobroles/Import/Form/DataSource.php, com.civicrm.hrjobroles/CRM/Hrjobroles/Import/Form/MapField.php, com.civicrm.hrjobroles/CRM/Hrjobroles/Import/Form/Preview.php, com.civicrm.hrjobroles/CRM/Hrjobroles/Import/Form/Summary.php, com.civicrm.hrjobroles/CRM/Hrjobroles/Import/Parser.php, com.civicrm.hrjobroles/CRM/Hrjobroles/Import/Parser/HrJobRoles.php, com.civicrm.hrjobroles/hrjobroles.php, com.civicrm.hrjobroles/templates/CRM/Hrjobroles/Import/Form/DataSource.hlp, com.civicrm.hrjobroles/templates/CRM/Hrjobroles/Import/Form/DataSource.tpl, com.civicrm.hrjobroles/templates/CRM/Hrjobroles/Import/Form/MapField.tpl, com.civicrm.hrjobroles/templates/CRM/Hrjobroles/Import/Form/MapTable.tpl, com.civicrm.hrjobroles/templates/CRM/Hrjobroles/Import/Form/Preview.tpl, com.civicrm.hrjobroles/templates/CRM/Hrjobroles/Import/Form/Summary.tpl, com.civicrm.hrjobroles/xml/Menu/hrjobroles.xml, com.civicrm.hrjobroles/xml/Menu/import.xml
Currently all Job Roles related fields are in Import Job Contract page. However, Roles needs to be imported after Job Contracts are created / imported so we need to :
- Create a new "Import Job Roles" page.
- Remove Job Role related fields from "Import Job Contract" page.
- a separate "Import Job Roles" page is created .
- Job Role related fields are removed from "Import Job Contract" page.
--------
**The new "import job roles" page**
**"import job contracts" page after roles related fields have been removed**
=> PCHR-868: import job role page

hrjobcontract/CRM/Hrjobcontract/Import/Parser/Api.php
When importing contracts from "import job contracts" page , the inserted contracts are different from the imported ones.
**sample file**
**when viewing them**
The source of problem was when importing new contracts , the revision IDs  inserted in the database are wrong and refer to previously inserted contracts .
=> PCHR-880: Fix the wrong data inserted in contracts after importing them

hrabsence/api/v3/Activity/Getabsences.php, hrabsence/js/app.js, hrabsence/tests/phpunit/api/v3/ActivityGetAbsencesTest.php
Now, besides the cancelled leaves, the calendar will also not show the rejected ones.
I've updated the Activity.getAbsences API action to handle multiples IDs passed to the status_id parameter. It now supports the != and the "NOT IN" operators.
Bellow are some screenshots showing the results:
Given 3 leave requests (one rejected, one cancelled and one waiting approval)
Before the change, the calendar was showing the rejected request:
After the change, the rejected request is longer displayed:
=> PCHR-851: Removes rejected leaves from the Calendar in Absences tab of the contact

hrjobcontract/CRM/Hrjobcontract/BAO/HRJobContractRevision.php, hrjobcontract/CRM/Hrjobcontract/Import/Form/DataSourceBaseClass.php, hrjobcontract/CRM/Hrjobcontract/Import/Form/MapFieldBaseClass.php, hrjobcontract/CRM/Hrjobcontract/Import/Form/PreviewBaseClass.php, hrjobcontract/CRM/Hrjobcontract/Import/Parser.php, hrjobcontract/CRM/Hrjobcontract/Import/Parser/Api.php, hrjobcontract/templates/CRM/Hrjobcontract/Import/Form/DataSource.tpl
Allowing users to be able to import job contracts revision by introducing a new "import mode" checkbox at "contracts import" page.
=> PCHR-799: import contracts revision

hrjobcontract/CRM/Hrjobcontract/BAO/HRJobContractRevision.php, hrjobcontract/CRM/Hrjobcontract/Upgrader.php
- Adding a new field called 'effective_end_date' to Job Contract Revision entity which keep an end of revision effective date if there is any newer revision.
- Creating Upgrader script which populates 'effective_end_date' values for every existing Job Contract revisions.
- Value of the field is automatically generated while saving Job Contract's revision.
The new field is designed mostly to handle Reports requirements but it can also be used with any other cases in the future.
=> PCHR-865 - Implementing 'effective_end_date' revision field

com.civicrm.hrjobroles/CRM/Hrjobroles/BAO/HrJobRoles.php, com.civicrm.hrjobroles/CRM/Hrjobroles/Import/Parser/HrJobRoles.php, hrjobcontract/CRM/Hrjobcontract/BAO/HRJobContract.php, hrjobcontract/CRM/Hrjobcontract/BAO/HRJobHealth.php, hrjobcontract/CRM/Hrjobcontract/Import/Parser/Api.php, hrjobcontract/CRM/Hrjobcontract/Import/Parser/BaseClass.php, hrjobcontract/CRM/Hrjobcontract/SelectValues.php
When importing contracts , many of  validation rules are incorrect because they are relying on field type attribute from DAO file. also i fixed  other issues in contract import such as the error page that appear if the health or life insurance provider field is empty.
=> PCHR-892: Cleaning contracts import validation

contactsummary/contactsummary.php, contactsummary/js/src/contact-summary.js, hrjobcontract/templates/CRM/Contact/Page/View/Summary.tpl
Contact "Personal Details" tab is the first and default tab in contact summary page but "Contact Summary" tab is needed to be the first instead.
Civicrm Core files are altered and the patch submitted to Civi-Core both master and 4.5 versions (https://issues.civicrm.org/jira/browse/CRM-18390)  Also currently **jobcontract** extension override the summary page template file . So this file is used  **hrjobcontract/templates/CRM/Contact/Page/View/Summary.tpl**  as a template file instead of this **CRM/Contact/Page/View/Summary.tpl** which means that i have to remove the hardcoded summary tab from their too.
- CiviCRM Jira : https://issues.civicrm.org/jira/browse/CRM-18390
- CiviCore patch (Master) : https://github.com/civicrm/civicrm-core/pull/8110https://github.com/civicrm/civicrm-core/pull/8 …
=> PCHR-618: Set contact summary tab to be the default one

com.civicrm.hrjobroles/CRM/Hrjobroles/DAO/HrJobRoles.php, com.civicrm.hrjobroles/CRM/Hrjobroles/Import/Parser/HrJobRoles.php, com.civicrm.hrjobroles/xml/Menu/import.xml, com.civicrm.hrjobroles/xml/schema/CRM/Hrjobroles/HrJobRoles.xml
The following errors are reported by QA while trying to import job roles :
1- Region not updated when value is valid, error not thrown on value mismatch.
2- Cost center => Type and amount not displayed on front end.
3- Cost center => if percent and absolute amount where both exist in the import file No error shown saying either one should be removed.
4- Funder => Type and amount not displayed on front end.
5- Funder => if percent and absolute about where both exist in the import file No error shown saying either one should be removed.
Also here some typos corrected :
1- start_date in import match select box should be => "Start Date"
2- end_date in import match select box  should be => "End Date"
3- job id in import match select box  should be=> "Job ID"
4- import page title  should be …
=> PCHR-876: Fix job roles import validation problems

com.civicrm.hrjobroles/CRM/Hrjobroles/BAO/Query.php, com.civicrm.hrjobroles/CRM/Hrjobroles/DAO/HrJobRoles.php, com.civicrm.hrjobroles/hrjobroles.php, com.civicrm.hrjobroles/xml/schema/CRM/Hrjobroles/HrJobRoles.xml, hrjobcontract/CRM/Hrjobcontract/BAO/Query.php
The Contract ID and the Job Role fields weren't available to be included in the file exported from the Advanced Search
The fields were configured to be available to the exported file. The Job Role fields were prefixed with 'Job Role' so they could be easily found on the list:
=> PCHR-891: Complete Job Contract and Role Export Feature

uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php
The following permissions were added:
- Access Leave and Absences CiviHR (Dashboard)
- Administer Leave and Absences
Here you can see the permissions available on Drupal:
=> PCHR-938: Add Leave & Absences CiviHR permissions

hrjobcontract/CRM/Hrjobcontract/Upgrader.php, hrjobcontract/hrjobcontract.php
- Creating new Upgrader function which installs CiviCRM scheduled daily Job upgrading Length of Service values for each Contact.
- Including the new scheduled job into extension's enable/disable/uninstall actions.
After executing the upgrade the Scheduled Job should be visible and active on index.php?q=civicrm/admin/job&reset=1 page.
=> PCHR-978 - creating Upgrader function which installs scheduled job and updating enable/disable/uninstall extension functions.

com.civicrm.hrjobroles/CRM/Hrjobroles/BAO/HrJobRoles.php, hrjobcontract/CRM/Hrjobcontract/BAO/HRJobContract.php, hrjobcontract/CRM/Hrjobcontract/BAO/HRJobDetails.php, hrjobcontract/CRM/Hrjobcontract/Dedupe/Merger.php, hrjobcontract/CRM/Hrjobcontract/Form/Merge.php, hrjobcontract/hrjobcontract.php, hrjobcontract/templates/CRM/Hrjobcontract/Form/Merge.hlp, hrjobcontract/templates/CRM/Hrjobcontract/Form/Merge.tpl, hrjobcontract/xml/Menu/hrjobcontract.xml
When merging duplicate contacts , Job contracts checkbox was appear under "move related" and if the checkbox is checked then all contracts and job roles will move to the main contact. The problem is there is a role to have only one active contract at a time (PCHR-869) and merging all contracts will violate this rule .
A list of all job contracts and roles now appear  allow the user select which one to keep after the merge    and which to remove , also in case there is a conflicting contracts between the two contacts then an error at the top of the page will be shown describing which contracts conflict with main contact contracts along with contracts IDs before the merge . also if a role selected but the assosiatve contract is not selected for the merge the merge will fail and an error …
=> PCHR-905: Merge contracts and roles when merging contacts

hrjobcontract/xml/Menu/import.xml
Changing Import job contracts page title from "JOB import" to "Import Job Contracts"
=> PCHR-982: Rename job contract import page title to 'Import Job Contracts'

contactaccessrights/CRM/Contactaccessrights/Form/ManageRights.php
in contacts manage access popup , the -select- option was appearing in both region and location select boxes and you can even choose it.
the -select- option was removed from options list array.
=> PCHR-995 : Remove -select- option from regions and locations select boxes

uk.co.compucorp.civicrm.hrleaveandabsences/sql/auto_install.sql
These are the default leave types that will be available right after the
installation of the extension
=> PCHR-904: Create the default leave types

com.civicrm.hrjobroles/js/src/job-roles/controllers/hr-job-roles-controller.js, com.civicrm.hrjobroles/js/src/job-roles/services/hr-job-roles-service.js, com.civicrm.hrjobroles/js/test/controllers/hr-job-roles-controller/hr-job-roles-controller_test.js, com.civicrm.hrjobroles/views/include/add_new_role.html
Now the "action" column is hidden when the values are being edited, and the "Cost Centre" are ordered according to the order chosen in the options screen.
Hiding column:
Ordering the values:
=> PCHR-857-Job role screen ui improvements

contactaccessrights/contactaccessrights.php, contactaccessrights/xml/Menu/contactaccessrights.xml
On contact summary page , anybody can see "**manage roles and teams**" link in action menu 
and if it clicked the following modal will appear to allow the user to manage that contact roles and teams :
or even by using the link directly : <civicrm URL>/admin/contact-access-rights/manage?&cid=CONTACT_ID a similer page will opened. 
But this is not correct behavior  , only specific users should be allowed to see the screens above .
A new permission created named "administer roles and teams" and only users with that permission are allowed to see the action bar menu or even access the page directly from the browser. Also this permission is set to be enabled by default for "civihr_admin" and "administer" Drupal roles.
https://github.com/compucorp/civihr-employee-portal/pull/115
=> PCHR-997: new permission - manage roles and Teams

com.civicrm.hrjobroles/CRM/Hrjobroles/BAO/Query.php
**Problem**: The where clause for those fields was being built with the
'hrjobroles' table alias, which isn't used anymore.
**Solution**: Replace the table alias with the actual table name
=> PCHR-889: Fix search for Job Role start and end dates

com.civicrm.hrjobroles/views/include/job_role_panel.html
For contacts with existing data, on both "Cost Centres" and "Funding" tabs, aligned the "action button" to the left directly under the column label, and ordered the "Cost Centres" options according to the configured ordering.
=> PCHR-857: UI adjustments for existing data

hrjobcontract/CRM/Hrjobcontract/Upgrader.php
There was still 'Job_Summary' data migrating from old HRJob extension when installing new HRJobContract. It was causing an error during buildkit installation when using current 'develop' branch. We don't use Job Summary data anymore so the data migration is now removed from the installer.
=> PCHR-1009 - Removing old Job_Summary data migration when installing the extension.

hrjobcontract/CRM/Hrjobcontract/DAO/HRJobDetails.php, hrjobcontract/CRM/Hrjobcontract/DAO/HRJobHealth.php, hrjobcontract/CRM/Hrjobcontract/DAO/HRJobPay.php, hrjobcontract/CRM/Hrjobcontract/DAO/HRJobRole.php
The CRM_Hrjobcontract_BAO_Query class relies on the 'where' property
of the fields to build the field list of the SELECT clause of the query used
to export contacts. Some of the Contracts fields didn't have this property
and when one of it was selected to be included in the exported
file, the built SQL query ended up incomplete giving a DB Syntax error.
=> PCHR-891: Fix Job Contracts fields configuration for export

hrjobcontract/CRM/Hrjobcontract/BAO/Query.php, hrjobcontract/templates/CRM/Hrjobcontract/Form/Search/Criteria/JobContract.tpl
These fields are legacy and will be completely removed from hrjobcontract on a
future PR. For now, we just don't allow they to be searched or included in a export.
=> PCHR-891: Remove contracts legacy fields

uk.co.compucorp.civicrm.hrleaveandabsences/sql/auto_install.sql, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/WorkDayTest.php
The pattern is created during the extension's installation.
The small change in WorkDayTest.php is just a removal of
a small debug code, which didn't deserve a commit for itself.
=> PCHR-945: Create the default Work Pattern

.editorconfig
Adding a [.editorconfig](http://editorconfig.org/) file to standardize coding style for all the project's developers/contributors
=> PCHR-1022: Adding .editorconfig file to repo

hrjobcontract/CRM/Contact/Form/Inline/CustomData.php, hrjobcontract/templates/CRM/Contact/Page/View/Summary.tpl
**hrjobcontract** extension override the following files : 
hrjobcontract/CRM/Contact/Form/Inline/CustomData.php
hrjobcontract/templates/CRM/Contact/Page/View/Summary.tpl
which were taken form civicrm 4.5 , i just updated them to work with 4.7 which resulted in fixing this error :
**User warning: Smarty error: unable to read resource: "CRM/common/wysiwyg.tpl"**
when viewing contact summary page since **wysiwyg.tpl** is not exist anymore in 4.7.
=> PCHR-921: fix contact page warnings

uk.co.compucorp.civicrm.hrnavigation/CRM/Core/BAO/Navigation.php
We have this error appearing on the civihr pages:
```
Notice: Undefined offset: 1 in CRM_Core_BAO_Navigation::createNavigation() (line 656 of /var/www/civicrm-buildkit/build/hr16/sites/all/modules/civicrm/CRM/Core/BAO/Navigation.php).
```
This started to happen after the work PCHR-343 was merged, which changes the CiviHR homepage from `civicrm/dashboard?reset=1` to `civicrm/tasksassignments/dashboard#/tasks` (see [this file](https://github.com/compucorp/civihr-tasks-assignments/blob/develop/uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/DashboardSwitcher.php)), basically making T&A the CiviHR dashboard
The hrnavigation code was still tring to split the url using the `?` querystring delimiter, but given that the T&A url doesn't have one, the offset notice was thrown
Simply …
=> PCHR-921: Remove warnings on Contact page

hrrecruitment/CRM/HRRecruitment/Form/Application.php, hrsampledata/GenerateHRData.php
Using CRM_Case_BAO_CaseContact class if CRM_Case_BAO_Case::addCaseToContact method is not available.
CRM_Case_BAO_CaseContact is a new class which comes in CiviCRM 4.7 while CRM_Case_BAO_Case::addCaseToContact is CiviCRM 4.5 / 4.6 method which we were originally using when developing the extensions.
=> PCHR-1043 - missing CRM_Case_BAO_Case::addCaseToContact() method

com.civicrm.hrjobroles/CRM/Hrjobroles/Import/Controller.php, com.civicrm.hrjobroles/CRM/Hrjobroles/Import/Field.php, com.civicrm.hrjobroles/CRM/Hrjobroles/Import/Form/DataSource.php, com.civicrm.hrjobroles/CRM/Hrjobroles/Import/Form/MapField.php, com.civicrm.hrjobroles/CRM/Hrjobroles/Import/Form/Preview.php, com.civicrm.hrjobroles/CRM/Hrjobroles/Import/Form/Summary.php, com.civicrm.hrjobroles/CRM/Hrjobroles/Import/Parser/HrJobRoles.php, com.civicrm.hrjobroles/templates/CRM/Hrjobroles/Import/Form/DataSource.tpl, com.civicrm.hrjobroles/templates/CRM/Hrjobroles/Import/Form/MapField.tpl, com.civicrm.hrjobroles/templates/CRM/Hrjobroles/Import/Form/MapTable.tpl, com.civicrm.hrjobroles/templates/CRM/Hrjobroles/Import/Form/Preview.tpl, com.civicrm.hrjobroles/templates/CRM/Hrjobroles/Import/Form/Summary.tpl
After migrating to civicrm 4.7 , The job roles page is no longer opening and through an HTTP 500 error page . The problem was in this file :
**com.civicrm.hrjobroles/CRM/Hrjobroles/Import/Form/DataSource.php**
Specifically in this line :
**CRM_Core_Config_Defaults::formatUnitSize(ini_get('post_max_size'), TRUE);** 
But since **CRM_Core_Config_Defaults** class is no longer exist in 4.7 the code was failing and the error page appear. 
I modified  the DataSource.php Form to extend the core class CRM_Import_Form_DataSource instead of CRM_Core_Form , Where the implementation is a little bit diffrent and using :
**CRM_Utils_Number::formatUnitSize(ini_get('post_max_size'), TRUE);** 
Instead of **CRM_Core_Config_Defaults::formatUnitSize(ini_get('post_max_size'), TRUE);**  .
I also done some …
=> PCHR-1068: Fix import job role issues 4.7 migration

uk.co.compucorp.civicrm.appraisals/CRM/Appraisals/Import/Form/DataSourceBaseClass.php, uk.co.compucorp.civicrm.appraisals/templates/CRM/Appraisals/Import/Form/DataSource.tpl, uk.co.compucorp.civicrm.appraisals/templates/CRM/Appraisals/Import/Form/MapField.tpl, uk.co.compucorp.civicrm.appraisals/templates/CRM/Appraisals/Import/Form/Preview.tpl, uk.co.compucorp.civicrm.appraisals/templates/CRM/Appraisals/Import/Form/Summary.tpl
After migrating to civicrm 4.7 , The  appraisals import page is no longer opening and   this exception is thrown 
`Cannot read unrecognized property CRM_Core_Config::$maxImportFileSize.`
The problem was in this file :
**uk.co.compucorp.appraisals/CRM/Import/Form/DataSourceBaseClass.php**
Specifically in these lines :
`    if ($config->maxImportFileSize >= 8388608) {
$uploadFileSize = 8388608;
}
else {
$uploadFileSize = $config->maxImportFileSize;
}`
But since **CRM_Core_Config** is no longer have this property `maxImportFileSize` , The error is thrown.
I modified  the DataSourceBaseClass.php class to to use this formula instead ( which is the same used in the core import files ) :
`$uploadFileSize = CRM_Utils_Number::formatUnitSize($config->maxFileSize . 'm', TRUE);
$uploadSize = …
=> PCHR-1069: Fix import appraisals issues after 4.7 migration

hrrecruitment/CRM/HRRecruitment/Form/HRVacancy.php, hrrecruitment/templates/CRM/HRRecruitment/Form/HRVacancy.tpl
After 4.7 migration , If you tried to create a new vacancy or vacancy template the page will not open and an HTTP 500 error page will appear instead. The problem was due to the following :
1- the usage of addWysiwyg() which is removed from 4.7 .
2- `$this->addSelect('status_id', array(), TRUE);` was not passing the entity name in parameters and addSelect() method in QuickForm class require an entity name to be able to fetch select list options .
1- addWysiwyg() get replaced with add('wysiwyg', ... ) which is the new way to add wysiwyg editor to the form. 
2- for addSelect issue and since there is a new method in QuickForm called getDefaultEntity()  (which is required to be implemented in any class that extend CRM_CORE_FORM ) I just let the method to return the default entity name  which …
=> PCHR-1072: Fix vancancy form issues after 4.7 migration

doc/DEVELOP.md, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php, uk.co.compucorp.civicrm.hrleaveandabsences/phpunit.xml.dist, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsenceTypeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/NotificationReceiverTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/WorkDayTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/WorkPatternTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/WorkWeekTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/WebTest/AbsenceType/FormTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/WebTest/WorkPattern/FormTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/bootstrap.php
After moving the development to CiviCRM 4.7 some errors were found on this extension:
**Problem**: When adding or editing an Absence Type, the following happened: Exception: "Cannot determine default entity. CRM_HRLeaveAndAbsences_Form_AbsenceType should implement getDefaultEntity()."
**Solution**: Added the getDefaultEntity() to the CRM_HRLeaveAndAbsences_Form_AbsenceType class
**Problems**:
1. When editing an existing Work Pattern, a black page was displayed and the server response had the status code of 500. The webserver error log had the message: PHP Fatal error: Class name must be a valid object or a string in /vagrant/hr16/sites/all/modules/civicrm/Civi/API/SelectQuery.php on line 99.
2. Trying to disable a Work Pattern or set it as default, by clicking on the actions of the list …
=> PCHR-1119: Fix L&A errors on CiviCRM 4.7

hrjobcontract/CRM/Hrjobcontract/BAO/Query.php
The JOIN clause that joined the contact table with the contract table would match every
contract for the given contact, even the deleted ones. Since the job roles are related to the
contract, this would also affect job roles searchs. A search for it could result in matches for
roles related to deleted contracts.
=> PCHR-889: Exclude deleted contracts from the query of the advanced search

hrcase/hrcase.php
The following error interrupts the install process of the {{hr16}} type build via buildkit:
`WD php: CRM_Core_Exception: Invalid Entity Filter in CRM_Core_BAO_CustomGroup::validateSubTypeByEntity() [error]`
The error appears when installing CiviHR via the following command:
**civibuild create hr163 --type hr16 --civi-ver 4.7.7 --url http://localhost:8124**
What happen is at the point where the builkit is about to enable **entity api extenision** the error is thrown ... This is what happen that cause the installation to fail :
1- **civicrm-drupal** module and specifically  in **civicrm.views.inc** file, its take advantage of **CRM_Core_BAO_CustomGroup::getTree** method which its implementation changed in civicrm 4.7.7+ due to some security updates.
2- due to these updates the following …
=> PCHR-1116: Error installing hr16 with civicrm 4.7.7

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/AbsencePeriod.php, uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/AbsencePeriod.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/xml/Menu/hrleaveandabsences.xml
This is how the list looks like:
The list contains only four fields:
- Title
- Start Date
- End Date
- Order
When there's more than one period, their order can be changed,
by clicking on the arrow on the Order column, to move it up or down.
The Start and End date columns use the crmDate smarty filter to
make sure the dates follow the default date format selected in CiviCRM
settings.
=> PCHR-953: Create Absence Periods list page

hrstaffdir/xml/auto_install.xml
When trying to install org.civicrm.hrstaffdir extension the following error is thrown :
**A fatal error was triggered: Could not find custom field for custom.civicrm_value_jobcontract_summary_10.final_termination_date_57**
The issue is when trying to install the extension , Its run this file  (**auto_install.xml**) which is still use 
**Final Termination Date** which is removed in this ticket  PCHR-774 .
I replaced **final termination date** with **job contract end date** .
=> PCHR-1150: installing org.civicrm.hrstaffdir throwing an error

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsencePeriod.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/AbsencePeriod.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/AbsencePeriod.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Validator/Date.php, uk.co.compucorp.civicrm.hrleaveandabsences/js/hrleaveandabsences.form.absenceperiod.js, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/AbsencePeriod.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/AbsencePeriod.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsencePeriodTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Validator/DateTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/WebTest/AbsencePeriod/FormTest.php
This is new Absence Period form for the Leaves and Absences extension. It's a quite simple form, with just 4 fields. All of them are mandatory. When adding a new Absence Period, the start date is automatically filled with the most recent date available, which can be:
- The current date, if there's no other Absence Period
- The maximum end date among all the existing Absence Periods + 1 day
The order number is also automatically filled following these rules:
- It's value is 1 if there's no other Absence Period
- It's value is the maximum weight among all the existing Absence Period + 1
This is how the form looks like:
=> PCHR-954: Create the Absence Period form

com.civicrm.hrjobroles/CRM/Hrjobroles/BAO/Query.php, com.civicrm.hrjobroles/CRM/Hrjobroles/DAO/HrJobRoles.php
When searching for Job Role Regions, the search values where not displayed on the
search description. For example, when searching for the "South America" region, the user would see this:
instead, they should see this:
This was happening because instead of the Region Options, we were passing the
list of Department Options to the method that builds the description making impossible
to get the correct name of the selected region.
It was also made an small change to the CRM_Hrjobroles_BAO_Query class to remove a dependency on the CRM_Hrjobcontracts_BAO_HrJobRole BAO to load the options to the location, department, region and level type fields.
=> PCHR-889: Fix the search description for Job Roles regions on the Adv. Search

hrcase/hrcase.php
When trying to install/enable **hrcase** extension after  enabling/installing **uk.co.compucorp.civicrm.tasksassignment** extension the following error is thrown :
`API error: DB Error: already exists`
And the installation/enabling process for **hrcase** fail. This also affect installing civihr via the buildkit as described in the ticket description.
:computer: Technically speaking , The error appear due to the following :
1- When installing **uk.co.compucorp.civicrm.tasksassignment* extension it is create a bunch of case types two of these case types have the following name ( **exiting** , **joining** ).
2- when installing **hrcase** assignment extension after it ...  it also try to create a bunch of case types and two of these also have similar names ( **exiting** , **joining** ).
3- …
=> PCHR-1151: Unset already exist case types in hrcase extenison

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsencePeriod.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/PublicHoliday.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsencePeriodTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/PublicHolidayTest.php
The number of Working Days is given by:
Number of days in a Period - Number of weekend days - public holidays
If a public holiday falls on a weekend, it's not counted twice.
In order to get the number of public holidays between two dates, I added the
getNumberOfPublicHolidaysForPeriod method to the PublicHoliday BAO.
=> PCHR-1109: Add the getNumberOfWorkingDays method to the AbsencePeriod

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsencePeriod.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsencePeriodTest.php
This method returns the number of days to work on an AbsencePeriod between the
given start and end dates.
This method doesn't count days outside the AbsencePeriod. Meaning that, If the given
start date is less than the AbsencePeriod start date, then the AbsencePeriod's start
date will be used. If the given end date is greater than AbsencePeriod end date,
then the AbsencePeriod's end date will be used.
=> PCHR-1110: Add the getNumberOfWorkingDaysToWork to the AbsencePeriod class

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/PublicHoliday.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/PublicHoliday.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/PublicHoliday.php, uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/PublicHoliday.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/PublicHolidayTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/xml/Menu/hrleaveandabsences.xml
Creating Public Holidays list page available under civicrm/admin/leaveandabsences/public_holidays?action=browse&reset=1
The page lists all Public Holidays with Title, Date, Enabled/Disabled fields and contains Edit, Enable/Disable and Delete actions. Edit action is not implemented as it's covered by different task.
At the bottom there is a button for creating a new Public Holiday (not implemented, covered by different task).
Public Holiday list page:
Delete action confirmation:
Disable action confirmation:
=> PCHR-1046 - Creating Public Holiday list page

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/PublicHoliday.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/PublicHoliday.php, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/PublicHoliday.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/PublicHoliday.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/WebTest/PublicHoliday/FormTest.php
Creating Public Holiday Form which allows to create / edit Public Holidays. It contains 'title', 'date' (with datepicker) and 'is_active' fields. Title and date are required fields. The form also allows to delete the Public Holiday which we are editing.
Creating Web tests for the Form.
Public Holiday Form
Public Holiday Form validation
=> PCHR-1047 - Creating Public Holiday Form, templates and Web test.

hrui/hrui.php
The issue was causing civicrm to reset the "Default location type". The line  of code responsible for this has been commented, but I am still not sure why was this done at first place.
=> PCHR-1146 : Commenting out the line causing "Default location type" to reset. 

com.civicrm.hrjobroles/hrjobroles.php, contactsummary/contactsummary.php, hrabsence/hrabsence.php, hrjobcontract/hrjobcontract.php, hrui/hrui.php, uk.co.compucorp.civicrm.appraisals/appraisals.php
Related PR https://github.com/compucorp/civihr-tasks-assignments/pull/63
-------------------------------------------------------------------------------
Changing contact tabs order to make more sense to the user , They are order according to this list :
* Summary
* Job contract
* Job role
* Personal details
* Absences
* Appraisals
* Assignments
* Tasks
* Documents
* Identification
* Immigration
* Emergency contacts
* Relationships ( the title changed to Managers )
* Bank details
* Career History
* Medical and Disability
* Qualifications
* Notes
* Groups
* Change log
Also Relationships tab title changed to "Managers" .
The change of order performed by playing with weight property for each tab and between each tab  and the next in order the weight is increased by 10 to give more space in …
=> PCHR-1139: Change contact tabs order

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/sql/auto_install.sql, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/AbsenceType.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsenceTypeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/WebTest/AbsenceType/FormTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/xml/schema/CRM/HRLeaveAndAbsences/AbsenceType.xml
To make things simpler on the entitlement calculation, it was decided to remove
these fields from the AbsenceType. Now, the expiration of carry forward days will
only be calculated in terms of duration.
This is how the Absence Type form was before the change:
And this is how it looks like after the change:
=> PCHR-1210: Remove the carry forward expiration date from Absence Type

hrjobcontract/CRM/Hrjobcontract/BAO/HRJobContract.php, hrjobcontract/CRM/Hrjobcontract/Upgrader.php, hrjobcontract/api/v3/HRJobContract.php, hrjobcontract/phpunit.xml.dist, hrjobcontract/tests/phpunit/CRM/Hrjobcontract/BAO/HRJobContractTest.php, hrjobcontract/tests/phpunit/HRJobContractTestTrait.php, hrjobcontract/tests/phpunit/api/v3/HRJobContractTest.php, hrjobcontract/tests/phpunit/bootstrap.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/EntitlementCalculation.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/EntitlementCalculator.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/ManageEntitlements.php, uk.co.compucorp.civicrm.hrleaveandabsences/css/hrleaveandabsences.css, uk.co.compucorp.civicrm.hrleaveandabsences/js/hrleaveandabsences.form.manage_entitlements.js, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/ManageEntitlements.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/EntitlementCalculationTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/EntitlementCalculatorTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/xml/Menu/hrleaveandabsences.xml
This adds the new Entitlement Calculation page. At this point we only have the basic structure for the page, which is a simple list displaying all the calculated entitlements for active contracts on a specific AbsencePeriod.
The page is available at: **civicrm/admin/leaveandabsences/periods/manage_entitlements** and it has a required parameter named **id**, which is the ID of the AbsencePeriod to calculated the entitlements for. It also accepts a **cid** parameter containing Contracts IDs. When this is present, the list will only display calculations for Contracts with the given IDs.
This is how the page looks like:
Next to each proposed entitlement, there is a small set of controls that allow the user to override that value (for now it only shows/hides the text field, nothing is saved …
=> PCHR-1039: Entitlement Calculation page

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/EntitlementCalculation.php, uk.co.compucorp.civicrm.hrleaveandabsences/js/hrleaveandabsences.form.manage_entitlements.js, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/ManageEntitlements.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/EntitlementCalculationTest.php
When the user clicks on a row of the entitlement calculation list, a popup should be
displayed containing the description of how the proposed entitlement was calculated:
=> PCHR-1086: Add a popup to display the details about the entitlement calculation

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/EntitlementCalculator.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/ManageEntitlements.php, uk.co.compucorp.civicrm.hrleaveandabsences/css/hrleaveandabsences.css, uk.co.compucorp.civicrm.hrleaveandabsences/js/hrleaveandabsences.form.manage_entitlements.js, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/ManageEntitlements.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsenceTypeTest.php
Two filters were added to the entitlement calculation list:
This filter allows the user to select if they want to see only overridden entitlements, only non overridden or both:
This filter allows the user to select which absence types they want to see the entitlements for:
=> PCHR-1087: Add entitlement calculation list filters

com.civicrm.hrjobroles/CRM/Hrjobroles/BAO/HrJobRoles.php, com.civicrm.hrjobroles/phpunit.xml.dist, com.civicrm.hrjobroles/tests/phpunit/CRM/Hrjobroles/BAO/HrJobRolesTest.php, com.civicrm.hrjobroles/tests/phpunit/HrJobRolesTestTrait.php, com.civicrm.hrjobroles/tests/phpunit/bootstrap.php, hrjobcontract/CRM/Hrjobcontract/BAO/HRJobContract.php, hrjobcontract/tests/phpunit/CRM/Hrjobcontract/BAO/HRJobContractTest.php, hrjobcontract/tests/phpunit/HRJobContractTestTrait.php, hrui/CRM/HRUI/Helper.php, hrui/hrui.php, hrui/phpunit.xml.dist, hrui/tests/phpunit/CRM/HRUI/HelperTest.php, hrui/tests/phpunit/HRUITrait.php, hrui/tests/phpunit/bootstrap.php
For the New summary page UI , The following information have to be viewed on the page :
1- Position and Normal Place of Work comes from Contract (people should have only 1 active contract) .
2- Department comes from Role. Could be multiple, so in that case separate by comma. (e.g. Finance, Marketing) .
3- Manager should come from Relationships > Line Manager is .
So I fetched them inside hrui_civicrm_alterContent so they are available to the front end developer to display them on the page and style them.
=> PCHR-1193: fetch needed data for new summary page UI

hrui/css/hrui.css
Implemented Vertical Tabs for Contact Summary Page
CSS has been taken from SimplyCivi 
[https://github.com/rayogram/SimplyCivi/blob/master/css/contact-tabs.css](url)
Before:
After:
=> PCHR-1190: Implemented Vertical Tabs for Contact Summary Page

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/ManageEntitlements.php, uk.co.compucorp.civicrm.hrleaveandabsences/css/hrleaveandabsences.css, uk.co.compucorp.civicrm.hrleaveandabsences/js/hrleaveandabsences.form.manage_entitlements.js, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/ManageEntitlements.tpl
This is a link at the top right side of the entitlement calculations list and, when clicked,
exports a CSV file with exactly the same information displayed on the screen.
As we need to export the data on the screen, even if the user has overridden some of
the entitlements, the file is generated by submitting the form so we can include the proper
values in the file.
This is where the link is located:
And this is how the CSV file looks like:
=> PCHR-1088: Add the "Export to CSV" action to the Entitlement Calculations page

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/ManageEntitlements.php, uk.co.compucorp.civicrm.hrleaveandabsences/css/hrleaveandabsences.css, uk.co.compucorp.civicrm.hrleaveandabsences/js/hrleaveandabsences.form.manage_entitlements.js, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/ManageEntitlements.tpl
These buttons are inside the "New Proposed Entitlement" header, and work as follow:
**Add 1 Day button**: Adds an extra day to every entitlement on the list and marks the
entitlement as overridden.
**Copy to All**: Copy the value of the first proposed entitlement on the list to all others and
marks the entitlements as overriden.
=> PCHR-1089: Add the "Copy to All" and "Add 1 Day" buttons

com.civicrm.hrjobroles/js/src/job-roles/services/date-validation.js, com.civicrm.hrjobroles/js/test/controllers/hr-job-roles-controller/hr-job-roles-controller_test.js
When wasn't informed the contract's end date it wasn't validated if the start date is lower than the contract's start date, the solution was remove the `checkIfStartIsLowerThanContractStart` method from the end's statement.
**Before**
**After**
=> PCHR-875: Fix contract's start date validation

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/ManageEntitlements.php, uk.co.compucorp.civicrm.hrleaveandabsences/css/hrleaveandabsences.css, uk.co.compucorp.civicrm.hrleaveandabsences/js/hrleaveandabsences.form.manage_entitlements.js, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/ManageEntitlements.tpl
There's a new action available on the "Comment" column of the entitlement
calculations list. By clicking it, the user is presented with a dialog box where they
can add/edit a comment to describe the the how that entitlement calculation was made.
Here is how it works:
=> PCHR-1090: Add a dialog box to allow the user to add/edit an entitlement comment

com.civicrm.hrjobroles/views/include/job_role_panel.html
The is-open attribute on the calendar directives of the "edit role" panel had a value set to an expression (`is-open="!!(CalendarShow.start_date)"`), that caused a [non-assignable expression](https://docs.angularjs.org/error/$compile/nonassign?p0=isOpen(%27start_date%27)&p1=isOpen&p2=uibDatepickerPopup) error.
Simply assigning the value of the `CalendarShow.{x}` property  instead of the "force to bool" expression solved the problem
=> PCHR-1105: Fix $compile "non-assignable expression" errors for calendars

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/ManageEntitlements.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/AbsencePeriod.php, uk.co.compucorp.civicrm.hrleaveandabsences/css/hrleaveandabsences.css, uk.co.compucorp.civicrm.hrleaveandabsences/js/hrleaveandabsences.js, uk.co.compucorp.civicrm.hrleaveandabsences/js/hrleaveandabsences.list.absenceperiod.js, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/ManageEntitlements.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/AbsencePeriod.tpl
From the Absence Periods list is now possible to go to the Entitlement Calculation page to manage the staff entitlements. To do this, there's a new action available to every period on the list, called "Manage Entitlements". By clicking on it, the user will get a confirmation message and, if they confirm, they will be redirect to the calculations page.
This is the action and the confirmation message:
=> PCHR-1114: Add the "Manage entitlements" action to the Absence Periods list

hrjobcontract/hrjobcontract.php
After searching for contacts , a list of (undefined index) warnings notices appear in the search page :
the source of the problem was in hrjobcontract_civicrm_searchColumns Hook implementation in job contract extension where the search result rows are not checked if they contain the location field  (hrjobcontract_details_location) which came from the contact current job contract , so in case some contacts in the search results don't have active job contract the notice will appear for everyone who doesn't have a contract.
I fixed the problem by adding  checks on $row['hrjobcontract_details_location'] so it doesn't through a notice if it is not exist.
=> PCHR-1225: fix contact search results page warnings

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsencePeriod.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/PublicHoliday.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/PublicHoliday.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsencePeriodTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/PublicHolidayTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/PublicHolidayTest.php
This new API action basically returns the value of the (also new)
PublicHoliday.getNumberOfPublicHolidaysForCurrentPeriod method. The API can
accept a single paramenter, named "exclude_weekends" that, when true, will not
count Public Holidays that falls on a weekend.
Returning the number of public holidays including those that fall on a weekend
```php
$result = civicrm_api3('PublicHoliday', 'getcountforcurrentperiod');
```
Returning the number of public holidays excluding those that fall on a weekend:
```php
$result = civicrm_api3('PublicHoliday', 'getcountforcurrentperiod', [
'exclude_weekends' => 1
]);
```
As the default **getcount** action of the CiviCRM API, this action returns an integer.
=> PCHR-1107: Add the getCountForCurrentPeriod action to the PublicHoliday API

hrjobcontract/CRM/Hrjobcontract/Upgrader.php, hrjobcontract/hrjobcontract.php
When trying to merge contacts on civihr 1.6 ( with civicrm 4.7.7 ) this error appear :
This is a civicrm 4.7.7 problem and not related to civihr that it doesn't create "**Contact Deleted by Merge**" activity type automatically when installed via the buildkit which is used in the core files to create an new activity after the merge get complete .
I added a new code to hrjobcontract_civicrm_install hook to check for existence of "**Contact Deleted by Merge** activity type and in case it doesn't exists it will be created. and for existing installations I've added an upgrader method to do the same thing. 
Note : this problem is solved in civicrm 4.7.8+ and "**Contact Deleted by Merge**" is created automatically.
=> PCHR-1070: Fix contact merge on civicrm 4.7.7

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/Task/ManageEntitlements.php, uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/Task/ManageEntitlements.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/WebTest/ManageEntitlements/AdvancedSearchTaskTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/xml/Menu/hrleaveandabsences.xml
This commit adds a new "Manage leave entitlement" to the Advanced Search. When
the user selects this action, they're redirected to a form containing a dropdown
listing all Absence Period, so they can select to which one they want to manage
the entitlements to. After selecting the period, we should redirect to the Manage
Entitlements page (with the selected Period ID and the ID of the contacts on the
search form).
Here you can see the new Task in action:
=> PCHR-1065: Add the "Manage leave entitlement" task to the Advanced Search

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsenceTypeTest.php
Trying to update an existing Absence Type where add_public_holiday_to_entitlement
was checked, was throwing the error: There is already one Absence Type where "Must
staff take public holiday as leave" is selected.
That happened because the validation rule that checks for existing Absence Types
with add_public_holiday_to_entitlement == 1 wasn't taking into account if the existing
type was the one being updated. I fixed this, by adding a "id <> $this->id" condition  
to the validation query, so it won't consider the type being updated as the existing one.
=> PCHR-1066: Allow AbsenceType with add_public_holiday_to_entitlement to be updated

hrui/hrui.php
When creating a new contact, the location type of the first phone number 
is automatically set to the default location type, but this doesn't happen to
the second number (Mobile), which end up with another location type by default.
We use the buildForm hook to alter the form in order to change the default
value of the location type field to the default location type. This is done only
if the phone number empty, so to avoid overwrite any previously selected
value.
Having "Work" set as the default Location type, this is how the field value was set before this change:
Now, this is the location type field showing the default location type for both phones after this change:
It still uses the default location type as long as the phone is empty:
If the phone is not empty, the saved location type …
=> PCHR-1146: Set the default phone location type when creating/editing a contact

hrui/hrui.php
CiviReport was removed from the list of components enabled
during hrui installation. With this, the component will be disabled
right after a new installtion with civibuild.
Since CiviReport won't be available anymore, I also removed a
piece of code that was deleting some of the reports created by
this component.
=> PCHR-1327: Disable CiviReport

hrcase/sql/activities_install.sql
Fix a missing semicolon that cause setting up a new civihr instance via the buildkit  to crash
=> PCHR-459: Fix a missing semicolon that cause buildkit setup to crash

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/WorkPattern.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/WorkPatternTest.php
When disabling a WorkPattern, we now throw a validation error it's it the last one
enabled.
This is how the error message is displayed to the user:
=> PCHR-914: If WorkPattern if the last active one, don't allow it to be disabled

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsencePeriod.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/sql/auto_install.sql, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsencePeriodTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsenceTypeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/xml/schema/CRM/HRLeaveAndAbsences/AbsenceType.xml
- Tests that used the "Year" were updated to use "Months" or "Days".
- The expiry date for the "Vacation" absence type was change to 12 months instead of 1 year
| Before | After |
|--------|-------|
|![captura de tela 2016-07-25 as 15 32 57](https://cloud.githubusercontent.com/assets/388373/17112606/194dadfc-527d-11e6-80be-b0f347c14587.png)|![captura de tela 2016-07-25 as 15 32 30](https://cloud.githubusercontent.com/assets/388373/17112614/212c0f3c-527d-11e6-8588-a11e85eb3842.png)|
=> PCHR-898:  Remove "Years" from toil and carry forward expiry dropdown

org.civicrm.reqangular/reqangular.php
In the `org.civicrm.reqangular` extension we always inject the _reqangular.min.js_ script, even in pages that are not really for CiviHR. Given that we're using (one of) the latest angular version, this seems to cause a conflict with the core angular pages in CiviCRM 4.5
A quick patch for this is to avoid injecting the file altogether for the angular-based core pages, while we figure out how to avoid relying on our own library version for the CiviHR pages
=> PCHR-1278: Do not inject civihr angular in angular-based core pages

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/LeaveBalanceChangeHelpersTrait.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveBalanceChangeTest.php
This scheduled job will run daily, checking for balance changes with an
expiry date in the past and creating the respective expiration record.
Example:
Imagine you have 3 days Brought Forward that will expire on 2016-04-01. This is how the balance change table will look like:
| id | amount | expiry_date | expired_balance_id |
|----|--------|-------------|--------------------|
| 1 | 3 | 2016-04-01 | NULL |
Now, after running the scheduled job, a new record will be created with the amount of days expired as a negative number. On this example, since no leave was taken, all the 3 days will expire:
| id | amount | expiry_date | expired_balance_id |
|----|--------|-------------|--------------------|
| 1 | 3 | 2016-04-01 | NULL |
| 2 | -3 | 2016-04-01 | 1 |
=> PCHR-1294: Add the scheduled job to expire leave balance changes

com.civicrm.hrjobroles/CRM/Hrjobroles/BAO/HrJobRoles.php, com.civicrm.hrjobroles/CRM/Hrjobroles/DAO/HrJobRoles.php, com.civicrm.hrjobroles/tests/phpunit/CRM/Hrjobroles/BAO/HrJobRolesTest.php, com.civicrm.hrjobroles/tests/phpunit/CRM/Hrjobroles/Import/Parser/HrJobRolesTest.php, com.civicrm.hrjobroles/xml/schema/CRM/Hrjobroles/HrJobRoles.xml
when trying to import job roles , an HTTP 500 error page appears .
another problem is when trying to save or edit a job role :
here is a quote from the QA team :
> *The problem is: *
I add a Title, choose the contract that has start and end dates as well, try to save it, but then the Title and end date disappears
I try to edit it, enter a title and save it but the title still not getting saved and both dates get unspecified
for the importer problem , I forget to change the method name in  CRM_Hrjobroles_BAO_HrJobRoles to contactExists but I was using this new name in the importer so I fixed this .
for the form problem , cost centers can be multiple and they are inserted in the database separated by vertical bar ( | ) so pusdocontant rule on cost center field doesn't accept that and …
=> PCHR-1340 : Fix adding and importing job roles errors

hrjobcontract/js/src/job-contract/controllers/contract.js
The issue was caused by these two commits in the past:
https://github.com/civicrm/civihr/commit/f5da231fc6486558f97e98e4af6a15fb3937bfe7
and
https://github.com/civicrm/civihr/commit/4210a556cd231ffe5ee0dc9f511cb2492a0bae0d
which seem to move Pay and Health entity fetching below the rest of the entities. The issue was that for both entities there was used Details revision ID instead of particular entities revision.
I've moved Pay and Health fetching into the $q.all() method to get current valid revisions.
=> UY-51 - Fixing of fetching Job Contract entities (pay and health).

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/WorkPattern.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsencePeriodTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsenceTypeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlementTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestDateTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/NotificationReceiverTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/PublicHolidayTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/WorkDayTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/WorkPatternTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/WorkWeekTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BaseTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/EntitlementCalculationTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/EntitlementCalculatorTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Validator/DateTest.php
This method will return the leave_days amount for any given date, in a period given by a start and an end date. The main use case for it is to calculate the amount of days to be deducted if a staff member using this work pattern takes a leave on that date.
It will rotate through the pattern's weeks to get the leave_days value. That is, starting from the Start Date, if the date falls on the first week, we get the leave_days amount from the first week of the pattern; if it falls on second week, we get it from the pattern's second week; if it's on the third week, we rotate and get the value from the pattern's first week again and so on.
While doing this, I noticed some of the WorkPattern tests were failing. This PR also includes fixes for them. I also did some overall refactoring to the …
=> PCHR-1443: Create the work pattern get leave days for date method

hrreport/CRM/HRReport/Form/Contact/HRDetail.php, hrreport/CRM/HRReport/Form/Contact/HRSummary.php
The following warning was appearing :
`Strict warning: Declaration of CRM_HRReport_Form_Contact_HRSummary::customDataFrom() should be compatible with CRM_Report_Form::customDataFrom($joinsForFiltersOnly = false) in require_once() (line 37 of civicrm/tools/extensions/civihr/hrreport/CRM/HRReport/Form/Contact/HRSummary.php).`
In civicrm 4.7 the signature for **CRM_Report_Form::customDataFrom** method is slightly changed so I've updated the extensions in civihr that override this method to match its signature . I also explicitly delcared all methods in (HRReport/Form/Contact/HRDetail.php) & ( HRReport/Form/Contact/HRSummary.php ) as public.
=> PCHR-1517: Fix non-compatible declaration of overridden methods in hrreport

hrrecruitment/CRM/HRRecruitment/Page/Dashboard.php
- Open Vacancies/Dashboard
- Then try to click on Absences, Mailing, Search, etc.
- The drop down menus don't appear, and nothing happens when clicking on these menus.
The reason behinde this is that  momentjs is used in hrrecruitment extension but it  points to wrong location ( momentjs was shipped with civicrm previously but not anymore in 4.7 and that's where it was pointing ).
since momentjs library is available in org.civicrm.reqangular extension i just changed hrrecruitment to use it.
=> PCHR-1229: Fix hrrecruitment extenstion momentjs script location

bin/drush-install.sh, com.civicrm.hrjobroles/CRM/Hrjobroles/Upgrader.php, com.civicrm.hrjobroles/hrjobroles.php, hrjobcontract/CRM/Hrjobcontract/Upgrader.php, hrjobcontract/hrjobcontract.php, hrui/CRM/HRUI/Upgrader.php, hrui/hrui.php
A set of changes to the navigation menu was required which is :
Remove the following menu items : 
- Search >> Full-text search
- Search >> Search builder
- Search >> Find assignments (Remove when T&A is enabled)
- Search >> Find activities (Remove when T&A is enabled)
- Search >> Custom searches
- Contacts >> Contact reports
- Contacts >> New activity (Remove when T&A is enabled)
- Contacts >> Import activities (Remove when T&A is enabled)
- Contacts >> New tag 
- Contacts >> Manage tags
- Appraisals (and its child menus)
- Reports (and its child menus)
- Administer >> People management >> Redaction rules
- Administer >> CiviReport (and its child menus)
- Job contracts (and move its child menus under "Contacts" below "Import contacts")
Also another menu items need to be created for …
=> PCHR-1516: modifications to menu items

hrabsence/CRM/HRAbsence/Form/AbsenceRequest.php
After making changes to an Absence Request, the user is redirect to an URL. This URL has a fragment, which is used by the backbone app to select which tab should be displayed. This fragment was added to the end of the URL by passing it to the CRM_Utils_System::url() method as part of the $query paramenter. This commit on the civicrm-core https://github.com/civicrm/civicrm-core/commit/c80e2dbf changed the behavior of how the method handles the $query value if it has a fragment (a string starting with #), turning part of the param value as the path for the URL, which led to a malformed URL.
The CRM_Utils_System::url() have a specific param for URL fragments, so, in order to fix the malformed URLs,  I updated every call to this method to pass the fragment using this param.
=> PCHR-1535: Fix malformed return URL for the Absence Record form

hrrecruitment/CRM/HRRecruitment/Form/HRVacancy.php
When Trying to edit a vacancy the start and end dates input boxes are shown empty 
The issue is inside quick form **setDefaultValues** method , the start and end dates are converted to a format not recognized by the used JavaScript date picker plugin.
another problem is after submitting the form , the following notices will appear in vacancy listing page :
which is because inside quick form **formRule** method , **start_date_display** and **end_date_display** where used instead of **start_date** and **end_date**.
Actually the date picker plugin appear to accept MySQL DateTime format so I just removed the date converting inside **setDefaultValues** method .
for the notices , i corrected the field names inside **formRule** method .
=> PCHR-1236: Blank start and end dates  input boxes when editing vacancies 

hrjobcontract/views/modalForm.html
**Problem**
Radio buttons missing in Job contract Pay page
**Fix**
1. For the custom radiobuttons to work "for" has to be mentioned for the label of the input tag(CSS written that way), which was missing. Adding the same fixes the visibility of radio buttons.
2. Markup modified to show the radio buttons properly.
**Before**
**After**
=> PCHR-1572: Show radiobuttons

bin/drush-install.sh
1- Set Default Language to (English - United Kingdom).
2- Set Default Currency to (GBP).
3- Add (GBP) to current list of enabled currencies.
4- Set Default Country to (United Kingdom).
5- Set Date formats (input and output formats) to "dd/mm/yy".
6- Set the Cusom CSS URL to point to the new theme which is available at "[civicrm.root]/tools/extensions/civihr/org.civicrm.bootstrapcivicrm/css/custom-civicrm.css"
=> PCHR-1580: Set default localisation settings

hrui/css/hrui.css
1. Fix menu height, make menu item hover state and delimiter take full height of the menu, so red area on the screenshot, instead of how it is right now.
=> PCHR-1576: Change style of CiviCRM menu

bin/drush-install.sh
Since this drush  command is called with $@:
`drush "$@" cvapi extension.install keys=$ENTITY_EXTS,$APP_EXTS`
the CiviCRM path argument (the first argument ) should be removed (shifted) to avoid being passed as drush option which is what I did in the PR.
=> Fetch CiviCRM path option and shift the options

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlement.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/sql/auto_install.sql, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/LeaveBalanceChangeHelpersTrait.php, uk.co.compucorp.civicrm.hrleaveandabsences/xml/schema/CRM/HRLeaveAndAbsences/LeaveBalanceChange.xml
Instead of using the entitlement_id FK, the LeavePeriodEntitlement will now be linked to LeaveBalanceChange via a polymorphic relationship using the source_id and source_type fields. Every LeaveBalanceChange record linked to a LeavePeriodEntitlement will have the value 'entitlement' on the source_type field and the related period entitlement id on source_id.
Since we had to create the new source_type field on LeaveBalanceChange, we also needed new value for this field for when the LeaveBalanceChange is linked to a LeaveRequestDay. In that case, the source_type is 'leave_request_day'
=> PCHR-1600: Remove link from LeavePeriodEntitlement to LeaveBalanceChange

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlement.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/sql/auto_install.sql, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlementTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/ContractHelpersTrait.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/EntitlementCalculationTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/LeaveBalanceChangeHelpersTrait.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/LeavePeriodEntitlementHelpersTrait.php, uk.co.compucorp.civicrm.hrleaveandabsences/xml/schema/CRM/HRLeaveAndAbsences/LeaveRequest.xml
With this change, the LeaveRequest won't be linked to the LeavePeriodEntitlement anymore. Now, in order to know which LeaveRequest was taken during a period, we just fetch the LeaveRequest between the LeavePeriodEntitlement dates (which are based on the AbsencePeriod and Contract dates). This gives us some flexibility to change the contract or period dates and "move" the LeaveRequest to another period.
Two new fields where added to the LeaveRequest entity: **type_id**, which is a FK to an AbsenceType; and **contact_id**, which is a FK to Contact and represents the use who will be taking the leave. All the methods (and related tests) used to fetch the the leave balance during an leave period were updated to use these new fields. So, basically, to get the number of leaves taken during a …
=> PCHR-1601: Change LeaveRequest to no depend on LeavePeriodEntitlement

hrjobcontract/CRM/Hrjobcontract/BAO/HRJobContract.php, hrjobcontract/api/v3/HRJobContract.php, hrjobcontract/tests/phpunit/CRM/Hrjobcontract/BAO/HRJobContractTest.php, hrjobcontract/tests/phpunit/api/v3/HRJobContractTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlement.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/LeavePeriodEntitlement.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/EntitlementCalculation.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/ManageEntitlements.php, uk.co.compucorp.civicrm.hrleaveandabsences/sql/auto_install.sql, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlementTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/EntitlementCalculationTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/LeavePeriodEntitlementHelpersTrait.php, uk.co.compucorp.civicrm.hrleaveandabsences/xml/schema/CRM/HRLeaveAndAbsences/LeavePeriodEntitlement.xml
An employee can have more than one contract during one Absence Period, meaning that the entitlement for a period is based on the contractual entitlement from each contract. For that reason, it doesn't make sense to have the LeavePeriodEntitlement linked to one specific contract. To fix this, the entity is now linked to the Contact, using the contact_id field, and then we can get the contracts and information related to it using both the contact_id and contract dates.
The main changes caused by this are:
- On LeavePeriodEntitlement, the getStartAndEndDates was updates to return an array with the start and end dates for all of the employee's contracts during that period.
- The getLeaveRequestBalanceForEntitlement and getBalanceForEntitlement methods (on LeaveBalanceChange) where updated to …
=> PCHR-1602: Change LeavePeriodEntitlement to support multiple contracts for a single period

hrui/hrui.php
CiviReport component is still required for job contracts export and old leave and absence extension reports so it need to be renabled , but we still need to hide other reports related menu items .
=> PCHR-1493: Revert #1046 and hide menu report component menu items

hrui/css/hrui.css
Users without the "Use the administration toolbar" permission, would not get the admin toolbar on the top of the page, which among other things would push down the entire page via the `.toolbar-drawer` class (and a javascript-added `padding-top`)
By enforcing the `padding-top` in the `hrui` extension, the issue is fixed
```css
body:not(.toolbar-drawer) {
padding-top: 30px;
}
```
=> PCHR-1618: Fix cut-off header for non-admin users

hrreport/CRM/HRReport/Form/Activity/HRAbsenceCalendar.php
When visiting the absence calendar (civicrm/report/instance/44&reset=1) the following error will appear : 
DB Error: syntax error
```SQL
Database Error Code: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND request.status_id IN (1,2) ORDER BY YEAR(request.activity_date_time), MON' at line 16, 1064
Additional Details:
Array
(
[callback] => Array
(
[0] => CRM_Core_Error
[1] => handle
)
[code] => -2
[message] => DB Error: syntax error
[mode] => 16
[debug_info] => SELECT
YEAR(request.activity_date_time) as year,
MONTH(request.activity_date_time) as month,
DAY(request.activity_date_time) as day,
absence.id as aid,
absence.activity_type_id as ati,
request.status_id status,
cac.contact_id as contact_id, …
```
=> PCHR-1631: Fix absence calendar query error

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlement.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlementTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/xml/option_groups/leave_balance_change_types_install.xml
Now, overridden entitlements are stored as the difference between proposed entitlement and the overridden value. For example, if the proposed entitlement was 20 and it was overridden to 50, we should store two balance changes. One of "Leave" type, with 20 as the amount and another one of "Overridden" type and 30 (50 - 20) as the value. This way, if we sum all the balance changes we'll get the right value, but we'll still have access to the original proposed value.
The tests were updated to reflect this and a new test was added, to cover the case when the overridden value is less than the proposed value.
A new "Overridden" type was added to the hrleaveandabsences_leave_balance_change_type option group
=> PCHR-1489: Change how overridden entitlements are stored

hrui/CRM/Core/BAO/Navigation.php
**Requirement**
When you are not admin or civi admin role, the logo drop down in CiviCRM, shows "Hide menu" instead of the "Self Service Portal" - fix it to say Self Service Portal for any role.
**Fix**
Showing "Self Service Portal" always.
=> PCHR-1650: Show SSP link always

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsencePeriod.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/ContractEntitlementCalculation.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/EntitlementCalculation.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/ManageEntitlements.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/EntitlementCalculationDetails.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/AbsencePeriod.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/PublicHoliday.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/SequentialTitle.php, uk.co.compucorp.civicrm.hrleaveandabsences/css/hrleaveandabsences.css, uk.co.compucorp.civicrm.hrleaveandabsences/js/hrleaveandabsences.form.manage_entitlements.js, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/ManageEntitlements.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/EntitlementCalculationDetails.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsencePeriodTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/ContractEntitlementCalculationTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/EntitlementCalculationTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/LeaveBalanceChangeHelpersTrait.php, uk.co.compucorp.civicrm.hrleaveandabsences/xml/Menu/hrleaveandabsences.xml
The Manage Entitlements page was update to be able to handle multiple period and multiple contracts.
After saving the entitlements for one absence period, if there are other absence periods starting after it, the user will be taken to the page to calculate the entitlements for the next period. This will go on until there are no more next period.
In order to inform the user that he'll be taken to calculate the entitlements for the next period, the label of the save button was updated (only when there are more periods to process):
(Note: the problem with the icon on top of the "S" is because of the new custom theme)
The old way do display the calculation details wasn't enough to handle multiple contracts. In this scenario the calculation is a bit more complicate and needs a more descriptive …
=> PCHR-1607: Make manage entitlements page able to handle multiple periods

bin/drush-install.sh
when creating a new site via the buildkit you wil get the following :
```
Array
(
is_error => 1
error_message => Unknown extension: uk.co.compucorp.civicrm.civihrcore
)
```
that's because the extension name is changed to uk.co.compucorp.civicrm.hrcore but it was not changed in in drush-install.sh file which was causing the issue.
=> PCHR-1665: fix civihr core extension key in drush-install

hrjobcontract/CRM/Hrjobcontract/BAO/HRJobLeave.php, hrjobcontract/CRM/Hrjobcontract/Import/EntityHandler/Generic.php, hrjobcontract/CRM/Hrjobcontract/Import/EntityHandler/HRJobDetails.php, hrjobcontract/CRM/Hrjobcontract/Import/EntityHandler/HRJobHealth.php, hrjobcontract/CRM/Hrjobcontract/Import/EntityHandler/HRJobLeave.php, hrjobcontract/CRM/Hrjobcontract/Import/Parser/Api.php, hrjobcontract/CRM/Hrjobcontract/Upgrader.php, hrjobcontract/tests/phpunit/CRM/Hrjobcontract/Import/Parser/ApiTest.php
When importing contracts, if the data for specific entity is not exists such as leave entitlements or health data then no revision will get created for that entity which cause loading the imported contracts to fail, The problem does not happen when creating job contract from the UI because a revision for each entity will be created even if no data inserted for it.
Changing the entity handler importer code for each entity to ensure the revision will get created , and changing how the contracts get imported via the API rather than calling the BAO methods directly for consistency since the API methods for some entities such as leave entity contain some additional logic not exits in BAO methods.
=> PCHR-1645: Ensure revision is created for each job contract entity via the importer

hrabsence/CRM/HRAbsence/BAO/HRAbsenceEntitlement.php, hrabsence/CRM/HRAbsence/BAO/HRAbsencePeriod.php, hrabsence/CRM/HRAbsence/Queue/EntitlementRecalculation.php, hrabsence/CRM/HRAbsence/Queue/Task/RecalculateContactsEntitlementForPeriod.php, hrabsence/CRM/HRAbsence/Test/Fabricator/HRAbsencePeriod.php, hrabsence/CRM/HRAbsence/Test/Fabricator/HRAbsenceType.php, hrabsence/CRM/HRAbsence/Upgrader.php, hrabsence/api/v3/HRAbsenceEntitlement.php, hrabsence/hrabsence.php, hrabsence/phpunit.xml.dist, hrabsence/tests/phpunit/CRM/HRAbsence/BAO/HRAbsenceEntitlementTest.php, hrabsence/tests/phpunit/CRM/HRAbsence/BAO/HRAbsencePeriodTest.php, hrabsence/tests/phpunit/bootstrap.php, hrjobcontract/CRM/Hrjobcontract/BAO/HRJobLeave.php, hrjobcontract/api/v3/HRJobLeave.php, hrjobcontract/scripts/RecalculateAbsenceEntitlement.php, hrjobcontract/scripts/RecalculateAbsenceEntitlementByContacts.php
**Problem**
When a new absence period is added, the entitlement for each contact is set to 0 instead of fetching the value from the contractual entitlement (the value set on the Leave tab of the contract dialog)
**Solution**
Whenever a new absence period is saved, a new task, containing the ID of the just saved period, is added to a "Entitlement Recalculation Queue", which will be processed by a new scheduled job that will update the entitlements for that period for all contacts.
This was created as a scheduled job because organizations can have a lot of contacts and doing this calculation for all of them might take some time.
-------------------------------------------------------------------------
**Refactoring**
The HRJobLeave BAO had a lot of methods which accessed directly tables …
=> PCHR-1692: Update entitlements when a new absence period is added

hrjobcontract/CRM/Hrjobcontract/Upgrader.php, hrjobcontract/sql/install.sql, hrjobcontract/sql/pchr-1655-alter_constraints_on_delete_cascade.sql, hrjobcontract/tests/phpunit/CRM/Hrjobcontract/BAO/HRJobContractTest.php
When trying to permanently delete a Contact there is an error if the Contact has Job Contracts existing in the database. To fix it I modified SQL tables definitions so now the Job Contracts are deleted with their revisions and entities while permanently deleting Contact from database.
Within this PR I did as follows:
- Creating upgrader script which modifies constraints on Job Contract tables
- Modifying install.sql script
- Creating unit test for checking delete cascade on Job Contract tables when deleting Contact.
=> PCHR-1655 - Cannot permanently delete individual user

hrjobcontract/views/contractSummary.html
**Problem:**
In Job contract, Notice period is visible even if amounts and units as blank
**Analysis & Fix:**
If Notice period is Zero a string value of 0 is set to `notice_amount`, and that is why `ng-if` is showing the value. 
Added condition to check whether the value is not 0
=> PCHR-1411: Hide Blank Notice period 

hrabsence/CRM/HRAbsence/BAO/HRAbsenceEntitlement.php, hrabsence/tests/phpunit/CRM/HRAbsence/BAO/HRAbsenceEntitlementTest.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Test/Fabricator/Contact.php
**Problem**
The period entitlement could be updated in two different ways:
- Manually, by clicking on the Absence tab of the contact page and then setting the values for each type and period
- Automatically, after updating a contract. In this case, the period entitlement is updated with whichever value is set on the leave tab of the contract dialog
The problem with the automatic update is that it would overwrite any existing entitlement set manually.
**Solution**
No, in order to no overwrite things, the method which recalculates the entitlement, will only save the new value if there is no existing entitlement for a contact and absence type during a given period.
=> PCHR-1707: Don't update absence period entitlement from contract after contract change

com.civicrm.hrjobroles/info.xml, contactaccessrights/info.xml, contactsummary/info.xml, hrabsence/info.xml, hrbank/info.xml, hrcareer/info.xml, hrcase/info.xml, hrdemog/info.xml, hrident/info.xml, hrim/info.xml, hrjobcontract/info.xml, hrmed/info.xml, hrprofile/info.xml, hrqual/info.xml, hrrecruitment/info.xml, hrreport/info.xml, hrsampledata/info.xml, hrstaffdir/info.xml, hrui/info.xml, hrvisa/info.xml, org.civicrm.bootstrapcivihr/info.xml, org.civicrm.hremergency/info.xml, org.civicrm.reqangular/info.xml, uk.co.compucorp.civicrm.appraisals/info.xml, uk.co.compucorp.civicrm.hrcore/info.xml, uk.co.compucorp.civicrm.hrleaveandabsences/info.xml
After the 2016-11-03 release, additional fixes had to be added to the 1.6.3 release.
Since this is not a public release yet, it was decided we should move the tag
instead of applying hotfixes. That is why we need to revert the version and
updated the release date here.
=> PCHR-1701: Revert CiviHR version

hrcase/hrcase.php
Issue affected admin part of CiviHR also.  The problem seems to happen because the activity's data is never queried from the DB.  Thus, the activity's type is null when the check is performed, and causes the error when the null value is used to bring a single result from the activitytype table.
Fixed by passing activity id instead of activity_type_id to activityCreatedByTaskandAssignments(), so data can be loaded from DB within function.
Should inspect the code to assure this same assumption will not cause further issues (assuming the object is loaded with all the information in DB).
=> PCHR-1177: Fixed API Call Error When Marking Tasks as Complete

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsencePeriod.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/PublicHoliday.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/ContractEntitlementCalculation.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Queue/PublicHolidayLeaveRequestUpdates.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Queue/Task/UpdateAllFuturePublicHolidayLeaveRequests.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreation.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestDeletion.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/PublicHoliday.php, uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/BaseHeadlessTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsenceTypeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/PublicHolidayTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreationTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestDeletionTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/LeavePeriodEntitlementHelpersTrait.php
The logic should be executed on the following situations:
- When creating a new Absence Type where "Must Take Public Holiday as Leave" is true
- When updating an existing Absence Type change the value of "Must Take Public Holiday as Leave" (either from true to false or from false to true)
- When deleting an Absence Type with "Must Take Public Holiday as Leave"
The PublicHolidayLeaveRequestCreation service was augmented with a new method to create public holiday leave requests for all public holidays in the future. It works by fetching all the dates and all the contracts which overlap those dates. Finally, it loop through all this and add a leave request for each date for each of the contracts contacts.
The PublicHolidayLeaveRequestDeletion service was augmented with a new method to delete …
=> PCHR-1196: Trigger Public Holiday Leave Requests creation/deletion when updating/deleting Absence Types

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Factory/PublicHolidayLeaveRequestService.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Queue/Task/UpdateAllFuturePublicHolidayLeaveRequests.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/JobContract.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreation.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestDeletion.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/PublicHolidayLeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Factory/PublicHolidayLeaveRequestServiceTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/JobContractTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreationTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestDeletionTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestTest.php
When we update a contract, more specifically its details (HRJobDetails) we must also update the Public Holiday Leave Requests accordingly to the contract dates. The contract period might have changed and then we will need to add new leave requests for public holidays overlapping the new period.
A new method was added to the PublicHolidayLeaveRequest service: `updateAllInTheFutureForContract()`. This method receives the ID of a contract and then:
1. Delete all leave requests for public holidays which are both in the future and overlaps the contract start and end dates
2. Creates leave requests for all public holidays which are both in the future and overlaps the contract start and end dates
Finally, using the `hook_civicrm_post()` hook, we call this new method every time a HRJobDetails is …
=> PCHR-1197: Trigger Public Holiday leave requests logic when updating contract

hrabsence/CRM/HRAbsence/Form/AbsenceRequest.php
Implemented so e-mails sent on associated absence events have the format:
userName <SystemEMail>.  In that way, when the e-mail gets to users, they'll see tha name of the user that caused it to be sent, but the e-mail which it was sent from remains to be the one configured as the system-wide default sender.
=> PCHR-1663: Changed Format of From Addresses

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
This PR introduces the `LeaveRequest.getBalanceChangeByAbsenceType` API endpoint, which will return the total change in balance that is caused by the leave requests of a given absence type, or of all the absence types of a given contact and period.
This endpoint supports the following parameters:
- **contact_id**: Mandatory The ID of the Contact to get the balance change for
- **period_id**: Mandatory The ID of the Absence Period to get the balance change for
- **statuses**: Optional (Default: null) An array of OptionValue values which the list will be filtered by
- **public_holiday**: Optional (Default: false) Based on the value of this param, the calculation will include only the leave requests that aren't/are public holidays
The output is going to be a list of Absence Types ids …
=> PCHR-1265: Add the LeaveRequest.getBalanceChangeByAbsenceType API endpoint

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Query/LeaveRequestSelect.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
This new param will make, when present and its value is true, the LeaveRequest.get return only Public Holiday Leave Requests. Otherwise, all Leave Request will be returned (according to the given params), except for those linked to Public Holidays.
To know if a Leave Request is a Public Holiday Leave Request, we need to go to its LeaveBalanceChange, through its LeaveRequestDate, and check that its type is 'Public Holiday'. In order to do that, the _LeaveRequestSelect_ class was created to wrap and "extend" the regular _SelectQuery_ which is used by default on the get API. Basically, it add joins to the leave_request_date and leave_balance_change tables, in order to be able to add conditions based on field of those tables. It also checks for the presence of the _public_holiday_ param in …
=> PCHR-1371: Add the public_holiday param to the LeaveRequest.get API

hrabsence/CRM/HRAbsence/Form/AbsenceRequest.php
Previous solution worked when using gmail as SMTP server, because gmail automatically replaces original "From" address for account being used to send the e-mail. Failed when testing aginst other SMTP servers
(sender should always be system-wide email). So, used call to CRM core Domain Entity to obtain default
system sender.
Tested on staging site by checking out branch directly. All tests were succesful, except test on line 38, which requires clarification on how to replicate, and test 39, which failed.
Results for tests can be seen here:
https://docs.google.com/a/compucorp.co.uk/spreadsheets/d/1n4Uovt9URyErQ2pMqt-hTGUBb2ezCVLR0J017xk_eDI/edit?usp=sharing
=> PCHR-1663: Loaded Domain Sender E-mail from Database

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Query/LeaveRequestSelect.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
A Leave Request is not linked directly to a Contract. Instead it's linked to a Contact and we use the Leave Request dates in order to know with which contracts it overlaps. This means we can have "stale" requests, which don't overlap any existing contract (this can happen, for example, when a contract length is decreased).
A call to the LeaveRequest.get API endpoint, even without any params, should no include those "stale" requests, so this PR updates the query used by the API to filter out any Leave Request not overlapping a contract. This was implemented by updating the query to join Leave Request with Contracts using the contact_id. Next, we join the Contract with its details, through the Contract Revision, in order to finally be able to add the conditions to return only the Leave …
=> PCHR-1756: Filter out leave requests not overlapping contracts

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Query/LeaveRequestSelect.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
This new API endpoint is an "extension" of the LeaveRequest.get and, in being so, it works exactly the same way and accepts the same params and options. The difference is on the returned values, where each Leave Request will include its balance and dates.
To call it, use:
```php
civicrm_api3('LeaveRequest', 'getFull');
```
And the response would be something like:
```json
{
"is_error": 0,
"version": 3,
"count": 2,
"values": [
{
"id": "17",
"type_id": "1",
"contact_id": "202",
"status_id": "1",
"from_date": "2016-02-01",
"from_date_type": "1",
"to_date": "2016-02-03",
"to_date_type": "1",
"balance_change": -3,
"dates": [
{
"id": "17",
"date": "2016-02-01"
},
{
"id": "18",
"date": "2016-02-02"
},
{
"id": "19",
"date": "2016-02-03"
}
]
},
{
"id": "19",
"type_id": "1",
"contact_id": "202", …
```
=> PCHR-1369: Add the LeaveRequest.getFull API endpoint

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/ContactWorkPattern.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/WorkDay.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/WorkWeek.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/WorkDay.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/WorkPattern.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/WorkPattern.php, uk.co.compucorp.civicrm.hrleaveandabsences/sql/auto_install.sql, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/ContactWorkPatternTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/WorkDayTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/WorkPatternTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/xml/option_groups/work_day_type_install.xml, uk.co.compucorp.civicrm.hrleaveandabsences/xml/schema/CRM/HRLeaveAndAbsences/WorkDay.xml
The valid values for the Work Day type were hardcoded as a set of constants on the WorkDay BAO. This would make it harder to change the option labels, add or remove new options and to return them on API responses in a consistent way. So, in order to avoid those problems, they were replaced with an option group named "Work Day Type".
The option group options are:
| label   | value | name            |
|---------|-------|-----------------|
| No      | 1     | non_working_day |
| Yes     | 2     | working_day     |
| Weekend | 3     | weekend         |
Every call to one of the removed constants was replaced with a call to a method which returns the respective option value value:
- `WorkDay::WORK_DAY_OPTION_NO` was replaced by `WorkDay::getNonWorkingDayTypeValue()`
- …
=> PCHR-1760: Replace class constants in WorkDay BAO with an OptionGroup

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsencePeriod.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlement.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Exception/InvalidLeaveRequestException.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreation.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/PublicHolidayLeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsencePeriodTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlementTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreationTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestDeletionTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/LeaveRequestHelpersTrait.php
This PR is about improvements to the LeaveRequest Create Logic. More validations have been added. These validations include: 
- Do not allow creating a new Leave Request without a start date
- Do not allow creating a new Leave Request with an end date greater than the start date
- Do not allow creating a new Leave Request overlapping another Leave Request with the status is: Approved, Admin Approved (Exception: if the other Leave Request is a Public Holiday Leave Request, then it can overlap), Awaiting Approval or More Information Requested
- Do not allow creating a new Leave Request with a balance change bigger than the remaining balance of the period if the Request’s AbsenceType do not allow overuse
- Do not allow a Leave Request which overlaps two absence periods (the start date is in …
=> PCHR-1677: Improvements to the Leave Request validation on save

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/sql/auto_install.sql, uk.co.compucorp.civicrm.hrleaveandabsences/sql/auto_uninstall.sql, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsenceTypeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/xml/schema/CRM/HRLeaveAndAbsences/AbsenceType.xml
A new flag named is_sick is added to the AbsenceType Entity.
The flag is a boolean field and It's default value is *false*. 
The "Sick" (ID: 3) reserved absence type have this flag set as *true*.
=> PCHR-1228: Add is_sick flag to AbsenceType Entity

uk.co.compucorp.civicrm.hrleaveandabsences/xml/option_groups/toil_amounts_install.xml
Created Toil Amount Option groups. The Option values are all reserved.
The initial values list (label / value)
- 0 Days / 0
- 1/4 Days / 0.25
- 1/2 Days / 0.5
- 3/4 Days / 0.75
- 1 Day / 1
- 1 1/4 Days / 1.25
- 1 1/2 Days / 1.5
- 1 3/4 Days / 1.75
- 2 Days / 2
- 2 1/4 Days / 2.25
- 2 1/2 Days / 2.5
- 2 3/4 Days / 2.75
- 3 Days / 3
=> PCHR-1383:  Create ToilAmount Option Group

contactaccessrights/CRM/Contactaccessrights/BAO/Rights.php, contactaccessrights/CRM/Contactaccessrights/Test/Fabricator/Rights.php, contactaccessrights/CRM/Contactaccessrights/Utils/ACL.php, contactaccessrights/phpunit.xml.dist, contactaccessrights/tests/phpunit/CRM/Contactaccessrights/Utils/ACLTest.php, contactaccessrights/tests/phpunit/bootstrap.php
When a local admin user, configured to have access to specific region(s)/location(s) tried to search for contacts, the resut included all contacts in the system, when it should only show contacts with current job roles in the region(s)/location(s) administered by the local admin.
The search filter was trying to use option_value ID to filter job roles, when option_value value was being stored in roles table.  Thus, they never matched.  This also caused a type mismatch error when optionvalue.value was a string (like "Headquarters") and not an integer, which caused an exception that made the filter ignore ACL $where and $wheretables being built in contactaccessrights extension, thus performing search on all contacts. 
Fixed by adding option_value.value to query to obtain access rights for …
=> PCHR-1751: Fix Filtering of Contacts by Value of Region/Location on Search

uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/apis/public-holiday-api.js, uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/models/instances/public-holiday-instance.js, uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/models/public-holiday-model.js, uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/mocks/apis/public-holiday-api-mock.js, uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/mocks/data/public-holiday-data.js, uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/apis/public-holiday-api_test.js, uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/models/instances/public-holiday-instance_test.js, uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/models/public-holiday-model_test.js
Implementation for publicholiday api end points as per ticket [PCHR-1275](https://compucorp.atlassian.net/browse/PCHR-1275).
`PublicHolidayAPI` will get all the publicholidays from backends.
`PublicHoliday` contains the publicholiday data and is wrapper over the API. It also has method `isPublicHoliday` to check if given date is public holiday or not.
`PublicHolidayInstance` is the publicholiday instance with helper method to get publicholiday data.
It is located under `civihr/uk.co.compucorp.civicrm.hrleaveandabsences/js/angular`.
The implementation is located under shared folder. 
The test cases are in tests folder. 
A sample absence is presented below 
```json
{
"is_error": 0,
"version": 3,
"count": 16,
"values": [{
"id": "1",
"title": "New Year's Day",
"date": "2016-01-01", …
```
=> PCHR-1275: PublicHoliday API,Model,ModelInstance

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/ContactWorkPattern.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/WorkPattern.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/WorkPatternCalendar.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/WorkPattern.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/ContactWorkPatternTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/WorkPatternTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/WorkPatternCalendarTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/WorkPatternTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/bootstrap.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/WorkPatternHelpersTrait.php
This API endpoint accepts only 2 params: `contact_id` and `period_id`. Based on that, it returns the contact calendar for the given period. The calendar is a list of dates with information about it's type, wether it's a working day, non-working day or weekend. The type information is fetched using the WorkPattern.
The dates returned are only those between the start and end date of the given absence period AND between any of the contacts contracts within the absence period. Example:
Given an Absence Period from 2015-01-01 to 2015-12-31 and given a Contract from 2015-02-01 to 2015-06-20 and another Contract from 2015-10-11 to 2016-03-04. The returned dates will be:
- From 2015-02-01 to 2015-06-20 (the period for the first contract)
- From 2015-10-11 to 2015-12-31 (the days of the contract …
=> PCHR-1689: Add the WorkPattern.getCalendar API endpoint

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsenceTypeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/AbsenceTypeTest.php
In this PR, The AbsenceType.calculateToilExpiryDate endpoint which, given a date, it calculates when the toil would expire is created. The endpoint supports the following parameters:
- id(required): The id of the absence type.
- date(required) : The date to calculate TOIL expiry for.
| absence_type_id  | allow_accruals_request  | accrual_expiration_duration|accrual_expiration_unit |
| ------------- | ------------- | ------------- |------------- |
| 1  | 0  |   |  |
| 2  | 1  |  |  |
| 3  | 1  | 10  |1  |
```php
$result = civicrm_api3('AbsenceType', 'calculatetoilexpirydate', array(
'absence_type_id' => 1,
'date' => "2016-10-11",
));
```
**$result =** 
```json 
{
"is_error": 1,
"error_message": "This Absence Type does not allow Accruals Request"
}
```
```php
$result = …
```
=> PCHR-1389: Calculate Toil expiry date API

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Exception/EntityValidationException.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Exception/InvalidLeaveRequestException.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
In this PR, the exceptions thrown during the Leave Request validation is updated to include more details. Besides the error message, it now  contains the field where the error was found and the Exception/Error code code.
A new exception class CRM_HRLeaveAndAbsences_Exception_EntityValidationExceptionhas been added which has two private fields: field and exceptionCode. The InvalidLeaveRequestException class is the only class that extends this class for now.
The following Error messages and Exception/Error codes were implemented
| Error Message | Error Code |
| ------------- | ------------- |
|Leave Requests should have a start date|leave_request_empty_from_date|
|Leave Request start date cannot be greater than the end date|leave_request_from_date_greater_than_end_date|
|The Leave request …
=> PCHR-1828: Add details for LeaveRequest validation errors

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php
In this PR, four additional validations are added to the LeaveRequest create BAO method.
They include:
- Check for empty contact_id
- Check for empty type_id
- Check for empty status_id
- Check to ensure that the to_date_type field should be mandatory if to_date is not empty
=> PCHR-1829: Improve Leave Request validation

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
This PR creates the LeaveRequest isValid API. The API uses the validateParams() method of the LeaveRequest BAO but does not make a call to LeaveRequest BAO create method.
The Response of the API includes the DAO field associated the error and also the error/Exception code for the exception.
Here are some sample request and responses for the API endpoint: 
_When from_date field is not present_
```php
$result = civicrm_api3('LeaveRequest', 'isvalid', array(
'contact_id' => 1,
'status_id' => 1,
));
```
Response: 
```json
{
"is_error": 0,
"version": 3,
"count": 1,
"values": {
"from_date": [
"leave_request_empty_from_date"
]
}
}
```
_When the absence type field is not included in the payload_
```php
$result = civicrm_api3('LeaveRequest', 'isvalid', array( …
```
=> PCHR-1761: Create Leave Request isValid API

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/TOILRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Exception/EntityValidationException.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Exception/InvalidTOILRequestException.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/TOILRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/TOILRequestTest.php
This PR creates the TOILRequest isValid API. The API uses the validateParams() method of the TOILRequest BAO but does not make a call to TOILRequest BAO create method.
The Response of the API includes the field associated the error and also the error/Exception code for the exception.
Here are some sample request and responses for the API endpoint:
_The TOIL amount is not valid_
```php
$result = civicrm_api3('TOILRequest', 'isvalid', array(
'type_id' => 1,
'contact_id' => 1,
'status_id' => 1,
'from_date' => '2016-11-14',
'toil_to_accrue' => 200,
'duration' => 120
));
```
Response: 
```json
{
"is_error": 0,
"version": 3,
"count": 1,
"values": {
"toil_to_accrue": [
"toil_request_toil_amount_is_invalid"
]
}
}
```
When all validations pass the response is:
```json
{
"is_error": 0,
"version": …
```
=> PCHR-1762: Create TOIL Request isValid API

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/SicknessRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Exception/InvalidSicknessRequestException.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/SicknessRequestTest.php
In this PR, an additional validation is added to the SicknessRequest create BAO method rather than relying on a database level exception to validate.
It includes:
Check for empty reason field
=> PCHR-1839: Improve Sickness Request validation

uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/SicknessRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/SicknessRequestTest.php
This PR creates the Sickness Request isValid API. The API uses the validateParams() method of the SicknessRequest BAO but does not make a call to SicknessRequest BAO create method.
The Response of the API includes the field associated the error and also the error/Exception code for the exception.
Here are some sample request and responses for the API endpoint:
_reason field is empty_
```php
$result = civicrm_api3('SicknessRequest', 'isvalid', array(
'type_id' => 1,
'contact_id' => 1,
'status_id' => 1,
'from_date' => '2016-11-14',
'from_date_type' => 1
'required_documents' => 1,
));
```
Response: 
```json
{
"is_error": 0,
"version": 3,
"count": 1,
"values": {
"reason": [
"sickness_request_empty_reason"
]
}
}
```
When all validations pass the response is:
```json
{
"is_error": 0,
"version": …
```
=> PCHR-1840: Create Sickness Request isValid AP

hrabsence/CRM/HRAbsence/BAO/HRAbsenceType.php, hrabsence/CRM/HRAbsence/Test/Fabricator/HRAbsenceType.php, hrabsence/tests/phpunit/CRM/HRAbsence/BAO/HRAbsenceTypeTest.php
On absence type deletion, leave entitlements associated to deleted absence types were being kept in the dtabase, breaking the leave entitlement interface for contract revisions.  Also, though front end validates if an absence type is being used in existing leave requests to allow/disallow deletion, this could be circumvented if you clicked on the delete link for the absence type, created a leave request for that absence type on another screen, and then confirmed deletion of absence type.
Implemented functionality to delete leave entitlements associated to Absence Type being deleted. Also, added validation to check if Absence Type being deleted is used on existing leave requests.
Added tests to verify use of deletion method in absence type BAO throws an exception when deleting absence …
=> PCHR-1644: Delete Leave Entitlements on Absence Type Deletion

uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/SicknessRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/SicknessRequestTest.php
In this PR, some modifications were made to SicknessRequest.get API endpoint.
When calling the SicknessRequest.get API, it now returns all the fields from the Sickness Requests plus the fields from the Leave Request linked through SicknessRequest.leave_request_id.
Given a Sickness Request with:
| id | leave_request_id |reason | required_documents|
| ------------- | ------------- | ------------- | ------------- |
|1|3|2|3,2,1|
And the related Leave Request (a few fields omitted for simplicity):
| id | from_date | from_date_type | contact_id| status_id | type_id |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
|3|2016-01-01|1|2|2|3|
A call to:
```php
$result = civicrm_api3('SicknessRequest', 'get', array(
));
```
Result: …
=> PCHR-1832: Modify SicknessRequest.get API to return associated LeaveRequest data

uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/TOILRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/TOILRequestTest.php
In this PR, some modifications were made to TOILRequest.get API endpoint.
When calling the TOILRequest.get API, it now returns all the fields from the TOIL Requests plus the fields from the Leave Request linked through TOILRequest.leave_request_id.
Given a TOIL Request with:
| id | leave_request_id | duration |
| ------------- | ------------- | ------------- | 
|1|3|240|
And the related Leave Request (a few fields omitted for simplicity):
| id | from_date | from_date_type | contact_id| status_id | type_id |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
|3|2016-01-01|1|2|2|3|
A call to:
```php
$result = civicrm_api3('TOILRequest', 'get', array(
));
```
Result:
```json
{
"is_error": 0,
"version": 3,
"count": 1,
"values": …
```
=> PCHR-1831: Modify TOILRequest.get API to return associated LeaveRequest data

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Query/TOILRequestSelect.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/TOILRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/TOILRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/SicknessRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/TOILRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlementTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/SicknessRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/TOILRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/SicknessRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/TOILRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/LeaveBalanceChangeHelpersTrait.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/LeaveRequestHelpersTrait.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/SicknessRequestHelpersTrait.php
This PR adds the "expired" filter to the TOILRequest.get API. When this filter is set, only expired TOILRequests will be returned, otherwise all will be returned.
Example usage:
```php
civicrm_api3('TOILRequest', 'get', ['expired' => true]);
```
The `TOILRequestSelect` was introduced to make this filter work. It wraps the `Civi\API\SelectQuery` class in order to join the TOILRequest with its LeaveBalanceChanges and be able to check if it's expired or not.
While working on this ticket, I found a few problems with TOILRequest and SicknessRequest apis and BAOs. They were all fixed:
- The spec for the contact_id field of the SicknessRequest.create API had the wrong class name. 
- The TOILRequest BAO was missing the validation of mandatory fields (duration and toil_to_accrue)
- The TOILRequest …
=> PCHR-1770: Extend TOILRequest.get API to filter expired requests

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveManager.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveManagerTest.php
This service encapsulates the logic to deal with who is the Leave Approver of an Admin of Leave and Absences. It has two methods:
It accepts a contactID and checks if the current logged in user is his/her Leave Approver. This is done by checking if there is an active "has Leave Approved by/is Leave Approver of" relationship between the two contacts.
It just checks if the current logged in user has the "administer leave and absences" permission
=> PCHR-1835: Add the LeaveManager Service

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Test/Fabricator/Relationship.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Query/LeaveRequestSelect.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveManagerTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/bootstrap.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/LeaveManagerHelpersTrait.php
This PR introduces the `managed_by` param for the `LeaveRequest.get` API. It accepts a Contact ID and, when present, it will make the API return only the Leave Requests of contacts managed by Contact with the given ID.
To know which contact is the manager of another contact, we use the "has Leave Approved by/is Leave Approver of" relationship. When the `managed_by` param is present, the LeaveRequestSelect class will add JOINs to the civicrm_relationship and civicrm_relationship_type.
The query also considers if the relationship is active today. That is, if the `start_date` and `end_date` are null or overlap the current date and if `is_active` is true
Say you have a manager with ID 1 and you have two contacts, with IDs 2 and 3. The manager is the Leave Approver only for the Contact with ID …
=> PCHR-1798: Add the managed_by param to the LeaveRequest.get API

hrjobcontract/CRM/Hrjobcontract/SelectValues.php
When importing job contracts, using "Not Applicable" as a pay scale resulted in an error.  This was because the label for all Pay Scales was expected to be of the form:
"<pay_scale> - <pay_grade> - <currency> <amount> per <periodicity>"
This meant the valid value to import a "Not Applicable" pay scale was, literally:
"Not Applicable - - per "
Fixed by building the expected label in CRM_Hrjobcontract_SelectValues::buildPayScales(), checking if pay_grade is empty, mirroring how the label is built on CRM_Hrjobcontract_BAO_Query::buildAdvancedSearchPaneForm().
=> PCHR-1414: Make "Not Applicable" Payscale a Valid Value to Import

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/ContactWorkPattern.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeavePeriodEntitlement.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/ContactWorkPatternTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestDeletionTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeavePeriodEntitlementTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/TOILRequestTest.php
This PR introduces the `LeavePeriodEntitlement.getEntitlement` API endpoint. It's a "complement" to `LeavePeriodEntitlement.getRemainder` and `LeavePeriodEntitlement.getBreakdown`, as it returns a list of LeavePeriodEntitlements IDs and its entitlement (the number of days available to be taken as leave at the start of the period).
The API supports 3 params:
* **entitlement_id** _Optional_. The id of a specific entitlement
* **contact_id** _Optional_. The contact we want to get the remainder of the entitlements
* **period_id** _Optional_. The period we want to get the remainder of entitlements
When calling the API, one should pass either only the entitlement_id or both the contact_id and period_id.
Getting the entitlement for a single LeavePeriodEntitlement
```php …
```
=> PCHR-1845: Add the LeavePeriodEntitlement.getEntitlement API endpoint

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/TOILRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreation.php, uk.co.compucorp.civicrm.hrleaveandabsences/sql/auto_install.sql, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/TOILRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreationTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/LeaveBalanceChangeHelpersTrait.php, uk.co.compucorp.civicrm.hrleaveandabsences/xml/schema/CRM/HRLeaveAndAbsences/LeaveRequest.xml
This PR updates the LeaveRequest DAO to_date field to be a required field.
The reason for this is that currently, a call to : 
```php
civicrm_api3('LeaveRequest', 'get', array(
'from_date' => array('>=' => "2016-01-01"),
'to_date' => array('<=' => "2016-12-31"),
));
```
will not include Single day Leave Requests. This is because currently the to_date field for single day leave request is null. 
So in this PR, for single day leave requests, the to_date field is set to be same value as the from_date field.
=> PCHR-1844: Set Leave Request to_date to be same as  from_date for single day leave requests

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Query/LeaveRequestSelect.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
The passing an array of fields to be returned to the `LeaveRequest.getFull` API, the `balance_change` and `dates` fields would always be included, even if they were not present on the list of fields to be returned.
This happens because both `balance_change` and `dates` are not actual fields on of the LeaveRequest, but fields added manually to the API results, after they were fetched from the database.
The LeaveRequestSelect class was updated to take into consideration if the `return` param passed to the API and, if it's not empty and doesn't includes `balance_change` and/or `dates`, they won't be includes on the results
=> PCHR-1369: Allow custom fields to be filtered out on LeaveRequest.getFull

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php
This PR solves the bug encountered when a Leave Request is updated and the dates overlap with the originally created leave request. To solve this, when a leave request is updated and the the overlapping leave request validation runs, If the leave request being updated is the only one returned as an overlapping leave request, an exception is not thrown.
=> PCHR-1677: Fix bug in overlapping leave request validation when a leave request is updated

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlement.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlementTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestDeletionTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/SicknessRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/TOILRequestTest.php
In cases when a LeavePeriodEntitlement has more than one LeaveBalanceChange with the same type_id, the `getBreakdown()`  method should return them as a single entry, where the amount will be the sum of the amounts of the grouped items.
So, say you have 2 balance changes of type "Leave", one with 5 days and another with 2 days. The returned date will be this single entry:
```json
{
"amount": 7,
"expiry_date": null,
"type": {
"id": 1,
"value": "leave",
"label": "Leave"
}
}
```
There's a special handling for Balance Changes of type "Overridden". They will be grouped together with balance changes of type "Leave". The reason is that "Overridden" days are the same thing as Leave. The "Overridden" type is just used internally for the system to be able to know that the original calculated number …
=> PCHR-1123: Group balance changes by type on LeavePeriodEntitlement.getBreakdown

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Query/LeaveRequestSelect.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/TOILRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
This PR modifies the query on LeaveRequestSelect.php to also return TOIL Leave requests.
The reason why TOIL request is not included currently is that TOIL requests creates its own balance changes hence the Leave Requests associated to TOIL Requests is not included on the results returned.
=> PCHR-1848: Modify Leave Request Select Query to return TOIL requests

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveManager.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveManagerTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
This is a new API endpoint that can be used to check if a given Contact is the manager of the contact of a given Leave Request.
It has two mandatory params:
- *contact_id*: The contact to check if the Leave Request is managed by 
- *leave_request_id*: The Leave Request to check if the contact is the manager of
```php
civicrm_api3('LeaveRequest', 'isManagedBy', ['contact_id' => 1, 'leave_request_id' => 1]);
```
If Contact with ID 1 is the manager of the contact for the the LeaveRequest with ID 1, this will be the response:
```json
{
"is_error": 0,
"version": 3,
"count": 1,
"values": true
}
```
Otherwise, the response will be:
```json
{
"is_error": 0,
"version": 3,
"count": 1,
"values": false
}
```
=> PCHR-1811: Add the LeaveRequest.isManagedBy() API endpoint

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Query/LeaveRequestSelect.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
This PR updates the LeaveRequest.getFull() API to include the balance_change for TOIL leave request.
Currently, the API does not return the balance changes for TOIL requests because the balance change for a TOIL leave request is created differently from that of a normal leave request.
This PR takes this difference into consideration and makes changes that will allow balance changes for TOIL requests to returned in the LeaveRequest.getFull() API endpoint
=> PCHR-1850: Extend LeaveRequest.getFull API to include the TOIL Request balance changes

hrabsence/CRM/HRAbsence/BAO/HRAbsenceType.php
As for HRAbsenece Module, when updating the Absence Type didn't update its associated Activity Type. As a result, this issue arrises, as in absence navigation menu, filter dropdown and tables in entitlements, calendar, statistics in my absence page are displaying title or label from Activity Types. 
**hrabsence/CRM/HRAbsence/BAO/HRAbsenceType.php's create function** has been modified to add Activity Type Update functionality when Absence Type is updated. Which solves the issue.
=> PCHR-1790: Fix for updating Activity Types with Absence Types

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/TOILRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsenceTypeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/TOILRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/AbsenceTypeTest.php
This PR takes care of updates/changes to TOIL requests when the TOIL accrual settings for an Absence Type is updated.
The following situations were taken care of in this PR:
- A test was added to verify that when an admin decreases the max number of days that can be accrued for an Absence Type, for open TOIL Request, the system "protects" itself and will not allow the request to be approved if the request amount is more than the new max.
- When an admin disables TOIL for an Absence Type, for all non-expired TOIL Requests, the TOIL requests + leave requests + balance changes + leave request dates associated with the TOIL is deleted
For situations when increase the TOIL expiry duration for an Absence Type is increase or decreased,
nothing is done because there's no way to distinguish …
=> PCHR-1683: Update TOIL Requests according to changes in Absence Type settings

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/SicknessRequestTest.php
LeaveRequest always deduct days from the entitlement, so their balance changes should always have a negative number as the amount.
The associated tests were updated to reflected this. They were also updated in order to add some more "randomness" (they were all using the same dates and balance changes, so I picked some different dates in order to generate some differente balance changes in the end)
=> PCHR-1681: Save LeaveRequest balance changes as a negative number

hrabsence/js/app.js
The filter view of the Marionette app can only use one model entity; the list view of the app had criteria and collection that correspond to the model of the filter view, hence the list view updates based on the changes made in the filter view. 
_Setting filter model_
```
HRAbsenceApp.filterRegion.show(new HRAbsenceApp.Filter.FilterView({
model: absenceCriteria
}));
```
_Setting list view criteria and region_
```
HRAbsenceApp.contentRegion.show(CRM.av = new HRAbsenceApp.List.ListView({
criteria: absenceCriteria,
collection: absenceCollection,
entitlementCollection: entitlementCollection,
absenceTypeCollection: absenceTypeCollection
}));
```
However, the calendar view's criteria and collection seem not match the filter view's model so changes in the filter didn't reflect in the calendar. …
=> PCHR-1757: Set calendar view criteria and collection to match filter model

hrjobcontract/CRM/Hrjobcontract/BAO/Query.php
Advanced search by contract type field was not searchable, and always resulted in an empty set of results when selecting several contract types.  Array of values selected by user for search was being imploded into a string of the form ('value1', 'value2', ... 'valuen') and then passed to CRM_Contact_BAO_Query::buildClause(), which caused the value to be treated as a single string, and the clause to be built as: IN ("(\'value1\', \'value2\', ... , \'valuen\')").
Fixed by passing value as an array to CRM_Contact_BAO_Query::buildClause(), which takes care of building the clause and quoting string values appropriately.  Found the same problem when searching by pension_is_enrolled, so fixed that one too.
=> PCHR-1787: Fix Search by Contract Type in Advanced Search

com.civicrm.hrjobroles/CRM/Hrjobroles/BAO/Query.php
Advanced search throws no result if you select a Region or Location for a job role. Multi-selects in general for job role section of dvanced search were being built with option_value.id as values, but query was being built comparing these option_value.id's with option_value.value's stored in job roles table. 
Fixed by changing the way selects are built, so that they now use option_value.value, just as they are built on job contract section of advanced search.
=> PCHR-1590: Fix Advanced Search for Job Roles Multi-selects

hrabsence/CRM/HRAbsence/Form/AbsenceRequest.php
When you added absences in Absences/New absence or when Approving or Rejecting an absence, an smtp error message was thrown: code: 501, response: 5.5.2 MAIL FROM syntax error.
As it turned out, there was a check when building the from address, validating if the target contact for the leave request had a manager.  If it didn't have a manager, the from address was being left empty, causing the error.
Refactored code into more manageable chunks, including a function built specifically to set the from address and making sure a from address was always being set.
=> PCHR-1819: Fix SMTP Error on Absence Request Save and Approve

uk.co.compucorp.civicrm.hrcomments/CRM/HRComments/API/Query/CommentSelect.php, uk.co.compucorp.civicrm.hrcomments/CRM/HRComments/BAO/Comment.php, uk.co.compucorp.civicrm.hrcomments/CRM/HRComments/Test/Fabricator/Comment.php, uk.co.compucorp.civicrm.hrcomments/api/v3/Comment.php, uk.co.compucorp.civicrm.hrcomments/tests/phpunit/CRM/HRComments/BAO/CommentTest.php, uk.co.compucorp.civicrm.hrcomments/tests/phpunit/api/v3/CommentTest.php
This PR modifies the default Get and Delete API endpoints of the Comment entity. The Get endpoint is modified to return only non deleted comments.
The Delete endpoint is modified to only soft delete comments by setting the is_deleted column of the comment to 1.
Given a Comment table
| id | entity_id | entity_name | contact_id| text | created_at | is_deleted |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |------------- |
|1|1|LeaveRequest|2|Randon Comment 1 |2017-01-17 12:51:13|0|
|2|1|LeaveRequest|2|Random Comment 2|2017-01-18 12:51:13|0|
|3|1|LeaveRequest|2|Random Comment 2|2017-01-19 12:51:13|1|
A call to
```php
$result = civicrm_api3('Comment', 'get', []);
```
Will return only non deleted values 
```json
{
"is_error": 0,
"version": 3, …
```
=> PCHR-1869: Modify Comment Entity Get and Delete API endpoints

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlement.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/AbsencePeriod.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlementTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveBalanceChangeTest.php
The `LeaveBalanceChange.createExpirationRecords()` method was created a long time ago and with all the changes in the data structure, it was not working anymore. The first thing this PR does is to fix all the existing tests for that method and make them all pass. Next, the method itself was updated to also be able to expire TOIL Requests and to be able to handle some complex cases, like when a TOIL Request overlaps a Brought Forward and we have to deduct a LeaveRequest which overlaps both, like on this example:
The logic is as follow:
- First we load all the LeaveBalanceChanges where the expiry_date is in the past but still don't have a expiry record yet (that is an associated LeaveBalanceChange where `expired_balance_changed_id` is `NOT NULL`)
- To each expired balance change, we also …
=> PCHR-1682: Make the extension capable of expiring TOIL Requests

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestCommentTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/bootstrap.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/SessionHelpersTrait.php
This PR improves the Leave Request BAO validations. New sets of validations related to absence type settings were added.
The new validations are: 
- A LeaveRequest where the number of days between from_date and end_date is greater than the number of days in max_consecutive_leave_days for the request's Absence Type cannot be created or updated. If max_consecutive_leave_days is blank (NULL, it means unlimited).
- A user is not allowed to cancel his/her own leave request if any of the following conditions is true:
If AbsenceType.allow_request_cancelation is true and LeaveRequest.from_date is in the past
If AbsenceType.allow_request_cancelation is false
- A Leave Request cannot be created for an absence type that is not active
=> PCHR-1677: More Improvements to Leave Request validation 

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/SicknessRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/SicknessRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/SicknessRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/SicknessRequestTest.php
This PR improves the validations on SicknessRequest BAO. It adds an additional validation related to the is_sick flag on an Absence Type i.e
- SicknessRequests can no longer be created/updated for AbsenceTypes where is_sick is false
This PR also fixes a loophole in SicknessRequest.isValid API endpoint.
**Problem:**  
A sickness request is created from a combination of parameters needed to create a leave request and additional parameters specific to a sickness request. Before this PR, SicknessRequest.isValid only runs the SicknessRequest validation function only(which only runs validation for SicknessRequest specific parameters), the fallout of this is that if the validations pass and for some reason some required conditions for creating a leave request was not met, this gives a false …
=> PCHR-1839: Improvements to Sickness BAO validations

uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/ApiPermissionTest.php
This PR fixes a permission issue when LeaveRequest.create API endpoint is used to update a leave request. 
Currently,  hook_civicrm_alterAPIPermissions is used to make sure that the only permission required for the Leave&Absence API endpoints is "access AJAX API".
**Problem**
Internally, the class responsible for permissions checks in the API considers create and update as two different actions/endpoints so in hook_civicrm_alterAPIPermissions, the permission is only applied to the create action.
**Solution**
hook_civicrm_alterAPIPermissions implementation on L&A is updated to add the "access AJAX API" permission to the "update" action of the "leave_request" entity
=> PCHR-1895: Fix permission issue when using LeaveRequest.create to update a Request

hrui/CRM/Core/BAO/Navigation.php
Current CRM_Core_BAO_Navigation in hrui extension throws an error on installation of CiviHR on CiviCRM v4.7.15.  This happend because CRM_Core_BAO_Navigation class overrides core class of CiviCRM and is using methods that are no longer in CiviCRM core, particularly CRM_Core_BAO_Dashboard::resetDashletCache().
Merged CRM_Core_BAO_Navigation class in CiviCRM v4.7.15 into the one in CiviHR hrui extension.
=> PCHR-1821: Merge CRM_Core_BAO_Navigation Class in Hrui with v4.7.15

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Query/ACLQueryHelper.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlement.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/ApiPermissionTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeavePeriodEntitlementTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
This PR fixes permission issues with LeaveRequest.get, LeaveRequest.getFull and LeavePeriodEntitlement.get API endpoints.
**Problem:**
When logged in as an user belonging to either civihr_staff or civihr_manager roles, a call to LeaveRequest.get, LeaveRequest.getFull or LeavePeriodEntitlement.get will return an empty set, even if the user has entitlements or leave requests for the given period. The reason is that, internally, civicrm adds special clauses to any SELECT query made through the API to an entity with a contact_id FK linked to the civicrm_contact table such that only roles with view all contacts' and  'edit all contacts' permissions can view records.
**Solution**
The ` addSelectWhereClause` method of the core DAO class is overridden in LeavePeriodEntitlement and LeaveRequest …
=> PCHR-1894: Fix Permission issue with LeaveRequest and LeavePeriodEntitlement

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/GeneralSettings.php, uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php, uk.co.compucorp.civicrm.hrleaveandabsences/settings/leaveandabsence.setting.php, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/GeneralSettings.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/xml/Menu/hrleaveandabsences.xml
This PR creates the Leave and absence general settings page. The general settings page hinges on the core Setting API to create, save and retrieve settings. 
The only setting added in this PR is the 'Relationships that are allowed to approve a Leave Request' setting. This field/setting gets its values from the RelationshipType.get API endpoint. It is a multi select field that allows selection of one or more relationship type. The values for this field is saved in civicrm_setting table.
=> PCHR-1791: Add Leave and Absence General Settings Page

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestStatusMatrix.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestStatusMatrixTest.php
This PR creates the LeaveRequestStatusMatrix Service. The service is used to determine if a leave request status can be updated according to some specific rules:
If the user changing the status is the contact_id of the Leave Request, then these are the changes allowed:
**For example, a staff member who is a leave request contact can update a leave request from 'Awaiting Approval' to 'Cancelled' status but cannot update from 'Awaiting Approval'  to 'More Information Requested' status**
If the user changing the status is the leave approver for of the Leave Request's contact or a Leave and Absence Admin, then these are the changes allowed:
**For example, a leave approver or a Leave and Absence admin can update a leave request from 'Awaiting Approval' to 'More Information Requested' status …
=> PCHR-1825: Create LeaveRequestStatusMatrix Service

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestRights.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestRightsTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/LeaveManagerHelpersTrait.php
This PR creates the LeaveRequestRights Service.
This service handles permission checks on different leave request status changes.
The service has various methods each dedicated to a leave request status and checks if the current user is authorized or permitted to change the status.
e.g `canCancelFor` method checks if the current user can cancel the leave request or not
=> PCHR-1834: Create LeaveRequestRights Service

uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/models/instances/sickness-leave-request-instance.js, uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/models/instances/sickness-leave-request-instance_test.js
The `LeaveRequestInstance` is extended to provide support for `SicknessRequestInstance`. 
The `create`, `isValid` and `update` methods are extended.
The appropriate `LeaveRequestAPI` endpoint is called with `sick` leave type status set.
=> PCHR-1417: Implement sickness instance

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Query/ACLQueryHelper.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Factory/SettingsManager.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/APISettingsManager.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/InMemorySettingsManager.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/SettingsManager.php, uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Factory/SettingsManagerTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/APISettingsManagerTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/InMemorySettingsManagerTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestStatusMatrixTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeavePeriodEntitlementTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/LeaveManagerHelpersTrait.php
This PR updates the `ACLQueryHelper` to build the ACL filter using the leave approver relationship types from the General Settings (https://github.com/civicrm/civihr/pull/1391). Before this, the filter would always use the 'has Leave Approved by' relationship.
The relationship types are stored in settings as a list of IDs. This IDs are added to the where clauses as `WHERE relationship_type.id IN(list, of, ids)`.
Testing code that uses the Setting API is a PAIN. You have to flush the cache/system on every test, making things really, really slow. In order to avoid that, I've created a `SettingsManager` interface and two implementations: `InMemorySettingsManager` and `APISettingsManager`. Together with that, there's a SettingsManager Factory, which is able to create instances of both, …
=> PCHR-1894: Build ACL filter using Leave Approver relationship types in settings

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Query/LeaveRequestSelect.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
When the `managed_by` param is present in a call to `LeaveRequest.get` or `LeaveRequest.getFull`, the `LeaveRequestSelect` class changes the database query to include filters to return only the leave requests of contacts managed by the contact with the ID given by `managed_by`.
`LeaveRequestSelect` was only filtering this by the 'has Leave Approved by' relationship type, though. Now that the extensions allows the configuration of multiple relationship types as "Leave Approvers", the class was updated to fetch the types from the settings and use them to build the query.
All the tests for the `managed_by` param were updated to also make sure they will work for both `get` and `getFull` endpoints.
=> PCHR-1798: Use Leave Approver relationship types for the managed_by param

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Factory/LeaveRequestService.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestRights.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/SicknessRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Factory/LeaveRequestServiceTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestRightsTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/SicknessRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/bootstrap.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/LeaveManagerHelpersTrait.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/LeaveRequestStatusMatrixHelpersTrait.php
This PR actually modifies the existing LeaveRequest Service. This create method of this class is a wrapper around the LeaveRequest::create BAO method. This PR adds some checks/validations to the already existing LeaveRequest Service create method. 
The validations are:
- Status can only be changed according to the LeaveRequestStatusMatrix: [#1399](https://github.com/civicrm/civihr/pull/1399)
- Status can only be updated only if the user has the permission required for the status  according to the LeaveRequestRights [#1407](https://github.com/civicrm/civihr/pull/1407)
- Managers cannot change the dates or absence type of their managees leave requests
=> PCHR-1836: Modify Leave Request Service

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/ACL/LeaveApproverTrait.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/ACL/LeaveInformationTrait.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Query/LeaveRequestSelect.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlement.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveManager.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/SettingsManagerTrait.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveManagerTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/SessionHelpersTrait.php
This PR updates the `LeaveManager.isContactManagedBy` method to use the leave approver relationship types in general settings in order to check if the a contact is managed by another. Before this, it would only consider the 'has Leave Approved by' relationship type as the only one valid for a leave approver.
The PR also includes some overall refactorings:
- Lots of removed duplication on the LeaveManager tests
- A SettingsManagerTrait was added in order to centralize the code to fetch the leave approver relationship types from settings
- The ACLQueryHelper was replaced by a trait, so it can be more easily reused in BAOs. Also, is make possible for this trait to use another trait (the SettingsManagerTrait) and avoid some code duplication
=> PCHR-1835: Change LeaveManager Service to use relationship types in general settings

uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php, uk.co.compucorp.civicrm.hrleaveandabsences/managed_entities/Job.mgd.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestRightsTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/LeaveManagerHelpersTrait.php
With this PR, the L&A extension will now have a default Leave Approver relationship type right after it gets installed. The new relationship type is named "Has Leave Approved By" and it's the default value on the General Settings.
The enable/disable/install/uninstall hooks were all updated to make sure the RelationshipType gets updated properly on each of this events. Originally, the idea was to use Managed Entities to create the relationship type but was not possible. The reason is that the `hrabsence` extension also creates the same relationship type. So, if that extension is installed before l&a, the managed entity creation will fail because the type already exists. Using hook, we can first check if it exists and only create it if it doesn't.
Due to the fact that now the extensions …
=> PCHR-1833: Set "Has Leave Approved By" as the default Leave Approver relationship type

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/SicknessRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Factory/SicknessRequestService.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/SicknessRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/SicknessRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/SicknessRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Factory/SicknessRequestServiceTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/SicknessRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/SicknessRequestTest.php
This PR modifies the already existing SicknessRequest Service by making the it to extend LeaveRequest Service [#1420](https://github.com/civicrm/civihr/pull/1420). 
Some necessary methods that needed a different implementation in SicknessRequest Service child class  were overridden and modified.
One of such is the fact that Leave Approvers and Admins can modify SicknessRequest dates on behalf of the Leave Contact, this was not possible in LeaveRequest Service. So the `canChangeDatesFor` function of Sickness Request service was added as an overridden function of the parent class to reflect this change.
Also the way a leave request is created and deleted is a bit different from that of SicknessRequest, this also was taken into consideration and the methods required for this in the parent …
=> PCHR-1838: Modify SicknessRequest Service

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/TOILRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Factory/TOILRequestService.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/TOILRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/TOILRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/TOILRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/TOILRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Factory/TOILRequestServiceTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/TOILRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/TOILRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/TOILRequestHelpersTrait.php
This PR creates the TOILRequest Service by making the it to extend LeaveRequest Service #1420.
Some necessary methods that needed a different implementation in TOILRequest Service child class were overridden and modified.
One of such is the fact that a TOILRequest creates its own balance changes, so the `createRequestWithBalanceChanges` method of the TOILRequest service was created to override that of the parent LeaveRequest Service class.
Also a bug that prevents a TOIL request from being updated due to an `overlapping leave request` error was fixed in this PR.
The methods for Creating and Deleting LeaveRequestBalance Changes were removed completely from the TOILRequest BAO and moved to the LeaveBalanceChange Service. Also TOILRequest Fabricator was updated to create its balance changes …
=> PCHR-1837: Create TOILRequest Service

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Page/Error404Checker.php, uk.co.compucorp.civicrm.hrcore/xml/Menu/hrcore.xml
Accessing non existing pages in civicrm application results in showing invalid data, being showed by default CiviCRM dashboard.
Implemented handling of invalid CiviCRM paths by overriding "civicrm" default path and redirecting to T&A Dashboard.
=> PCHR-1871: Redirect Invalid URL's to T&A Dashboard

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsenceTypeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlementTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/AbsenceTypeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/LeaveBalanceChangeHelpersTrait.php
This PR fixes an issue with expired TOIL/Brought Forward Leave Balance Changes.
**Problem:**
It's possible to create Leave Requests for dates in the past. That can affect the number of expired Brought Forward/TOIL days. 
Example: 
Absence Period: 2016-01-01 to 2016-12-31
Brought Forward expired in 2016-03-01
Brought Forward amount: 5 days
Number of days taken before expiry date: 2
Number of expired days: 3
Then, after the expiry date, a new LeaveRequest single day leave request is added for the date of 2016-02-15. Since it represents a leave taken before the expiry date, we must recalculate the number of expired days, which will become 2 instead of 3).
Currently the system does not support this, because the expiry calculation is done daily by a scheduled job and doesn't take into …
=> PCHR-1896: Recalculate Brought Forward/TOIL for leave request past days

uk.co.compucorp.civicrm.hrcomments/CRM/HRComments/BAO/Comment.php, uk.co.compucorp.civicrm.hrcomments/tests/phpunit/CRM/HRComments/BAO/CommentTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestCommentTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
This PR modifies the Create method of the Comment Entity BAO. 
The changes are as follows:
- The create method now allows the created_at date parameter to be passed when creating a new comment although this is still disallowed when updating a comment.
- As a security check for allowing this (1st change), a new comment will not be allowed to be created when the created_at date is less than the created_at date of the last comment for that entity.
The created_at is also added as an optional parameter for the LeaveRequest.addComment API endpoint.
=> PCHR-1868:  Modify LeaveRequest.AddComment API and Comment.create 

hrabsence/js/models.js
The default value of `period_id` of the `AbsenceCriteria` model was simply the string of the last period's id.
```js
period_id: _.last(_.keys(CRM.absenceApp.periods)),
```
This created a problem as the views' templates are looping through `period_id` via `_.each`
```
<% _.each(active_period_ids, function(periodId) { %>
```
By providing a multi-digit id, for example "10", instead of an array would result in the `periodId` param of the callback being "1", and "0" (since it loops through the string's characters) which would obviously result in an error
The default `period_id` is now always an array, and, if found, it is also the id of the current period, rather than of the last one in the list
=> PCHR-1978: Fix period_id list in backbone views

org.civicrm.bootstrapcivicrm/js/enable-select2.js
- Change select2 element display property to `inline-block` instead of `inline`
- Add a callback to hide all select fields that haven't an option
**Before**
**After**
=> AI-22: Fix select2 fields

uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/LeaveRequestHelpersTrait.php
This PR creates the LeaveRequest.getAttachments API endpoint. 
This API retrieves a list of attachments for a leave request
Given a Leave Request with ID of 1 having some attachments previously uploaded for it:
**Sample Request**
```php
$result = civicrm_api3('LeaveRequest', 'getAttachments', array(
'leave_request_id' => 1
));
```
**Sample Response**
```json
{
"is_error": 0,
"version": 3,
"count": 2,
"values": [
{
"attachment_id": "1",
"name": "LeaveRequestSampleFile1.txt",
"mime_type": "text/plain",
"upload_date": "2017-02-21 14:29:58",
"url": "http://localhost:8900/index.php?q=civicrm/file&reset=1&id=1&eid=1"
},
{
"attachment_id": "2",
"name": "LeaveRequestSampleFile2.txt",
"mime_type": "text/plain",
"upload_date": "2017-02-22 13:21:14",
"url": …
```
=> PCHR-1916: Create LeaveRequest.getAttachments API endpoint

hrcase/CRM/HRCase/Upgrader.php, hrcase/hrcase.php
Removing all the managed case types from hrcase and keep them to be created manually.
For existing sites , **civicrm_managed** table should be cleared from any managed Case type record defined by this extension before upgrading civihr ( by running a query like this : 
```php
DELETE FROM civicrm_managed WHERE entity_type = 'CaseType' and name IN ('Exiting', 'Joining', 'Probation', 'Appraisal')
```
).
=> PCHR-459: Removing managed case types from hrcase

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestAttachment.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestAttachmentTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/LeaveRequestHelpersTrait.php
This PR creates the LeaveRequest.deleteAttachment API endpoint.
The API uses the delete method exposed by the newly created LeaveRequestAttachment Service.
Also only Leave Approvers and admins can delete attachments from a Leave Request.
Sample Request
```php
$result = civicrm_api3('LeaveRequest', 'deleteattachment', array(
'leave_request_id' => 1,
'attachment_id' => 1,
));
```
Response
```json
{
"is_error": 1,
"version": 3,
"count" : 0,
"values: [],
}
```
**Note** that this API only works currently when called in php/smarty but not via REST. When called via REST the check_permissions parameter is set to true and cannot be overriden and triggers some checks in core.  There is a blocker in core that prevents an attachment from being created or deleted due to this …
=> PCHR-1917: Create LeaveRequest.deleteAttachment API

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Query/ContactSelect.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/Contact/GetLeaveManagees.php, uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveManagerTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/ApiPermissionTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/ContactTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeavePeriodEntitlementTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
This PR creates the Contact.getleavemanagees API endpoint.
This endpoint returns a list of contacts managed by the current logged in user. That is, all the contacts the logged in user manages with any of the relationships defined in the Leave and Absences general settings page.  Deceased and deleted contacts (i.e where is_deleted = 1 or is_deceased = 1 are not returned).
**Sample request:**
```php
$result = civicrm_api3('Contact', 'getleavemanagees');
```
**Sample Response:**
```php
{
"is_error": 0,
"version": 3,
"count": 1,
"values": {
"437": {
"id": "437",
"contact_type": "Individual",
"do_not_email": "0",
"do_not_phone": "0",
"do_not_mail": "0",
"do_not_sms": "0",
"do_not_trade": "0",
"is_opt_out": "0",
"sort_name": "John Doe",
"display_name": "John Doe",
"preferred_mail_format": …
```
=> PCHR-1968: Create Contact.getleavemanagees endpoint.

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/AbsenceTab.php, uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/AbsenceTab.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/xml/Menu/hrleaveandabsences.xml
In this PR, The L&A extension adds an Absence tab to the contacts summary page using hook_civicrm_tabset hook.
It also adds the page for the Absence tab.
=> PCHR-2001: Add absence tab to L&A extension

hrjobcontract/CRM/Hrjobcontract/BAO/HRJobContract.php, hrjobcontract/api/v3/jobcontract_utils.php, hrjobcontract/tests/phpunit/CRM/Hrjobcontract/BAO/HRJobContractTest.php, hrui/hrui.php
Currently contact header information was not updated on creating  or deleting existing contract for the given contact. Which was due to not loading `contact.js` form **hrui** module which si responsible to update the contact header.
Added `contract.js` in `hrui.php` of **hrui** module  to load on contact page load.
`CRM_Core_Resources::singleton()->addScriptFile('org.civicrm.hrui', 'js/src/contact.js');`
Added logic to _civicrm_hrjobcontract_api3_get_current_revision so that if no current revision is found, it searches for a future revision.
Included clauses to query on HRJobContract::getCurrentContract() to take into account revisions in the future and limited to current contracts.
Added an assertion to test use of HRJobContract::getCurrentContract() does not return null when there are …
=> PCHR-1893: Add contact.js to load on contact page load

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Query/ContactSelect.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/Contact/Getleavemanagees.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/ContactTest.php
This PR modifies the Contact.getleavemanagees API.
A new required parameter: 'managed_by' is added.  Previously the API returns contacts information for contacts managed by the currently logged in user. The API has been modified to now return contact information for contacts managed by the given contactID passed in via the managed_by parameter.
=> PCHR-1968: Modify Contact.getleavemanagees API

uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php
Currently, we need to set the permissions for L&A manually. When we uninstall the extension, these permission get deleted though, and when we install it again the permissions have to be set once more. This is quite problematic for leave and absences, since it's still in development and not using upgraders yet, which forces us to reinstall the extension whenever there are changes in the db structure. 
We're adding this to the postInstall hook so we can have the system automatically set with permission after installing the extension. This is mainly useful for deployments with compubot, while it still have to reinstall the extension.
The roles `civihr_staff`, `civihr_manager` and `civihr_admin` all have the `'access leave and absences'` permissions.
The role `civihr_admin` also have the …
=> PCHR-2050: Set default CiviCRM permissions for L&A

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Query/LeaveRequestSelect.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
This PR extends LeaveRequest.get and LeaveRequest.getFull API endpoints to support the 'unassigned' Boolean Parameter.
The 'unassigned' parameter returns Leave Requests for contacts without active Leave managers, when false, it returns Leave Requests for contacts with active Leave managers for LeaveRequest.get and LeaveRequest.getFull
When the parameter is absent, LeaveRequest.get and LeaveRequest.getFull returns Leave Requests for all contacts irrespective of whether they have an active Leave manager or not.
Note that contacts without Leave managers and contacts having an inactive relationship with leave managers both fall under the category of contacts without active leave managers.
Different tests were also added to ensure that ACL's and other existing parameters on the API's were …
=> PCHR-2044: Extend LeaveRequest.get and LeaveRequest.getFull API to support the 'unassigned' Parameter

hrabsence/CRM/HRAbsence/BAO/HRAbsenceType.php, hrabsence/CRM/HRAbsence/Upgrader.php
A leave type can be deleted only if it has no approved absences related to it. However if the leave type is used only in a contract then it can be deleted. In a [related PR](https://github.com/civicrm/civihr/pull/1290) this was fixed by deleting all entries in `civicrm_hrjobcontract_leave` related to the deleted type. The problem here was that the API call to fetch them was being limited to 25 entries.
- Remove the limit on the `civicrm_api3('HRJobLeave', 'get')` API call
- Add an upgrader to remove all entries from `civicrm_hrjobcontract_leave` that do not have a related entry in `civicrm_hrabsence_type`
- I removed `sequential` from the API call since it's not relevant
=> PCHR-1892: Cleanup orphan contract leave

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/WorkPattern.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/WorkPattern.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/WorkPatternTest.php
This PR changes the way a WorkPattern is deleted:
A WorkPattern that fulfils any of the following criteria is not allowed to be deleted, instead an exception is thrown.
- If the WorkPattern is the default one
- If there's at least one ContactWorkPattern where the pattern_id is the ID of the WorkPattern being deleted.
A new WorkPattern service is created to implement these new changes
=> PCHR-2046:  Don't allow deleting a Work Pattern that has ever been used by a contact

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/WorkPattern.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/WorkPattern.php
This PR hides the delete option on the Work Pattern list and form for a  WorkPattern that cannot be deleted.
=> PCHR-2047: Hide delete option on work pattern list and form for a WorkPattern that cannot be deleted

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsenceTypeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/AbsenceTypeTest.php
This PR changes the way an AbsenceType is deleted:
An Absence that has at least one leave request for it is not allowed to be deleted.
The logic for this is implemented in the AbsenceType service. Also existing logic in the `del` method of the AbsenceType BAO is moved to the delete method of the AbsenceType service.
=> PCHR-2048: Don't allow deleting an Absence Type that has been used.

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/AbsenceType.tpl
This PR hides the delete option on the Absence Type listing page for an Absence Type that cannot be deleted(either a used or reserved absence type) . For used Absence Types(  [#1662](https://github.com/civicrm/civihr/pull/1662)), the delete button is shown on the edit form but when the button is clicked it displays an error message that the absence type should be disabled and can't be deleted.
**Screenshot when trying to delete a used absence type on the edit form:**
=> PCHR-2049: Hide the delete option/button on the Absence Type list and edit form for an Absence Type that cannot be deleted/

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Factory/PublicHolidayLeaveRequestService.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreation.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/PublicHolidayLeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreationTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestDeletionTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/LeaveBalanceChangeHelpersTrait.php
This PR makes some modifications to the way the balance change for a public holiday is created when creating a public holiday leave request using the Public Holiday Leave Request creation service. 
**Before:**
The calculation for the number of days to be deducted for a public holiday is always -1 day.
**Now:**
Instead of always deducting -1 day, it  deducts the amount specified by the Work Pattern of the contact (which could either be the default work pattern or the work pattern assigned to the contact effective for the public holiday date).
=> PCHR-1195: Modify the Creation Logic For Public Holidays Leave Request.

hrjobcontract/CRM/Hrjobcontract/Page/JobContractTab.php
Currently, All absence types are fetched and displayed in UI. Both in Contract Summary and New Contract Modal Tab.
1. We need to modify file `hrjobcontract/CRM/Hrjobcontract/Page/JobContractTab.php` file to display only active absence types as follows.
```
absenceTypeResult = civicrm_api3('HRAbsenceType', 'get', array(
'return' => 'id,title',
));
```
To following to get only the active absence types.
```
absenceTypeResult = civicrm_api3('HRAbsenceType', 'get', array(
'is_active' => 1,
'return' => 'id,title',
));
```
1. Disabling the Absence type: "Vacation"
2. Vacation is not displayed in Contract Summary
3. Vacation is not displayed in New Contract leave Tab
=> PCHR-1501: Get absence types that are only active

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlement.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlementTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/EntitlementCalculationTest.php
This PR fixes issues with Inability to save and override the 'New Proposed Period Entitlement' column on the confirm calculations page.
The was fixed once the code for creating public holiday leave requests when creating balance changes for public holidays after saving entitlements on the confirm calculations page was removed. (This code was never needed and has been removed).
It turned out that the public holiday leave requests were created without passing the false (don't run validation) parameter to the LeaveRequest BAO create method thereby causing validation errors which prevented the all the methods in the transaction to successfully execute..
Some other issues/cleanup was also done:
Removing old balance changes related to a LeavePeriodEntitlement after it gets overridden/re-saved …
=> PCHR-1108: Fix Issues with being unable to save and override New Proposed Entitlement

bin/drush-install.sh
This PR is related to: https://github.com/compucorp/civihr-employee-portal/pull/287. It removes removes hrabsence from the list of extensions installed by default.
=> PCHR-2058: Don't install hrabsence by default when creating a new site with civibuild

uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php
This is related to https://github.com/compucorp/civihr-employee-portal/pull/288. 
The code to set the default permissions during the extension installation was removed, because now the permissions will not be set using the civihr_default_permissions feature
=> PCHR-2021: Remove the code use to set default permissions

bin/drush-install.sh
This is one more step towards the complete replacement of hrabsence by L&A. With this, when creating a new site with civibuild, the process will:
- Install l&a and hrcomments by default
- Don't install hrabsence
=> PCHR-2057: Change list of extensions installed by default with civibuild

uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/Contact/Getleavemanagees.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/ContactTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/bootstrap.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/ApiHelpersTrait.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/SessionHelpersTrait.php
This PR fixes ACL issues with Contact.getLeaveManagees API endpoint.
Currently the API returns an empty result set for users without 'edit all contacts' or 'view all contacts' permissions.
To fix this, the Contact.getLeaveManagees is modified to ignore the default civicrm ACL checks by setting check_permissions parameter to false.
The 'ACL' needed for this endpoint was already implemented in the ContactSelect Query class:
- A Leave Approver only gets to see his/her managees and can't view the managees of another Manager.
- An Admin can view the managees of any Manager.
- A staff member can't view managees of any manager.
Some of the tests were modified to set check_permissions to true just to be sure that civicrm 'ACL' checks will be ignored.
=> PCHR-1968: Fix ACL issues with Contact.getLeaveManagees API Endpoint

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/ManageEntitlements.php
Redirecting back to return URL after saving on Confirm Calculations page works fine for sites without clean URL enabled as the function responsible for saving the returnUrl relies on the q string parameter in the URL. However for sites with clean Url enabled, the q parameter does not exist.
This PR fixes this issue and makes sure that the redirection works for cases when clean Url is enabled or is not
=> PCHR-1064:  Fix Issues With Redirecting back to Return URL after Saving On Confirm Calculations Page

hrjobcontract/api/v3/HRJobLeave.php
Whenever the leave information on a contract was updated, the entitlement for the contract period was recalculated. This was done using the `recalculateAbsenceEntitlement` method of the `CRM_HRAbsence_BAO_HRAbsenceEntitlement` BAO, from the `hrabsence` extension.
This recalculation isn't necessary anymore, because now, after updating a contract, the user is redirected to the Entitlement Calculation page.
The piece of code has to be removed though, because it will cause errors if we try to save/create a contract while the `hrabsence` extension is disabled.
**Note**: There are still some parts of the hrjobcontract (and other extensions) that call method and APIs of the hrabsence, but these will not cause errors on any of the main functionalities of the system (adding contracts, job roles, …
=> PCHR-2058: Remove old entitlement calculation when updating leave on a contract

hrabsence/CRM/HRAbsence/Form/AbsenceType.php
Creating two absence types with the same name is permitted, but they will use the same activity_type_id. When one is deleted the activity type for it is also deleted. The whole system becomes unusable and the following error is displayed:
Add a rule to check for absence types with duplicate names, but only when creating a new type
- I wasn't sure which was the best option for checking if it's a 'create' or 'update'. I used the `$self->getAction()` but I'm open to changing it to a `isset($fields['id'])` if that makes more sense.
=> PCHR-2055: Disallow Duplicate Absence Types

hrcase/CRM/HRCase/DefaultCaseAndActivityTypes.php, hrcase/CRM/HRCase/Upgrader.php
To give a more generic option for task types a 'Other Task' type will be added
- I'm not sure if it should also be added to CRM_HRCase_DefaultCaseAndActivityTypes::$defaultActivityTypes and would like to hear from the reviewer what they think. If it is added here the upgrade will need to be changed since 'create' will create a duplicate.
=> PCHR-1980: Add upgrade method to add 'other task' task type

hrjobcontract/CRM/Hrjobcontract/Upgrader.php
In hrjobcontract/CRM/Hrjobcontract/Upgrader.php `upgrade_1027` is used twice because two separate feature branches used the same name and were then merged.
This should be changes to use the next available number.
=> Fix duplicate upgrader names

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreation.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreationTest.php
When trying to create a new contract and no Absence Type with  'Must take Public holiday as leave request' exists, an exception is thrown and the contract cannot be created.
This PR fixes the issue by exiting the function for creating the Public Holiday Leave requests once an Absence Type with  'Must take Public holiday as leave request' does not exist.
=> PCHR-1197: Fix issues with Creating a Contract when no Absence Type with MTPHL exists

uk.co.compucorp.civicrm.hrcore/backstop_data/page-objects/contact-summary.js, uk.co.compucorp.civicrm.hrcore/backstop_data/page-objects/documents.js, uk.co.compucorp.civicrm.hrcore/backstop_data/page-objects/modals/assignment.js, uk.co.compucorp.civicrm.hrcore/backstop_data/page-objects/modals/contact-access-rights.js, uk.co.compucorp.civicrm.hrcore/backstop_data/page-objects/modals/document.js, uk.co.compucorp.civicrm.hrcore/backstop_data/page-objects/modals/job-contract.js, uk.co.compucorp.civicrm.hrcore/backstop_data/page-objects/modals/task.js, uk.co.compucorp.civicrm.hrcore/backstop_data/page-objects/page.js, uk.co.compucorp.civicrm.hrcore/backstop_data/page-objects/tabs/job-contract.js, uk.co.compucorp.civicrm.hrcore/backstop_data/page-objects/tabs/job-roles.js, uk.co.compucorp.civicrm.hrcore/backstop_data/page-objects/tabs/tab.js, uk.co.compucorp.civicrm.hrcore/backstop_data/page-objects/tasks.js, uk.co.compucorp.civicrm.hrcore/backstop_data/scenarios/contact-edit-form.json, uk.co.compucorp.civicrm.hrcore/backstop_data/scenarios/styleguide.json, uk.co.compucorp.civicrm.hrcore/backstop_data/scenarios/ta-documents.json, uk.co.compucorp.civicrm.hrcore/backstop_data/utils/custom-casperjs.js, uk.co.compucorp.civicrm.hrcore/gulpfile.js
This PR contains the following:
1) Removed the styleguide backstopjs scenario, as now the styleguide extension itself will have that scenario (see [here](https://github.com/compucorp/org.civicrm.styleguide/pull/1))
2) Renamed `backstop:action` tasks in `backstopjs:action`
3) Added `backstopjs:approve` task
4) Now on page ready backstop will close the notification (if any) before taking a screenshot
5) Using the cid = 2 in all scenarios
6) Removed some of the scenarios for the Documents page (T&A), because of [this issue](https://github.com/ariya/phantomjs/issues/11151). PhantomJS has a bug with how it parses dates, and that leads the Documents page to not show any documents, which then leads to errors when CasperJS tries to click on documents that are not there. I don't know of any …
=> PCHR-2124: Remove styleguide backstop scenario + misc

org.civicrm.styleguide/styleguide.civix.php, org.civicrm.styleguide/styleguide.php
Loop over current defined menus and initializ 'child' index for the menu items that doesn't has the index defined. 
Before:
After:
=> AI-109: Fix styleguide error

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Adds a pull request template.
Each creator of a pull request defined their own structure for the description.
This template will be used as a suggested format for the description.
To see what the PR template looks like now check [here](https://github.com/civicrm/civihr/blob/PCHR-2159-pull-request-template/.github/PULL_REQUEST_TEMPLATE.md)
---
=> PCHR-2159: Add Pull Request Template

bin/drush-install.sh
If download.civicrm.org is down the `drush_install.sh` script will hang indefinitely
Add a timeout on the `wget` call, limiting the number of tries to 3 and the timeout each time to 60 seconds
Duplicate of https://github.com/civicrm/civihr/pull/1728 as branch was renamed
=> PCHR-2158 Add Timeout to Translation Fetching

uk.co.compucorp.civicrm.hrleaveandabsences/views/manager-leave/components/manager-leave-container.html, uk.co.compucorp.civicrm.hrleaveandabsences/views/my-leave/components/my-leave-container.html
After syncing 1.7 with 1.6, the dropdown on the "Record New Absence" is not opening anymore and the "Record Sickness" and "Record Overtime" options are not accessible
My Leave
Manager Leave
Not exactly sure why the dropdowns stopped working after 1.7 sync. As other dropdowns with `uib-dropdown` is working fine, added the same for `My Leave`& `Manager Leave`.
=> PCHR-2203: Fix dropdown for My/Manager Leave

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/WorkDay.php, uk.co.compucorp.civicrm.hrleaveandabsences/sql/auto_install.sql, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/WorkDayTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/xml/schema/CRM/HRLeaveAndAbsences/WorkDay.xml
When saving/editing a Work Pattern, it's possible to set the Leave Days amount for a working day. Currently, if you select any amount other than 1 Day, the saved amount will be incorrect.
When saving/editing the leave day amount for a working day in a Work Pattern other than 1 Day, the saved amount will be incorrect.
The reason for this is that the column for leave_days in the Work Day table is integer and some of the leave day values are float e.g 0.5 for Half day. When these values are saved, they get rounded up to integers in the database i.e 0.5 becomes 1 and 1.5 becomes 2.
This PR fixes that by changing the leave_days column to VARCHAR and also binding the column to the leave_days_amount option group. The obvious solution would have been to change to change the column type to decimal …
=> PCHR-2161: Fix issues with Leave Days amount is not saved correctly on a Work Pattern

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Factory/RequestNotificationTemplate.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Mail/Message.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestMailNotificationSender.php, uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Factory/RequestMailNotificationTemplateTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Mail/MessageTest.php
When a Leave Request is created/updated, Email notifications are sent out. However a Public holiday leave request is a special kind of leave request in that it is created by the system itself and not by a user. While running the Public Holiday scheduled job to create a leave request, I found an error in the Logs. This error is thrown because the system could not find an Email template for the Public Holiday Leave Request type. This PR makes sure that for Public Holiday leave requests, notifications are not sent since we are not supposed to send notifications for a Public Holiday Leave request
When running the Public Holiday Updates Schedule Jobs, this error is found in the Logs, 
`Call to a member function getTemplateID() on null in …
=> PCHR-2142: Fix error when running Public Holiday Updates Scheduled Job

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsenceType.php
When an action is performed on an Absence Type from the Absence Type listing page such as disabling/enabling or setting an absence type as default, the absence type loses the initial colour it had before the action was taken.
The reason for the colour of the Absence type being reset is that the AbsenceType BAO create method modifies the colour using this condition before it get saved in the database.
```php
$params['color'] = strtoupper($params['color']);
```
When an absence type is disabled, the payload to the Absence Type create API looks like this:
```php
civicrm_api3('AbsenceType', 'create', [
'id' => 1,
'is_active' => 0
]);
```
When being disabled/enabled, the colour parameter is not present but the colour parameter gets to be modified and ends up being set to null.
The condition to …
=> PCHR-2202:  Colour is reset when enabling/disabling an Absence Type from the list

uk.co.compucorp.civicrm.hrleaveandabsences/views/manager-leave/components/manager-leave-requests.html
Manager was not navigated to the correct page by using First/Last/Previous/Next buttons
This PR does not include BackstopJS tests as Manager Leave Report section is already covered.
=> PCHR-2201: Manager Leave pagination Fix

uk.co.compucorp.civicrm.hrcomments/CRM/HRComments/API/Query/CommentSelect.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Query/ContactSelect.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Query/LeaveRequestSelect.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Query/Select.php
Up until now, CiviHR 1.7 was based on CiviCRM 4.7.9. This PR updates it to follow the changes introduced since then and make it compatible with 4.7.18.
The only problem found was related to the usage of the `SelectQuery` class, used to create some custom get* APIs (e.g. `LeaveRequest.getFull`, `Contact.getManagess`, etc). On civicrm/civicrm-core#7725, a lot of changes to support APIv4 were introduced, including changes to this class, which now is abstract and cannot be instantiated, breaking any code which was using the `SelectQuery` class.
To fix this, the *Select classes now use the Api3SelectQuery class instead. For L&A, a new `CRM_HRLeaveAndAbsences_API_Query_Select` was added. It extends `Api3SelectQuery`, but introduces a new constructor which accepts the params array. Internally, …
=> PCHR-2113: Make CiviHR 1.7 compatible with CiviCRM 4.7.18

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsencePeriod.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsencePeriodTest.php
When attempting to create/update an absence period with same title as an already existing absence period, an error is displayed and the site crashes.
The title column of the absence period table is a unique field and this is what causes a exception of type `PEAR_Exception`to be thrown. Since the Absence Period form is expecting an error of type `InvalidAbsencePeriodException` to be thrown, the exception does not get to be handled.
A validation function to check for the existence of an absence period with same title as the one being created/updated was added and an exception of type `InvalidAbsencePeriodException` is thrown if such absence type is found. The exception is caught and the error message displayed appropriately.
=> PCHR-2200: Fix Uncaught Exception When Attempting to Create an Absence Period With Same Title

hrvisa/CRM/HRVisa/Activity.php, hrvisa/tests/phpunit/CRM/HRVisa/ActivityTest.php
One of the features of the hrvisa extension is to check for expired visas and, in case this is a required document and the existing one is expired, it creates Activities to "notify" the user that it has to be updated.
In order to do this, it first checks if such Activity already exists (to avoid spamming the user with duplicated activities) and it does that by looking for activities where the Contact of the expired visa is the target. This check was done by inspecting the `targets` property returned by the API, but since the changes introduced by https://github.com/civicrm/civicrm-core/pull/9841, `targets` is not returned anymore and the code was failing.
To fix this, I first thought about replacing `targets` with something else, but then I realized that this check is not required at all. …
=> PCHR-2113: hrvisa activity handling fixes

hrabsence/api/v3/Activity/Getabsences.php
After upgrading to CiviCRM 4.7.18, this error started being displayed on the contact summary page:
The was caused by a call to the `getAbsences` custom action of the Activity API. It uses the `_civicrm_api3_activity_get_formatResult` function, which had its signature changed by this commit:
https://github.com/civicrm/civicrm-core/commit/bc4b6f0f5694d1a5b8e2151e6dcf9a394c300df4#diff-7673c7d055caeab2a3ec5d05a1553293R395
Due to this change, any call to this action was resulting in a warning, because `getAbsences` was not passing the new third param added to the function.
This fixes the warning by fetching the options from the `$params` array and passing it to the function.
=> PCHR-2113: Fix warning on the Activity.getAbsences API

uk.co.compucorp.civicrm.hremails/email-templates/src/assets/scss/components/_email.scss
When using the `margin` mixin, the margin was erroneously set to 40px instead of 40px 0, resulting in the email being decentered horizontally
=> PCHR-2197: Apply correct margin to .email

uk.co.compucorp.civicrm.hremails/email-templates/dist/leave-request.html, uk.co.compucorp.civicrm.hremails/email-templates/src/assets/scss/app.scss, uk.co.compucorp.civicrm.hremails/email-templates/src/assets/scss/components/_request.scss, uk.co.compucorp.civicrm.hremails/email-templates/src/layouts/leave-absences.html, uk.co.compucorp.civicrm.hremails/email-templates/src/pages/leave-request.html, uk.co.compucorp.civicrm.hrleaveandabsences/managed_entities/EmailTemplate.mgd.php
Adding the email template for a leave request
* A new layout has been created, called `leave-request.html`. The idea is that all L&A emails will share the same layout, which might (still not sure) be different from the layout rest the other emails
* The whole request is a component, called `.request`. In it we have different elements like `.request-comment`, `.request-attachment`, etc
There is a problem with additional margin at the bottom of the comments and files list. We can't use pseudo-selectors like or `:not(:last-child)` (for example to say that every comment except the last one should have a bottom margin), because of two reasons
1) The css is always applied inline to the markup when the production-ready template is created (basically there is no css that can be applied …
=> PCHR-2197: Responsive email templates for L&A

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php
When trying to accrue TOIL for an absence type whose current balance is Zero for that period, It returns an error that the Leave Request Balance change is greater that the remaining balance for the absence type. This error is actually valid for a leave request especially if the absence type does not allow overuse but employee should be able to accrue TOIL even if current balance is Zero provided the other validations for accruing TOIL passes.
This PR also fixes an issue whereby TOIL can not be accrued when there is no working day for the TOIL request. Since an employee may want to accrue TOIL for days that are non-working days.
Trying to accrue TOIL when the current balance change for the absence type for the period is Zero returns an error.
Trying to accrue TOIL when the TOIL request has …
=> PCHR-2209: Fix bug with requesting TOIL when current Entitlement Balance is Zero

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestStatusMatrix.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestStatusMatrixTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
Currently when an Admin or Leave manager tries to request leave, an error is returned that the leave request cannot be created. This is due to the fact that the Manager Status transition matrix is used when making the request and it does not allow a transition from 'No status' to 'Awaiting Approval' Status(The default status set for a new leave request).  [See Matrix Here](https://compucorp.atlassian.net/browse/PCHR-1825)
When an Admin or Leave Manager requests leave for themselves or on behalf of a Staff member, the Manager Status Matrix is used.
An Admin or Leave Manager cannot request leave for themselves.
Changes were made such that when an Admin or Leave Manager requests  leave for themselves, the Staff Status transition matrix is used since at this point they are requesting leave as …
=> PCHR-2207: Fix issues with Admin or Leave Manager not being able to create Leave Request for themselves

uk.co.compucorp.civicrm.hremails/email-templates/src/assets/scss/app.scss, uk.co.compucorp.civicrm.hremails/email-templates/src/assets/scss/components/_buttons.scss, uk.co.compucorp.civicrm.hremails/email-templates/src/assets/scss/components/_callout.scss, uk.co.compucorp.civicrm.hremails/email-templates/src/assets/scss/mixins/_buttons.scss, uk.co.compucorp.civicrm.hremails/email-templates/src/assets/scss/mixins/_margin.scss
This PR contains fixes for the Outlook desktop and web client, so that it can render the email templates as expected
https://github.com/zurb/foundation-emails/issues/416
Solution described in [this comment](https://github.com/zurb/foundation-emails/issues/416#issuecomment-249432270) had been implemented
https://github.com/zurb/foundation-emails/issues/415
Solution described in [this comment](https://github.com/zurb/foundation-emails/issues/415) had been implemented
https://litmus.com/help/email-clients/outlookcom-margins/
So apparently Outlook decides to strip margins for block elements (or at least for `<table>`s). So from now on if we need to put a bottom margin after a `<callout>`, we need to use `<spacer>`. The margin had been removed from the callout to avoid inconsistency with the …
=> PCHR-2198: emails framework amendments

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/AbsencePeriod.php
When the 'Manage Entitlement' action for an absence period is clicked Instead of leading to the Entitlement Calculation page, It does not respond and some errors appear in the console. 
The Absence Period listing page requires a core JS file 'jquery.crmEditable.js' which used to be loaded by default in Civicrm version 4.7.9 but now is no longer loaded by default in Civicrm version 4.7.18.
The 'jquery.crmEditable.js' file is loaded for the Absence Period listing page.
=> PCHR-2217: Fix Issues with "Manage Entitlements" action on the Absence Period list

uk.co.compucorp.civicrm.hremails/email-templates/dist/leave-request.html, uk.co.compucorp.civicrm.hremails/email-templates/dist/toil-request.html, uk.co.compucorp.civicrm.hremails/email-templates/src/assets/scss/components/_request.scss, uk.co.compucorp.civicrm.hremails/email-templates/src/pages/leave-request.html, uk.co.compucorp.civicrm.hremails/email-templates/src/pages/toil-request.html, uk.co.compucorp.civicrm.hremails/email-templates/src/partials/la-footer.html, uk.co.compucorp.civicrm.hremails/email-templates/src/partials/request-attachment.html, uk.co.compucorp.civicrm.hremails/email-templates/src/partials/request-comment.html, uk.co.compucorp.civicrm.hremails/email-templates/src/partials/request-data.html, uk.co.compucorp.civicrm.hrleaveandabsences/managed_entities/EmailTemplate.mgd.php
This PR adds the TOIL Request email template and refactors some of the code shared between the different L&A emails
To avoid rendering issues in different email clients, the `request-comment` component had been turned into a table
**Before**
```html
<div class="request-comment">
<div class="request-comment-header">
<span class="request-comment-author">{$value.commenter}:</span>
<span class="request-comment-datetime">{$value.created_at|crmDate}</span>
</div>
<div class="request-comment-body">
{$value.text}
</div>
</div>
```
**After**
```html
<tbody>
<tr>
<td class="request-comment-header">
<span class="request-comment-author">{$value.commenter}:</span>
<span class="request-comment-datetime">{$value.created_at|crmDate}</span>
</td>
</tr>
<tr>
<td class="request-comment-body">
{$value.text} …
```
=> PCHR-2198: Responsive email templates for TOIL Request

hrcase/CRM/HRCase/Upgrader.php, hrjobcontract/CRM/Hrjobcontract/Test/Fabricator/HRHoursLocation.php, hrjobcontract/CRM/Hrjobcontract/Test/Fabricator/HRPayScale.php, hrjobcontract/CRM/Hrjobcontract/Upgrader.php, hrjobcontract/tests/phpunit/CRM/Hrjobcontract/Import/Parser/ApiTest.php, hrui/CRM/HRUI/Upgrader/Steps/4701.php, hrui/tests/phpunit/CRM/HRUI/HelperTest.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1000.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1001.php
Some tests of hrjobcontract and hrui extension were failing due to the changes introduced in PCHR-1687.
Tests for hrjobcontract and hrui extensions were failing, since they relied on values that were removed in upgrades created for PCHR-1687.  Also, some warnings were being thrown by upgrades, when trying to access non-existing array keys.  Upgrade 1000 of hrcore extension was also failing on tests.
Fixed by using constructors to create missing values for tests, implementing checks prior to access array values and updating tests setup to install required extensions.  Fixed upgrade 1000 of hrcore installation by including the name of the file being downloaded.
---
=> PCHR-1687: Fix Failing Tests

hrcase/CRM/Case/BAO/CaseType.php, hrrecruitment/xml/case/Application.xml
Removing the XML that adds the Application worked to remove this case type. However, when installing the hrrecruitment extension it depends on the Application case type to install some custom groups.
This was merged in #1782 but should be reverted until we figure out the best approach.
You can see the [diff](https://github.com/civicrm/civihr/compare/ee26142b80240db7dcc205b975ebba5eb1558472...hotfix/undo-PCHR-1928-changes) from the last commit before #1782 was merged and this branch show that the only changed files are the JS files from Debarshi's ticket.
`civibuild` will fail because it tries to create custom fields that depend on the Application case type.
`civibuild` will work. 
It reverts all changes from #1728 (except deletion of commented code which I didn't think was worth …
=> Re-add the Application XML and CaseType override

uk.co.compucorp.civicrm.hremails/email-templates/dist/leave-request.civicrm.html, uk.co.compucorp.civicrm.hremails/email-templates/dist/sickness-request.civicrm.html, uk.co.compucorp.civicrm.hremails/email-templates/dist/toil-request.civicrm.html, uk.co.compucorp.civicrm.hremails/email-templates/src/pages/leave-request.civicrm.html, uk.co.compucorp.civicrm.hremails/email-templates/src/pages/sickness-request.civicrm.html, uk.co.compucorp.civicrm.hremails/email-templates/src/pages/toil-request.civicrm.html, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Mail/Message.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Mail/Template/BaseRequestNotification.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Mail/Template/SicknessRequestNotification.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestMailNotificationSender.php, uk.co.compucorp.civicrm.hrleaveandabsences/managed_entities/EmailTemplate.mgd.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Mail/MessageTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Mail/Template/LeaveRequestNotificationTemplateTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Mail/Template/SicknessRequestNotificationTemplateTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Mail/Template/TOILRequestNotificationTemplateTest.php
When an Email Notification is sent for a Leave Request, The leave request link in the email is the same regardless of whether the recipient is the Staff or Leave Manager. The link is supposed to lead to `my-leave` page for a Staff member and `manager-leave` page for the Leave manager.
This PR also adds the Absence Type Name parameter to the Email templates and also the Sickness reason parameter is now passed directly to Sickness Email template.
The Leave request link is the same for a staff and a leave manager.
The Absence type name is a static value in the email templates.
The Sickness reason parameter was not passed directly to the template.
The leave request link in the email templates is now determined by who the recipient is i.e whether a Staff or Leave manager.
The Absence Type name …
=> PCHR-2142: Fix Leave Request Link. Add some more parameters to Email Templates

uk.co.compucorp.civicrm.hremails/email-templates/dist/leave-request.civicrm.html, uk.co.compucorp.civicrm.hremails/email-templates/dist/sickness-request.civicrm.html, uk.co.compucorp.civicrm.hremails/email-templates/dist/toil-request.civicrm.html, uk.co.compucorp.civicrm.hremails/email-templates/src/pages/leave-request.civicrm.html, uk.co.compucorp.civicrm.hremails/email-templates/src/pages/sickness-request.civicrm.html, uk.co.compucorp.civicrm.hremails/email-templates/src/pages/toil-request.civicrm.html, uk.co.compucorp.civicrm.hrleaveandabsences/managed_entities/EmailTemplate.mgd.php
The single quotes passed to the `truncate` filters weren't escaped, causing a PHP syntax error when the templates were read in the EmailTemplate.mgd.php file
```html
<span>{$fromDate|truncate:10:''|crmDate} {$fromDateType}</span>
```
```html
<span>{$fromDate|truncate:10:\'\'|crmDate} {$fromDateType}</span>
```
=> PCHR-2199: Escape single quotes in templates

.githooks/pre-commit
This PR adds a sharable pre-commit hook that will run the "[JavaScript Semi-Standard Style](https://github.com/Flet/semistandard)" linter on any non-minified javascript file that is about to get committed.
For the time being if the linter throws an error the dev simply gets a warning, but the idea is that in a month time (just to make sure that there is no flaw in the process) the hook will reject the commit altogether.
The reason for using https://github.com/Flet/semistandard instead of https://github.com/feross/standard is simply that the former doesn't have the insane "no semicolons" rule
Below is an annotated example of the hook in action
```shell
$ git s
On branch PCHR-2262-precommit-js-styleguide
Changes to be committed:
(use "git reset HEAD <file>..." to unstage)
modified: …
```
=> PCHR-2262: Add pre-commit hook to check for JS style

hrjobcontract/CRM/Hrjobcontract/Upgrader.php
An upgrade for hrjobcontract extension was throwing an exception when being ran on some environments, where the particular fix it was trying to apply was already implemented.
On some installations, civicrm_hrhours_location table was being created without defining the id field as a primary key and not setting it as autonumeric, which made it all but impossible to add new records to it, via the front-end of civihr. To solve this problem, an upgrader was created to add the constraints to the table. However, staging environment, among others, already had the fix, which caused a DB error when the upgrader tried to add the primary key again.
Fixed by catching the exception, and throwing it only if primary key and autonumeric has not been set for the id field in the table.
---
=> PCHR-1687: Catch Exception When Creating PK for Hours Location Table

uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/ApiPermissionTest.php
Trying to delete a LeaveRequest or a Comment using the API and the check_permissions option enabled (which is the case when you use Javascript for API calls), would result in an error saying that the "administer CiviCRM" permission was required
The L&A extension sets "access AJAX Api" as the only permission required for a list of APIs it uses. LeaveRequest.delete and Comment.delete were missing from this list.
The list was updated to set the proper required permission for LeaveRequest.delete and Comment.delete. 
---
=> PCHR-2265: Fix permissions required for the delete action of the LeaveRequest and Comment APIs

.githooks/pre-commit
Updated pre commit hook from 
`semistandard  "$files" --verbose | snazzy`
to
`semistandard --global inject --global CRM --verbose "$files" | snazzy`
This will avoid declaring inject/CRM globals manually or in files.
=> PCHR-1344: Add env and global options for semistandard

hrjobcontract/CRM/Hrjobcontract/BAO/HRJobContract.php, hrjobcontract/api/v3/HRJobContract.php, hrjobcontract/tests/phpunit/CRM/Hrjobcontract/BAO/HRJobContractTest.php, hrjobcontract/tests/phpunit/api/v3/HRJobContractTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/ContactWorkPattern.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/WorkPattern.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Queue/Task/UpdateAllFuturePublicHolidayLeaveRequestsForWorkPatternContacts.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/JobContract.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreation.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestDeletion.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/ContactWorkPatternTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/WorkPatternTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/JobContractTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreationTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestDeletionTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestTest.php
The amount deducted for a Public Holiday Leave request is gotten from the leave day amount on the Work Pattern that a contact is using. It is therefore necessary to update Public Holiday Leave requests in the future when a Work Pattern changes so that the amount deducted for these requests can be kept in sync with appropriate amount to be deducted based on the leave day amount. 
When a Work Pattern is updated, Public Holiday Leave requests in the future are not updated.
When a Work Pattern is updated, Public Holiday Leave requests in the future are updated.
Rather than update Public Holiday Leave Requests for all contacts when a Work Pattern is updated, for WorkPatterns that is not the default and is used or will be used by some contacts in the future , Public Holiday Leave Requests are …
=> PCHR-2246: Changes to a Work Pattern does not reflect on Public Holiday Leave Request

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/WorkPatternCalendar.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/WorkPatternTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/WorkPatternCalendarTest.php
WorkPattern.getCalendar API returns the calendar dates for a contact for a given period. The dates returned are dates for which the contact has an active contract.
For a contact that has an active contract for a given period that spans over a year, 365 calendar dates are supposed to be returned but the API returns inconsistent results for this on different environments like staging, test sites, local.
The WorkPattern.getCalendar API returns inconsistent results.
The reason for this is that the API fetches all the existing contracts for all contacts in the system for the period and uses that to calculate calendar dates for a contact instead of fetching just the contracts for the contact.
Results returned by the The WorkPattern.getCalendar API is now consistent.
The API was changed to fetch …
=> PCHR-2241: Fix issues with WorkPattern.getCalendar API returning inconsistent results

hrcase/CRM/HRCase/Upgrader.php, hrui/hrui.php, hrui/tests/phpunit/CRM/HRUI/HelperTest.php, hrui/tests/phpunit/HRUITrait.php, uk.co.compucorp.civicrm.hrcore/hrcore.php
All option values have a "value" field which acts like their ID. If this value is changed it could cause major problems since it acts like a database foreign key. For example changing the "value" for an absence type would change all absences created in the system that point to that absence type. The aim of this PR is to hide the option to edit the value.
From the admin option edit screen (/civicrm/admin/options) you can change the value.
From the admin option edit screen (/civicrm/admin/options) the value field is not displayed.
=> PCHR-1826: Hide Option Value Edit Field

uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php
When the Leave and Absence civiHR extension is disabled/uninstalled, the Leave manager can still see Manager Leave and My Leave page on the SSP. The reason is that it is the Employee portal module that creates the permissions that is needed to see this pages. This PR allows the L&A extension to create these permissions itself.
The L&A extension does not create the permissions for accessing Manager Leave and My Leave page on the SSP.
The L&A extension creates the permissions for accessing Manager Leave and My Leave page on the SSP.
=> PCHR-2196: Add permissions for accessing my leave and leave manager page on SSP

hrui/templates/CRM/common/footer.tpl
Add "User guide" link to civicrm pages which links to "http://civihr-documentation.readthedocs.io/en/latest/"
=> PCHR-2213: Add user guide link in civicrm pages

uk.co.compucorp.civicrm.hrcore/backstop_data/casper_scripts/documents/document/pick-due-date.js, uk.co.compucorp.civicrm.hrcore/backstop_data/casper_scripts/documents/document/select-assignee.js, uk.co.compucorp.civicrm.hrcore/backstop_data/casper_scripts/documents/document/show-all-fields.js, uk.co.compucorp.civicrm.hrcore/backstop_data/page-objects/modals/document.js
Since, the layout of the the New Document Modal in Task and Assignment is modified as per the new requirement, previous test cases need to be updated work with new changes.
(Previous and after screenshot of modal can be seen in backstopjs tests screenshot below)
1. `/casper_scripts/documents/document/pick-due-date.js` and `/casper_scripts/documents/document/select-assignee.js` files are modified to open respective tab before selecting the fields.
2. `/casper_scripts/documents/document/show-all-fields.js` `showMore()` function is removed as now there is no section for show more fields.
3. Updated the selector in `/page-objects/modals/document.js` while selecting assignee. And added `showTab(tabName)` function to show respective tab based on `tabName`
4. Backstopjs Tests:
Following failed …
=> PCHR-2145: Update backstopjs tests to reflect new changes in document modal

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/PublicHoliday.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreation.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestDeletion.php, uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/PublicHolidayTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreationTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestDeletionTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestTest.php
Currently creating a Public Holiday with past dates is not allowed as it would involve creating Public Holiday Leave requests for employees for that date (If MTPHL is true) and this will impact on things like Entitlements, Brought Forward, Expired balance Changes and so on, However there are some valid reasons why this may be necessary, one of such is when migrating data from an old system to use the new L&A it may be necessary to create past public holidays for contacts, also when creating a contract for an employee and the contract is created after the dates for some public holidays have passed but those public holidays are supposed to be included in the contract.
The system does not allow creating Public Holidays in the past and also does not allow creating past public holidays within …
=> PCHR-2235: Allow Public Holidays/Public Holiday Leave Requests With Past Dates To be Created

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreation.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreationTest.php
When running the Public Holidays batch job after setting Must Take Public Holiday Leave Requests set to No for an absence type right after creating a Public Holiday, the job is unable to run and an error is displayed. This is because the function responsible for creating Public Holiday leave requests for all contacts does not return early if it does not find an Absence type with MTPHL set to Yes.
The function responsible for creating Public Holiday leave requests for all contacts does not return early if it does not find an Absence type with MTPHL set to Yes.
The function responsible for creating Public Holiday leave requests for all contacts returns if it does not find an Absence type with MTPHL set to Yes.
=> PCHR-2278: Fix crash when running Public Holiday Job when no Absence Type with MTPHL exists

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/PublicHoliday.php
When the 'Delete' action for a Public Holiday on the Public Holidays listing page is clicked Instead of the Public Holiday being deleted, It does not respond and some errors appear in the console.
The Public Holidays listing page requires a core JS file 'jquery.crmEditable.js' which used to be loaded by default in Civicrm version 4.7.9 but now is no longer loaded by default in Civicrm version 4.7.18.
The 'jquery.crmEditable.js' file is loaded for the Public Holidays listing page.
=> PCHR-2292: Fix Issues being unable to delete a Public Holiday

uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/manager-leave/components/manager-leave-requests.js, uk.co.compucorp.civicrm.hrleaveandabsences/views/manager-leave/components/manager-leave-requests.html
Added approve and reject shortcuts to actions dropdown
In order to approve/reject a leave you needed to click "Respond", then select an according status from a dropdown and then Save the status of leave.
Now along with "Respond" you have "Approve" and "Reject" options which are followed by a simple confirmation popup.
- Utilised leave.reject() and leave.approve() functions. 
- Refactored the code and remove repetition, use maps.
- Changed ng-if to ng-switch in both JS and template files for better code readability.
- Selected appropriate colors for approval/rejection comparing to a red cancellation (cannot be undone) color.
- TODO: once Angular is updated to 1.5.10 ng-switch-when "approve|reject|cancel" syntax should be used in order to reduce the code.
=> PCHR-2238: Add approve and reject shortcuts

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestRights.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestRightsTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestTest.php
Currently A Leave manager  can only edit the dates of a Sickness Request when it is in an Open status (Awaiting Approval or More Information Required). This PR removes that restriction.
A Leave manager can only edit the dates of a Sickness Request when it is in an Open status.
A Leave manager can edit the dates of a Sickness Request in any status provided all other validation rules pass.
=> PCHR-2167:  Allow Leave Manager to Edit Sickness Request dates For all Statuses

uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php
Currently when adding a relationship for a contact, it is possible to add a Leave Approver relationship with between a contact and itself. For the case of a Leave manager, this would allow the manager view his/her own leave requests in the manage leave page. 
A contact can be assigned a Leave Approver relationship with itself.
A contact cannot be assigned a Leave Approver relationship with itself.
---
=> PCHR-2180: Fix issue with Manager being able to view own leave requests

org.civicrm.reqangular/dist/reqangular.min.js, org.civicrm.reqangular/src/common/models/contact.js, org.civicrm.reqangular/src/common/services/api.js
Remove chained API calls from base `API`while getting count of total number of records.
1. In Base API's `getAll()` the same API call is made twice, 1st call is made only to get specific no of records according to pagination setup, and the 2nd call is made to get all the data to determine no of pages for `pagination`. The 2nd call does not need to have the chained API calls as it only cares about total no of records and not the actual data. So removing the chained API calls will improve performance.
```javascript
_.omit(params, function (__, key) { return _.startsWith(key, 'api.'); });
```
---
=> PCHR-2249: Remove chained API calls while getting count

hrcase/CRM/HRCase/Upgrader.php
A merge conflict caused an upgrader in the hrcase extension to produce warnings when being run.
The hrcase upgrader caused "Invalid argument supplied for foreach()" warnings. The upgrader was likely not functioning as expected.
The upgrader runs as expected and without warnings.
---
hrcase only has a broken selinium test :cry:
=> PCHR-2300: Fix Merge Conflict

uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/controllers/request-ctrl.js, uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/controllers/sub-controllers/leave-request-ctrl.js, uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/controllers/sub-controllers/leave-request-ctrl_test.js
The absence types which does allow to have Accrual Requests(TOIL) , are not visible in the Record New Absence popup's Dropdown.
1. in `leave-request-ctrl.js` `allow_accruals_request` was set to false, which means the popup will not display such absence types in the dropdown. It was wrong so removed it.
2. Code has been refactored, 
- `self` replaced by `bind`
- `initAbsenceType()` renamed to more meaningful `setInitialAbsenceTypes()`
- `canViewOrEdit()` removed as it is not required, and in most cases `!this.isMode('create')` is used instead of `canViewOrEdit()`, as both means same.
**Screenshot**
Still there is a issue when we first select TOIL and then click on Single Day, the dropdown values is being reset to Holiday. This is because `changeInNoOfDays()` function internally calls …
=> PCHR-2227: TOIL not showing up in Record New Absence Popup

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
When a  Leave request is to be created/updated and It fails validation, the error message is displayed in a red bar, at the bottom of the Leave Request modal. This PR modifies the error message sent from the back end for these validations to conform to that described in the L&A Wireframe document. 
Also currently the error code for the leave request validation exception that is thrown when a validation fails is sent to the Frontend. This PR changes this to send the Error message because it is user friendly and more readable.
The L&A leave request validation alerts does not conform to that described in the L&A Wireframe document.
The Back end sends error code for the validation exception to the Frontend.
The L&A leave request validation alerts conforms to that described in the L&A …
=> PCHR-2275: Modify Leave And Absence Alerts To Conform to What is in WireFrame

hrjobcontract/views/modalForm.html
While creating new contract, in the Leave tab, if the input boxes for Entitlement are clicked and then deselected, numbers are shown as floating point even though the number is an integer. Floating points should not be shown until the number is a float.
Added `hrjc-number-float="true"` in the HTML which takes care of this scenario.
=> PCHR-2236: Dont display decimals for contracts entitlements

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/ManageEntitlements.php, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/ManageEntitlements.tpl
Once you create a contract you are redirected to Manage Leave Entitlements page. This page has a back button and it redirected to Contact Summary tab instead of Job Contract tab.
Back button redirected to Contact Summary tab.
Back button redirects to Job Contract tab.
Back button's href was changed from javascript:history.back() to {$smarty.get.returnUrl}. "returnUrl" is simply a get query param that we already have in the URL on the Manage Leave Entitlements page. We use $smarty instead of $_GET['returnUrl'] because $_GET will simply not work.
Since this is a tpl file that was changed, there are no tests to pass.
---
=> PCHR-2215: Back button on Manage Leave Entitlements page doesn't redirect to the contract

.githooks/pre-commit, package.json
For reasons I wasn't able to identify, using `semistandard "$files" --verbose` randomly fails, not catching style errors of files that are about to be committed
Also common globals should not be declared inline in the hook, otherwise manual `semistandard` invocations might end up giving a different output than the hook
1. Using `semistandard $files --verbose | snazzy` (so `$files` instead of `"$files"`) seems to solve the problem with random linter failures when committing files with style errors
2. Created a `package.json` file with the global declarations
3. As a bonus, added messages informing when the linter starts and if the linter didn't find any error
=> PCHR-2303: Improve semistandard hook

hrjobcontract/CRM/Hrjobcontract/Import/Parser/Api.php, hrjobcontract/tests/phpunit/CRM/Hrjobcontract/Import/Parser/ApiTest.php
Importing contracts with 'Full Time' hours type was rendering blank FTE's, that were able to be fixed by editing the contract and saving with no modifications.
When importing contracts with Full Time Hours Type, Actual Hours amount is not and should not be given, as it should be calculated from the selected hours location instead.  However, when importing, hours amount was being left blank, causing FTE to be blank also.
Added a check for hours type when calculating automatic values, so that when 'Full Time' hours type is selected for the contract being imported, the value of the number of hours is copied from the standard hours configured in the hours/location.
Added a test that asserts when 'Full Time' hours type is used, the value of hours_amount is equal to the value of standard_hours. …
=> PCHR-2154: Fix FTE Calculation on Import of Full Time Hours Type

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/APIWrapper/DefaultLimitRemover.php, uk.co.compucorp.civicrm.hrcore/hrcore.php, uk.co.compucorp.civicrm.hrcore/phpunit.xml.dist, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/APIWrapper/DefaultLimitRemoverTest.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/bootstrap.php
CiviCRM API has by a default a limit of 25 results when doing a "get" action and when there is no limit specified. This could cause problems specially when some developers forget this fact so its better to remove the limit and whenever the developer need any limit on the results then he can just add the limit as a parameter to the API.
If no limit specified , all "get" API calls return only the first 25 results.
If not limit specified , all the results appear and not just the first 25 :
also if the limit specified  , it should still works fine as before : 
I've implemented [hook_civicrm_apiWrappers ](https://docs.civicrm.org/dev/en/master/hooks/hook_civicrm_apiWrappers/) hook inside hrcore extension and defined a wrapper class called CRM_HRCore_APIWrapper_DefaultLimitRemover  that take …
=> PCHR-2219: Remove the default API limit

hrjobcontract/CRM/Hrjobcontract/DAO/HRJobContractRevision.php
Job contract history table does not show Pay scale, Total salary and Hours type data. Depending on the contact, it is possible that it shows contract details for another unrelated contact.
1- Create a new contact
2- Add a contract with pay and hour details
3- Update terms and create a new revision but just change the position title
4- Update terms again but only update pay
5- Refresh the page. The latest revision in "Full History" will not show pay details
1- Create a new contact
2- Add a contract with pay and hour details
3- Update terms and create a new revision but just change the position title
4- Update terms again but only update pay
5- Refresh the page. The latest revision in "Full History" will still show all the current details.
When getting a given job contract entity data (such …
=> PCHR-1877 : Changing foreign keys join columns from ID to jobcontract_revision_id for HRJobContractRevision entity

com.civicrm.hrjobroles/hrjobroles.php, contactsummary/contactsummary.php, hrabsence/hrabsence.php, hrident/hrident.php, hrjobcontract/hrjobcontract.php, hrqual/hrqual.php, hrrecruitment/hrrecruitment.php, hrvisa/hrvisa.php
Implementing 'hook_civicrm_tabset' instead of 'hook_civic…rm_tabs' as it's deprecated in CiviCRM 4.7.
Includes changes for extensions below:
- hrjobroles
- contactsummary
- hrabsence
- hrident
- hrjobcontract
- hrqual
- hrrecruitment
- hrvisa
=> PCHR-1604 - Update extensions to use hook_civicrm_tabset instead of hook_civicrm_tabs

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/WorkPatternCalendar.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/WorkPatternCalendarTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/WorkPatternTest.php
Currently when viewing the calendar view as a manager, the calendar does not show up for contacts without a contract. This is because the logic for returning the calendar for a contact depends on the contact having an active contract.
Contacts without contracts does not have calendar dates returned for the period selected
The main reason why the contract is needed is for contacts using work pattern with multiple weeks, we need the contract dates to determine the effective date for the work pattern.
Contacts without contracts now have calendar dates returned for the period selected. The calendar dates are based off the contacts work pattern and for dates where the contact's work pattern is not active, the default work pattern is used.
Initially, the route to fix this problem was to …
=> PCHR-2298: Fix Issue with Calendar Not Showing Up for a Contact Without A Contract

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php
This PR optimizes the validations that a leave request goes through before getting saved in the database. Aside gain in performance, the intention is also that this will help minimize race conditions currently experienced when same leave request is saves simultaneously and inserted more than once in the database as the validations take time to run else the possibility of having more that one leave request get to the database.
Other options are currently being explored to solve the race condition issue. See [Here](https://gist.github.com/tunbola/515a1cbe70961e70907894a098a176d4)
- Some commonly used objects like Absence Type, Absence Period are now fetched once and passed to required validation functions that need them. 
- Instead of using API to communicate with the Job contract extension …
=> PCHR-2260: Optimize Leave Request Validations

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/AbstractDrupalInteractionTaskForm.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/CreateUserRecordTaskForm.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/SendInvitationEmailTaskForm.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Service/DrupalUserService.php, uk.co.compucorp.civicrm.hrcore/hrcore.php, uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/SendInvitationEmailTaskForm.tpl
After user accounts are created in bulk without an invitation email being sent, there should be a way to send out invitation email in bulk.
There wasn't a way to send invitation e-mails to contacts created by importing a file.
Added an action on the Advanced Search form to send invitation e-mail to selected contacts.
---
=> PCHR-2150: Bulk Sending of Invitation Mails

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php
In a scenario where you cannot use more than your remaining balance, and it also has half days (say 1.5), if you request a Leave Request with the same amount, the validation would fail, saying you cannot use more than the remaining balance
During the Leave Request validation, we pass the `$params` array to the `calculateBalanceChangeFromParams` method, which would then convert the `from_date_type` and `to_date_type` values to option values arrays (containing labels, values and names). These arrays would be passed to the `calculateBalanceChange` method, where the calculation actually happens. This method expects the date types as values though, not as arrays. Whenever it get the values in an unexpected format, it would consider it to be a full day. So, when …
=> PCHR-2134: Allow a LeaveRequest with half day to use all the remaining balance

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1000.php, uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/controllers/request-ctrl.js, uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/mocks/data/leave-request-data.js, uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/mocks/data/option-group-mock-data.js, uk.co.compucorp.civicrm.hrleaveandabsences/xml/option_groups/leave_request_day_type_install.xml
The labels were updated to:
- "1/2 AM":  "Half-day AM"
- "1/2 PM":  "Half-day PM"
---
=> PCHR-2345: Update labels of "1/2 AM" and "1/2 PM" option values

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/ContactWorkPattern.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Exception/InvalidContactWorkPatternException.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/ContactWorkPatternTest.php
The DB schema of the ContactWorkPattern has a unique key that prevents the creation of two records with the same contact_id and effective_date. If you use the API and try to create such a duplicate record, it will respond with a cryptic "DB Error: already exists message" and also the faulty SQL query, in case debug was enabled.
The response of the ContactWorkPattern.create API that would create a duplicate record would look like this:
```json
{
"error_code": "already exists",
"sql": "INSERT INTO civicrm_hrleaveandabsences_contact_work_pattern (contact_id , pattern_id , effective_date ) VALUES ( 204 ,  1 ,  20160607000000 )  [nativecode=1062 ** Duplicate entry '204-2016-06-07' for key 'unique_pattern_per_effective_date']",
"tip": "add debug=1 to your API call to have more info about the …
```
=> PCHR-2352: Better error handling duplicated ContactWorkPattern

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/CreateUserRecordTaskForm.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Service/DrupalUserService.php, uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/CreateUserRecordTaskForm.tpl
It is possible to create a user record with an valid email that does not match the drupal username validation rules, for example "foo+1@bar.com"
You can create a user record from the form that doesn't have a valid username. Attempts to update that user later from the Drupal admin area will fail.
The username and email are validated before creation of user records. Validation failures are displayed with an explanatory message.
- The PR was created as a replacement for #1971 as it used the wrong branch name
=> PCHR-2149: Validate Username and email

hrreport/CRM/HRReport/Form/Activity/HRAbsenceDates.mgd.php, hrreport/CRM/HRReport/Form/Activity/HRAbsenceDates.php, hrreport/templates/CRM/HRReport/Form/Activity/HRAbsenceDates.tpl
We need to import data from the old Absence extension into the new Leave and Absence extension. The current Absence report in the Absence extension lists each leave request on a single line with a sum of the amount deducted for the leave requests rather than listing each leave dates on its own line with the amount deducted for each date. 
This new Absence Dates report is a modified version of the Absence Report that lists the leave dates on its own line, removes some un-needed columns also add some new columns that is necessary for data import into L&A extension.
The Absence Dates report has the following columns:
- Absence ID(The ID that identifies leave dates belonging to the same group)
- ContactID
- Absence Type
- Absence Date
- Qty(Amount Deducted for the date)
- Status
- Comment
And …
=> PCHR-2336: Create Absence Dates Report.

hrui/CRM/HRUI/Upgrader.php, hrui/CRM/HRUI/Upgrader/Steps/4705.php
Dropdown select Social Account Type on contact edit view was showing no values,
Option group for Social Account Type (name: website_type) was inadvertently disabled by a previous upgrade (4702 of HRUI extension) when making a chained create call to change the option group title from "Website Type" to "Social Account Type".
Fixed by adding an upgrader to activate the website_type option group.
---
=> PCHR-2316: Fix Social Account Type Dropdown

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/Pre/PrimaryAddressSetter.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1004.php, uk.co.compucorp.civicrm.hrcore/hrcore.php
When an administrator creates a new contact, addresses may have one of several different location types. The system will allow him to add several different addresses (one for each location type) and set one of them as primary. This conflicted with the logic implemented in the SSP, where it is required for the 'Home' address to be the primary address for the contact in order to be able to view and edit the contact's personal information.
The problem was SSP uses 'Home' location type to look for the address to be used on the dashboard and the My Details edit view, making the assumption this 'Home' address is also the contact's primary address. If the contact did not have the 'Home' address set as primary, but some other address, saving the address through the SSP effectively saved the …
=> PCHR-2340: Set 'Home' as Default Location and Primary Address

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/ManageEntitlements.php
When a contract with future date is added for a contact and after saving the contract and upon redirection to the Manage entitlement page, the entitlement page is blank for the period that the future contract is active in.
Entitlement cannot be updated for Contacts having contracts with future dates.
The reason for the Management entitlement page being empty is because the start and end dates of the absence period was not properly passed to the `HrJobContract.getcontactswithcontractsinperiod` and the API was using the value of the current present date as the start and end date (see [Here](https://github.com/civicrm/civihr/blob/a3a8ec3d4aedc9d749b9d32fda05b3432707ab97/hrjobcontract/CRM/Hrjobcontract/BAO/HRJobContract.php#L649-L649)) to find contacts with contracts so for Contacts whose …
=> PCHR-2382: Fix bug causing Contacts with future Contract Dates not being displayed in Manage Entitlement page

uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/staff-leave-report.html
As a Staff, on the My Leave report section the TOIL requests are missing their expiry date label according to Invision mock:
https://projects.invisionapp.com/share/WX71LBMPJ#/screens/157876104
This PR fixes that issue.
The `toil_expiry_date` was used to display the expiry date and the format comes from the `report.dateFormat` setting.
---
=> PCHR-2388: display expiry date for TOIL requests on My Leave

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1000.php
Installing the extension on a new site will result in an error saying that `hrleaveandabsences_leave_request_day_type' is not a valid option for field option_group_id`. The error started after one of the changes introduced by https://github.com/civicrm/civihr/pull/1983, where we now run all the upgraders during the installation. One of them, tries to access the option group mentioned on the error, but it does this at a moment of the process where it's not available yet.
The installation process cannot be finished because of the mentioned error. Since the option group doesn't exists, the API call used to updated one of its option values fail and throw an Exception.
The installation process completes without any problems. We now catch the thrown exception to avoid the error.
---
=> PCHR-2396: Fix an upgrader error during the extension installation

uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/controllers/sub-controllers/toil-request-ctrl.js, uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/controllers/sub-controllers/toil-request-ctrl.spec.js
This PR fixes the following issues:
* As a staff, when creating a new TOIL request, after selecting a date the expiry date is calculated, but if the date changes the expiry date is not calculated again.
* The expiry date should be calculated from the *To Date* on *Multiple Days* and from *From Date* on *Single Day*. Currently the expiry date is only calculated from the *From Date*.
`toil-request-ctrl.js`'s method `calculateToilExpiryDate` was refactored to allow staff to update the expiry date for new requests, but lock the expiry date on open requests. Managers can still update the expiry date freely using the UI.
`toil-request-ctrl.spec.js` was refactored to test *staff edits new request* and *staff edits open request* scenarios. 
---
=> PCHR 2384: fix expiry date update on toil request modal

uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/directives/leave-request-popup/details-tab/sickness.html
When admin/manager record sick request for themselves, they are able to select checkboxes. This PR fixed this issue.
To the `$ctrl.isRole('staff')` condition was added `$ctrl.isSelfRecord` condition introduced in https://github.com/civicrm/civihr/pull/1999
No tests required for this local change.
=> PCHR-2395: Fix sick leave request

uk.co.compucorp.civicrm.hrleaveandabsences/scss/base/helpers/_disabled.scss
As per https://github.com/civicrm/civihr/pull/2002 the styling source file were forgotten to be added. This PR adds this SCSS file.
The built CSS file was included, but the source SCSS file was forgotten to be added.
No tests needed to be run for this PR.
=> PCHR-2406: Add missing SCSS file

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestRights.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestRightsTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestTest.php
When an admin tries to edit a Leave/TOIL request dates, the Leave Request popup never completes the save action and doesn't save updated dates. This PR fixes this issue.
An admin could not successfully edit the dates of a TOIL or leave request.
An admin can edit successfully the dates of a TOIL/Leave request.
This PR fixes access rights for admin actions while editing TOIL request.
The condition logic in the `CRM/HRLeaveAndAbsences/Service/LeaveRequestRights.php` was amended to grant Admins all rights on the date change, yet preserving the current condition logic for Managers.
1. The code is slightly refactored in order to remove duplicating pieces.
2. Unit tests contained assumptions that Admin **cannot** change dates. Since the requirements have been changed, the tests had been amended …
=> PCHR-2397: Allow admin edit toil request dates

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Import/Parser/Base.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1000.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1002.php, uk.co.compucorp.civicrm.hrleaveandabsences/xml/option_groups/sickness_reason_install.xml
This PR adds the _Other- Please add Comment_ Sickness reason option value.
Also an issue whereby an error is thrown during installation on a fresh site where L&A has not been previously installed was fixed. See [PR](https://github.com/civicrm/civihr/pull/1996).
Also previously, the value of `1` was set as default sickness reason when importing sickness requests via the L&A Importer. This PR replaces that value with the `Other` sickness option value just created.
the _Other- Please add Comment_ Sickness reason option value is now part of the sickness reason option group.
The PseudoConstant cache was flushed so that the values can be fetched from the db rather than returning the cached values. The error reported on [PR](https://github.com/civicrm/civihr/pull/1996) was due to the fact that …
=> PCHR 2310:  Add 'Other- Please add Comment' Sickness Reason Option value

uk.co.compucorp.civicrm.hremails/email-templates/dist/sickness-request.civicrm.html, uk.co.compucorp.civicrm.hremails/email-templates/src/pages/sickness-request.civicrm.html, uk.co.compucorp.civicrm.hrleaveandabsences/managed_entities/EmailTemplate.mgd.php
When Importing Leave request data of type sickness, Smarty complains of an error on Line 205 of the sickness request email template although the sickness email still gets sent. 
The error is a syntax error resulting from the php condition on that line not being properly formatted.
This PR properly formats the code and error is no more thrown when importing sickness requests.
=> PCHR-2391: Fix error thrown in Sickness email template.

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlementTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreationTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestDeletionTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
After deleting a contract, the Leave Requests and Public Holidays within its period are not displayed on the Absence Report anymore, but their balance changes are still counted in the balance calculation, resulting on an invalid value.
The Absence Report uses the `LeaveRequest.get` and` LeaveRequest.getFull` APIs to load the requests to be displayed. These APIs only return requests that overlap the contracts of a user. The balance information, however, is loaded using the `LeaveRequest.getBalanceChangeByAbsenceType` API, which has a slightly different logic that doesn't consider contracts for the balance calculation. If an admin deletes a contract, a call to `LeaveRequest.get` (or `getFull`) will return no requests for that contract period, but `LeaveRequest.getBalanceChangeByAbsenceType` …
=> PCHR-2381: Only consider requests overlapping contracts for balance calculation

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/ContactWorkPattern.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/ContactWorkPatternTest.php
When a Work Pattern is assigned to a Contact and the Work Pattern gets disabled, The disabled Work pattern is still applied to leave request deduction amount calculations and and is also used for the Contact's calendar  for the period when the Contact Work pattern is effective even though the Work pattern has been disabled.
A disabled Work Pattern that is assigned to a Contact is no longer applied to Leave Request deduction amount calculations and not used for the Contact's calendar even though the Contact Work pattern is still effective, rather, the calculation is done based on the default Work pattern and also the calendar is displayed based on the default Work Pattern.
The `ContactWorkPattern::getForDate` method was modified to return Contact Work patterns that is linked to an active …
=> PCHR-2423: Disabled Work Pattern Is Still Applied to Leave Request Amount Calculations and Contact Calendar

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/WorkPattern.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/WorkPattern.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/WorkPatternTest.php
The default Work pattern is the work pattern used by contacts without an effective Contact Work pattern, therefore it must be enabled always and should not be disabled.
The default Work Pattern can be disabled from the Work Pattern listing page. Also a new Work Pattern can be created as default and inactive.
The default Work Pattern cannot be disabled from the Work Pattern listing page and also a new Work Pattern cannot be created as default and inactive.
A `validateParams` method was created in the Work Pattern BAO patterned after the one in LeaveRequest BAO and some other BAO's in L&A. A new `validateDefaultWorkPattern` method was created to handle the validations for this task.
A validation method that ensures that there is at least one active Work Pattern available was removed as it …
=> PCHR-2428: Fix Issue with being able to disable the default Work Pattern.

uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/controllers/request-ctrl.js, uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/controllers/sub-controllers/leave-request-ctrls.spec.js
This PR fixes an issue when opening an existing leave request the date types fields stay in a loading state that never completes.
The error was introduced after moving code on the `request-ctrl.js`'s `updateAbsencePeriodDatesTypes` method into `loadAbsencePeriodDatesTypes` to separate initializing vs updating values. The specific issue was failing to set the loading `fromDayTypes` and `toDayTypes` variables to false after the initialization phase was completed.
Tests were added to the initialization phase to make sure the loading variables are set to false after requests are completed.
The error handling on `updateAbsencePeriodDatesTypes` was refactored in order to take advantage of the already defined `handleError` function.
---
=> PCHR-2432: Fix date types not loading when editing a leave request

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
When importing leave requests for a Contact that does not have entitlement for the absence type being imported for, It causes error to be thrown and the screen goes blank. This error does not currently occur when requesting leave because a contact without entitlement is not allowed to request leave on the SSP.
Validation is not done to ensure that a contact has Entitlements in the Leave Request BAO mainly because the front end already handles this. 
Validation is done to ensure that a contact has Entitlements in the Leave Request BAO since other sources like the L&A importer now exists to create leave requests.
The reason for the error occurring was that In the Leave Request BAO validation function the expression `$leavePeriodEntitlement->getBalance()`  was returning an error: `PHP Fatal …
=> PCHR-2436: Handle error when Contact does not have Entitlement When importing Leave Requests

hrjobcontract/CRM/Hrjobcontract/Form/PayScale.php
When saving a pay scale the "is_active" checkbox is ignored if unchecked. This means that you cannot set a payscale to inactive.
When saving a payscale with "is active" unchecked it is always saved as active.
The checkbox is not ignored and it is possible to save a checkbox as inactive.
The cause was that checkbox values are not send from the client in the $_POST request unless they are checked. The solution is to set a default value if not included in the request body.
Since this is a small file I did some cleanup, replacing the old array syntax and trying to reduce the long lines to under 80 characters.
---
=> PCHR-2299: Allow non active pay scales

hrjobcontract/views/modalChangeReason.html, hrjobcontract/views/modalForm.html, uk.co.compucorp.civicrm.hrcore/backstop_data/backstop.tpl.json, uk.co.compucorp.civicrm.hrcore/backstop_data/utils/custom-casperjs.js
This PR applies fixes to the HRJobContract extension that are necessary due to the amnesty-styling migration in Shoreditch (explained [here](https://github.com/compucorp/org.civicrm.shoreditch/pull/24))
All the changes to the markup are explained in the [shoreditch PR](https://github.com/compucorp/org.civicrm.shoreditch/pull/24)
A minor change was made to BackstopJS: now if a test can't find a selector, the whole test suite is not interrupted, it simply displays a warning message and move on to the next test
---
=> PCHR-2464: Adjustments for amnesty styling merging in shoreditch

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/EntitlementCalculation.php, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/ManageEntitlements.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/EntitlementCalculationTest.php
Currently on the Manage Entitlement page, we don't display a column that shows the TOIL accrued by the contact for the previous period, This causes some confusion in the remaining days column calculation. 
For example with the current default sample data in L&A, the contact took 1 leave day for the TOIL absence Type in 2016, If the entitlement for TOIL in 2016 was overridden to be 10, When being redirected to calculate entitlements for 2017 Period.
Remaining Days = Previous Year Entitlement - Days Taken.
Expected Remaining Days: 10 - 1 = 9
What is actually seen is 10 - 1 = 10
The reason for 10 - 1 = 10 being observed for the Remaining days in the before section is that the contact accrued an additional TOIL of 1 day during the period 2016. So the calculation for the remaining days column …
=> PCHR-2170:  Fix issues with TOIL Days Remaining calculation being incorrect

hrui/hrui.php
CiviHR does not work with multiple language sites. This is because the Drupal views module will try to create views using hardcoded column names. These column names are changed by enabling a multiple language site, for example `civicrm_option_value.label` becomes `civicrm_option_value.label_en_US`
Enabling multiple language and clearing the cache will cause a total site failure because the required views columns will be missing when rebuilding the views. In order to avoid this problem (which happened on the demo site) we will hide the option to enable multiple language.
You could see "Multiple Languages Support" under Administer > Localization > Languages, Currency, Locations. Enabling it would kill your site.
"Multiple Languages Support" is hidden from the form on Administer > …
=> PCHR-1830: Hide multiple language options on localization form

hrjobcontract/tests/phpunit/HRJobContractTestTrait.php
Some tests were failing in the job contract extension with errors while trying to assert the display_name of some contacts created for the failing tests.
The tests were failing on CiviHR 1.7 and after merging this PR, will sync 1.7 with 1.6
The error observed in the tests were traced to a behaviour in the core Contact.create API.
If you try to create a contact with last name as `0`, it creates just fine and civi sets the display_name by concatenating the `first_name` and the `last_name`. For the example below, `display_name` is `Name 0`
```php
$contact = civicrm_api3('Contact', 'create', [
'contact_type' => 'Individual',
'first_name' => 'Name',
'middle_name' => 'N.',
'last_name' => 0,
'email' => 'name_0@example.org',
]);
```
However if you try to update the contact e.g
```php …
```
=> PCHR-2482: Fix bug when creating and updating a contact with last name as Zero in Job Contract tests

hrjobcontract/CRM/Hrjobcontract/ExportImportValuesConverter.php, hrjobcontract/CRM/Hrjobcontract/Import/EntityHandler/HRJobLeave.php, hrjobcontract/CRM/Hrjobcontract/Import/FieldsProvider/Generic.php, hrjobcontract/CRM/Hrjobcontract/Import/Parser/Api.php, hrjobcontract/CRM/Hrjobcontract/SelectValues.php, hrjobcontract/tests/phpunit/CRM/Hrjobcontract/Import/Parser/ApiTest.php
Contract Entitlements are imported along with the contract information for a contact via the job Contract Importer. However, the contract entitlements to be imported are still pointing to the absence/leave types of the old Absence extension. Also the contract entitlements for all the leave types are imported as a comma separated value in the `Contract Leave Amount` column of the CSV which is not a very intuitive way to import the entitlements.
The contract entitlements are pointing to the old absence extension leave types and the contract entitlements for all the leave types are imported as a comma separated values in the `Contract Leave Amount` column.
The contract entitlements are pointing to L&A absence/leave types and the contract entitlements for all the leave types are imported …
=> PCHR-2482: Import Contract Entitlements for L&A

uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/manage-leave-requests.html
This PR adds a balance change column to Manager Leave Requests table.
_Note: this is a 13'' screen_
1. New `<th>` and `<td>` containing balance change value were added. If the balance change is greater than 0, then the change will be shown with "+" symbol.
2. Additionally, inline CSS styles `style="width: x%"` were replaced with `width="x%"` and moved to `th`
1. HTML Indentation and code readability was improved
2. No tests pass needed
3. The layout is not great, but it was confirmed that the table UI is to be improved later
=> PCHR-2288: Add balance change column to Manager Leave Requests table

hrjobcontract/views/modalForm.html
After an unsuccessful attempt (https://github.com/civicrm/civihr/pull/2067) to fix unresolved conflicts after sync (https://github.com/civicrm/civihr/commit/365e785a77c0aa1f166a5f13b91880fee1d3bb35) the Leave tab in the Contract Modal Form had 1.6 interface view instead of 1.7.
This PR fixes this issue.
1. The latest stable version of the modalForm.html file was taken from (https://github.com/civicrm/civihr/blob/53ea41a5b9ee4e20fb1023d896ae63b479ce4f8d/hrjobcontract/views/modalForm.html)
2. Commits from https://github.com/compucorp/org.civicrm.shoreditch/pull/24 related to the modalForm.html file were applied manually (except re-indentation)
3. Re-indentation was made manually
4. Backstop was run
Backstop between https://github.com/civicrm/civihr/commit/53ea41a5b9ee4e20fb1023d896ae63b479ce …
=> PCHR-2353: Fix issues with Modal Form after fixing unresolved conflicts

uk.co.compucorp.civicrm.hrcore/backstop_data/casper_scripts/ssp-leave-absences/manager/manager-leave-calendar_current-month-visible.js, uk.co.compucorp.civicrm.hrcore/backstop_data/page-objects/ssp-leave-absences-manager-leave-calendar.js, uk.co.compucorp.civicrm.hrcore/backstop_data/page-objects/ssp-leave-absences-my-leave-calendar.js, uk.co.compucorp.civicrm.hrcore/backstop_data/scenarios/ssp-la-manager-leave-calendar.json, uk.co.compucorp.civicrm.hrcore/backstop_data/scenarios/ssp-la-my-leave-calendar.json
BackstopJS tests stopped working for calendar. This PR fixes this issue.
BackstopJS was hanging on the Manager Leave / My Leave calendars scenarios.
The selectors were not up-to-date. The fix was to update selectors and *not* rely on generic selectors like &lt;tr&gt;, but unique selector, such as `leave-calendar-month .chr_leave-calendar__item`. This decreases the probability breaking the test even if the markup structure changes. 
As per @AkA84 suggestion the screenshots of *all months* view are removed from BackstopJS for Manager Leave / My Leave calendars due to the lack of necessity.
---
=> PCHR-2519: Fix BackstopJS for Manager leave calendar

uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/ManageEntitlements.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-calendar.html, uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/staff-leave-report.html
This PR adds the "class markers" to avoid the [enable-select2.js](https://github.com/civicrm/org.civicrm.shoreditch/blob/master/js/enable-select2.js) and [radio-checkbox.js](https://github.com/civicrm/org.civicrm.shoreditch/blob/master/js/radio-checkbox.js) scripts to the marked radio/select elements, that was resulting in broken styles
---
=> PCHR-2464: Additional post-amnesty-merge fixes 

com.civicrm.hrjobroles/CRM/Hrjobroles/API/Query/ContactHrJobRolesSelect.php, com.civicrm.hrjobroles/CRM/Hrjobroles/API/Query/VirtualEntitySelectQuery.php, com.civicrm.hrjobroles/CRM/Hrjobroles/BAO/ContactHrJobRoles.php, com.civicrm.hrjobroles/CRM/Hrjobroles/Test/Fabricator/HrJobRoles.php, com.civicrm.hrjobroles/CRM/Hrjobroles/Upgrader.php, com.civicrm.hrjobroles/api/v3/ContactHrJobRoles.php, com.civicrm.hrjobroles/hrjobroles.php, com.civicrm.hrjobroles/tests/phpunit/api/v3/ContactHRJobRoleTest.php
This PR Adds the `ContactHrJobRoles.get` API. Its main purpose is to allow getting the Job Roles of specific contacts without having to pass through the intermediary HRJobContract API.
A call to this API will return a list of fields from the Job Roles table (not all of them) + a contact_id, which is a field from the Job Contract table.
This API also addresses an issue related to permission. Without it, a user would need access to both HRJobRoles and HRJobContracts APIs, which both might have confidential data. With the new API, we can keep those APIs hidden behind more restrictive permissions and expose only ContactHrJobRoles, which, by the way, doesn't return any type of confidential data.
To get something like "All the contacts that work in the IT department", an API call like this …
=> PCHR-2353: Add the ContactHrJobRoles.get API

hrjobcontract/CRM/Export/BAO/Export.php, hrjobcontract/CRM/Hrjobcontract/BAO/Query.php, hrjobcontract/CRM/Hrjobcontract/DAO/HRJobLeave.php, hrjobcontract/CRM/Hrjobcontract/Export/Converter.php, hrjobcontract/CRM/Hrjobcontract/ExportImportValuesConverter.php
Currently, trying to export contract leave entitlements when exporting a contact information does not work, the resulting CSV downloaded contains a blank column or inaccurate data for the Contract Leave Amount column.
Also since the import format for Contract entitlements has been changed in CiviHR 1.7, there is need also to allow Contract entitlements to be exported in this format to allow clients migrating entitlements data from 1.6 to 1.7 to do so seamlessly.
Exporting the contract leave entitlement data is broken and does not give accurate data. The export format is not compatible for import into a CiviHR 1.7 site
Exporting the contract leave entitlement now gives accurate data and it also exports data in a format that is compatible for import into 1.7 in addition to the format …
=> PCHR-2503: Fix issues with being unable to export Contract Entitlements

hrjobcontract/js/test/controllers/contract_test.js, hrjobcontract/js/test/services/contract-details_test.js, hrjobcontract/js/test/services/contract-health_test.js, hrjobcontract/js/test/services/contract-hour_test.js, hrjobcontract/js/test/services/contract-leave_test.js, hrjobcontract/js/test/services/contract-pay_test.js, hrjobcontract/js/test/services/contract-pension_test.js
This PR fixes a few issues with HR Job Contracts tests. Some tests were passing without actually running their expectations. Also the code structure was fixed to follow the guide style, but without following naming conventions. 
* Linting was applied to `contract_test.js` even though this file was working properly.
* Most services were mocking the wrong HTTP endpoints and expectations were not being run because these services would reject their promises.
* This PR only touches files in immediate need of fixing.
* Naming conventions were not applied as to keep the PR short and simple.
* In the future we'll need to add some capability for throwing an error when a promise rejection is not handled properly. This will help with cases such as this one were tests were successful because no …
=> PCHR-2478: fix HR Job Contracts tests for staging branch

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Query/LeaveRequestSelect.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
The unassigned filter on the Leave and Absence Dashboard page does not work as it should. For example leave requests for a contact with an active leave approver relationship also having another relationship will show up when the unassigned tab is clicked. The unassigned tab is only supposed to show leave requests for contacts without an active leave approver relationship.
The unassigned filter when clicked will return leave request results for a contact having an active leave approver relationship and other relationships.
The unassigned filter when clicked returns only results contacts without an active leave approver relationship.
- The query responsible for fetching results for `LeaveRequest.get` and `LeaveRequest.getFull` Api's joins directly to the `relationship` table via the leave …
=> PCHR-2480: Fix bug in unassigned filter when contact has multiple relationships

hrjobcontract/CRM/Hrjobcontract/BAO/Query.php
When a leave type option is selected in the `Job Contract: Leave` tab in the advanced search page, No contact is returned even though contacts having contract entitlements for those leave types exist. This is observed for CiviHR 1.6. For 1.7 the `Job Contract: Leave` tab does not show any option at all but has been fixed by this [PR](https://github.com/civicrm/civihr/pull/2096).
When an option is selected in the `Job Contract: Leave` tab in the advanced search page, No contact is returned even though contacts having contract entitlements for those leave types exist
When an option is selected in the `Job Contract: Leave` tab in the advanced search page,  contacts having contract entitlements for those leave types are returned.
- The where condition in the query that allows contacts having …
=> PCHR-2486: Fix issue with Advanced search not working when an option is selected in the Job Contract: Leave Tab

bin/civihr-crm-api-tests.sh, bin/civihr-webtests.sh, bin/drush-install.sh, bin/git-release.sh, doc/INSTALL.md, hrreport/CRM/HRReport/Form/Contact/HRSummary.php, hrui/CRM/HRUI/Upgrader/Steps/4701.php, hrui/hrui.php, hrui/js/src/hrui.js
Since the functionality offered by the hrvisa and hrident extensions is planned to be replaced by the improved documents feature these extensions are not required going forward. However, as they are potentially used by existing clients we will not remove them from the code.
For new installations the hrvisa and hrident extensions are enabled.
The hrvisa and hrident extensions will not be enabled for new installations. References to code that depends on these extensions will be removed or altered.
This PR changes the installation script, but also adds a conditional for anywhere outside the hrvisa and hrident extensions that their code is used, or anywhere that uses custom groups, fields, activities or anything that is normally created by these extensions.
---
hrvisa tests are broken on …
=> PCHR-2493: Disable hrvisa and hrident extensions

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Mail/Message.php, uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/apis/leave-request-api.js, uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/apis/leave-request-api.spec.js, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Mail/MessageTest.php
This PR utilises https://github.com/civicrm/civihr/pull/2051 and makes links in leave requests email notifications lead directly to Leave Request Modal with a correct leave request opened.
Links are now populated with a proper GET query containing leave request ID.
```php
$queryString = '?leave-request-id=' . $this->leaveRequest->id;
$leaveUrl = CRM_Utils_System::url('my-leave#/my-leave/report' .
$queryString, [], true);
```
This PR also fixes the issue with showing balance. The problem was happening because `LeaveRequest.find()` method utilised `get` API3 method which lacked **balance_change** and **dates** properties to be returned. Now `getFull` method is used for the `.find()` method, which is also already used in `.all()` method.
---
=> PCHR-2536: Add unique leave request links in emails

uk.co.compucorp.civicrm.hrleaveandabsences/scss/components/_leave-calendar.scss, uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-calendar-month.html
As part of this PR(and https://github.com/compucorp/civihr-employee-portal-theme/pull/213), responsive design has been implemented for the My Leave calendar.
My Leave calendar got broken from https://github.com/civicrm/civihr/pull/2100
1. Added `ng-if` statement to hide `chr_leave-calendar__names-container`
2. Added `ng-class` to add the bootstrap classes only for manager leave.
3. Added `margin-bottom` to remove unwanted bottom padding.
---
=> PCHR-2510: Fix my leave calendar

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestTest.php
When a user edits an already created leave and changes any other thing apart from the date, the user can decide to either use the balance change as of when the leave request was created or recalculate if the balance change is now different. This PR implements the Backend changes needed to achieve this.
There is no way for the `LeaveRequest.create` API to know whether the leave balance for an already created request should be retained or recalculated. 
The `LeaveRequest.create` API was modified to accept a new parameter called `change_balance`. This parameter when present and true will allow the leave request balance changes to be updated using the current work pattern for the contact. If not present or if present and false means that the leave request balance will remain untouched.
---
=> PCHR-2558: Add change_balance parameter to LeaveRequest.create API.

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Query/LeaveBalancesSelect.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlement.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeavePeriodEntitlement.php, uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlementTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/ApiPermissionTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeavePeriodEntitlementTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/LeaveBalanceChangeHelpersTrait.php
This PR adds the `LeavePeriodEntitlement.getLeaveBalances` API. This new API aggregates data that is already available via other APIs like `LeavePeriodEntitlement.getRemainder` and `LeavePeriodEntitlement.getEntitlement`, but it does this with a much better performance and reduced number of queries, especially because it can be used to get information for multiple contacts with a single request.
To get the same information provided by the new API, one would need a chained API call similar to this one:
```javascript
CRM.api3('Contact', 'getleavemanagees', {
"sequential": 1,
"managed_by": 205,
"api.LeavePeriodEntitlement.getentitlement": {"contact_id":"$value.id","period_id":2},
"api.LeavePeriodEntitlement.getremainder": {"contact_id":"$value.id","period_id":2,"include_future":1}
})
```
As …
=> PCHR-2495: Add the LeavePeriodEntitlement.getLeaveBalances API

uk.co.compucorp.civicrm.hrleaveandabsences/views/absence-tab/components/absence-tab-custom-work-pattern-modal.html, uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-balance-tab-filters.html, uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-request-popup/details-tab/common.html, uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-request-popup/details-tab/sickness.html, uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-request-popup/details-tab/toil.html, uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-request-popup/leave-request-popup-body.html, uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/manage-leave-requests.html
In Absence Tab Admin cannot create neither TOIL nor Sick leave request. This PR fixes this issue.
This happens because in Admin section the `<select>` element behaviour  was overridden. The class "no-select2" prevent the selector element from being overridden. **The "broken" selectors do not write values to components via ng-model!**
```html
<select>...</select>
``` 
```html
<select class="no-select2">...</select>
``` 
This PR also fixes the styling of selectors in other places in L&A:
**Before**: only 6 selectors out of 27 had "no-select2" class.
**After**: all files containing selectors have the "no-select2" class.
This PR also fixes the styling of selectors in other places in L&A:
**Before**
**After**
This PR also prevents such a behaviour in the future for other components:
- Leave …
=> PCHR-2554: Fix Admin TOIL & Sick Leave Request creation

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/ACL/LeaveInformationTrait.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Query/ContactSelect.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Query/LeaveBalancesSelect.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Query/LeaveRequestSelect.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/Contact/Getleavemanagees.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/ContactTest.php
Currently the Contact.getLeaveManagees API only supports one mandatory parameter: `managed_by` which allows the API to returned contacts managed by the contact ID passed in the managed_by parameter. To make the API more flexible, the unassigned parameter is introduced in this PR to allow the API to return contacts that do not have an active Leave Approver relationship.
The Contact.getLeaveManageesAPI does not support the unassigned parameter.
The Contact.getLeaveManageesAPI now supports the unassigned parameter. 
These are the rules that guide the new unassigned parameter in relation to the existing managed_by parameter:
- If the `unassigned` parameter isn't present in the request, then `managed_by` must be required.
- If `unassigned` is false, then `managed_by` must be required.
- If …
=> PCHR-2556: Contact.getLeaveManagees API to support the unassigned parameter.

hrjobcontract/CRM/Export/BAO/Export.php, hrjobcontract/CRM/Hrjobcontract/Export/Converter.php
This PR fixes issues with contract entitlements export. The issues are:
- When exporting contract entitlements, the contact ID is also needed in order for this information to be imported to CiviHR 1.6 but currently there is no way to select Contact ID as a field to be exported when exporting Contact Information via advanced search.
- Currently, when Contract entitlements is exported for a contact, a default blank value is added in the CSV for the case where the contact does not have entitlement for a particular leave type. However this was causing issues when importing these blank values into CiviHR 1.7 as it is considered an invalid leave amount type.
Contact ID field cannot be exported along with entitlement data.
Blank values are added in CSV to represent when a contact does not have …
=> PCHR-2503: Fix issues with Contract Entitlement Import

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php
At the moment Manager cannot reject or cancel a leave request if the leave request balance change is greater than the current entitlement balance.
_The simple use case is the following:_
1) Staff creates a single day Overtime TOIL
2) This Overtime TOIL is approved by Manager
3) Staff creates two single day Leave Requests and in both uses the balance of Overtime TOIL (1)
4) One of the Leave Requests mentioned above is then approved by Manager
5) Manager now cannot cancel or reject the second Leave Request since the Overtime TOIL balance is now (0)
This PR fixes this issue.
Manager cannot approve the second Leave Request, but also cannot cancel (or reject) it.
Manager cannot approve the second Leave Request, but **can** cancel (or reject) it.
A check for a status was added in the function …
=> PCHR-2535: Fix Leave Request cancellation or rejection by Manager

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/ApiPermissionTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
When opening an existing Leave Request, we should show its breakdown (the list of each of its dates, together with a number of days deducted for each of them). 
This is information is stored in the database, but scattered in a few tables. This new API should be used to expose an easy way to fetch it while avoiding to expose too many data structure details.
There's no easy way to get the breakdown of a Leave Request
The `LeaveRequest.getBreakdown` is available to be used to fetch the breakdown of a Leave Request.
It has a mandatory `leave_request_id` param, that should be used to give the ID of the Leave Request to which we want to get the breakdown to.
The breakdown of a Leave Request is just a list of its dates together with the number of days deduct for it. Here is a sample response: …
=> PCHR-2544: Add the LeaveRequest.getBreakdown API

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Query/LeaveBalancesSelect.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeavePeriodEntitlementTest.php
The results of the `LeavePeriodEntitlement.getLeaveBalances` API are currently being indexed by the contact ID, as if it is returning a list of contacts. However, as mentioned on https://github.com/civicrm/civihr/pull/2105, the API is actually a way to aggregate data from multiple different APIs/Entities to return it in a more performant way and in an easier to parse format. So, given each record is actually a mix of data from different places, they don't really have an ID and the response should not be indexed by the contact one.
The results are indexed by the contact ID:
```json
{
"is_error": 0,
"version": 3,
"count": 4,
"values": {
"4": {
"contact_id": "4",
"contact_display_name": "civihr_staff@compucorp.co.uk",
"absence_types": [
{
"id": 1,
"entitlement": "28.00",
"used": 13.5, …
```
=> PCHR-2495: Do not return results indexed by contact ID

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Import/Parser/Base.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreation.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Import/Parser/BaseTest.php
Currently, when Importing Leave Requests the validations for balance change is buggy because it does use the amount to be deducted as it is in the CSV for the validation, rather it uses the amount calculated from the contact's work pattern for the dates to be imported for. 
This PR fixes this issue.
When importing Leave Requests, the leave request balance change amount used for validating balance change is the one gotten from the `LeaveRequest::calculateBalanceChange` method rather than the `total_qty` field in the CSV.
- The second parameter passed to `LeaveRequest::create` was changed from `$validate` to `$validationMode` where the available validation Modes are: VALIDATIONS_ON, VALIDATIONS_OFF and IMPORT_VALIDATION.
- The validationMode is passed as  IMPORT_VALIDATION when creating …
=> PCHR-2563: Fix bug when validating Balance Change on Leave Request Import

hrjobcontract/CRM/Export/BAO/Export.php, hrjobcontract/CRM/Hrjobcontract/BAO/Query.php
When exporting Contract information via advanced search, records for all contract revisions are exported which is something we don't necessarily need, If we need it it can be exported via the export function on the Job contract page. 
Also when exporting contract entitlements, in the CSV the Contract Leave Amount column is messed up as it concatenates the contract entitlements for all contracts in same row.
- When exporting contract entitlements, in the CSV the Contract Leave Amount column concatenates the contract entitlements for all contracts in same row.
- When exporting contract information via advance search, the information is exported for all contract revisions.
- When exporting contract entitlements, in the CSV the Contract Leave Amount column concatenates the contract …
=> PCHR-2503: Fix Contract Export to Only Export Records for the Latest Contract Revision

hrjobcontract/CRM/Hrjobcontract/Import/Form/SummaryBaseClass.php, hrjobcontract/CRM/Hrjobcontract/Import/Parser/EntitlementUpdate.php, hrjobcontract/templates/CRM/Hrjobcontract/Import/Form/Summary.tpl
When importing Contract entitlements for Contacts with existing Contract, Only the Contact ID field is required and entitlements are imported for the latest revision of the Contact's current Contact. However since Entitlement Calculation needs to be done after the import, there is a flaw in this process as the Entitlement calculation considers all active Contracts within a Period for the contact, so it is necessary to update entitlements for all the Contact's Contracts.
Also a message informing the user of the need to go to the Entitlement calculation after a successful Contract entitlement update is added in this PR.
- When importing Contract entitlements for a Contact, the Contact ID field is required
- There is no message prompting the user to go to the entitlement calculation page …
=> PCHR-2503: Make Contract ID compulsory when importing Contract Entitlements

hrabsence/CRM/HRAbsence/Upgrader.php
On https://github.com/civicrm/civihr/pull/2096/ a new upgrader was added in other to remove a scheduled job used to update the entitlements on the old extension, which one be necessary anymore with 1.7. However, Civi wasn't able to execute the upgrader because it didn't return `TRUE`, which is considered as a failure by the upgrade process.
Civi wasn't able to run the upgrader to remove the scheduled job
The upgrader now returns `TRUE` and civi is able to run it successfully.
---
(No tests involved in this)
=> PCHR-2223: Fix HRAbsence upgrader 1404

hrabsence/hrabsence.php
In CiviHR 1.6, the hrabsence is responsible to manage the "has Leave Approved by" relationship, which means:
- When the extension is installed, it creates the relationship type
- When the extension is uninstalled, it deletes the relationship type
For 1.7, the new L&A extension should be the one responsible for this. Otherwise, if someone uninstalls hrabsence after L&A is installed, it will remove the relationship type and may cause problems in L&A (e.g, losing existing relationships between managers and staff members)
When hrabsence is uninstalled it deletes the "has Leave Approved by" relationship type
When hrabsence is uninstalled it DOES NOT delete the "has Leave Approved by" relationship type
---
(No tests affected by this)
=> PCHR-2605: Don't delete the "has Leave Approved by" relationship type when hrabsence is uninstalled

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlement.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlementTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Import/Parser/BaseTest.php
When trying to update an already approved leave request, e.g trying to change the status or add a comment, or upload a file and the Entitlement Balance is Zero, an error: ` 'There are only 0 days leave available. This request cannot be made or approved` is returned to the manager/user trying to update the Leave.
Trying to update an already approved leave request e.g trying to change the status or add a comment, or upload a file returns an error when the Entitlement Balance is Zero.
- The reason for the error returned is that when validating an already approved leave, the already approved leave is considered as a fresh leave request not minding the fact that its balance change has previously been deducted from the entitlement Balance.
- Since the approved leave to be updated is treated as …
=> PCHR-2538: Fix issue with not being able to update an already Approved Leave when Entitlement Balance is Zero

uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/AbsencePeriod.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/PublicHoliday.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/WorkPattern.tpl
This PR adds blank space characters to admin table headers so they can be displayed correctly when they are in sticky mode.
This PR is linked to https://github.com/compucorp/org.civicrm.shoreditch/pull/50
When sticky table headers are empty (`<th></th>`) they are displayed incorrectly. To fix this issue a blank space character was added (`&nbsp;`).
* BackstopJS tests were run on the Shoreditch PR.
* Indentation was fixed on `Page/AbsencePeriod.tpl`. Since it was only 5 lines total it was not added in a separate commit.
---
=> PCHR-2543: Add missing white space on admin table headers

uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/controllers/request.controller.js
The `initRoles` function on `request.controllers.js` is missing a few key comments such as the return value of the function and a comment on an exception where the user role is set to staff if they are managing their own leave.
Just added the missing comments. This doesn't affect minified files nor tests.
=> PCHR-2330: Add notes to request controller's initRoles function

uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/WorkPattern/Details.tpl
This PR removes a duplicate "label" field on work patterns and adds a missing "active" checkbox.
BackstopJS tests were run for work pattern screens.
---
=> PCHR-2545: Add missing active field and remove duplicate label field

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestTest.php
This [#2103](https://github.com/civicrm/civihr/pull/2103) made some changes to the way Balance changes are updated. Basically, If the dates of a leave request do not change and the `change_balance` parameter is false or not present, the balance change does not get updated. However it fails to factor in TOIL requests because the balance changes are created more differently than for a Leave Request.
- Balance changes for a TOIL request is equivalent to the value of the `toil_to_accrue` parameter and does not depend on the TOIL request dates. The validation for skipping a balance change update when the dates of a leave request does not change was causing issues in Accruing TOIL especially when the TOIL dates does not change but the Toil to Accrue changes.
- The logic for skipping a balance …
=> PCHR-2601: Fix issue with TOIL not being Accrued properly when TOIL dates do not change and Toil to Accrue changes.

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php
At the moment is it possible to:
1) Set Leave Request status to More information required with a negative closing balance by Manager
2) Set Leave Request status to Awaiting for approval with a negative closing balance by Staff
3) Approve a Leave Request with a negative closing balance by manager
This PR fixes this issue.
The problem was in the function that calculates the balance change for **existing** leave requests:
```php
public static function getTotalBalanceChangeForLeaveRequest(LeaveRequest $leaveRequest, $expiredOnly = false) {
...
return $balance; // for Leave Requests using current TOIL balance this value was negative, though the actual calculation was correct
}
```
This lead to the following condition to pass while it should have been failing:
```php
// …
```
=> PCHR-2535: Disallow transitions to non-cancelling statuses with a negative closing balance

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/WorkPattern.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/WorkPatternTest.php
When trying to create a Work Pattern with same label as one already existing in the database, An db error is shown on the screen.
- When trying to create a Work Pattern with same label as one already existing in the database, rather than a Db error, A user friendly error is shown on the Work Pattern listing page
=> PCHR-2664: Add validation for unique Work Pattern labels

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/WorkPattern.php, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/WorkPattern/Calendar.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/WebTest/WorkPattern/FormTest.php
This PR fixes the following issues on the Work Pattern admin form:
* It changes the wording of the validation messages from `Please inform the [field name]` to `Please fill in the [field name]`.
* Stopped select inputs from turning into select2 components by applying the fix introduced in this PR:
https://github.com/compucorp/org.civicrm.shoreditch/pull/52
Please check https://github.com/compucorp/org.civicrm.shoreditch/pull/52 for before and after screens of the fix for this issue.
* Validation messages were updated in these files:
- `CRM/HRLeaveAndAbsences/Form/WorkPattern.php`
- `tests/phpunit/WebTest/WorkPattern/FormTest.php`
The last one is a unit test that expects these messages to appear when the validation fails.
* The `no-select2` class was added only to the …
=> PCHR-2545: Fix Work Pattern issues

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsenceTypeTest.php
When trying to create an Absence Type with same title as one already existing in the database, A db error is shown on the screen.
- When trying to create an Absence Type with same title as one already existing in the database, rather than a Db error, A user friendly error is shown on the Absence Type listing page.
---
=> PCHR-2665: Add validation for unique Absence Type titles

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/WorkPattern.php, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/AbsenceType.tpl
The `Set As Default` and `Delete` links are not working on the Absence Type Listing Page.
- The `Set As Default` and `Delete` links are not working on the Absence Type Listing Page. On clicking the links, nothing happens.
- Also clicking the `Set As Default` link on the Work Pattern listing page throws an error in the console.
- A missing class  in the Absence Type template page was added and also the `jquery.crmEditable.js` file was added to the Absence Type listing page file to fix the `Set As Default` and `Delete` links.
The missing class needed to be present to allow this variable to get its expected value
[Here](https://github.com/civicrm/civihr/blob/a2ea576b469094608c91504777816af0e442f259/uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/AbsenceType.tp …
=> PCHR-2049:  Fix issues with Non Working Links On Absence Type And Work Pattern Listing Page

uk.co.compucorp.civicrm.hrleaveandabsences/xml/option_groups/absence_type_calculation_unit_install.xml
This PR adds the Absence Type Calculation unit option group. The options would determine what unit to calculate entitlements, leave requests for an Absence type.
The available options are Days, Hours.
---
This change does not affect tests.
=> PCHR-2694:  Add absence type calculation unit option group.

hrabsence/CRM/HRAbsence/Upgrader.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1005.php, uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php
This PR updates the label of the main menu items of the old and new L&A extensions
The item was labeled "Absences"
The items were labeled
1. Leave and Absences
2. Administer / Leave and Absences
The item is now labeled "Leave"
The items are now labeled
1. Leave
2. Administer / Leave
=> PCHR-2610: Update L&A menu items labels

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/AbstractDrupalInteractionTaskForm.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/CreateUserRecordSingleTaskForm.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/CreateUserRecordTaskForm.php, uk.co.compucorp.civicrm.hrcore/hrcore.php, uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/CreateUserRecordSingleTaskForm.tpl, uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/CreateUserRecordTaskForm.tpl, uk.co.compucorp.civicrm.hrcore/xml/Menu/hrcore.xml
The "Create User Record" action links to a Drupal screen to create the user account. To keep it more consistent we will use the "Create User Record" screen from #2101 to create the user account and set up roles.
The actions menu on the user profile page shows a link to "Create User Record" which leads to the Drupal user creation page.
The actions menu on the user profile page shows a link to "Create User Account" which leads to the form from #2101 
This builds on the work done in #2101 by extending from the parent form. It operates differently by getting the contact ID from the request query string. It also uses a separate template, since some changes will likely be made when creating a user account for a single contact.
---
=> PCHR-2549: Change to Contact Record Creation

.github/PULL_REQUEST_TEMPLATE.md, Jenkinsfile
After a long wait and multiple requests from developers, we'll finally start using Jenkins to automatically run the tests for our Pull Requests. 
This PR adds the initial version of the Jenkinsfile with the very minimum required to start. We're not covering all the tests yet. At this moment, Jenkins will only run the PHP Unit tests. 
Soon enough other types of tests will be covered (Like JS Tests, Web Tests and Backstop JS), as well as Code Style checks and no failure will pass unnoticed.
Developers had to run the tests manually. Reviewers had to trust the developer to run the rights tests.
When a PR has the "Ready for Testing" label assigned to it, Jenkins will pull it, run the PHP Unit tests automatically (for all the extensions) and update the PR status with the test results.
Jenkins …
=> PCHR-2427: Add the Jenkinsfile

com.civicrm.hrjobroles/CRM/Hrjobroles/BAO/HrJobRoles.php, com.civicrm.hrjobroles/tests/phpunit/CRM/Hrjobroles/BAO/HrJobRolesTest.php, hrvisa/CRM/HRVisa/Activity.php, hrvisa/tests/phpunit/CRM/HRVisa/ActivityTest.php
Some of the PHP unit tests have been failing for a while. It's hard to know the exact reason, but this is probably because either:
- Changes were made to the extension but the tests were not ran
- The tests started failing after a CiviCRM upgrade and we didn't cache
This PR fixes these tests
There were 4 failing tests. 2 in hrvisa and 2 in job roles:
All the tests are passing:
- The HRVisa tests were failing because they were using a deprecated CiviCRM function. Civi now throws an exception when this function is used and this was causing the tests to fail. The fix was basically to replace the deprecated function with the new one suggested by Civi.
- There were 2 tests failing in Job Roles, each one for a different reason:
- One of the tests was failing because the query in …
=> PCHR-2427: Fix failing PHP unit tests

org.civicrm.bootstrapcivihr/bootstrapcivihr.php, uk.co.compucorp.civicrm.hrcore/hrcore.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1005.php
This PR renames the labels of two core menu items: "Contacts" and "Administer".
It also contains changes that make sure that the css file of the `org.civicrm.bootstrapcivihr` extension (`civihr.css`) is included in every page of civicrm
Finally, in #2186 I made a mistake and renamed "Leaves and Absences" into "Absences" instead of "Leave", this PR takes care of that
The two menu items are called "Contacts" and "Administer".
The `civihr.css` is not included in pages that CiviCRM treats as "forms" (like the "Advanced Search" page)
The two menu items are now called "Staff" and "Configure".
The `civihr.css` is included in every page
=> PCHR-2611: Update core menu items

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/AbsenceType.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/AbsenceType.hlp, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsenceTypeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlementTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/NotificationReceiverTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/EntitlementCalculatorTest.php
This PR makes some changes to the Absence Type Form by adding the `Calculate Leave in field` which allows the user to select if Leave for the Absence Type is to be calculated in Hours or Days. It also implements some Form logic for the new changes.
- The `Calculate Leave in` field was not present in the Absence Type form
- The `Calculate Leave in field` was added to the Absence Type form. This field is a select field that uses the option values in the `absence_type_calculation_unit` option group as its select options.
- For an Absence Type that is linked to an existing leave request, the `Calculate Leave in` field cannot be changed.
- If Leave is in hours, Public Holiday cannot be added to the entitlement.
- References to days in the form labels were removed
=> PCHR-2696: Changes to the Absence Type Form for Leave in Hours Requirements

hrrecruitment/CRM/HRRecruitment/Upgrader.php, hrrecruitment/hrrecruitment.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1006.php
This PR fixes a couple of bugs
1. The "Vacancies" menu item hadn't been renamed in #2189 as expected
2. The position of "Vacancies" and "Leave" was wrong
1. We had a "Vacancies" menu item
2. The "Leave" menu item was after "Vacancies"
1. We have a "Recruitment" menu item
2. The "Leave" menu item is before "Vacancies"
The changes were done with Upgraders
=> PCHR-2747: Fix menu items order and Vacancies label

uk.co.compucorp.civicrm.hrcore/hrcore.php
This PR adds a "Self Service Portal" to the main menu in the CiviHR admin
Initially the menu item was meant to be added via an upgrader, but then quickly realized that no matter how high of a weight we assigned to the item, it would still appear before "Help" and "Developer" in the menu list.
This was due to [hrui](https://github.com/civicrm/civihr/blob/staging/hrui/hrui.php#L997) extension, which added those two items on the fly using the `hook_civicrm_navigationMenu` hook, practically bypassing the DB completely, and as such ignoring any weight assigned to the menu items.
So in the end the hook was used also here in hrcore.
=> PCHR-2616: Add ssp menu item on the fly

hrui/CRM/Core/BAO/Navigation.php
This PR removes the old "Self Service Portal" link in the CiviHR logo submenu, given that now we have a standalone button that redirects (see #2220 )
=> PCHR-2618: Remove ssp link in civihr logo submenu

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Mail/Template/BaseRequestNotification.php, uk.co.compucorp.civicrm.hrleaveandabsences/managed_entities/EmailTemplate.mgd.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Mail/Template/LeaveRequestNotificationTemplateTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Mail/Template/SicknessRequestNotificationTemplateTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Mail/Template/TOILRequestNotificationTemplateTest.php
Currently emails managers and staff receive emails when a leave request is created or the leave request status is changed. These emails contain only dates now since only "days" Absence Type calculation unit is currently supported now.
Since now "hours" Absence Type calculation unit is supported in Leave in Hours, this PR adds support of time output to the emails mentioned above.
In `CRM/HRLeaveAndAbsences/Mail/Template/BaseRequestNotification.php`:
```php
// New function added that returns calculation unit name (required to decide which format to show)
private function getAbsenceTypeCalculationUnitName(LeaveRequest $leaveRequest) {
$absenceType = new CRM_HRLeaveAndAbsences_BAO_AbsenceType();
$absenceType->id = $leaveRequest->type_id;
$absenceType->find(true);
$calculationUnitId = …
```
=> PCHR-2770: Support time output in email templates

Jenkinsfile, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/WorkDay.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/WorkDayTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Mail/MessageTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Mail/Template/LeaveRequestNotificationTemplateTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Mail/Template/SicknessRequestNotificationTemplateTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Mail/Template/TOILRequestNotificationTemplateTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestRightsTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestStatusMatrixTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/bootstrap.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/LeaveRequestHelpersTrait.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/OptionGroupHelpersTrait.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/WorkDayHelpersTest.php
This PR fixes several errors while running the L&A tests with Jenkins. There were different types of errors, but almost all of them happened only the first time the tests were executed on a brand new site (which is exactly what Jenkins does). The only exception was with a set of tests around Leave Request attachments, that failed because the test site didn't have the attachments patch applied.
This is the situation before the fixes:
All the tests are passing:
Please check the next section for details on the problems and the solutions that were applied.
As previously mentioned, there were different types of errors. Here is a list of them, and the solutions that were applied:
There are a number of tests in this extension that requires changes in CiviCRM core related to attachments. I've …
=> PCHR-2789: Fix L&A tests in Jenkins

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1007.php
This PR adds an upgrader to the L&A extension in order to remove the direct link of the "Leave" menu item in the admin, and to add instead a sub menu to it
The "Leave" menu item is a simple directly link to /civicrm/leaveandabsences/dashboard
The "Leave" menu item is now a toggle for a sub menu, containing items pointing to the individual sections of the L&A admin
=> PCHR-2625: Add sub menu to Leave menu item

uk.co.compucorp.civicrm.hrcore/hrcore.php
This PR adds the "Access CiviCRM developer menu and tools" permission to the set of available permissions in CiviHR, which will then be later used to decide whether to allow the user to see developer-related pages
=> PCHR-2626: Add 'Access CiviCRM developer menu and tools' permission

hrui/hrui.php
This PR adds a new permission checks on the Developer's menu items and paths. Those can now be accessed only by users with the "access CiviCRM" and "access CiviCRM developer menu and tools" permissions
=> PCHR-2627: Use developer permission on developer menu and paths

uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/UserMenuMarkup.tpl
The user menu, which is now the same component used both in the SSP and in the admin, contained an item called "User Guide" pointing [here](http://civihr-documentation.readthedocs.io/en/latest/self-service-portal/login-screen/)
Given that now the SSP will have a separate "Help" menu item (see [here](https://github.com/compucorp/civihr-employee-portal/pull/375)), the "User Guide" item can be safely removed
_(The screenshot is from the admin, but it's the same also in the SSP)_
=> PCHR-2630: Remove user guide menu from user menu dropdown

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlement.php, uk.co.compucorp.civicrm.hrleaveandabsences/sql/auto_uninstall.sql
This PR fixes an issue encountered when saving a Leave Period Entitlement. When the changes for the entitlement is to be logged in the Entitlement Log table an error is thrown on the screen.
The db error thrown is as a result of wrong values being inserted for the created_date column of the Leave Period Entitlement Log table.
The following lines of code was causing the `$editor` and `$createdDate` to evaluate to `1` whenever $leavePeriodEntitlement->editor_id and $leavePeriodEntitlement->created_date is not empty.
```php
$editorId = !empty($leavePeriodEntitlement->editor_id) ?: CRM_Core_Session::getLoggedInContactID();
$createdDate = !empty($leavePeriodEntitlement->created_date) ?: date('YmdHis');
```
The value of `1` being inserted into the `created_date` column which is a DATETIME type …
=> PCHR-2765:  Fix issues with creating entitlements

uk.co.compucorp.civicrm.hrcore/backstop_data/casper_scripts/onboarding-wizard/address.js, uk.co.compucorp.civicrm.hrcore/backstop_data/casper_scripts/onboarding-wizard/contact.js, uk.co.compucorp.civicrm.hrcore/backstop_data/casper_scripts/onboarding-wizard/dependents.js, uk.co.compucorp.civicrm.hrcore/backstop_data/casper_scripts/onboarding-wizard/emergency_contact.js, uk.co.compucorp.civicrm.hrcore/backstop_data/casper_scripts/onboarding-wizard/payroll.js, uk.co.compucorp.civicrm.hrcore/backstop_data/casper_scripts/onboarding-wizard/profile_picture.js, uk.co.compucorp.civicrm.hrcore/backstop_data/data/onboarding-wizard-data.js, uk.co.compucorp.civicrm.hrcore/backstop_data/page-objects/onboarding-wizard.js, uk.co.compucorp.civicrm.hrcore/backstop_data/scenarios/onboarding-wizard.json
As part of this PR, backstop JS tests has been added for the Onboarding Wizard Pages
1. `onboarding-wizard-data.js` is added, which contains the form data for the required fields.
1. In `onboarding-wizard-data.js` file, the ID's used as selectors, are not completely reliable, as they are generated by Drupal. But there is no other way to select a particular field. So went with this approach.
=> PCHR-2760: Onboarding Wizard Backstop tests

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/ContactWorkPattern.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestDeletion.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/WorkPattern.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/ContactWorkPatternTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/LeaveBalanceChangeHelpersTrait.php
This API is needed for a user to successfully request a leave in hours. The number of hours to be deducted for the Leave Request Start and End dates is set by the user on the Leave Request modal. The Front End needs the WorkDay information for a particular leave date in order to be able to present available options to the user for the start and end dates of the Leave request.
```php
civicrm_api3('LeaveRequest', 'getWorkDayForDate', array(
'leave_date' => '2016-06-01',
'contact_id' => 204,
));
Response:
{
"is_error": 0,
"version": 3,
"count": 3,
"values": {
"time_from": "09:00",
"time_to": "17:30",
"number_of_hours": "7.50"
}
}
```
- This PR adds a new `ContactWorkPatternService` class with a `getContactWorkDayForDate` which encapsulates the logic to retrieve the workday for a given date …
=> PCHR-2834: Create LeaveRequest.getWorkDayForDate API

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlement.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/ManageEntitlements.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlementTest.php
Currently, Entitlements created or updated together on the Entitlement calculation page when the Save button is clicked have their created date few seconds apart. As part of the requirements for [PCHR-2713](https://compucorp.atlassian.net/browse/PCHR-2713), We need a way to group entitlements that are updated at the same time by their date. This PR makes that possible.
Entitlements created/updated as a group when clicking the save button on the Entitlements calculation page do not have the same created date.
Entitlements created/updated as a group when clicking the save button on the Entitlements calculation page now have the same created date.
- A new parameter `$createdDate` was introduced on the `LeavePeriodEntitlement::saveFromCalculation` function.
- The same created date for the …
=> PCHR-2880: Set Created Date to be same for Entitlements Created/Updated together on Calculation Page

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Factory/LeaveBalanceChangeCalculation.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Factory/LeaveDateAmountDeduction.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsenceTypeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
When creating a TOIL request, the amount to be accrued is validated against the values of the toil amounts option group. This was causing an a validation error when requesting TOIL in hours and the number of hours does not match the option values in the toil amounts option group because for TOIL in hours, the user can enter a custom amount in hours for TOIL to be accrued
Only TOIL in hours that match the values of the TOIL amount option group can be requested
The user can request TOIL for a custom amount in hours that is not part of the values of the TOIL amount option group.
- I had to add the specification for the `toil_to_accrue` param for the LeaveRequest.create API. The API field was bound to the toil_amount option group and any value passed in the parameter that is not part of the …
=> PCHR-2878: TOIL validation for Leave in Hours

hrrecruitment/CRM/HRRecruitment/Upgrader.php, hrui/CRM/HRUI/Upgrader/Steps/4706.php, hrui/hrui.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1008.php
Menu item class that get inserted when updating the menu item icon from the form is changed from fa to **crm-i** in this PR https://github.com/civicrm/civicrm-core/pull/11025  but the upgrader I wrote still use the **fa** class.
Default icons use **fa** class.
Default icons use **crm-i** class.
Since this is not merged to staging, I just updated the existing upgraders directly.
=> PCHR-2830: Replacing fa class for menu item icons with crm-i

org.civicrm.hremergency/CRM/Hremergency/Upgrader.php, org.civicrm.hremergency/CRM/Hremergency/Upgrader/Steps/1002.php
This PR creates a new Emergency Contact relationship option, "Son/Daughter"
The "Son/Daughter" option did not exist.
The "Son/Daughter" option exists.
=> PCHR-2921: Add "Son/Daughter" Emergency Contact relationship option

hrjobcontract/CRM/Hrjobcontract/ExportImportValuesConverter.php
There needs to be changes to exported contract entitlements columns so that the exporter can know whether the entitlements exported are in hours or days. This PR effects this change.
The contract entitlements for leave types exported are not labelled by the calculation unit type.
Contract entitlements for leave types exported are now labelled by the calculation unit type.
=> PCHR-2889: Changes to Contract Entitlement Export

uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-calendar-day.html
This PR fixes several issues in Leave Calendar:
- Legend for hours absence type (by syncing via https://github.com/compucorp/civihr-employee-portal-theme/pull/276)
- Tooltip caption for TOIL in hours
The captions need to be logically separated depending on the calculation unit because they show the data from different sources. For requests in **days** the value is taken from an option group, while for requests in **hours** the value is taken from the request itself and should be formatted accordingly.
```html
<p ng-if="day.calculationUnit.name === 'days'">
{{day.supportData.toilAmounts[day.contactData.leaveRequest.toil_to_accrue].label}}</p>
<p ng-if="day.calculationUnit.name === 'hours'">
{{day.contactData.leaveRequest.toil_to_accrue | timeUnitApplier : 'hours' }}</p>
```
---
✅ Manual …
=> PCHR-2929: Fix leave calendar

hrui/css/hrui.css
_(Related to https://github.com/compucorp/org.civicrm.shoreditch/pull/71/)_
The padding top of the body was enforced in hrui, but it should have been done in Shoreditch as it related to the new menu, which is defined in the theme extension
=> PCHR-2931: Fix layout problems with Shortcut module

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/AbsenceType.tpl
This PR disables the Absence Type calculation unit selector if it cannot be changed (for example, when such an absence type has already been used in leave requests).
In PHP form builder the `disabled` attribute is now conditionally set:
```php
$this->addSelect(
'calculation_unit',
$this->getCalculationUnitSelectorParams(),
TRUE
);
// ...
private function getCalculationUnitSelectorParams () {
$calculationUnitSelectorParams = [
'options' => $this->getCalculationUnitOptions(),
// ...
];
if ($this->absenceTypeHasEverBeenUsed()) {
$calculationUnitSelectorParams['disabled'] = 'disabled';
}
return $calculationUnitSelectorParams;
}
```
However, this is not enough since the disabled selector would not provide a value on form submit which makes such an Absence Type updating impossible due to the …
=> PCHR-2883: Improve Absence Types calculation unit selector

org.civicrm.bootstrapcivihr/gulpfile.js
As part of [this PR](https://github.com/civicrm/civihr/pull/2290) some overly-specific exclusion patterns were added to the gulpfile of the `org.civicrm.bootstrapcivihr` theme extension.
This PR makes them more generic
```js
.pipe(postcss([postcssPrefix({
prefix: bootstrapNamespace + ' ',
exclude: [
/^html/, /^body/, /page-civi/,
'.crm-container .blockUI.blockOverlay', // class to display spinner on overlay
'.crm-container .dataTables_processing', // class to display spinner datatable load
outsideNamespaceRegExp
]
})]))
```
```js
.pipe(postcss([postcssPrefix({
prefix: bootstrapNamespace + ' ',
exclude: [
/^html/, /^body/, /page-civi/, /crm-container/, outsideNamespaceRegExp
]
})]))
```
=> PCHR-2949: Fix namespace exclusion patterns

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Exception/InvalidLeaveRequestMailNotificationSenderException.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Mail/Message.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestMailNotificationSender.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Mail/MessageTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestMailNotificationSenderTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/MailHelpersTrait.php
Currently Email field from "Organization contact information" from` /civicrm/admin/domain?action=update&reset=1` is used as the From email address for L&A emails. We need the from email to be picked from `/civicrm/admin/options/from_email_address?reset=1`, When there is no default from address, the first from address is picked.
Email field from "Organization contact information" from` /civicrm/admin/domain?action=update&reset=1` is used as the From email address for L&A emails.
The default From email address at `/civicrm/admin/options/from_email_address?reset=1` is used as the From email address for L&A emails. When there is no default, the first email address is used.
- The From email addresses listed at `/civicrm/admin/options/from_email_address?reset=1` are actually option values of …
=> PCHR-2863: Change Default From Address For L&A Email Notifications

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/ManageEntitlements.php
When exporting a CSV from the Manage Entitlements page, the time unit wasn't applied to overridden entitlements
There's a special condition that checks for overridden values when exporting the CSV. Now we use the `TimeUnitApplier` to apply the unit there as well.
The overridden values now have time units in the exported CSV:
---
[x] Tests pass
=> PCHR-2962: Show time unit for overridden values in the CSV exported from the Manage Entitlements page

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1005.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1006.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1007.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1008.php, uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php
_(nevermind the name of the branch with the wrong ticket number, the correct ticket was created after the PR)_
This PR introduces several fix to some of the L&A upgraders, see the Technical Details section
* The `CRM_HRLeaveAndAbsences_Upgrader_Step_1008` trait was using a upgrader function numbered `4706`, fixed it
* This
```php
use CRM_Core_BAO_SchemaHandler as SchemaHandler;
use CRM_HRLeaveAndAbsences_BAO_LeaveRequestDate as LeaveRequestDate;
```
was unnecessarily added to all the new upgraders, removed it
* In #2189 i wrote
> Finally, in #2186 I made a mistake and renamed "Leaves and Absences" into "Absences" instead of "Leave", this PR takes care of that
but didn't fix the wrong name everywhere, now it's fixed
* The `1006` upgrader moved the "leave" menu item before the "Vacancies" …
=> PCHR-2960: Fix L&A upgraders

hrjobcontract/CRM/Hrjobcontract/Upgrader.php
The Job Contracts extension adds some items to the Administer -> Customize Data and Screens -> Dropdowns menu, with links to pages where the users can add/update options to the extension's option groups. The URLs of these links contains the option group ID.
In some very unusual setups, the ID of the option group in the database might be different than the menu item link (especially when data is copied from one site to another), making it impossible for users to add or update the options.
The links to the Job Contract dropdowns followed this structure: `civicrm/admin/options?gid=<ID>` where ID was the option group ID
The links to the Job Contract dropdowns now have the option group name instead of their ID. They now follow this structure: `civicrm/admin/options/<option_group_name>`
As part …
=> PCHR-2957: Use option group names in Job Contract dropdowns links

hrrecruitment/hrrecruitment.php
_(nevermind the name of the branch with the wrong ticket number, the correct ticket was created after the branch was already created in other repos)_
The recruitment extension got its menu item's icon set for existing sites in the upgrader [here](https://github.com/civicrm/civihr/pull/2248), but the icon wasn't set when the extension was simply installed from scratch (as it happens for new sites). This PR fixes that.
=> PCHR-2961: Set recruitment menu item icon also on install

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsencePeriod.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlement.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Factory/PublicHolidayLeaveRequestService.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Queue/Task/UpdatePublicHolidayLeaveRequestsForAbsencePeriod.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeavePeriodEntitlement.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreation.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestDeletion.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/PublicHolidayLeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsencePeriodTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlementTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreationTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestDeletionTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/LeavePeriodEntitlementHelpersTrait.php
Currently if there is at least one absence type with MTPHL = Yes, the scheduled job will create public holidays for contacts having contracts in the system if a job is put on the queue. Since this is just a setting on the absence type Level, This PR makes changes such that only contacts that have entitlement of that absence type should have public holiday requests created (in addition to the existing conditions for a public holiday leave request to be created).
Also since public holiday leave requests will now only be created when the contact has entitlement for the absence type with MTPHL = Yes in addition with other conditions that need to be satisfied to create the Public Holiday leave request. It is possible for public holiday leave request not to be created at some particular point …
=> PCHR-2856: Modify Conditions To Create Public Holiday Leave Requests.

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1005.php
The scheduled jobs for some sites may not match the [expected state](https://compucorp.atlassian.net/wiki/spaces/PCHR/pages/100532387/Scheduled+jobs). This PR adds an upgrader to sync all scheduled jobs to match the expected state.
Each site could have had a different configuration for scheduled jobs.
Scheduled jobs for each site match the configuration from the Wiki. Any scheduled jobs not listed in the Wiki will be disabled.
=> PCHR-2839: Sync Scheduled Job State

org.civicrm.hremergency/CRM/Hremergency/Upgrader.php, org.civicrm.hremergency/CRM/Hremergency/Upgrader/Steps/1003.php
Emergency contacts have no required fields. With the new separation of "Emergency Contacts" and "Dependants" it is important that "Is a Dependant" is always set. In other places we require it (but hide the field) as well as name, mobile number and relationship. These should be required everywhere.
Emergency contact custom fields had no required fields.
Emergency contacts have the following required fields:
- Name
- Mobile Number
- Relationship with Employee
- Is a Dependant?
=> PCHR-2998: Add Upgrader to set Emergency Contact Required Fields

hrui/CRM/HRUI/Upgrader.php
After a merge conflict an upgrader was renamed, but it wasn't added to
the upgrader after renaming.
An upgrader trait that adds a new custom field was not added to the base upgrader class.
The upgrader trait is added.
- The conflict was fixed in [this commit](https://github.com/civicrm/civihr/commit/c21a632d8df1cc657c40bb80536217ab1c174cfa)
=> PCHR-3018: Re-add missing upgrader

uk.co.compucorp.civicrm.hrcore/api/v3/Job/CheckCivihrVersion.php
This PR adds the API endpoint to send statistics. The endpoint is still empty right now.
There was no `Job.check_civihr_version` endpoint`
There is a `Job.check_civihr_version` endpoint` and it is only accessible to those with "Access AJAX API" permission (by default)
=> PCHR-3025: Add API Endpoint

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Model/CiviHRStatistics.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Model/ReportConfiguration.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Model/ReportConfigurationAgeGroup.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Service/CiviHRStatisticsJSONConvertor.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Files/statistics_sample_request.json, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Service/CiviHRStatisticsConvertorTest.php
To make it easier to deal with the statistics that we will send, and avoid using large, complicated arrays these classes will represent all data to be send in the statistics request. 
The goal is to produce a JSON string with [this format](https://gist.github.com/mickadoo/3eb09bafa18760c12fcccced7a1afc33).
There were no classes to use when gathering and sending statistics.
There are classes to represent all the data being sent. Another class is responsible for producing a JSON string to match the [expected specification](https://gist.github.com/mickadoo/3eb09bafa18760c12fcccced7a1afc33).
=> PCHR-3026: Classes to Represent Pingback Statistics

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Queue/Task/UpdateAllPublicHolidayLeaveRequests.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Queue/Task/UpdateAllPublicHolidayLeaveRequestsExceptThoseAlreadyCreatedInThePast.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreation.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsenceTypeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreationTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestTest.php
If a public holiday is added in the past or future when there is no absence type with MTPHL = Yes, public holiday leave requests will not be created for any of the the public holiday dates. However when MTPHL is now set = Yes for an absence type, only public holiday leave requests in the future get created. This PR modifies this logic when the MTPHL property of an absence type is toggled, in order to allow leave requests for past holiday dates to also be created.
Public Holiday leave requests for past public holiday dates(that does not have leave requests created for them for all qualified contacts) are not created when an Absence Type MTPHL is set to Yes.
Public Holiday leave requests for past public holiday dates(that does not have leave requests created for them for all qualified …
=> PCHR-2906: Create Public Holiday Requests in the past when MTPHL is set to yes

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/ContactWorkPattern.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Queue/Task/UpdateAllFuturePublicHolidayLeaveRequests.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/ContactWorkPatternTest.php
Currently, when changes are made to a Work Pattern, public holiday leave requests in the future are updated for all contacts using the work pattern If the work pattern has effective end date is greater than or equal to the current date for a work pattern that is not the default.
However for the case when a contact is newly assigned a custom Work Pattern, we don't currently update future public holiday leave requests for the contact. This PR makes changes such that when a custom work pattern whose effective end date is greater than or equal to the current date is newly assigned to a contact, public holiday leave requests in the future are updated for the contact.
- Public holiday leave requests in the future are not updated for a contact that is newly assigned a custom work pattern.
- …
=> PCHR-3011: Update Public Holiday Leave Requests For Contact When Contact is Assigned A Custom Work Pattern

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveDateDaysAmountDeduction.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveDateDaysAmountDeductionTest.php
When saving a leave request in days with the To date being an half day type, the balance change displayed on the modal is correct but after saving the request the balance change is incorrect because instead of 0.5 to be deducted for the To date, 1 is deducted instead. This PR fixes the bug.
Half-day is not taken into account for To date when requesting Leave after the request is saved.
Half-day is taken into account for To date when requesting Leave after the request is saved.
- When calculating the balance change after a leave request is saved, because the time `00:00 and 23:59` has already been added for the leave request from date and to date respectively, There is an issue with this line [here](https://github.com/civicrm/civihr/blob/ebab52f182e811d10d68be9864c29dbbe08a9409/uk.co.compuc …
=> PCHR-2995: Fix Issue with Half-day not taken into Account For To date When requesting Leave

uk.co.compucorp.civicrm.hrcore/backstop_data/data/onboarding-wizard-data.js, uk.co.compucorp.civicrm.hrcore/backstop_data/page-objects/onboarding-wizard.js
This PR fixes the backstop js tests for Onboarding Wizard, which was introduced on https://github.com/civicrm/civihr/pull/2247.
1. The Path was wrong for the some of the JS files
2. For the test cases to work, the form needed to be submitted once.
3. Some of the form data used was not necessary as the already submitted form data could have been used.
1. Fixed the paths in https://github.com/civicrm/civihr/pull/2363/files#diff-633654d50389da72e0fb1986cb0b4928L1
2. Added the requirement of form submission in 
https://compucorp.atlassian.net/wiki/spaces/PCHR/pages/117984407/BackstopJS+CiviHR
3. Removed the unnecessary form data, only kept dependents data, as backstop is not able to use the same from saved data.
=> PCHR-2760: Fix Onboarding Wizard backstop JS Tests

uk.co.compucorp.civicrm.hrcontactactionsmenu/LICENSE.txt, uk.co.compucorp.civicrm.hrcontactactionsmenu/README.md, uk.co.compucorp.civicrm.hrcontactactionsmenu/hrcontactactionsmenu.civix.php, uk.co.compucorp.civicrm.hrcontactactionsmenu/hrcontactactionsmenu.php, uk.co.compucorp.civicrm.hrcontactactionsmenu/info.xml
This PR creates the uk.co.compucorp.civicrm.hrcontactactionsmenu  extension. This is just the first commit for this extension and it only contains the basic skeletal extension structure.
This extension will provide functionality that allows other extensions add menu items to the contact actions menu on contact summary page.
The extension will provide a hook called addContactMenuActions, This hook can be invoked by other extensions that needs to add menu items to specific panels of the contact actions menu.
=> PCHR-3067: Add the contactactionsmenu extension.

Jenkinsfile
With our current workflow, not all Pull Requests target staging. Most of the time, a PR will target a feature branch, which groups a number of PRs for smaller tasks, until the feature is complete and finally ready to be merged to staging. 
It was not possible for Jenkins to run the tests for such Pull Requests. Before running the tests, a new site is created using `civibuild` and the PR's branch as the value for the `--hr-ver` option. The command then tries to pull the code from this branch in all the repositories used by CiviHR but, in most of the cases, the branch will only exist in one or two of them and the installation will fail, making Jenkins mark the build as failed.
After the site is created and before running the tests, Jenkins:
- Checks out the PR branch
- Merge the PR target …
=> PCHR-3095: Add support for running tests in Jenkins for feature branches

org.civicrm.hremergency/CRM/Hremergency/Test/BaseHeadlessTest.php, org.civicrm.hremergency/tests/phpunit/CRM/Hremergency/Service/EmergencyContactServiceTest.php, org.civicrm.hremergency/tests/phpunit/api/v3/Contact/DeleteemergencycontactTest.php, org.civicrm.hremergency/tests/phpunit/bootstrap.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Test/Helpers/SessionHelper.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Service/DrupalUserServiceTest.php
Jenkins cannot run the hremergency tests. Whenever it tries it, it fails with this error:
```
[civihr_PR-2238-QTNEV4RQWI3LHQFNHVVNONTJAJCGQNOPCH4L6BQMFDWYHF7L54LQ] Running shell script
+ cd /opt/buildkit/build/hr17-dev_PR-2238/sites/all/modules/civicrm/tools/extensions/civihr/org.civicrm.hremergency
+ phpunit4 --testsuite=Unit Tests --log-junit /var/lib/jenkins/workspace/civihr_PR-2238-QTNEV4RQWI3LHQFNHVVNONTJAJCGQNOPCH4L6BQMFDWYHF7L54LQ/reports/phpunit/result-phpunit_hremergency.xml
PHPUnit 4.8.21 by Sebastian Bergmann and contributors.
RuntimeException: Suite includes headless tests (CRM_Hremergency_Service_EmergencyContactServiceTest) which require CIVICRM_UF=UnitTests.
Tip: Run the headless tests and end-to-end tests separately, e.g.
$ phpunit4 --group headless
$ phpunit4 --group e2e …
```
=> PCHR-3100: Fix hremergency PHP tests

Jenkinsfile
This PR updates the Jenkinsfile so that notifications are sent to Hipchat once a build starts and once it  completes (successfully or not).
No notifications were sent from Jenkins to Hipchat
A notification is sent when the build starts:
It contains a link to the PR or branch being built, as well a link to the report on the Blue Ocean UI, in Jenkins.
When the build finishes, you have different messages for when it was successful:
Or for when it failed:
In parts of the file, it's possible to see that double quotes were used for String interpolation:
```groovy
return "<a href=\"${env.CHANGE_URL}\">\"${env.CHANGE_TITLE}\"</a>"
```
However, in other places, it seems that single quotes have been used for the same purpose:
```groovy
return 'Click <a href="$BLUE_OCEAN_URL">here</a> to see the …
```
=> PCHR-3096: Send Hipchat notifications for Jenkins builds

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Model/CiviHRStatistics.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Service/Stats/StatsSender.php, uk.co.compucorp.civicrm.hrcore/api/v3/Job/CheckCivihrVersion.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Service/Stats/StatsSenderTest.php, uk.co.compucorp.civicrm.hrcore/xml/services.xml
As part of the pingback epic CiviHR statistics will be gathered from each client site and sent to a central server. This PR deals with the sending of the statistics.
Functionality to send statistics was unfinished
We have a class that accepts a statistics object, turns it to JSON and sends it to a server. The server endpoint can be overridden in your settings file. Both successful transmissions and errors will be logged.
=> PCHR-3029: Sending Stats

.github/PULL_REQUEST_TEMPLATE.md
The PR template does not have a section regarding overridden/patched core files, which could be overlooked by a dev when she documents the PR. This PR adds one
=> PCHR-3120: Add "core overrides" section to PR template

uk.co.compucorp.civicrm.hrcontactactionsmenu/CRM/HRContactActionsMenu/Hook/AddContactMenuActions.php, uk.co.compucorp.civicrm.hrcontactactionsmenu/tests/phpunit/CRM/HRContactActionsMenu/Hook/AddContactMenuActionsTest.php
This HRContactActionsMenu provides functionality that allows other extensions to add menu items to the contact actions menu on contact summary page via the `addContactMenuActions` hook.
This PR defines the hook and the parameter that other extensions calling the hook will expect.
- The impementation for the  addContactMenuActions hook was not present.
- The implementation for the  addContactMenuActions hook was added.
- The action to invoke the addContactMenuActions hook will be added in the `contactactionsmenu_civicrm_pageRun` hook implementation. This will be added in subsequent PR when the template for the contact actions menu is added.
A sample implementation of the hook e.g by the Leave and Absence extension will be:
```php
function hrleaveandabsences_addContactActions(ActionsMenu …
```
=> PCHR-3069: Add the addContactMenuActions Hook implementation

uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/AbsenceType.tpl
It's not possible to disable carry forward per leave type once enabled. This PR fixes that bug.
The same bug was present for TOIL Expiry select field, that is fixed too.
**Carry Forward**
**TOIL**
**Carry Forward**
**TOIL**
This is a regression issue. In https://github.com/civicrm/civihr/pull/2300, we have added hidden fields to store the select values, but when we untick the select fields from code, the change event(https://github.com/civicrm/civihr/pull/2300/files#diff-80451403917186e0141a3b6700e2b299R357) does not get fired. So added the same in all places where we change the value of select from code.
=> PCHR-3130: Fix for Wrong Select Field values sent to backend in Absence Type Page

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Wrapper/LeaveRequestDates.php, uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/API/Wrapper/LeaveRequestDatesTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/bootstrap.php
Leave Requests ending on the last day of an Absence Period were not being displayed on the Absence Report and on the Leave Calendar.
This was a regression introduced by https://github.com/civicrm/civihr/pull/2260. In that PR, two changes related to the `from_date` and `to_date` fields were made in order to support Leave Request in hours:
- Their type [changed from date to datetime](https://github.com/civicrm/civihr/pull/2260/files#diff-0c81d1d212efc488e009f00d2cad8678R338)
- The LeaveRequest.create API was changed ([here](https://github.com/civicrm/civihr/pull/2260/files#diff-7bf537a036f3438a73ec57bd207d87daR37) and [here](https://github.com/civicrm/civihr/pull/2260/files#diff-7bf537a036f3438a73ec57bd207d87daR784)) to automatically set the hour in case it was not present (i.e. it's a …
=> PCHR-3099: Make sure LeaveRequest.get and .getFull API will return requests ending on the last day of a period

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/CMSData/UserMailNotifier/Drupal.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/CMSData/UserMailNotifierFactory.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/CMSData/UserMailNotifierInterface.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/CMSData/UserRole/Drupal.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/CMSData/UserRoleFactory.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/CMSData/UserRoleInterface.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/CMSData/UserMailNotifier/DrupalTest.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/CMSData/UserMailNotifierFactoryTest.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/CMSData/UserRole/DrupalTest.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/CMSData/UserRoleFactoryTest.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/drupal_function_mocks.php
This PR adds some generic CMS related classes and interfaces to the HRCore extension that can be used by other extension to display and perform CMS framework related actions.
CMS User interfaces related to Roles and Mail notification were not present.
The following interfaces were added in this PR:
- CRM_HRCore_CMSData_UserMailNotifierInterface: This interface provides methods for notifying the CMS user mainly for sending password reset email and welcome email functionality and can be extended by relevant CMS framework class
- CRM_HRCore_CMSData_UserRoleInterface: This interface provides information about the roles of a CMS user.
The following classes were added to implement the Interfaces
- The CRM_HRCore_CMSData_UserRole_Drupal and the CRM_HRCore_CMSData_UserMailNotifier_Drupal class …
=> PCHR-3073: Add CMS Data related classes

uk.co.compucorp.civicrm.hrcore/backstop_data/page-objects/modals/document.js, uk.co.compucorp.civicrm.hrcore/backstop_data/page-objects/ssp-leave-absences-manager-leave-requests.js, uk.co.compucorp.civicrm.hrcore/backstop_data/scenarios/leave-balances.json
This PR fixes Backstop tests which were throwing errors or did not complete.
This scenario was not completing
"Admin Portal: Leave Balances"
The credential was wrong, so it has been changed to `admin`.
These 3 scenarios were not completing
"Leave and Absences: Manager Leave Requests: Apply leave on behalf of staff"
"Leave and Absences: Manager Leave Requests: Apply sickness on behalf of staff"
"Leave and Absences: Manager Leave Requests: Apply toil on behalf of staff"
The selector to open the dropdown buttons to choose the leave type, was wrong. So changed it to `.button-container leave-request-record-actions .dropdown-toggle'`.
These 3 scenarios were not completing
"T&A / Documents / Document / Select Type"
"T&A / Documents / Document / Select Assignee"
"T&A / Documents / Document / Pick …
=> PCHR-3151: Fix backstop tests

uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-balance-tab.html
In Leave Balance, staff names are not alphabetically ordered. This PR fixes the bug.
This is not a regression issue, 
In `leave-balance-tab.html`, added `orderBy: 'contact_display_name'` filter.
=> PCHR-3054: Order Staff names alphabetically in Leave Balance

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/CMSData/UserMailNotifier/Drupal.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/CMSData/UserMailNotifierFactory.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/CMSData/UserMailNotifierInterface.php, uk.co.compucorp.civicrm.hrcore/config/container/container.xml, uk.co.compucorp.civicrm.hrcore/hrcore.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/CMSData/UserMailNotifier/DrupalTest.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/CMSData/UserMailNotifierFactoryTest.php
This PR is a follow up to [#2399](https://github.com/civicrm/civihr/pull/2399)
It modifies the UserNotifier Interface so that a single instance of the class can be used to send notifications to multiple users, Also the UserInterface Factory now gets the CmsFramework parameter from inside the create method.
- A new instance of the UserNotifier class would have to be created per user to send notification to multiple users.
- A new getUser method was added to the UserMailNotifierInterface class and the constructor method was removed.
- The create method of the UserMailNotifierFactory was modified to get the userFramework within the method, This is to allow the UserMailNotifier class to be easily made into a civi container that can be called from any extension. There were some issues in …
=> PCHR-3073: Modify UserNotifier Interface and related classes.

uk.co.compucorp.civicrm.hrcore/backstop_data/page-objects/onboarding-wizard.js
This PR fixes the Failing Backstop test in Onboarding Wizard.
In https://github.com/compucorp/civihr-employee-portal/commit/dc26aac1b158f968409b9514a6b0f63e86e582bd form key was changed to `do_you_have_any_dependants`. Updated the ID in backstop tests accordingly.
=> PCHR-3169: Fix Onboarding Backstop JS Test

hrui/css/hrui.css
This PR hides "Delete", "Restore from Trash" and "Delete Permanently" buttons form contact page.
1. Delete botton:
2. Restore and delete permanently buttons
1. Delete button hidden. 
2. restore and delete permanently hidden:
1.Add following css rule to hide `.crm-contact-restore`, `.crm-contact-delete` and `.crm-contact-permanently-delete` in file [hrui.css](https://github.com/civicrm/civihr/blob/staging/hrui/css/hrui.css)
```css
.crm-contact-restore, 
.crm-contact-delete,
.crm-contact-permanently-delete {
display: none;
}
```
**Note:** Here the buttons could have been removed frm templates but it would require an override to  CiviCRM core template file, which is a complex process for just to hide buttons, so css is used instead.
- These buttons from current place is hidden and will be …
=> PCHR-3072: Hide buttons via css

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/CMSData/UserAccount/Drupal.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/CMSData/UserAccountFactory.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/CMSData/UserAccountInterface.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/CMSData/UserAccount/DrupalTest.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/CMSData/UserAccountFactoryTest.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/drupal_function_mocks.php
This PR adds some generic CMS related classes and interfaces to the HRCore extension that can be used by other extension to display and perform CMS framework related actions.
The class added in this PR is the UserAccount Interface and its related classes.
CMS User interfaces and classes related to User Account were not present.
The following interface was added in this PR:
- CRM_HRCore_CMSData_UserAccountInterface: This interface provides methods functionality for taking some actions/providing some information on a user account. Currently it provides method for cancelling, enabling and disabling a user account and also provides information on whether a user account is disabled or not.
The following class was added to implement the Interface
- The CRM_HRCore_CMSData_UserAccount_Drupal …
=> PCHR-3138: Add UserAccount Interface and related classes

uk.co.compucorp.civicrm.hrcontactactionsmenu/CRM/HRContactActionsMenu/Page/UserAccount.php, uk.co.compucorp.civicrm.hrcontactactionsmenu/hrcontactactionsmenu.civix.php, uk.co.compucorp.civicrm.hrcontactactionsmenu/hrcontactactionsmenu.php, uk.co.compucorp.civicrm.hrcontactactionsmenu/xml/Menu/hrcontactactionsmenu.xml
This PR adds the page URL's for disabling, enabling and deleting the CMS user of a contact and the Page callbacks that handles these functionalities.
The functionality for disabling, enabling and deleting the CMS user of a contact does not exist.
- The User account interface and related classes added in #2408, were utilized to implement the needed functionalities, The disable, enable and cancel methods on this interface were used after getting the appropriate CMS object from the factory.
- Commits 57074b5 fixes the access arguments for the User notifier related paths added in a previous PR, the arguments needed is 'access CiviCRM' rather than 'edit all contacts'
- Also there's an error about the CRM_Hrcontactactionsmenu_ExtensionUtil not found in the hrcontactactionsmenu.php file, this …
=> PCHR-3138: Add Page URL Callbacks for Disabling/Enabling and Deleting User Account

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/CMSData/Role/DrupalRoleService.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Service/Stats/StatsCache.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Service/Stats/StatsGatherer.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Service/Stats/StatsSender.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Service/Stats/StatsCacheTest.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Service/Stats/StatsGathererTest.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Service/Stats/StatsSenderTest.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/bootstrap.php
After going over the QA plan myself locally I noticed some things that could be improved. This PR fixes those.
- Roles that had no login date were excluded
- Cache expiration was checking if the cache was created earlier than 1 week ago today at 00:00:00
- Report configuration count was not included
- The warning about setting CIVIHR_STATISTICS_ENDPOINT was unclear
- Error responses from the server were not handled well. Even though an error was generated Civi doesn't really do HTTP status codes, and the HTTP client doesn't really care about them so much anyway.
- Most recent login date for all roles is included (except anonymous and authenticated user)
- Cache expiration checks if the cache was created simply early than 1 week ago (from now)
- Report configuration count is included
- The …
=> PCHR-3182: Fixes From Local Testing

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1016.php
This PR fixes the the URL for the Leave Balances tab in the main menu.
This issue was introduced due to the way we used to merge incomplete code into `la-milestone-3` instead of using a feature branch.
The first URL for the Leave Balances tab was `#/balance-report` introduced by #2045 and the [1007 upgrader referenced it](https://github.com/civicrm/civihr/blob/staging/uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1007.php#L53).
After discussing the changes with @jamienovick the tab URL was changed to `#/leave-balances` and updated in #2070 before the 1007 upgrader was merged in #2240
To fix this issue a new 1016 upgrader has been added which updates the URL of leave balances to the right one:
```php
<?php
trait CRM_HRLeaveAndAbsences_Upgrader_Step_1016 { …
```
=> PCHR-3015: Fix Leave Balances URL

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/CMSData/UserAccount/Drupal.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/CMSData/UserAccount/DrupalTest.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/drupal_function_mocks.php
This PR fixes a bug in the isUserDisabled method added in #2408
The isUserDisabled method of the CRM_HRCore_CMSData_UserAccount_Drupal class was not returning correctly.
The isUserDisabled method of the CRM_HRCore_CMSData_UserAccount_Drupal class was fixed to returning correctly.
=> PCHR-3088: Fix bug in Drupal User Account isUserDisabled method

uk.co.compucorp.civicrm.hrcore/backstop_data/casper_scripts/ssp-leave-absences/staff/my-leave-calendar_tooltip.js, uk.co.compucorp.civicrm.hrcore/backstop_data/page-objects/ssp-leave-absences-my-leave-calendar.js, uk.co.compucorp.civicrm.hrcore/backstop_data/scenarios/ssp-la-my-leave-calendar.json
This PR adds Backstop scenarios for the Leave Calendar tooltip.
After Shoreditch was removed from SSP ([in this PR](https://github.com/compucorp/civihr-employee-portal/pull/396)) the tooltip styles provided by Shoreditch were also removed. This could have been avoided if BackstopJS scenarios were implemented for it.
In order to display the tooltip, a new methods were added to the `ssp-leave-absences-my-leave-calendar.js` page object:
Just clears all selected months and doesn't wait for anything:
```js
// Script:
page.init(casper).clearAllSelectedMonths();
// Page Object Method:
clearAllSelectedMonths: function () {
this.casper.evaluate(function () {
jQuery('.chr_leave-calendar__day-selector .close.ui-select-match-close')
.each(function () {
jQuery(this).click();
});
});
return this;
}
``` …
=> PCHR-2984: Add SSP Calendar's tooltip BackstopJS scenarios

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1017.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php
After changing the Leave Request's Absence Type to a type with a different calculation unit, users were not able to update the request status. Staff members would get an error saying that one of the date type or date amount fields had to be empty and Managers would get an error saying that they could not change the request dates (even though they were not changing any date).
As a staff member, trying to update the status of a Leave Request that had its Absence Type changed to another one with a different calculation unit would result in a validation error:
As a manager, trying to update the status of the same Leave Request would result in a validation error saying that the dates could not be changed:
Staff members can now update the Leave Request status after it had its Absence Type …
=> PCHR-3094: Fix validation errors after changing Leave Request's Absence Type

hrcase/CRM/HRCase/Upgrader.php
After clearing the cache some sites show an error that:
```
CRM_Core_Exception: 
Invalid Entity Filter in CRM_Core_BAO_CustomGroup::validateSubTypeByEntity()
```
It happens when this method call is made:
```CRM_Core_BAO_CustomGroup::validateSubTypeByEntity('Case', 'Exiting')```
For custom groups not based on Contacts, `validateSubTypeByEntity` expects an integer as the second argument. This has been the case ever since it was introduced in [April, 2016](https://github.com/civicrm/civicrm-core/commit/79363422d47677e58596798ed26304c8c4b9953c#diff-d9f1be3fcfd7cea0a4864a21997c258aR642).
This call is triggered after clearing the cache. During rebuilding of the cache the views plugin data cache is rebuilt . This leads to a call to `civicrm_views_data_alter` when CiviCRM tries to load all custom …
=> PCHR-2502: Remove Unused Custom Groups

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1007.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1018.php
This PR makes the `Line Manager/Line Manager is` Relationship and the `Leave Approver of/has Leave Approved by` Relationship types reserved.
The `Line Manager/Line Manager is` Relationship and the `Leave Approver of/has Leave Approved by` Relationship types are not reserved and can be disabled or deleted.
The `Line Manager/Line Manager is` Relationship and the `Leave Approver of/has Leave Approved by` Relationship types are now reserved and can not be disabled or deleted.
- Since the HR core extension is responsible for creating the `Line Manager/Line Manager is `Relationship type, An upgrader was added in this extension to make the relationship type reserved.
-  Since the Leave and Absence extension is responsible for creating the ` Leave Approver of/has Leave Approved by` Relationship …
=> PCHR-3083: Make Line Manger and Leave Approver Relationship Types reserved

hrui/CRM/HRUI/Upgrader.php, hrui/CRM/HRUI/Upgrader/Steps/4708.php, hrui/hrui.php
This PR enables the Activities Contact tab on the contact summary page for new and existing installations. The tab was previously disabled/hidden via the installation of the HRUI extension.
The Activities Contact tab is not visible on the contact summary page
The Activites Contact tab is now visible on the contact summary page
=> PCHR-3080: Enable the CiviCRM Activities Contact tab for new and existing installation

uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestTest.php
The `CRM_HRLeaveAndAbsences_Service_PublicHolidayLeaveRequestTest::testItUpdateAllInTheFutureWhenTheContractDetailsAreUpdated` test fails when executed near during the last days of January
The test was failing with this error:
```
There was 1 error:
1) CRM_HRLeaveAndAbsences_Service_PublicHolidayLeaveRequestTest::testItUpdateAllInTheFutureWhenTheContractDetailsAreUpdated
PEAR_Exception: DB Error: already exists
/vagrant/hr17/sites/all/modules/civicrm/CRM/Core/Error.php:946
/vagrant/hr17/sites/all/modules/civicrm/packages/PEAR.php:921
/vagrant/hr17/sites/all/modules/civicrm/packages/DB.php:985
/vagrant/hr17/sites/all/modules/civicrm/packages/PEAR.php:575
/vagrant/hr17/sites/all/modules/civicrm/packages/PEAR.php:224
/vagrant/hr17/sites/all/modules/civicrm/packages/DB/common.php:1905 …
```
=> PCHR-3231: Fix tests failing on the last days of January

uk.co.compucorp.civicrm.hrcore/backstop_data/scenarios/tab-absence.json, uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php
This PR renames the Absence tab in the Contact's view to "Leave".
The hrleaveandabsences_civicrm_tabset function in hrleaveandabsences.php was modified in order to rename the absence title:
```php
function hrleaveandabsences_civicrm_tabset($tabsetName, &$tabs, $context) {
//check if the tabset is Contact Summary Page
if ($tabsetName == 'civicrm/contact/view') {
$contactId = $context['contact_id'];
$tabs[] = [
'id'        => 'absence',
'url'       => CRM_Utils_System::url('civicrm/contact/view/absence', ['cid' => $contactId]),
'title'     => ts('Leave'),
'weight'    => 10
];
}
}
```
BackstopJS scenarios for absence-tab ran successfully, with the only issue being that the change was not detected in Backstopjs 2.x but it did in 3.x
This PR is related to …
=> PCHR-3222 change absence tab name and icon

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/BuildForm/ActivityFilterSelectFieldsModifier.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/BuildForm/ActivityLinksFilter.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1008.php, uk.co.compucorp.civicrm.hrcore/hrcore.php
The Civicrm activity tab was enabled in a recent PR: #2434, This PR modifies the results and activity type filters on the activity tab page to only consider activities of type 
- Email
-  Inbound email 
- Reminder Sent
- Print PDF Letter.
- All active activity types are displayed and can be filtered by on the activity tab page.
- The `Add New activity` link tab was modified to only display links related to the chosen activity types mentioned in the PR description.
To achieve this, the hrcore_civicrm_buildForm was implemented to intercept the `CRM_Activity_Form_ActivityLinks` form responsible for supplying the activity links and then the list was filtered to only include the needed activity types.
Also after implementing the hook, the Inbound email and Reminder Sent activity types were not …
=> PCHR-3081: Modify the CiviCRM activity tab to only show activities of certain types only

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/Tabset/ActivityTabModifier.php, uk.co.compucorp.civicrm.hrcore/hrcore.php
This PR renames the Activities tab to Communications. 
The Activities tab is named as Activities
The Activity tab was renamed to Communications by implementing `hook_civicrm_tabset` in the HRCore extension.
=> PCHR-3082: Rename Activities tab to Communications.

uk.co.compucorp.civicrm.hrcontactactionsmenu/CRM/HRContactActionsMenu/Component/GroupButtonItem.php, uk.co.compucorp.civicrm.hrcontactactionsmenu/CRM/HRContactActionsMenu/Helper/Contact.php, uk.co.compucorp.civicrm.hrcontactactionsmenu/templates/CRM/HRContactActionsMenu/Page/Inline/Actions.tpl, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Component/ContactActionsMenu/LineManagersListItem.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Component/ContactActionsMenu/NoSelectedLineManagerTextItem.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Helper/ContactActionsMenu/WorkflowActionGroup.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Test/BaseHeadlessTest.php, uk.co.compucorp.civicrm.hrcore/hrcore.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Helper/ContactActionsMenu/WorkflowActionGroupTest.php
This PR displays the Workflow related menu items on the main panel of the Contact Actions menu using the hook provided by the contactactionsmenu extension.
Workflow related menu Items were displayed statically.
- The Workflow related menu items are now displayed dynamically depending on the contact being viewed on the contact summary page.
- The Tasks and Assignments extension being the owner of the workflow related menu items is supposed to be the one to implement the `addContactMenuActions` hook but since the extension is supposed to be a standalone and independent of CiviHR, the HRCore extension implements the hook instead with a check to make sure that the T&A extension is enabled before injecting the menu items via the hook.
With Contact having no Line Manager
With Contact having a …
=> PCHR-3076: Display Workflow Info on Contact Actions Menu

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1018.php, uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-calendar-day.html
As per https://github.com/civicrm/civihr/pull/2443 end time can be chosen for single day leave requests in hours calculation unit. However, existing such leave requests are storing end time currently equal to start time. This upgrader fetches such leave requests, retrieves information about work pattern day basing on the date of the leave request and, if it is still a working day, sets the end time from the working day as an end time of the leave request.
The upgrader simply takes "to" date of the single day request (which equals the "from" date) and  replaces the time taken from the work pattern day corresponding to this date.
```php
// Construct query that selects all existing single day leave requests in hours
$query = "SELECT leaveRequest.id
FROM {$leaveRequestTable} leaveRequest …
```
=> PCHR-3251: Upgrader for single day requests in hours

uk.co.compucorp.civicrm.hrcontactactionsmenu/templates/CRM/HRContactActionsMenu/Page/Inline/Actions.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Component/ContactActionsMenu/LeaveApproversListItem.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Component/ContactActionsMenu/NoSelectedLeaveApproverItem.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Helper/ContactActionsMenu/LeaveActionGroup.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Mail/Message.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveManager.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Helper/ContactActionsMenu/LeaveActionGroupTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Mail/MessageTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveManagerTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestMailNotificationSenderTest.php
This PR displays the Leave related menu items on the main panel of the Contact Actions menu using the hook provided by the contactactionsmenu extension.
Leave related menu Items were displayed statically.
The Leave related menu items are now displayed dynamically depending on the contact being viewed on the contact summary page.
The Leave and Absences extension implements the `addContactMenuActions` hook to display Leave related menu items on the Contact Actions menu.
With Contact Having no Leave Approver
With Contact Having a Leave Approver
When the Add Leave Approver Button is clicked
When the Record Leave button is clicked
=> PCHR-3075:  Display Leave Info on Contact Actions Menu

uk.co.compucorp.civicrm.hrcontactactionsmenu/CRM/HRContactActionsMenu/Helper/CommunicationActionGroup.php, uk.co.compucorp.civicrm.hrcontactactionsmenu/hrcontactactionsmenu.php, uk.co.compucorp.civicrm.hrcontactactionsmenu/templates/CRM/HRContactActionsMenu/Page/Inline/Actions.tpl, uk.co.compucorp.civicrm.hrcontactactionsmenu/tests/phpunit/CRM/HRContactActionsMenu/Helper/CommunicationActionGroupTest.php
This PR displays the Communication related menu items on the main panel of the Contact Actions menu using the hook provided by the contactactionsmenu extension.
Communication related menu Items were displayed statically.
The Communication related menu items are now displayed with dynamic links depending on the contact being viewed on the contact summary page.
When the Send Email Button is clicked:
When the Record Meeting Button is clicked:
When the Create PDF Letter Button is clicked.
=> PCHR-3078: Display Communications Info on Contact Actions Menu

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsencePeriod.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/ManageEntitlements.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsencePeriodTest.php
When there is no absence period with dates containing the current date and a user tries to update entitlements after creating/updating a contract, an Error 500 page appears. This PR fixes the issue by redirecting to Manage entitlements calculation page to calculate entitlements for the closest absence period to the current date after creating/updating a contract. 
- When a user tries to update entitlements after creating/updating a contract, entitlements is calculated for the absence period with dates containing the current date.
- Rather than calculate entitlements for the absence period explicitly with dates containing the current date when a user tries to update entitlements after creating/updating a contract, entitlements is calculated for the closest absence period to the current …
=> PCHR-3056: Use Closest Absence Period to Current Date For Manage Entitlement Calculation

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/CMSData/UserPermission/Drupal.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/CMSData/UserPermissionFactory.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/CMSData/UserPermissionInterface.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/CMSData/UserAccountFactoryTest.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/CMSData/UserMailNotifierFactoryTest.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/CMSData/UserPermission/DrupalTest.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/CMSData/UserPermissionFactoryTest.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/drupal_function_mocks.php
This PR adds some generic CMS related classes and interfaces to the HRCore extension that can be used by other extensions.
The class added in this PR is the UserPermission Interface and its related classes
CMS UserPermission interface and related classes were not present.
The following interface was added in this PR:
- CRM_HRCore_CMSData_UserPermissiontInterface: This interface provides functionality to check if a CMS user has access to certain permissions or not.
The following class was added to implement the Interface
- The CRM_HRCore_CMSData_UserPermission_Drupal class
The following factory class was added:
- The CRM_HRCore_CMSData_UserPermissionFactory.
- These classes were added primarily to aid the task being done in https://compucorp.atlassian.net/browse/PCHR-3074
=> PCHR-3074: Add the CMS User Permission Interface and related classes

package-lock.json, package.json
This PR adds [stylelint](https://stylelint.io/) to the pre-commit hook, enforcing the style defined in the [stylelint-config-sass-guidelines](https://github.com/bjankord/stylelint-config-sass-guidelines) configuration, based on [sass-guidelin.es](https://sass-guidelin.es/)
The default regex pattern did not allow any bem__type--selector. There is available a [stylelint-selector-bem-pattern](https://github.com/simonsmith/stylelint-selector-bem-pattern) plugin that we could have used, but in the end I opted to simply not enforcing any pattern at all, given that we are using a mix of BEM and non-BEM selectors across our css codebase
The default rule allowed only 1 level of nesting, which was a bit too much. I've raised the limit to a much more reasonable (but yet strict enough) depth of 3 …
=> PCHR-3246: Implement stylelint for SASS files

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Page/Reports.php, uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Page/Reports.tpl, uk.co.compucorp.civicrm.hrcore/xml/Menu/hrcore.xml
This PR introduces changes necessary to support the enhancement described on https://github.com/compucorp/civihr-employee-portal/pull/440. Please check that PR for more details
=> PCHR-3285: Redirect from the SSP report pages to the CiviHR admin

uk.co.compucorp.civicrm.hrcontactactionsmenu/CRM/HRContactActionsMenu/Helper/CommunicationActionGroup.php, uk.co.compucorp.civicrm.hrcontactactionsmenu/tests/phpunit/CRM/HRContactActionsMenu/Helper/CommunicationActionGroupTest.php
This PR renames the Communications menu group title to follow what is the original wireframe rather than the mockup. The title is changed from `Communicate` to `Communications`
=> PCHR-3291: Rename Communications Menu Title

contactaccessrights/CRM/Contactaccessrights/Helper/ContactActionsMenu/ContactAccessActionGroup.php, contactaccessrights/tests/phpunit/CRM/Contactaccessrights/Helper/ContactActionsMenu/ContactAccessGroupTest.php
This PR renames the Contact Access Rights menu group title to follow what is the original wireframe rather than the mockup. The title is changed from `User Has Access To:` to  `User Has CiviHR Admin Access To:`
=> PCHR-3286: Rename Contact Access Rights menu group title

uk.co.compucorp.civicrm.hrcontactactionsmenu/CRM/HRContactActionsMenu/Page/UserAccount.php, uk.co.compucorp.civicrm.hrcontactactionsmenu/hrcontactactionsmenu.php, uk.co.compucorp.civicrm.hrcontactactionsmenu/templates/CRM/HRContactActionsMenu/Page/Inline/Actions.tpl
This PR fixes some of the issues encountered by QA while testing the [PCHR-2823](https://compucorp.atlassian.net/browse/PCHR-2823)
- The `Delete staff member` link on the contact actions menu was not working and showing an error page.
- After a user account is disabled the `Disable User Account` button remains instead of the `Enable User Account` button and there is no way to re-enable the user. 
- The Delete staff member text is supposed to be dynamic depending on whether the contact has a user account or not.
- The issues mentioned above existed.
- The Delete Staff member text was made dynamic depending on whether contact has a user account or not:
- The delete link on the contact actions menu was not working and showing an error page: The error page was due to calling a wrong method on …
=> PCHR-3289: Fix issue with Delete button, Disable button and Delete Staff member text.

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Component/ContactActionsMenu/LeaveApproversListItem.php
The leave approvers names list for a contact on the Leave Menu section on the contact actions menu are links but nothing happens when the links are clicked. Clicking on a leave approver name is actually supposed to lead to the contact summary page for the leave approver.
- Clicking on the leave approvers name does nothing.
- Clicking on the leave approvers name leads to the the leave approver contact summary page.
=> PCHR-3288: Link Leave Approver to contact page

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Helper/ContactActionsMenu/LeaveActionGroup.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/BaseHeadlessTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Helper/ContactActionsMenu/LeaveActionGroupTest.php
This PR updates the text for when a contact has no leave approver to match what is in the wireframe on the [Wiki](https://compucorp.atlassian.net/wiki/spaces/PCHR/pages/121277611/Contact+page+actions+-+UX+improvements)
Also a divider is added after the Record Leave buttons to separate it from other sections on the leave menu group.
- The text is updated from `You have not selected a Leave Approver` to `The staff member does not have a leave approver`
=> PCHR-3287: Update Text and Add Divider After Record Leave Buttons

hrui/css/hrui.css
This PR hides the notes and permissions fields on the Add relationship modal
=> PCHR-3079: Hide permissions and notes field

uk.co.compucorp.civicrm.hrcontactactionsmenu/CRM/HRContactActionsMenu/Component/UserInformationLinkItem.php, uk.co.compucorp.civicrm.hrcontactactionsmenu/CRM/HRContactActionsMenu/Helper/UserInformationActionGroup.php, uk.co.compucorp.civicrm.hrcontactactionsmenu/hrcontactactionsmenu.php, uk.co.compucorp.civicrm.hrcontactactionsmenu/tests/phpunit/CRM/HRContactActionsMenu/Helper/UserInformationActionGroupTest.php
This PR updates some texts to match what is in the wireframe for the contact menu actions. The texts updated are:
- Button text to add a user account was updated from : `Create a user for this staff member` to `Add User account`
- Text display when contact has no user account was updated from: `There is no user for this staff member` to `There is no user account for this staff member`
Also the Account Disabled text was added for the scenario when User account for a contact is disabled.
- These changes above were not present.
Before updating button and text display
When User is disabled:
After updating button and text display.
With User Disabled:
=> PCHR-3290: Update button text and Add Account disabled text

uk.co.compucorp.civicrm.hrcontactactionsmenu/hrcontactactionsmenu.php
After the changes [here](https://github.com/civicrm/civihr/pull/2486/files#diff-04d94654672bea1a580ad62a06c751c9R45), The UserInformationActionGroup constructor will only accept null if the respective CMS related interface is not passed.
For the instance where the Contact does not have a user account, empty string are passed for the CMS related interface parameters causing an error to be thrown.
Error is thrown when viewing the contact page of a contact with no CMS user.
The The UserInformationActionGroup constructor is passed null for the CMS interface related parameters when Contact has no CMS user and no error is thrown when viewing the contact summary page of such a Contact.
=> PCHR-3344: Fix Contact Summary Page error for  a Contact without User Account

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1010.php
This PR adds an upgrader to install the Contact actions menu extension.
No upgrader to install the Contact actions menu extension extension
An upgrader in HRCore to install Contact actions menu extension is added.
The contact actions menu extension needs to be installed so that the upgraders adding `administer staff accounts` [permission](https://github.com/compucorp/civihr-employee-portal/pull/445) to respective roles can run
=> PCHR-3346: Add upgrader for enabling contact actions menu extension

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1010.php
When installing the Contact actions menu extension via the cli, an error is thrown that the extension does not exist. 
The extension list is refreshed before trying to attempt to install the extension.
=> PCHR-3346: Refresh extensions

bin/drush-install.sh
This PR adds the contact actions menu extension to the list of CiviHR extensions installed when building a site. The extension is added to the `drush-install.sh` file.
The contact actions menu extension is not part of the list of CiviHR extensions installed when building a site
The contact actions menu extension is now part of the list of CiviHR extensions installed when building a site
=> PCHR-3355: Install Contact Actions Menu By Default

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/CMSData/UserRole/Drupal.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/CMSData/UserRoleInterface.php
This PR modifies the UserRole interface `getRoles` method to allow the Authenticated Role for a user to be filtered off from the list of user roles returned.
The Authenticated Role is returned along with the list of user roles by default when calling the getRoles method of the User Roles interface.
The Authenticated Role can be excluded from the list of user roles by default when calling the getRoles method of the User Roles interface.
- This PR is needed for the task to be done on https://compucorp.atlassian.net/browse/PCHR-3349.
=> PCHR-3349: Allow to filter the Authenticated User role.

uk.co.compucorp.civicrm.hrcontactactionsmenu/CRM/HRContactActionsMenu/Component/UserInformationLinkItem.php, uk.co.compucorp.civicrm.hrcontactactionsmenu/CRM/HRContactActionsMenu/Component/UserRoleItem.php
This PR hides the Authenticated User role and also the User Id of the contact from being displayed on the contact actions menu.
The Authenticate user role and the User Id is displayed on the contact actions menu.
The Authenticate user role and the User Id is no more displayed on the contact actions menu.
=> PCHR-3349:  Hide Authenticated Role and User ID

bin/git-release.sh, com.civicrm.hrjobroles/info.xml, contactaccessrights/info.xml, contactsummary/info.xml, hrbank/info.xml, hrcareer/info.xml, hrcase/info.xml, hrdemog/info.xml, hrim/info.xml, hrjobcontract/info.xml, hrmed/info.xml, hrprofile/info.xml, hrqual/info.xml, hrrecruitment/info.xml, hrreport/info.xml, hrstaffdir/info.xml, hrui/info.xml, org.civicrm.bootstrapcivihr/info.xml, org.civicrm.hremergency/info.xml, org.civicrm.reqangular/info.xml, uk.co.compucorp.civicrm.hrcomments/info.xml, uk.co.compucorp.civicrm.hrcore/info.xml, uk.co.compucorp.civicrm.hremails/info.xml, uk.co.compucorp.civicrm.hrleaveandabsences/info.xml, uk.co.compucorp.civicrm.hrsampledata/info.xml
Bumping extension versions to 1.7.4 in preparation for this month's release.
The `git-release.sh` script was also updated to remove references to old extensions, that are not being updated anymore and will be soon removed
=> PCHR-3318: Bump version to 1.7.4

uk.co.compucorp.civicrm.hrcore/hrcore.php
This PR adds a new permission that will be used in subsequent tickets to check if a user has permission to access certain menu items or access certain configuration options.
The 'access root menu items and configurations' did not exist.
The 'access root menu items and configurations' was added (not in use yet).
https://github.com/compucorp/civihr-employee-portal/pull/450 updates the permission to match the changes here.
=> PCHR-3354: Add permission 'access root menu items and configurations'

uk.co.compucorp.civicrm.hrcore/hrcore.php
The "CiviHR Website" link should only be accessible to users with the "CiviHR - Access root menu items and configurations" permission.
The "CiviHR Website" link was accessible to users with the "Administer CiviCRM" permission.
The "CiviHR Website" link is only accessible to users with the "CiviHR - Access root menu items and configurations" permission.
=> PCHR-3365: Change Permission for "CiviHR Website" Link

hrdemog/CRM/HRDemog/Upgrader.php, hrjobcontract/CRM/Hrjobcontract/Upgrader.php, hrrecruitment/CRM/HRRecruitment/Upgrader.php, hrui/CRM/HRUI/Upgrader.php, hrui/CRM/HRUI/Upgrader/Steps/4708.php, org.civicrm.hremergency/CRM/Hremergency/Upgrader.php, org.civicrm.hremergency/CRM/Hremergency/Upgrader/Steps/1004.php
This PR sets custom field groups that should not be editable to "is_reserved"=yes for the following custom groups
- Extended demographics
- Contact length of service
- Application
- Vacancy
- Evaluation field
- Emergency contact
- Inline custom data
=> PCHR-3353: Set Custom Groups to Reserved

bin/drush-install.sh
After this #2496 was merged, when creating a new site with buildkit, it fails with some errors:
```php
WD php: CRM_Core_Exception: Invalid Entity Filter in CRM_Core_BAO_CustomGroup::validateSubTypeByEntity() (line 692 of                                                                      [error]
/vagrant/hr17/sites/all/modules/civicrm/CRM/Core/BAO/CustomGroup.php).
Cannot modify header information - headers already sent by (output started at /vagrant/buildkit/vendor/drush/drush/includes/output.inc:38) bootstrap.inc:1486                              [warning]
CRM_Core_Exception: Invalid Entity Filter in CRM_Core_BAO_CustomGroup::validateSubTypeByEntity() (line 692 of /vagrant/hr17/sites/all/modules/civicrm/CRM/Core/BAO/CustomGroup.php).
Drush command terminated abnormally due to an …
```
=> PCHR-3379: Fix Error When Creating a New Site With Buildkit

hrident/CRM/HRIdent/Upgrader.php, hrjobcontract/CRM/Hrjobcontract/Upgrader.php
This PR ensure the following custom groups are reserved if they exist in any installations.
* Identification
* Job contract dates
* Job contract summary
* Job summary
=> PCHR-3392: Set some Installation Custom Field Group Reserved Yes

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlement.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlementTest.php
Currently when overriding a contact's  entitlement for an absence period with a value of **0** on the manage entitlements page, the form gets submitted successfully but the change is not reflected instead of displaying the Overridden entitlement of **0**, it reverts back to the default entitlement for the contact without being overridden.
- When overriding a contact's  entitlement for an absence period with a value of **0**, it reverts back to the default entitlement for the contact without being overridden.
The issue was traced to [Here](https://github.com/civicrm/civihr/blob/a893ab83690c59c81b10671bf85e59341531600d/uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlement.php#L207).
The `$overriddenEntitlement` gets type casted to a boolean here which …
=> PCHR-3034: Fix Issue When Overriding Entitlement With Zero Value

hrident/CRM/HRIdent/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1011.php
An upgrade was required to move Custom Group Identify to is_reserved yes. Due to the fact that HRIdent extension have been disabled on some installation, the implementation was migrated to HRCore. This ensures consistency across systems.
=> PCHR-3392: Moved HRIdent Upgrade to HRCore

uk.co.compucorp.civicrm.hrcore/backstop_data/page-objects/contact-summary.js, uk.co.compucorp.civicrm.hrcore/backstop_data/scenarios/contact-access-rights.json, uk.co.compucorp.civicrm.hrcore/gulp/tasks/backstopjs.js, uk.co.compucorp.civicrm.hrcore/package-lock.json, uk.co.compucorp.civicrm.hrcore/package.json
The `backstopjs` gulp tasks always returned a code `0` even if BackstopJS failed (either because of some errors or because some diffs were found). This made the tasks not suitable for automated process. This PR fixes the issue, so that the task returns a code `1` if any error occured
Additionally, the "contact access rights" scenarios were updated as the "manage access rights" buttons was moved inside the contact actions panel. This was done as part of the "contact actions" epic but unfortunately I forgot to update the scenarios as well. 
Also please note that the contact used in the scenario had been changed from "staff" to "admin", as now the button appears only for users that have the "access CiviHR" permission
Finally, this PR also updates the BackstopJS version to the latest …
=> PCHR-3243: Fix backstopjs task's return code

hrui/CRM/HRUI/Upgrader.php, hrui/CRM/HRUI/Upgrader/Steps/4710.php
Custom group field called `Inline Custom Field` is currently titled `Inline Custom Data`. There is need to change the title to `NI/SSN Number`, whether it is reserved or not in any setup.
=> PCHR-3433: Rename Inline Custom Field Data

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreation.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestDeletion.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/PublicHolidayLeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreationTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestDeletionTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/bootstrap.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/LeaveBalanceChangeHelpersTrait.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/PublicHolidayHelpersTrait.php
Currently when a public holiday leave request is deleted by the Admin for a contact, If a condition that triggers the creation of public holiday leave requests occurs e.g change in Work Pattern, the public holiday leave request is created for the contact again.
When a public holiday leave request is deleted by the Admin for a contact, it gets created again when a condition that triggers public holiday creation happens.
When a public holiday leave request is deleted by the Admin for a contact, it does not get created again when a condition that triggers public holiday creation happens.
- The Admin deletes public holiday leave requests via the `LeaveRequestService.delete` function, rather than hard delete the requests, the function was modified to now soft delete public holiday leave …
=> PCHR-3423: Do not allow deleted Public holiday Leave Request for Contact to be re-created

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/BuildForm/LocalisationPageFilter.php, uk.co.compucorp.civicrm.hrcore/hrcore.php
A new permission called `access root menu items and configurations` has been added. The implication of this on Localisation Page is that some fields will not be available for editing by users that do not have such permission.
=> PCHR-3420: Hide Options on Localisation Page

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1012.php
This PR adds a link to the custom fields edit page.
The "administer" submenu did not have any direct link to the edit custom fields page.
The "administer" submenu has a direct link to the edit custom fields page.
I forgot to add this in the last PR so adding it here. Since the upgrader hasn't been released yet we do not need a new one.
=> PCHR-3375: Add custom fields shortcut

hrjobcontract/CRM/Hrjobcontract/BAO/HRJobContract.php, hrjobcontract/api/v3/HRJobContract.php, hrjobcontract/tests/phpunit/CRM/Hrjobcontract/BAO/HRJobContractTest.php, hrjobcontract/tests/phpunit/api/v3/HRJobContractTest.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1011.php
This PR makes some changes needed by [#324](https://github.com/compucorp/civihr-tasks-assignments/pull/324). 
- To send the daily reminder email, we need to ensure that the recipients have an active contract, the  
`Jobcontract.getContactsWithContractsInPeriod` provides this information but does not accept a list of contact ID's to check for. The `Jobcontract.getContractsWithDetailsInPeriod` accepts a list of contacts to check for but the information returned is far too much than what we need.
- Daily reminder emails are now to be sent to the primary work emails of a recipient with an active contract. The Work location type is not reserved in the database and as such the name can be changed which may affect the sql query in code where we have asked that the email be of the Work type.
- …
=> PCHR-3382: Modify Jobcontract.getContactsWithContractsInPeriod API And Reserve Work Location Type

com.civicrm.hrjobroles/CRM/Hrjobroles/Upgrader.php, hrjobcontract/CRM/Hrjobcontract/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1012.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1013.php
The PR updates permissions on menu items in the "Configure" submenu. It also fixes some links and adds a link to "Localise CiviHR" which was missing.
- Many of the permissions on the "Configure" submenu item used `administer CiviCRM`
- Some of the links were broken
- The case of the permission for some links was incorrect
- The "Localise CiviHR" menu item did not exist
- Permission for the items that should not be viewable by non-root users has been changed to `access root menu items and configurations`
- Some of the links for menu items created in other PRs have been fixed
- Fixed a mistake in the permission case, `Access CiviCRM` => `access CiviCRM`
- Create the "Localise CiviHR" menu item
- 'Custom Fields' is an exception for the permissions update, it was added as part of this epic …
=> PCHR-3376: Update Permissions

hrjobcontract/CRM/Hrjobcontract/Upgrader.php
This fixes issues reported in the QA for the configuration menu changes
One of the labels was incorrect
'Normal Place of Work' is now 'Normal Places of Work'
=> PCHR-3162: Update label

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
When validating the maximum consecutive days that can be taken when a leave request is to be created, the validation does not consider actual working days in the leave request date range based on the contact work pattern, hence leave requests that should have been allowed to be created are not.
- Take for example a contact using the default work pattern having weekends as non working days for the contact. If a contact requests leave from Monday this week to Monday next week, thats 6 days of leave the the contact is requesting.
Assuming the max consecutive leave days allowed for the absence type the contact is requesting leave for is 6 days, these request should have been allowed but its not allowed currently.
The validation assumes that the contact is requesting for 8 days(weekend …
=> PCHR-3372: Take Contact Work Pattern into Consideration when validating Max consecutive leave days

uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/manage-leave-requests.html, uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/partials/leave-request-dates.html, uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/partials/staff-leave-report-requests-rows.html
This PR adds times for TOIL requests in Staff Leave Report and Manage Leave Report.
1. Create a shared partial for request dates/times:
```html
{{request.from_date | formatDate : null : (request.request_type === 'toil' ? 'hours' : unit)}}
<span ng-if="request.dates.length > 1">
-
{{request.to_date | formatDate : null : (request.request_type === 'toil' ? 'hours' : unit)}}
</span>
<span ng-if="request.dates.length === 1 && (unit === 'hours' || request.request_type === 'toil')">
-
{{request.to_date.slice(11, 16)}}
</span>
```
2. Then replace the dup code with a new partial in reports.
```html
<td ng-init="unit = absenceType.calculation_unit_name"
ng-include="$root.sharedPathTpl + 'components/partials/leave-request-dates.html'"></td>
```
----
Only manual tests were performed.
=> PCHR-3474: Add TOIL times in reports

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1020.php, uk.co.compucorp.civicrm.hrleaveandabsences/xml/option_groups/toil_amounts_install.xml
This PR removes the Zero Days TOIL amount option value from the toil amounts option group.
- The Zero Days TOIL amount option value was present in the toil amounts option group.
- The Zero Days TOIL amount option value is no longer present in the toil amounts option group.
The option value was removed from the toil_amounts option group xml installation file for new sites and removed via an upgrader for existing sites.
- Part of the fixes for this ticket(PCHR-2769) was also to re-order the TOIL amounts options in the TOIL request modal but that has already been fixed as part of https://compucorp.atlassian.net/browse/PCHR-3427.
=> PCHR-2769: Remove the Zero Days TOIL amount option value.

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1020.php
Currently the end time for TOIL requests in **days** is stored as `23:59`. TOIL requests in **hours** store it as `00:00` instead of `23:59`.
Due to new requirements (https://github.com/civicrm/civihr/pull/2534), all TOIL requests now have both *start* and *end* times and the allowed time interval is 15 minutes starting from 00:00 - the time `23:59` becomes invalid. As a result, the time `23:59` will not be selected in the according selector in the Leave Request Modal and will also look odd in the Leave Report.
This PR adds an upgrader that transforms all TOIL requests end time into `23:45` (`23:45:00` if we consider the format on the server).
It gets all existing not deleted TOIL requests and transforms the end date/time by preserving the date and changing the time.
```php
// ... …
```
=> PCHR-3476: Add an upgrader to amend existing toil requests end time to 23:45

uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/mocks/data/option-group.data.js, uk.co.compucorp.civicrm.hrleaveandabsences/xml/option_groups/work_pattern_change_reason_install.xml
There was a typographical error in the work pattern change option naming. This PR fixes the issue.
=> PCHR-3451: New Option Group Work Pattern Change

uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/ManageEntitlements.tpl
In the "Manage Leave Entitlements" page, the controls that filtered the list by the overridden status apparently got stuck after a couple of interactions, and the list didn't update anymore. Also none of the filters were selected by default, although these are radio-like filters, when one should always be selected.
The problem was that the filters are a set of radio buttons (the buttons themselves are hidden via css), but the buttons did not share the same `[name]` attribute, meaning that when one was selected, the others were not automatically de-selected
```html
<input type="radio" class="override-filter" value="1">
<input type="radio" class="override-filter" value="2">
<input type="radio" class="override-filter" value="3">
```
Here are the buttons in action, made visible
Simply adding …
=> PCHR-3489: Fix entitlements override filter

uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/UserMenuMarkup.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/ManageEntitlements.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/AbsencePeriod.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/AbsenceType.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/PublicHoliday.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/WorkPattern.tpl
Some templates of our customized CiviHR pages were susceptible to XSS attacks. Mainly these are templates that render the contents of text fields without escaping them.
The contents were printed on the page as they were entered by the user, without any filtering or escaping. On this example, look at what would happen if a user would create a new Absence Period with the title  `<script>alert(1);</script>`:
When the page is rendered, the title is printed, which ends up adding a new script tag to the markup and the Javascript in that tag is executed when the page loads. Note also that, because the title renders as an HTML tag without any text in it, the Absence Period is not displayed on the page.
The field contents are now escape using the `escape` filter from Smarty. This filter works in a …
=> PCHR-3487: Escape user entered data

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1022.php
Since new work pattern are being created, the need arose to update existing records to the new default value of `As per contract`. This PR caters for that.
All existing records are fetched and updated to the new default value using chained api call.
```php
civicrm_api3('ContactWorkPattern', 'get', [
'return' => ['id'],
'api.ContactWorkPattern.update' => [
'change_reason' => 1,
'id' => "\$value.id"
],
]);
```
=> PCHR-3451: Default Existing Work Pattern to As per contract

org.civicrm.hremergency/CRM/Hremergency/Upgrader/Steps/1004.php
This ticket originally made some custom groups reserved. However because of a [bug in the CiviCRM Core](https://issues.civicrm.org/jira/browse/CRM-21853) the `is_multiple` value was set to `false` if it wasn't included in the params. This ticket fixed that problem, instead of waiting for the [Core PR](https://github.com/civicrm/civicrm-core/pull/11877).
The list of Custom Groups that were updated in the original ticket are:
- Extended demographics
- Probation
- Activity custom fields
- Contact length of service
- Application
- Vacancy
- Evaluation field
- Emergency contact
- Inline custom data
Looking at the custom groups on staging there is only one of those, "Emergency Contact" where `is_multiple` is true. Since the value will be set to `false` if it isn't included we don't need to fix …
=> PCHR-3353: Quickfix for "is_multiple" Bug

hrjobcontract/CRM/Hrjobcontract/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1014.php
In #2553 I fixed one of the updated groups as part of this epic. I missed some custom groups updated in a separate ticket though #2513. This PR fixes those groups.
To be sure this PR fixes all of them I checked the groups changed in #2513 or #2502 to make a list and compared them against groups on staging where `is_multiple` is 1
- Extended_Demographics
- Contact_Length_Of_Service
- Application
- application_case
- Evaluation_fields
- Emergency_Contacts
- Inline_Custom_Data
- Identify
- HRJobContract_Dates
- HRJobContract_Summary
- HRJob_Summary
- Identify
- HRJobContract_Dates
- Medical_Disability
- Qualifications
- Immigration
- Career
- Emergency_Contacts
- Emergency_Contacts
- Identify
- HRJobContract_Dates
Emergency Contacts was fixed in #2553 so this PR will fix the other two.
After …
=> PCHR-3392: Quickfix for 'is_multiple' bug

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1012.php
This PR removes relationships type that are not needed by CiviHR. The relationships types are:
* Case Coordinator is
* Employee of
* Head of Household for
* Household member of
```json
{
"is_error": 0,
"version": 3,
"count": 4,
"values": [
{
"id": "9",
"name_a_b": "Case Coordinator is"
},
{
"id": "5",
"name_a_b": "Employee of"
},
{
"id": "7",
"name_a_b": "Head of Household for"
},
{
"id": "8",
"name_a_b": "Household Member of"
}
]
}
```
```json
{
"is_error": 0,
"version": 3,
"count": 0,
"values": []
}
```
A new upgrader was implemented for HRCore since this is a change that affects all extensions:
```php
<?php
trait CRM_HRCore_Upgrader_Steps_1012 {
/**
* Removes relationship types that are not necessary for CiviHR.
*/
public function upgrade_1012() {
$relationshipsToBeDeleted = [
'Case …
```
=> PCHR-3411: Remove unnecesary relationship types

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1024.php
When creating PDF Letter or sending email from contact page action button, some templates which are meant to be part of System Workflow Message Templates show as part of User-driven Message templates. These are `CiviHR Leave Request Notification`, `CiviHR TOIL Request Notification` and `CiviHR Sickness Record Notification`. This PR fixes that by moving them as appropriate.
The affected records do not belong to any workflow, making them show up as user-driven message. This was fixed by ensuring each of those templates belong to a workflow. For this purpose, new option group and option values were created. This is because the template `workflow_id` is a pseudo reference to `option value id`, which also have a reference to `option group` by `option_group_id`.
After setting up the option …
=> PCHR-3506: Move Leave Request Template to System Workflow Message

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Wrapper/LeaveRequestDates.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/API/Wrapper/LeaveRequestDatesTest.php
API calls to LeaveRequest.getcount are limited to 25. This is because an API wrapper that sets the default limit to 0 (no limit) is not applied
If you have more than 25 leave requests and call LeaveRequest.getcount it will always return 25
If you have more than 25 leave requests and call LeaveRequest.getcount it will always return the correct count
The problem was that the function for the API request was called directly. This means that the request lifecycle was not called. The request lifecycle calls the `CRM_HRCore_APIWrapper_DefaultLimitRemover` but [only](https://github.com/civicrm/civihr/blob/94deaa003f590b7a3e07e0027606ae45c7da9660/uk.co.compucorp.civicrm.hrcore/hrcore.php#L243
) if it's a `GET` request. By changing to a `civicrm_api3` call we go through the request lifecycle and …
=> PCHR-3510: Fix Limit On Leave Request getcount

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestRights.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestRightsTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestTest.php
When a TOIL was requested and the TOIL days are now past and the Absence Type does not allow past accrual, neither Admin nor Staff is able to cancel such request. An error message `You may only request TOIL for overtime to be worked in the future` is displayed on trying to cancel such a TOIL request.
We want the only the Admin and Leave Managers to be able to cancel such TOIL requests. This PR makes changes to make this happen.
- The Administrator and Leave manager can not cancel a TOIL request with past dates if the Absence type does not allow past accrual.
- The staff can not cancel  a TOIL request with past dates when absence type does not allow past accrual.
- The Administrator and Leave manager can now cancel a TOIL request with past dates even if the Absence type does not allow past …
=> PCHR-2576: Fix Issue with Admin Not Being able to Cancel TOIL with Past Dates

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/BuildForm/OptionEditPathFilter.php, uk.co.compucorp.civicrm.hrcore/hrcore.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Hook/BuildForm/OptionEditPathFilterTest.php
For locked option groups we don't want to show the gear icon to allow inline editing. This PR hides that link.
Locked option groups (where `is_locked` is true) would still have a link to edit them inline in forms.
In this example **phone types** is locked
Locked option groups (where `is_locked` is true) do not show a link to edit them inline in forms.
In this example **phone types** is locked
The way this works is based on the implementation of the [addOptionsEditLink](https://github.com/civicrm/civicrm-core/blob/master/CRM/Core/Form/Renderer.php#L350) method. The method will only add the link _if_ the `data-option-edit-path` is set. By removing it we make sure this method does not show the link.
=> PCHR-3464: Hide link to edit locked option groups in forms

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1008.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1019.php
When running PHPUnit tests some warnings are displayed during extension setup. This PR fixes those warnings.
Warnings are displayed during setup of PHPUnit test
No warnings are displayed
The real culprit is the `civicrm_api3_relationship_type_create` function, in particular [this line](https://github.com/civicrm/civicrm-core/blob/4.7.27/api/v3/RelationshipType.php#L46):
```
if (!isset($params['label_a_b'])) {
$params['label_a_b'] = $params['name_a_b'];
}
```
Which issues a warning when `$params['name_a_b']` is not set. As a fix for now we include all data in the update request and avoid the missing index notices.
This has already been fixed in core in [this commit](https://github.com/civicrm/civicrm-core/commit/0782c7b9321591b43bb46ae698dc71224ad50672#diff-a5b74abbbbe643c7f71f5856d6c9d138R …
=> PCHR-3526: Fix Warnings In Tests

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1023.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php
Sequel to #2572, which creates the LeaveBalanceChangeExpiryLog entity, This PR utilizes the entity to log expired balance change records created by the Scheduled job that expires balance changes. 
Also an Upgrader was added to revert the wrong expiration of some balance change records that were expired before due date.
- No logging is done when the  Scheduled job that expires balance changes runs.
- There exists some balance change records that were wrongly expired by the scheduled job.
- Logging is done when the  Scheduled job that expires balance changes runs using the LeaveBalanceChangeExpiryLog entity.
- Balance change records that were wrongly expired by the scheduled job were fixed and made not to appear expired again.
=> FAR-247: Implement logging for Expired Balance Changes

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php
The SQL query responsible for selecting balance changes to expire selects balance changes linked to already deleted TOIL accrual requests. The query is only supposed to select balance changes linked to non deleted TOIL accrual requests.
- When SQL query selects balances linked to a deleted TOIL request, this causes an exception to be thrown when selecting dates overlapping balance to [expire ](https://github.com/civicrm/civihr/blob/81d97c204a4e6f84ec836f07b055f481a88b6360/uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChange.php#L656), particularly when fetching the LeaveRequest linked to the leave date in order to get the [entitlement](https://github.com/civicrm/civihr/blob/81d97c204a4e6f84ec836f07b055f481a88b6360/uk.co.compucorp.civicrm.hrleaveandabsenc …
=> FAR-252: Fix error with Scheduled Job trying to expire balances linked to deleted TOIL requests

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlementTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
At the moment it is impossible to create Leave Requests and TOIL Accruals for the same day.
This PR allows to create requests for the same day according to the rules:
1) It should be possible to create multiple leave requests in hours within the same day. They can also "touch" together in terms of time, for example, one request ends at 9:00 and another starts at 9:00 of the same day.
2) It should be possible to create one AM and one PM leave request within the same day using leave in days allowance.
3) It should not be possible to create one leave request in days and one leave request in hours on the same day, regardless of the request in hours start and end time. 
4) It should not be possible to create more than one AM leave request within the same day. Same for PM.
5) It should be …
=> PCHR-3580: Allow multiple requests on same date on backend

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Mail/Message.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Mail/MessageTest.php
Leave request notification emails need to be suppressed for user creating or editing the leave request. 
For example, If a staff member creates a new leave request or edits an existing leave request the staff member should not get a notification email but the leave approver should get a notification email. Also If a leave approver creates/edit a leave request, the leave approver should not get a notification email but the target staff member should.
- Leave request notifications are sent for all eligible recipients including the user creating/editing the request
- Leave request notifications are sent for all eligible recipients excluding the user creating/editing the request
- The email of the current logged in user (i.e the user creating or editing the leave request) is excluded from the …
=> PCHR-3497: Suppress Leave Request Notification Emails for Person Creating/Editing the Request

hrjobcontract/CRM/Hrjobcontract/Page/View/Summary.tpl, hrui/templates/CRM/Contact/Page/View/Summary.tpl, hrui/templates/CRM/common/footer.tpl, uk.co.compucorp.civicrm.hrcore/hrcore.php
The footer text should be updated to show the licence version and the site URL instead of "Project Website".
We will also restrict the site status to only root users.
* The licence was "Powered by CiviHR version 1.7.5.  CiviHR is openly available under the GNU AGPL License and can be downloaded from the Project website ."
* Any user with access to CiviCRM could see the site status in the footer
* The licence is "Powered by CiviHR 1.7.5. CiviHR is openly available under Version 3 of the GNU AGPL License and can be downloaded from www.civihr.org."
* Only root users can see the site status in the footer
=> PCHR-3570: Footer Updates

uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php
The `CRM_HRLeaveAndAbsences_BAO_LeaveRequestTest::testToilCanBeAccruedWhenTheToilRequestHasNoWorkingDay` test started failing on staging and on all Pull Requests targeting staging. The reason is that the test creates a TOILRequest with some hardcoded dates. Such requests can only be created with dates in the future and the hardcoded dates are now in the past.
The `from` and `to` dates for the request were hardcoded as `2018-05-05` and `2018-05-06` respectively.
The test verifies the validation of TOIL Requests during non-working days and the hardcoded dates were for a saturday and sunday. To make sure we'll always have a date in the future, the code was changed to always use the saturday and sunday of the next week, relative to the current date.
The reason the code uses `'sunday next …
=> PCHR-3652: Fix failing PHP test

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/WorkPattern.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/WorkPatternTest.php
Currently, It is possible to disable a custom Work pattern and subsequently make such work pattern to be the default work pattern. This PR fixes the issue and makes this action not to be possible.
-  It is possible to disable a custom Work pattern and subsequently make such work pattern to be the default work pattern.
-  It is not possible to disable a custom Work pattern and subsequently make such work pattern to be the default work pattern
=> PCHR-3660: Make it impossible to set a disabled Work pattern as default.

hrjobcontract/CRM/Hrjobcontract/Page/View/Summary.tpl, hrui/templates/CRM/Contact/Page/View/Summary.tpl, hrui/templates/CRM/common/footer.tpl, uk.co.compucorp.civicrm.hrcore/hrcore.php
In https://github.com/civicrm/civihr/pull/2584 I changed the permission check to use a global template variable defined in the `pageRun` hook. In pages where you're editing something this hook is not called and this leads to the footer not being displayed. This causes further problems when displaying help texts.
- The footer was not displayed on edit pages
- Help text icons did not correctly show the help text bubble
- The footer is displayed on edit pages
- Help text icons correctly show the help text bubble
=> PCHR-3671: Revert Changes to Footer

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
Based on the specification for the New Staff Calendar, A contact should be able to view other contact's leave requests via the API, This was not previously possible because of the Leave Request ACL rules allows a staff to view only his leave requests, a manager to only view leave requests of his managees while an administrator can view leave requests for all contacts.
- The former Leave Request ACL rules applies when a contact tries to get another contact's request via the API.
- The Leave ACL query in the `addSelectWhereClause` function in the Leave Request BAO was modified to allow a contact get other contact's leave requests via the API irrespective of whether the contact is a staff, leave manager or Admin.
- A couple of tests in the `api_v3_LeaveRequestTest` class was broken after the …
=> PCHR-3516: Allow Contact to get Leave Requests For Other Contacts via API

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Service/Stats/StatsGatherer.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Test/BaseHeadlessTest.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Service/Stats/StatsGathererTest.php
Data for the following new fields should be collected for each client site:
- number of job roles
- number of cost centres
- number of funders
- number of custom field groups
- number of custom fields
- number of case types
- number of HR resources
- number of HR resource types
Data for these fields was not collected or sent
Data for these fields is collected and sent
I was unaware of some of these definitions before so it might help the reviewer to know:
- Funder is a list of contact IDs that is part of the job roles table. Each job role can have multiple funders, which are separated by `|`
- HR Resource Type is Drupal content of a specific type. It is viewable from "HR Resources" from the SSP
- HR Resources are files attached to any of the HR Resource Types
I did not include HR Resource …
=> PCHR-3650: New Fields for Pingback

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/CMSData/SiteInformation/DrupalSiteInformation.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/CMSData/SiteInformation/SiteInformationInterface.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Service/Stats/StatsGatherer.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Service/Stats/StatsGathererTest.php
CiviCRM has a contacts table, Drupal has a users table. To link these two tables there is a UFMatch table.
We use the UFMatch table for tracking CMS user count. Usually this is fine because when new users are created, a corresponding record is created for them in UFMatch. However if a contact record is deleted, but the Drupal user account still exists we have a disparity in the counts.
We used UFMatch to count CMS users
We use the Drupal user table to count CMS users
=> PCHR-3669: Use Drupal User Count Instead Of UFMatch

com.civicrm.hrjobroles/views/include/add_new_role.html, com.civicrm.hrjobroles/views/include/job_role_panel.html
After adding tool icon for some of the option groups in Job Role, dropdown list for those options were not properly displayed. This fixed the issue.
Initially css class `crm_custom-select--full` [which was removed](https://github.com/civicrm/civihr/pull/2546) has been restored and bootstrap `col` added for proper arrangement of elements.
```html
<div class="form-group">
<label for="newDepartment" class="col-xs-4 control-label">Department:</label>
<div class="col-xs-6">
<div class="form-inline">
<div class="crm_custom-select crm_custom-select--full">
<ui-select
prevent-animations
ng-model="jobroles.editData['new_role_id']['department']"
theme="civihr-ui-select"
title="Choose a Department">
<ui-select-match prevent-animations allow-clear placeholder="Select a …
```
=> PCHR-3460: UI Improvement for Option Groups

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/ACL/LeaveInformationTrait.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Handler/GenericLeaveFieldPermissions.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Handler/GetBreakDownFieldPermissions.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Handler/LeaveFieldPermissions.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Wrapper/LeaveRequestFieldsVisibility.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestRights.php, uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/API/Handler/GenericLeaveFieldPermissionsTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/API/Handler/GetBreakDownFieldPermissionsTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestRightsTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
Based on the new requirements for the new Staff Calendar that allows a user to view leave requests for other user which was formerly impossible #2614 , Even though leave requests for other contacts can now be viewed, there are some sensitive/restricted fields that a user should not be able to see for contacts that he does not have access to. By having access to, I am referring to the Leave ACL rules which here means that a staff can only view these sensitive fields for his own leave requests only and for other's requests, a pre-determined configurable value is shown for these fields. For a manager he can only view these sensitive/restricted fields for the leave requests of his manages only while an Admin can view all fields for all contacts leave requests.
- A staff can view all fields …
=> PCHR-3701: Selectively Modify Leave Request API Field return Value based on User Role and Leave ACL Permissions

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1017.php
This PR updates some settings which are viewable at `/civicrm/admin/setting/misc`
- Logging was disabled by default
- Max upload size was 3 MB
- Max attachment file count was 3
- Logging is enable by default
- Max upload size is 10 MB
- Max attachment file count is 10
=> PCHR-3613: Add upgrader to change site settings

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Handler/GenericLeaveFieldPermissions.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/API/Handler/GenericLeaveFieldPermissionsTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
Currently, A contact can fetch TOIL requests for other contacts he does not have access to, For example a Manager can fetch TOIL requests for contacts other than his managees via the API.
Based on the requirement for the new Staff Calendar, this task makes sure that the Leave ACL rules is implemented for TOIL requests when fetching requests via the API, i.e
- The Staff can only fetch own TOIL requests
- Manager can only fetch  TOIL requests of managees
- Admin can fetch all TOIL requests.
- A contact can fetch TOIL requests for other contacts he does not have access to.
- A contact can not fetch TOIL requests for contacts he does not have access to.
- The LeaveRequest BAO implementation of the  `addSelectWhereClause` method by ensuring that TOIL Leave requests belonging to contacts that …
=> PCHR-3726: Disallow fetching other contact's TOIL requests via API

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1017.php
This PR adds an upgrader to migrate location types. The pattern for migrating types is:
- Billing → Personal
- Home → Personal
- Main → Personal
- Other → Personal
- Work → Work
Some entities had location types "Billing", "Main", "Home" or "Other"
All entities that reference location type point to either the "Personal" or "Work" location type
=> PCHR-3730: Migrate Location Types

hrjobcontract/views/modalChangeReason.html, hrjobcontract/views/modalForm.html
This PR fixes issue with mouse pointer in Job Contract for staff.
The class pointer was not defined in the `hrjobcontract` extension css and thus removed. In place of the css, `href` markup was used. Sample snippet is shown below:
```html
<a href ng-click="openOptionsEditor('/civicrm/admin/options/hrjc_contract_type?reset=1', 'hrjobcontract_details_contract_type')">
<i class="crm-i fa-wrench"></i>
</a>
```
---
=> PCHR-3743: Tool Icon Mouse Pointer Job Contract

hrjobcontract/config.rb, hrjobcontract/css/hrjc.css, hrjobcontract/scss/civihr/partials/_shoreditch-imports.scss, hrjobcontract/scss/hrjc.scss
This PR syncs styles in the HRJobContract extension with Shoreditch. Please see https://github.com/compucorp/org.civicrm.shoreditch/pull/110 for more info.
```ruby
line_comments = false // that's why this PR introduces 2K+ deletions
```
```css
/* Moved outside ##{$module} {...} */
@import 'civihr/bootstrap-variables';
@import 'bootstrap/variables';
```
```css
@import '../../../org.civicrm.shoreditch/scss/bootstrap/overrides/variables';
@import '../../../org.civicrm.shoreditch/scss/bootstrap/mixins/prefix';
##{$module} {
// Still keep generic datepicker styles inside namespace
@import '../../../org.civicrm.shoreditch/scss/angular/overrides/uib-datepicker';
}
// Import mobile datepicker styles outside namespace
@import '../../../org.civicrm.shoreditch/scss/angular/overrides/outside-namespace …
```
=> PCHR-3724: Sync styles with Shoreditch

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/API/Handler/GenericLeaveFieldPermissions.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/API/Handler/GenericLeaveFieldPermissionsTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
On #2618 , Changes were made to restrict access to Leave request API field values based on the User and Leave ACL rules. This PR introduces an exception to the condition in which the type_id restricted field values is displayed based on the hide_label property on the Absence Type introduced in #2625 . The rule is that even if a user does not have access to other contact's restricted fields, For the type_id field, if the Absence Type label is set to Public, the user is allowed to view the type_id field values.
- A user can not view the field value for the type_id field of a contact he does not have access to.
- A user can view the field value for the type_id field of a contact he does not have access to if the Absence Type label is set to public.
- A new method that sets visible absence …
=> PCHR-3519: If Absence Type Public Label is set to true, always include Absence Type field in Leave Requests

uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-calendar-day.html
This PR simply hides the deduction info for **other staff** from tooltips in Leave Calendar since the deduction info is omitted for **other staff** from the Leave Request response API.
Note: staff can still see their own Leave Requests deduction, which is expected.
Simply add an `ng-if` condition to the HTML template:
```html
<div ng-if="leaveRequest.from_date_amount"
>For: {{leaveRequest.from_date_amount...</div>
```
----
Since this is a very minor change, only manual tests were performed.
=> PCHR-3774: Do not show deduction for other staff in tooltips

hrui/hrui.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/ValidateForm/AdminFormOptionsValidation.php, uk.co.compucorp.civicrm.hrcore/hrcore.php
in #1776 , The value field for Option value was made non editable and non visible. For the `hrleaveandabsences_toil_amounts` and `hrleaveandabsences_leave_days_amounts` option groups, we need to make an exception to this logic as it is necessary for users to be able to edit the value fields for these option groups.
- The value field for all option values of all option groups is hidden and not editable
- The value field for the `hrleaveandabsences_toil_amounts` and `hrleaveandabsences_leave_days_amounts` option groups option values are now editable while that of other option groups remain non editable.
- Validation was added for the value field to ensure that only numbers and decimal up to two d.p are allowed for the field.
=> PCHR-3677: Allow The Value Field For TOIL  and Leave Days Amounts Option Values To Be Editable

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Base.php, uk.co.compucorp.civicrm.hrcore/hrcore.civix.php, uk.co.compucorp.civicrm.hrcore/hrcore.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Base.php, uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.civix.php, uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php, uk.co.compucorp.civicrm.hrsampledata/hrsampledata.php
Right after creating a new CiviHR site (with any of the build methods available), CiviCRM would tell us that there were some extension updates available. We run all of an extension upgraders during the installation, so it's not possible for any of them to have any pending updates.
After some investigation, it turns out that this was caused by the extension schema version not being saved to the database after the installation is complete. Without that, Civi doesn't know that the extension is already in the latest version and tells the user that they should update it.
Users would be informed about pending extension updates right after a CiviHR installation.
Users will not informed about pending extension updates right after a CiviHR installation.
When developing a CiviCRM extension, it's …
=> PCHR-3787: Fix postInstall hooks

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/PageRun/LocationTypeFilter.php, uk.co.compucorp.civicrm.hrcore/hrcore.php
We want to keep the number of default location types to 2; "Personal" and "Work". "Billing" is created by core and is reserved. It is required in some parts of CiviCRM so we should not delete it. Instead it was made inactive and in this PR we will hide it from the location type edit page.
"Billing" appeared in the location type edit page
"Billing" does not appear in the location type edit page
=> PCHR-3631: Hide Billing Location Type

uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/UserMenuMarkup.tpl
Change link title in SSP and in CiviHR admin to "My Account" from "Edit Account"
=> PCHR-3799: change link title in SSP and in CiviHR admin to My Account from Edit Account

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/BuildForm/ContactAdvancedSearch.php, uk.co.compucorp.civicrm.hrcore/hrcore.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Hook/BuildForm/ContactAdvancedSearchTest.php
This PR removes a few unused fields from the Contact's advanced search form:
* Exclude / Include by Privacy Options
* Preferred Communication Method
* Preferred Language
A new buildForm hook was added to handle the removal of the fields:
```php
<?php
class CRM_HRCore_Hook_BuildForm_ContactAdvancedSearch {
public function handle($formName, &$form) {
if (!$this->shouldHandle($formName)) {
return;
}
$this->removeUnnusedSearchFields($form);
}
private function shouldHandle($formName) {
$expectedFormName = 'CRM_Contact_Form_Search_Advanced';
return $formName === $expectedFormName;
}
private function removeUnnusedSearchFields($form) {
$basicSearchFields = $form->get_template_vars('basicSearchFields');
$fieldsToRemove = [
'privacy_toggle',
'preferred_communication_method',
'preferred_language'
]; …
```
=> PCHR-3563: Remove unused fields from contact advanced search

Jenkinsfile
We need to use the patches to CiviCRM core from our Compucorp fork in Jenkins, otherwise some of the tests for newer features which rely on core changes will fail.
Jenkins used the `civicrm/civicrm-core` branch for CiviCRM, without any changes
Jenkins applies the `compucorp/civicrm-core` to the branch used for CiviCRM
Since the patches will be applied, the manual patching for attachments changes was removed.
=> PCHR-3636: Apply patch to CiviCRM in Jenkinsfile

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Mail/MessageTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestMailNotificationSenderTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/MailHelpersTrait.php
Some tests seem to rely on the order in which they are run. This PR fixes those cases and also uncovered a bug in SQL generation, which was also fixed.
- Some tests that check behavior if no default FROM email is set will fail when run alone as the FROM email exists
- Generated SQL included an `IN` statement that wrapped the target IDs inside single quotes which meant it was treated as a single string argument instead of a list of integers.
- The tests checking behavior without default FROM email address remove all FROM email addresses before running
- The bug in the SQL generation was fixed
Regarding the SQL bug, the tests were passing on Jenkins but not on local sites. Here is an overview of the differences and causes.
- 2 Leave Requests
- A has ID 3 with contact ID 9
- B has ID 4 with …
=> PCHR-3636: Make Tests more Isolated, Fix SQL Bug

hrui/templates/CRM/common/footer.tpl, uk.co.compucorp.civicrm.hrcore/hrcore.php
With this change only root admins and other users with "view system status on footer" will be able to view the System Status on Footer as requested on PCHR-3570
All users could see the system Status
Root Admin
HR_Admin
=> PCHR-3570: Footer Changes

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1018.php
Deleting unneeded phone types, relabeling phone to landline and migrating phones to new phone types
There were five phone types:
Phone
Mobile
Fax
Pager
Voicemail
There are only two reserved phone types:
Landline(Relabeled from Phone)
Mobile
=> PCHR-3553: Delete Phone Types

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestAttachment.php, uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestAttachmentTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
Currently the LeaveRequest.getAttachments API allows a staff to view leave attachments for another staff. This PR incorporates the Leave ACL rules into this API, basically, A staff should only be able to view own attachments, A manager should be able to view attachments for managees only while Admin can view leave attachments for all contacts leave requests.
- The LeaveRequest.getAttachments API does not return results based on Leave Request ACL rules
- The LeaveRequest.getAttachments API returns results based on Leave Request ACL rules
=> PCHR-3820: Add Leave Request ACL Rules to LeaveRequest.getAttachments API

hrcase/CRM/HRCase/Upgrader.php
After adding [category custom field](https://github.com/compucorp/civihr-tasks-assignments/pull/374) to case type, existing records are to be categorized. If case type name is application, they are defaulted to `Vacancy` otherwise they are defaulted to `Workflow`.
Existing case types are not grouped by categories
Existing case types are assigned to either vacancy or workflow category.
The upgrader is executed after the case type category have been setup.
```
$customFieldId = CRM_Core_BAO_CustomField::getCustomFieldID('Category');
if ($customFieldId == null) {
return FALSE;
}
```
=> PCHR-3836: Update Existing Case Types with Case Type Category

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1018.php
Change order of individual prefix options to:
1. Mr.
2. Mrs.
3. Ms.
4. Miss
5. Dr.
The order used was the default for CiviCRM.
=> PCHR-3545: Changed Order For Individual Prefix

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1018.php
Remove the "Main" and "Other" location types as they are not required.
The "Main" and "Other" location types existed on some sites
The "Main" and "Other" location types are removed
=> PCHR-3611: Remove Main And Other Location Types

uk.co.compucorp.civicrm.hrcore/hrcore.php, uk.co.compucorp.civicrm.hrcore/js/hrcore.js
This PR adds virtual pageviews tracking for the Contact Summary tabs
The Contact Summary page does not trigger any browser history changes when switching tabs, meaning that Google Analytics cannot track by default the user's movement in it
In order to track the user, a custom script had been added to the hrcore extension which, open the user selecting a tab, creates a virtual pageview and sends it to GA via Google Tag Manager. The pageview has the URL that the page would have if the user were to land directly on the selected tab (so if the selected tab is "Job Roles", the virtual pageview url is `/civicrm/contact/view?reset=1&cid={id}&selectedChild=hrjobroles`)
The custom script is inside `hrcore.js` a simple, vanilla js file contained in hrcore. There is a long term plan to eventually …
=> PCHR-3875: Add tracking of virtual pageviews for contact tabs

hrcase/CRM/HRCase/Upgrader.php
After adding [category custom field](https://github.com/compucorp/civihr-tasks-assignments/pull/374) to case type, existing records are to be categorized. If case type name is application, they are defaulted to `Vacancy` otherwise they are defaulted to `Workflow`.
Existing case types are not grouped by categories
Existing case types are assigned to either vacancy or workflow category.
The upgrader is executed after the case type category have been setup.
```
$customFieldId = CRM_Core_BAO_CustomField::getCustomFieldID('Category');
if ($customFieldId == null) {
return FALSE;
}
```
=> PCHR-3836: Update Existing Case Types with Case Type 

uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/apis/calendar-feed-config.api.js, uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/instances/calendar-feed-config.instance.js, uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/models/calendar-feed-config.model.js, uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/mocks/apis/calendar-feed-config-api-mock.js, uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/mocks/data/calendar-feed-config.data.js, uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/apis/calendar-feed-config.api.spec.js, uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/instances/calendar-feed-config.instance.spec.js, uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/models/calendar-feed-config.model.spec.js
This PR adds Calendar Feed API, model and instance files to support further front-end development of the Calendar Feeds. The files allow to:
- Create Calendar Feed
- Get all Calendar Feeds
The files did not exist.
Calendar Feed API, Modal and Instance exist.
The files were created in consistency with other API files, models and instances.
----
⏹Manual Tests - omitted
✅Jasmine Tests - augmented and passed
✅JS distributive files - included
⏹CSS distributive files - not needed
⏹Backstop tests - not needed
⏹PHP Unit Tests - not needed
=> PCHR-3889: Create Calendar Feed API, Model and Instance

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1020.php
For old and new sites: Relabel "Line manager" relationship 
'Line Manager is' to 'Is Line Managed by'
'Line Manager' to 'Is Line Manager of'
Only changed the Label, because the name is used explicitly in some places, such as https://github.com/compucorp/civihr/blob/0a7d1905be8e5148222bece35aebb2a4884ebfc4/uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Service/Manager.php#L16
=> PCHR-3603: Relabel Line Manager Relationship

uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeExpiryLogTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php
Some tests fail in Jenkins
Some tests failed in staging. Depending on the time they were there could be a second of difference in two variables which caused a failure.
The difference in time is accounted for
It doesn't happen all the time, but sometimes staging tests fail.
The failing test is from L&A
```
There was 1 failure:
1) CRM_HRLeaveAndAbsences_BAO_LeaveBalanceChangeTest::testCreateExpiryRecordsLogsExpiredBalanceChanges
10
Failed asserting that two DateTime objects are equal.
--- Expected
+++ Actual
@@ @@
-2018-06-20T13:52:23+0100
+2018-06-20T13:52:22+0100
```
The cause seems to be a slight difference in time. This difference happens if the first date is created near a change in seconds, and the second one happens in the next second.
The difference should be handled by the test, …
=> PCHR-3909: Fix Time Related Tests

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1021.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1022.php
Some contact summary fields are visible by default. This PR changes the default for Suffix, Instant messenger and Social Accounts to un-check so they are hidden from users by default
Before un-checking the fields, it was ensured that no record previously existed relating to them.
```php
private function up1022_getUnusedContactEditOptionNames() {
$names = [];
foreach (['Contact', 'IM', 'Website'] as $name) {
$params = ['return' => ['id']];
if ($name === 'Contact') {
$params['suffix_id'] = ['IS NOT NULL' => 1];
}
$result = civicrm_api3($name, 'get', $params);
if ($result['count'] == 0) {
array_push($names, $name === 'Contact' ? 'Suffix' : $name);
}
}
return $names;
}
```
They are also compared against previously activated fields. This implies that they are ignored if not previously checked. …
=> PCHR-3544: Hide Fields for Contact Summary

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
Made all currencies available for new installations
Only few currencies was available on new installations
All Currencies are available on new CiviHR installations by default
Couldn't find any CiviCRM API to retrieve currencies, so made direct query.
=> PCHR-3546: Make All Currencies Available

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1012.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1020.php
In some sites, the "Localise CiviHR" menu (under "Configure") was appearing duplicated. This was happening for two reasons:
- The upgraders were being called twice. This was already fixed by https://github.com/compucorp/civihr/pull/2659
- The upgrader which adds the menu item was relying on translated strings that were not stored in the database. For this reason, it could not find the existing menu item and would end up creating a new one
On https://github.com/compucorp/civihr/pull/2659, we fixed the issue for new sites, as the upgraders would not run twice anymore. However, the duplicated menu still exists in sites created after the menu item has been added and before the fix was release.
New and existing sites don't have the duplicated menu anymore.
In CiviHR, we use Word Replacements …
=> PCHR-3755: Fix duplicated "Localise CiviHR" menu

uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/partials/leave-request-dates.html, uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/partials/staff-leave-report-requests-rows.html
This PR fixes the issue when you delete a leave request from the Staff Report screen and the leave types are showed wrong.
The dates of the request that was not deleted are correct, but the leave type is wrong.
This happens because of `ng-init`, which does not react to the changes.
```js
<tr
ng-repeat="request in requests track by $index"
ng-init="absenceType = report.absenceTypesIndexed[request.type_id]"
```
This PR also fixes the same issue but with the calculation unit.
------
Only manual tests were performed.
=> PCHR-3391: Fix leave type in staff report after request deletion

uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-calendar-day.html
This PR shows non-working days in the Staff Leave Calendar. It also now shows public holidays.
Match HTML classes with CSS selectors:
```js
chr_leave-calendar__day-container--non-working
// to 
chr_leave-calendar__day-container--type--non-working
// and
chr_leave-calendar__day-container--public-holiday
// to
chr_leave-calendar__day-container--type--public-holiday
```
```html
<div class="chr_leave-calendar__day-container"
...
ng-class="{
'chr_leave-calendar__day-container--type--weekend': day.contactData.isWeekend,
'chr_leave-calendar__day-container--type--non-working': day.contactData.isNonWorkingDay,
'chr_leave-calendar__day-container--type--public-holiday': day.contactData.isPublicHoliday
}">
```
```css
/* Already like that */
.chr_leave-calendar__day-container--type--non-working { …
```
=> PCHR-3919: Show non-working days on leave calendar

hrjobcontract/CRM/Hrjobcontract/Upgrader.php
This PR renames page title from `Job Contract Benefit Name` to `Benefits`.
An upgrader was executed to change the page title for job contract benefit to Benefits
```php
'api.OptionGroup.create' => [
'title' => 'Benefits'
],
```
=> PCHR-3555: Rename Job Contract Benefit Name

hrui/hrui.php
When accessing the localise page on CiviHR, an error was thrown saying `QuickForm Error: nonexistent html element`. This PR fixes the issue.
Check was carried out to ascertain the form `makeMultilingual` element exists, before removing it.
```php
$form->elementExists('makeMultilingual')
```
=> PCHR-3911: QuickForm Error on the Localise CiviHR Page

hrjobcontract/CRM/Hrjobcontract/Upgrader.php
This PR renames page title from `Job Contract Deduction Name` to `Deductions`.
An upgrader was executed to change the page title for job contract deduction to Deductions
```php
'api.OptionGroup.create' => [
'title' => 'Deductions'
],
```
=> PCHR-3556: Rename Job Contract Deduction Name

hrjobcontract/CRM/Hrjobcontract/Upgrader.php
This PR renames page title from `Job Contract End Reasons` to `Contract End Reasons`.
An upgrader was executed to change the page title for job contract end reasons to `Contract End Reasons`
```php
'api.OptionGroup.create' => [
'title' => 'Contract End Reasons'
],
```
=> PCHR-3558: Rename Job Contract End Reason

hrjobcontract/CRM/Hrjobcontract/Upgrader.php
This PR renames page title from `Job Contract Revision Change Reason` to `Contract Revision Reasons`.
An upgrader was executed to change the page title for job contract revision change reason to `Contract Revision Reasons`
```php
'api.OptionGroup.create' => [
'title' => 'Contract Revision Reasons'
],
```
=> PCHR-3557: Rename Job Contract Revision Change Reason

contactsummary/js/karma.conf.js, hrjobcontract/js/karma.conf.js, uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/karma.conf.js
This PR fixes failing JS tests due to the introduction of these PRs:
* https://github.com/compucorp/civihr/pull/2705 - introduces modules and allows spec files to be included in source folder.
* https://github.com/compucorp/civihr/pull/2712 - introduces the specific spec files inside source folder for the first time.
The issue is that the ContactSummary and JobContract include files from the source folder in the L&A extension. These reference files are needed when sharing code between extensions, such as models and components from L&A.
The issue is that when Karma finds spec files inside L&A's source folder, it includes them, and run the tests as if they are part of the extension under test. To avoid this, spec files are skipped from being included:
```js
// Before
{ pattern: civihrPath + …
```
=> PCHR-3868: Fix js tests

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequestCalendarFeedConfig.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/LeaveRequestCalendarFeedConfig.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/LeaveRequestCalendarFeedConfig.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1031.php, uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.civix.php, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/LeaveRequestCalendarFeedConfig.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/LeaveRequestCalendarFeedConfig.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestCalendarFeedConfigTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/xml/Menu/hrleaveandabsences.xml
This PR adds the functionality to list, create, update and delete a calendar feed configuration and also adds the configuration link to the menu using the LeaveRequestCalendarFeedConfig Entity added here #2707 
- There was no way to administer a calendar feed.
- The functionality to list, create, update and delete a calendar feed configuration is now available.
- An upgrader was added to insert the Calendar Feeds menu.
- The form and page templates reuse the classes and Javascript scripts used by other Admin configuration pages.
=> PCHR-3866: Administer Calendar Feeds Functionality

com.civicrm.hrjobroles/CRM/Hrjobroles/Upgrader.php, hrjobcontract/CRM/Hrjobcontract/Upgrader.php
This PR deletes `Other` option value from option group cost centre for new site. In existing setups, the value is deleted if not in use.
The option value `Other` is created by default on the system.
The option value is either removed based on job roles status
The system is first checked for existence of job roles data
```php
$jobRoles = civicrm_api3('HrJobRoles', 'get');
```
after which `Other` option is deleted if no record exist.
```php
civicrm_api3('OptionValue', 'get', [
'option_group_id' => 'cost_centres',
'api.OptionValue.delete' => [
'name' => 'Other'
],
]);
```
For systems with job roles data, `other` option is deleted when not in use
```php
if (! $inUse) { // disables cost centre other
$this->deleteCostCentreOther()
}
```
=> PCHR-3559: Delete Cost Centre Other Option

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1024.php
Need to remove the following Social Accounts, if not used and disable if used:
Work
MySpace
Vine
Google+
Snapchat
Tumblr
Need to change the Order of the Social Accounts to the Following:
LinkedIn (default)
Twitter
Facebook
The other Social Accounts was left as-is.
All these social accounts where created by default during installation of CiviHR
Only three social accounts are available for systems with the addition of previously used ones on existing setup
=> PCHR-3606: Remove Some Social Accounts and Reorder the Remaining

hrjobcontract/CRM/Hrjobcontract/Upgrader.php
This PR fixes issues with Job Contract Benefit management after the [previous](https://github.com/compucorp/civihr/pull/2714) upgrade.
Updating `option_group` [requires](https://github.com/civicrm/civicrm-core/blob/master/CRM/Core/BAO/OptionGroup.php#L95) setting the `is_active` attribute as it defaults to `false` if not set.
=> PCHR-3555: Fixed Regression Issue with Adding New Benefit

hrjobcontract/CRM/Hrjobcontract/Upgrader.php
This PR fixes issues with Job Contract Deduction page management after the [previous](https://github.com/compucorp/civihr/pull/2716) upgrade.
Updating `option_group` [requires](https://github.com/civicrm/civicrm-core/blob/master/CRM/Core/BAO/OptionGroup.php#L95) setting the `is_active` attribute as it defaults to `false` if not set.
=> PCHR-3556: Fixed Regression Issue with Adding Deduction

hrjobcontract/CRM/Hrjobcontract/Upgrader.php
This PR fixes issues with `Job Contract Revision Reason` management after the [previous](https://github.com/compucorp/civihr/pull/2715) upgrade.
Updating `option_group` [requires](https://github.com/civicrm/civicrm-core/blob/master/CRM/Core/BAO/OptionGroup.php#L95) setting the `is_active` attribute as it defaults to `false` if not set.
=> PCHR-3557: Fixed Regression Issue with Adding Contract Revision Reason

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/LeaveRequestCalendarFeedConfig.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/LeaveRequestCalendarFeedConfig.php, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/LeaveRequestCalendarFeedConfig.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/LeaveRequestCalendarFeedConfig.tpl
Sequel to #2724 that added the `visible_to` and `composed_of` filter fields to the LeaveRequestCalendarFeedConfig Entity. This PR allows the create/edit page for administering calendar feed configurations to support these filter fields and also display the values of these fields on the calendar feed listing page.
- The calendar field administration does not support Contact and Leave type filters
-  The calendar field administration now supports Contact and Leave type filters. In essence, an administrator can set what contacts a leave feed is to be composed of by setting the department and locations the contacts should belong to and also the contacts that are allowed to view the feed link on the SSP by setting the department and locations these contacts can belong to. Also the Leave types …
=> PCHR-3922: Make the Calendar Feed Administration Support Contact and Leave Types Filters

uk.co.compucorp.civicrm.hrcore/js/hrcore.js
If the [datalayer](https://www.drupal.org/project/datalayer) module is not present/enabled on a site, an error gets thrown by a script in the `hrcore` extension that is trying to use the `dataLayer` global object that that module provides
=> PCHR-3929: Fix JS console error if datalayer drupal module is not present/enabled

hrjobcontract/CRM/Hrjobcontract/Upgrader.php, hrjobcontract/xml/length_of_service.xml
Makes contract length read only and hides it from Personal Details Screen
To hide the field just changed the 'is_active' field of CustomGroup to 0
=> PCHR-3608: Makes Contract Length Read Only

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/Dashboard.php
This PR removes unnecessary permissions export on the Admin Dashboard.
The permissions were added globally in the whole CiviHR (CiviCRM pages) here https://github.com/compucorp/civihr-employee-portal/pull/503.
So we simply remove permissions exports from the Dashboard:
```php
CRM_Core_Resources::singleton()
/*->addPermissions([
'access leave and absences',
'administer leave and absences',
'access leave and absences in ssp',
'manage leave and absences in ssp',
'can administer calendar feeds'
])*/ // not needed anymore
->addStyleFile('uk.co.compucorp.civicrm.hrleaveandabsences', 'css/leaveandabsence.css')
```
----
It was manually tested that the Admin Dashboard still has all needed permissions to work with.
=> PCHR-3897: Remove unnecessary permissions export

uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/dropdown-button/components/calendar-feeds-dropdown-button.html
This PR makes the Calendar Feed Dropdown Button "Add new feed" button open the Add Calendar Feed form in the same tab.
Just remove the `target="_blank"` attribute from the `<a>` element.
----
Tested manually.
=> PCHR-3936: Open Add Feed form in the same tab

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1030.php
This PR adds new set of sickness reason option value after either deleting (for new systems) or disabling (for old systems) the existing option values. The new set of sickness reasons are listed below:
* Cold, Cough, Flu - Influenza
* Headache/Migraine
* Gastro-intestinal Problems
* Back Problems
* Injury, Fracture
* Dental and Oral Problems
* Pregnancy Related
* Anxiety/Stress/Depression/Other Psychiatric Illnesses
* Chest and Respiratory Problems
* Ear, Nose, Throat (ENT)
* Endocrine/Glandular Problems
* Eye Problems
* Genitourinary and Gynaecological Disorders
* Other Musculoskeletal Problems
* Surgery Related
* Other
Existing option values are available after setup.
After running upgrade, only the newly required options are available for selection.
Leave request was checked for …
=> PCHR-3561: Change Options for Sickness Reason

com.civicrm.hrjobroles/CRM/Hrjobroles/API/Query/ContactHrJobRolesSelect.php, com.civicrm.hrjobroles/api/v3/ContactHrJobRoles.php, com.civicrm.hrjobroles/tests/phpunit/api/v3/ContactHRJobRoleTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequestCalendarFeedConfig.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/BaseHeadlessTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestCalendarFeedConfigTest.php
Currently, when configuring a LeaveRequestCalendarFeedConfig in the create/update form, you can set who the feed should be visible to based on department and location that the contact should belong to. This PR implements this logic in the LeaveRequestCalendarFeedConfig.get API by checking for the departments and locations that the current user belongs and using this information to determine whether the user has access to fetch a feed configuration or not. Admins (users with the (`can administer calendar feeds` permission) can view all feed configurations, while users without these permissions can only view the feed configuration based on the feed visibility settings.
- The visibility logic is not implemented for the LeaveRequestCalendarFeedConfig.get API, therefore all users can view all …
=> PCHR-3903: Implement Visibility Logic for LeaveRequestCalendarFeedConfig.get API

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestTest.php
This PR customises the message for the case when user attempts to approve their own leave request. Currently an admin can attempt to do that and now instead of seeing **You can't change the Leave Request status from 3 to 1** they see **You can't approve your own leave requests**. Also, the **You can't change the Leave Request status from 3 to 1** was transformed to show real labels and not numbers: **You can't change the Leave Request status from "Awaiting Approval" to "Approved"**.
Instead of returning a generic error, we now use a function that determines the case for a custom error or returns the default generic one.
```php
private function getErrorMessageForInvalidStatusTransition($params) {
// if own request and transitioning to "Approved" - custom error message
if ($isOwnRequest && …
```
=> PCHR-3927: Customise error message for approval transition

uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/LeaveRequestCalendarFeedConfig.tpl
This PR improves the visual representation of the Add Calendar Feed (as well as Edit Calendar Feed) forms.
- dynamic hints are now muted, contain asterisk
- grouped fields are separated from each other with extra paddings
Simply changed the structure and classes of hints:
```html
<div class="col-sm-9 pull-left text-muted form-group">
<span>*</span>
<span class="visible_to_help_text"></span>
</div>
```
HTML indentation and JS was refactored.
----
This PR was tested manually.
=> PCHR-3939: Improve UI for Add Calendar Feed form

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/LeaveRequestCalendarFeedConfig.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/PublicHoliday.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/WorkPattern.php
This PR ticks the Calendar Feed **Enabled** checkbox by default.
```php
public function setDefaultValues() {
if(empty($this->defaultValues)) {
if ($this->_id) { // if editing
// ...
} else { // if creating a new feed
$this->defaultValues['is_active'] = TRUE; // <<<
```
The code is also a bit refactored, the `checkbox` input type was changes to `advcheckbox` to avoid unnecessary post-processors such as:
```php
$checkboxFields = ['is_default', 'is_active', 'allow_accruals_request', ... ];
foreach ($checkboxFields as $field) {
if(!array_key_exists($field, $params)) { // if checkbox is not checked
$params[$field] = 0; // set value to 0
```
`advcheckbox` makes such post-processing out of the box (see https://docs.civicrm.org/dev/en/latest/framework/quickform/):
ℹ️The `checkbox` was changed to …
=> PCHR-3956: Enabled is active field by default

uk.co.compucorp.civicrm.hrcore/vendor/icalendar/includes/date.php, uk.co.compucorp.civicrm.hrcore/vendor/icalendar/includes/framework.php, uk.co.compucorp.civicrm.hrcore/vendor/icalendar/includes/ical.php, uk.co.compucorp.civicrm.hrcore/vendor/icalendar/includes/index.html, uk.co.compucorp.civicrm.hrcore/vendor/icalendar/includes/recurringdate.php, uk.co.compucorp.civicrm.hrcore/vendor/icalendar/includes/timezone.php, uk.co.compucorp.civicrm.hrcore/vendor/icalendar/zapcallib.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequestCalendarFeedConfig.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Helper/CalendarFeed/LeaveTime.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/LeaveRequestCalendarFeed.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestCalendarFeedData.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestCalendarFeedIcal.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/LeaveRequestCalendarFeedConfig.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestCalendarFeedConfigTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Helper/CalendarFeed/LeaveTimeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestCalendarFeedDataTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestCalendarFeedIcalTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestCalendarFeedConfigTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/xml/Menu/hrleaveandabsences.xml
This PR adds functionality for actual Leave request Ical feed generation off the Feed configuration.
This PR also depends on https://github.com/compucorp/civihr-employee-portal/pull/511 which allows the calendar feed URL not to be blocked by the public firewall and to be publicly accessible. 
- The functionality for generating Leave request Ical feed was not present.
Trying to retrieve the Ical for a disabled feed or non existent hash
Trying to retrieve the Ical for a valid and enabled feed
- A new public URL `civicrm/calendar-feed` was added that allows a user add a calendar feed to his preferred calendar application. 
A fully formed feed URL is similar to: `civicrm/calendar-feed?hash=7f9e70bebdc30dab872829893c47a3ac` where the hash is the feed config hash.
- A new class …
=> PCHR-3870: Provide Functionality for getting Leave Ical Feed Via URL

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1026.php
Deletes some default groups and hide one of them. 
All Groups  existed on default installation and with demo data
After this upgrade, no group will be visible by normal users
Figured out that deleting Administrators group does not cause any problem, because it is not even created in default installation, only when  using sample data.  
Case resources is created on default installation, so i disabled and hide it for safety
=> PCHR-3607: Delete Default Groups and Hides One of Them

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/CreateUserRecordTaskForm.php
When adding new user account, `Send Welcome Email` was not checked by default. This PR changes the display by setting it to checked by default.
The checked value of the element was set to checked
```php
$element->setChecked(TRUE);
```
=> PCHR-3839: Select Send Welcome Email by Default

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1000.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1021.php
This PR add a function to  disable 'Prefer Not to Say' Gender Option on an existing Upgrader.
The Prefer Not to Say option was active by default
The Prefer Not to Say Option will be disabled by this Upgrader
=> PCHR-3975: Disable Prefer Not To Say Gender Option

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1000.php
In https://github.com/compucorp/civihr/pull/2698 the hrcore extension was updated in order for it to automatically enable all the available currencies in CiviCRM.
The solution worked without a problem in CiviCRM 4.7.27, but it stopped working after we upgraded CiviHR to 5.3.0. When trying to install the hrcore in a site using 5.3.0, the installation fails with this error:
```php
Array
(
[is_error] => 1
[error_message] => Value already exists in the database
)
```
It is not possible to install hrcore in a site using CiviCRM 5.3.0
It is now possible to install hrcore in a site using CiviCRM 5.3.0
In CiviCRM, the list of enabled currencies is stored as Option Values under the `currencies_enabled` Option Group. Each Option Value there represents one enabled currency. The name of the Option …
=> PCHR-3983: Fix for enabling all currencies in hrcore

uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php
Currently, it is impossible for a contact to have a Leave approver relationship with itself because of a restriction to do this.
- A contact cannot have a leave approver relationship with itself
- A contact can have a leave approver relationship with itself
The implementation of the `hook_civicrm_validateForm` for the `CRM_Contact_Form_Relationship` in Leave and absences extension prevents a contact from being assigned as own leave approver. This code was removed altogether since there is no more need for it.
=> PCHR-4001: Allow Contact to Be own Leave Approver When Assigning Leave Approver  Relationship

hrui/templates/CRM/common/footer.tpl, uk.co.compucorp.civicrm.hrcore/hrcore.php
This PR hides System Notifications for non root users.
System notification is disabled for all non root users by implementing `hook_civicrm_check` and clearing the messages.
```
$messages = [];
```
This also implies no system notification will be rendered in the `/civicrm/a/#/status` page.
An existing `view system status in footer` has also been [renamed](https://github.com/compucorp/civihr-employee-portal/pull/524) to `view system notifications` since they both serve similar purpose of restricting access to system notification by non root users.
=> PCHR-3999: Hide all Civicrm System Notifications

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1021.php
This Upgrader Fixes the 'Missing Log Tables' issue on some installation after CiviCRM upgrade to 1.7.8
This error is not shown anymore.
=> PCHR-3998: Fix Missing Log Tables

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestStatusMatrix.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestStatusMatrixTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
Sequel to #2780, which allows a user to be assigned as own leave approver irrespective of the role of the user, This PR makes some changes in the way a user interacts with own requests especially when such a user is its own leave approver.
These changes allow a user irrespective of the role to assume the role of a leave manager on own request when the user is own leave approver. For example a Staff that is own leave approver can now cancel, approve and perform the same actions a leave manager can on a leave request for own request.
The new changes are summarised as follows
- An Admin can manage own requests irrespective of whether he is own leave approver or not
- A Staff can manage own request only if the staff is own leave approver
- A Manager can manage own request only if the manager …
=> PCHR-4002: Allow User Who is Own Leave Approver Take Admin Actions on Own Requests

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1022.php
This Upgrader removes the Recruitment menu in Admin Portal
The removal is done by deleting the Menu entry in the civicrm_navigation table on the database. Then,the extension is disabled and uninstalled using CiviCRM Extension API.
=> PCHR-4003: Hide Recruitment Menu on Admin Portal

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestRights.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestRightsTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestTest.php
Previously, Only an Admin can delete a leave request. This PR allows users that are their own leave approvers to delete their own leave requests.
- Only Admins can delete leave requets
- Admins can delete all leave requests while users that are their own leave approvers can delete their own leave requests.
The `canDeleteFor` method of the LeaveRequestRights Service was modified to accommodate for the new change.
```php
public function canDeleteFor($contactID) {
if ($this->currentUserIsAdmin()) {
return TRUE;
}
if (!$this->currentUserIsLeaveContact($contactID)) {
return FALSE;
}
return $this->currentUserIsLeaveManagerOf($contactID);
}
```
=> PCHR-4040: Allow user who is own Leave Approver to delete own requet

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/CreateUserRecordTaskForm.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Service/DrupalUserService.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Service/DrupalUserServiceTest.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/drupal_function_mocks.php
This PR fixes issues with creating user account for restored contact.
Creating user account results in an error, indicating duplicate emails address
Creating user account attempts to create a new user record which is not needed for restored account. User account is therefore checked before processing request.
```php
$user = $this->drupalUserService->findUserByEmail($contact['email']);
if (!$user) {
$this->createAccount($contact, $roles);
}
else {
$this->restoreAccount($user, $roles, $contact['id']);
}
```
When user accounts are deleted, their UFID also gets deleted in the process. When restored, the UFID do not get re-created. Only the account was set to active once again. After checking and updating existing account, new UFID was generated.
```php
public function restoreAccount($user, …
```
=> PCHR-3345: Unable to Create User Account for Restored Contact

hrcase/CRM/HRCase/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1023.php
This PR moves the upgraders for creating the Case Type Category custom field and the upgrader for assigning categories to Case Types. The upgraders were moved from the Tasks and Workflow extension to the HRCore and HRCase extensions.
The reason for moving the upgraders is because assigning a category to Case Types only works for existing installations.  For new installations, the upgraders were running before the default case types were being created since they are created in the HRCase and HRRecruitment extensions.
The PR that removes the upgraders from the Tasks and Workflows extension is this one:
https://github.com/compucorp/civihr-tasks-assignments/pull/400
The creation of the category custom field was moved to HRCore because this field is generic, independent of the Case Type or …
=> PCHR-4017: Move Case Type Category Upgraders

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestRights.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestRightsTest.php
Currently only the Admin can edit leave dates irrespective of the leave type and leave status, while other users like the staff and leave managers are bound by some rules which determine whether they can edit the leave dates or not. This PR makes it possible for Own leave approvers to be treated like an Admin for own requests and allowing such users edit the leave dates of their request irrespective of the status of the leave request or the leave request type.
- Only Admins can edit dates of a leave request irrespective of the status of the leave request or the leave request type.
- Own Leave approvers now have admin capabilities when editing their own requests as they can now edit the dates irrespective of the status of the leave request or the leave request type.
The `canChangeDatesFor` …
=> PCHR-4054: Allow Own Leave Approver Edit Leave Dates For Own Request.

com.civicrm.hrjobroles/CRM/Hrjobroles/API/Query/ContactHrJobRolesSelect.php, com.civicrm.hrjobroles/CRM/Hrjobroles/Test/Fabricator/HrJobRoles.php, com.civicrm.hrjobroles/tests/phpunit/api/v3/ContactHRJobRoleTest.php
When filtering leave by admin on leave requests and calendar tab, records for staff whose job role are out of active date are returned. This PR fixes this by ensuring that date of filtering falls within staff job roles start and end date.
Filter result includes staff records whose job role start date is more than filter date or end date is less than the filtering date.
Filter result no longer include staff records whose job role start date is more than filter date or end date is less than the filtering date.
Date filtering was [applied](https://github.com/compucorp/civihr/blob/staging/com.civicrm.hrjobroles/CRM/Hrjobroles/API/Query/ContactHrJobRolesSelect.php#L126) to the filter query to ensure job role start and end date are put into consideration.
```
$today = date('Y-m-d H:i:s'); …
```
=> PCHR-4076: Fix Filters on Admin Leave - Leave Requests and Calendar Tab

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1022.php
This Upgrader disables and uninstalls the HR Recruitment extension.
The HR Recruitment was active and there was a "Recruitment" menu in Admin portal
The HR Recruitment will be disabled and uninstalled, so there won't be a "Recruitment" menu in Admin Portal
- The extensions folder need to be removed after this task is released to the clients
- This upgrader will also remove all data created by the extension
=> PCHR-4003: Hide Recruitment Menu in Admin Portal

uk.co.compucorp.civicrm.hrcore/gulp/tasks/requirejs.js, uk.co.compucorp.civicrm.hrcore/gulp/tasks/sass.js, uk.co.compucorp.civicrm.hrcore/gulp/tasks/test.js, uk.co.compucorp.civicrm.hrcore/gulp/utils.js, uk.co.compucorp.civicrm.hrcore/gulpfile.js
After https://github.com/compucorp/civihr/pull/2804 `gulp backstopjs:reference` stopped working. This PR fixes this issue. 
The initial problem was that the "extension related" tasks (like "test", "watch" and "requirejs") were initiated even if just BackstopJS task was execution was asked. Thus, they checked for provided extension, which we never provide when running BackstopJS.
So, in order to avoid this issue we need to wrap these tasks inside functions with callbacks.
```js
gulp.task('build', function (cb) {
var buildTasksNames = spawnTasks(['sass', 'requirejs', 'test']);
gulp.series(buildTasksNames)(cb);
// and similar for "watch"
// ...
function spawnTasks (taskNames) {
return taskNames.map(function (taskName) {
return utils.spawnTaskForExtension(taskName, tasks[taskName]);
});
}
``` …
=> PCHR-4049: Fix gulp tasks

uk.co.compucorp.civicrm.hrcore/backstop_data/page-objects/ssp-my-details.js, uk.co.compucorp.civicrm.hrcore/backstop_data/scenarios/la-dashboard.json, uk.co.compucorp.civicrm.hrcore/backstop_data/scenarios/ssp-la-manager.json, uk.co.compucorp.civicrm.hrcore/backstop_data/scenarios/ssp-la-my-leave.json, uk.co.compucorp.civicrm.hrcore/backstop_data/scenarios/ta-calendar.json, uk.co.compucorp.civicrm.hrcore/backstop_data/scenarios/ta-documents.json, uk.co.compucorp.civicrm.hrcore/backstop_data/scenarios/ta-tasks.json, uk.co.compucorp.civicrm.hrcore/package-lock.json, uk.co.compucorp.civicrm.hrcore/package.json
This PR contains miscellaneous improvements and fixes to CiviHR's backstopjs set up
~~Update BackstopJS to the beta version, currently `v3.5.0`. The rationale behind this decision is the same as the one described [here](https://github.com/compucorp/backstopjs-config/commit/62d3f9fa8c0e9014f77f001398e802c01c726189)~~
Using the beta version caused an issue in which a node package was not properly installed when running `npm i` in the civihr root, thus causing `gulp` commands to not execute
I couldn't find the reason for it, so instead of using the beta version I used the latest stable version (`v3.5.2`). It doesn't contain the improvement that the beta contains, but it's at least stable
After #2790 , the format of urls of angular apps have changed, for example:
```diff
- …
```
=> PCHR-4098: Misc BackstopJS fixes and improvements

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestCalendarFeedData.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestCalendarFeedDataTest.php
This PR fixes an issue when some leave requests are not included in a calendar feed due to their "from" and "to" dates.
The table below shows which leave requests were **expected** to be added but were not added.
```
TODAY     +3 MONTHS           NOW    EXP    BUG
------------|-----------|------------    
LR1   +++++++                                X      X
LR2          +++++++                         X      V     YES
LR3                +++++++                   V      V
LR4                      +++++++             X      V     YES
LR6                            +++++++       X      X
LR7   ++++++++++++++++++++++++++++++++       X      V     YES
```
Logically wise the date selection was wrong, the correct logic is:
**Whenever at least one day of a leave request appears in the period …
=> PCHR-4110: Fix calendar feeds leave requests inclusion logic

uk.co.compucorp.civicrm.hrcore/hrcore.php
This PR changes the link pointed at by `user guide` under the help menu for `HR Admin` to http://userguide.civihr.org/en/latest/
User guide help menu points to `http://civihr-documentation.readthedocs.io/en/latest/`
User guide help menu points to `http://userguide.civihr.org/en/latest/`
The civicrm navigation [url](https://github.com/compucorp/civihr/blob/staging/uk.co.compucorp.civicrm.hrcore/hrcore.php#L510] for user guide help menu was updated to `http://userguide.civihr.org/en/latest/`
=> PCHR-4072: Update help link to lead to freshdesk knowledge base 

bin/apply-core-fork-patch.sh
This PR changes the implementation of Apply Core Fork Patch Script from using the api to using `diff` url when creating patch. This helps to reduce tendency for API rate limit errors.
API rate limit applies to core fork request for git diff in commits when creating patch.
No API rate limit is applicable to git diff request when applying core fork patch to create patch. 
The api base url was changed to non api url in order to avoid rate limiting in requests.
```
REPO_BASE_URL="https://github.com/compucorp/civicrm-core"
```
=> PCHR-3797: Improve Apply Core Fork Patch Script to Avoid API Rate Limit Errors

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1032.php
This PR changes the labels for some of the default assignee options:
<table>
<tr>
<th>From</th>
<th>To</th>
</tr>
<tr>
<td>By relationship to workflow client</td>
<td>By relationship to target staff member</td>
</tr>
<tr>
<td>User creating the case</td>
<td>User who starts the workflow</td>
</tr>
</table>
Since these options are created by CiviCRM core, a new upgrader was added to HRCore:
```php
<?php
trait CRM_HRCore_Upgrader_Steps_1032 {
public function upgrade_1032() {
$optionValuesNewLabels = [
'BY_RELATIONSHIP' => 'By relationship to target staff member',
'USER_CREATING_THE_CASE' => 'User who starts the workflow',
];
$optionValuesNames = array_keys($optionValuesNewLabels);
$optionValues = civicrm_api3('OptionValue', 'get', [
'name' => ['IN' => $optionValuesNames], …
```
=> PCHR-3410: Change default assignee option labels

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/BuildForm/DataSourceFilter.php, uk.co.compucorp.civicrm.hrcore/hrcore.php
This PR allows the user to pass contact subtype as a GET parameter when force is set to 1. Then this subtype is used as the default value on the DataSource selection Form
It was not possible to pass contact subtype as a parameter.
When force is set to 1 and contactType is set to "Individual", the "Individual" checkbox is selected by default. The same happens with all other contact subtypes.
=> PCHR-4061: Allow Passing Contact Subtype as a Parameter

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1032.php
This Upgrader changes the staff menu structure. It add new menus, removes some old menus and disable import submenus, as they will be moved in new upgrader.
I could not use chained API calls because CiviCRM implicitly add $value.id to the chained calls, so instead of creating new menu, the chained call was editing the previews one.
=> PCHR-4059: Improve Staff Menu

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1032.php
After uninstalling the Recruitment extensions, some of it's submenus were left on the Database. This upgrader just removes them.
There were some submenus left on the navigation table after uninstalling the extension.
The submenus will be deleted from the database by this upgrader
Removing these submenus does not prevent the pages from being accessible directly via URL, as these pages belongs to another extensions. It's just for cleanup purposes.
=> PCHR-4101: Remove Recruitment Submenus

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1032.php
This Upgrader changes the options to use names instead of Label on navigation API calls. There was a problem in items where the names are different from Labels. This PR is an amendment to [PCHR-4059: Improve Staff Menu](https://github.com/compucorp/civihr/pull/2836)
Some Import items were not disabled on Staff menu
All Import items will be disabled on Staff Menu
=> PCHR-4131: Hide Import Menus From Staff Menu

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1032.php
This PR is an amendment to [PCHR-4059: Improve Staff Menu](https://github.com/compucorp/civihr/pull/2836) where there was an issue with the menu link in New Meeting.
The menu wrongly pointed to /activity?reset=1&action=add&context=standalone
The menu link is pointing to civicrm/activity?reset=1&action=add&context=standalone
=> PCHR-4132: Add the Correct Menu Link to New Meeting

Jenkinsfile, bin/civihr-crm-api-tests.sh, bin/civihr-webtests.sh, bin/drush-install.sh, bin/git-release.sh, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Service/Stats/StatsGatherer.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Test/BaseHeadlessTest.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1031.php, uk.co.compucorp.civicrm.hrsampledata/tests/phpunit/CRM/HRSampleData/BaseCSVProcessorTest.php
This PR prevents hrrecruitment for being installed on new sites. It also removes all occurrencies of hrrecruitment on the code
Hrrecruitment was being installed on new sites.
Hrrecruitment will not be installed on new sites
=> PCHR-4139: Remove HRRecruitment For New Sites

uk.co.compucorp.civicrm.hrcore/hrcore.php
The link was [previously](https://github.com/compucorp/civihr/pull/2822) updated but incorrect URI was used. This PR changes the URI as appropriate.
User guide help menu points to `http://userguide.civihr.org/en/latest/`
User guide help menu points to `http://userguide.civihr.org/`
The URI contains `en/latest/` which was not meant to be part of it. The civicrm navigation [url](https://github.com/compucorp/civihr/blob/staging/uk.co.compucorp.civicrm.hrcore/hrcore.php#L510] for user guide help menu was therefore updated.
=> PCHR-4138: The link is wrong

uk.co.compucorp.civicrm.hrcore/hrcore.php
This PR changes the heading of the import page from "Import Contacts" to "Import Staff"
The page heading was "Import Contacts"
The Page heading will be "Import Staff"
It is required to clear the cache for this change to take effect.
=> PCHR-4063: Changing Import Contacts to Import Staff

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1033.php
In order to access the `message template menu`, permission to `access root menu items and configurations` is required. This does not give `HR admin` access to the page even though they have access to a granular permission - `edit user-driven message templates`. This PR adds the two new granular permissions to the existing permission.
The permissions for both `Communications` and `Message Templates` were modified to ensure it grants access to users with any of the following permission - 
* access root menu items and configurations
* edit system workflow message templates
* edit user-driven message templates
```
'api.Navigation.create' => [
'permission' => implode(',', $permissions),
'permission_operator' => 'OR'
],
```
The permissions were created using this PR …
=> PCHR-4150: Grant HR Admin access to message template menu

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1033.php
After granting [permission](https://github.com/compucorp/civihr-employee-portal/pull/460) to HR Admin to access `user-driven message templates`, access to the menu was also implemented in the following PR:
* PCHR-4150: Grant HR Admin access to message template menu - [#2848](https://github.com/compucorp/civihr/pull/2848)
=> PCHR-3488: Permission to Edit Message Templates

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1034.php
This PR fixes an upgrader introduced in https://github.com/compucorp/civihr/pull/2776 The upgrader was missing a return TRUE which was forgotten when fixing git conflicts.
The missing `return TRUE` was added to https://github.com/compucorp/civihr/blob/64435a95e1b1d5b4caf90c43a5a968659109012f/uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1034.php :
```php
<?php
trait CRM_HRCore_Upgrader_Steps_1034 {
public function upgrade_1034() {
// ...
return TRUE;
}
}
```
=> PCHR-3369: Fix return value for upgrader

Jenkinsfile
The failure threshold in Jenkins was set to `1`. This would make Jenkins mark a build as passed when it had exactly 1 failure, as it can be seen [here](https://jenkins.compucorp.co.uk/blue/organizations/jenkins/Tasks%20and%20Assignments/detail/staging/55/pipeline/45) (Open the details of the JS test to see the reported failure).
The threshold was set to `0`, which will make Jenkins mark a build as failed if it has 1 or more failures.
The threshold has always been `1` since the [Jenkins file was introduced](https://github.com/compucorp/civihr/pull/2195). There's no explanation why I set it like that, but it was clearly a mistake.
=> PCHR-4166: Set Jenkins failure threshold to 0

contactsummary/contactsummary.php, hrcareer/hrcareer.php, hrident/hrident.php, hrmed/hrmed.php, hrqual/hrqual.php, hrstaffdir/hrstaffdir.php, hrui/hrui.php, hrvisa/hrvisa.php
The main reason for this is that `$this` was being passed as the store param in places that we didn't have a context object (i.e. outside of an instance method). Up to PHP 7.0, this would work without a problem, but starting from PHP 7.1, this now results in an error: https://3v4l.org/QXYLB
In a few places, instead of $this, `CRM_Core_DAO::$_nullObject` was being used. This is a risky approach, as it's possible for $_nullObject to not be null (it is just a public static property of the DAO class). This has been removed as well.
This is not really related or necessary for the work I'm doing for the CiviHR installation profile. I'm doing the tests for PCHR-3681 in an environment with PHP 7.1 installed and ended up stumbling upon this issue, so I thought it would be nice to fix it.
=> PCHR-3681: Remove unnecessary param in calls to CRM_Utils_Request::retrieve()

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php, uk.co.compucorp.civicrm.hrcore/hrcore.php
This PR changes the staff directory page title to "Staff Directory". It also adjusts the Upgraders call in Upgrader.php, that was forgotten when solving merge conflict.
The Page title was "Advanced Search"
The Page Title is now "Staff Directory"
for this, the hook_civicrm_alterMenu was used. For changes on this hook to take effect is required to clear the cache.
=> PCHR-4065: CHange Staff Directory Page Title

hrjobcontract/CRM/Hrjobcontract/Upgrader.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/BuildForm/ContactFormCustomGroupFilter.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/PageRun/ContactSummaryCustomGroupFilter.php, uk.co.compucorp.civicrm.hrcore/hrcore.php
The Contact_Length_Of_Service custom group was disabled as part of https://compucorp.atlassian.net/browse/PCHR-3608 in https://github.com/compucorp/civihr/blob/ca1854d9030af597f0d29eea9b5fe33f0a8f9c6b/hrjobcontract/CRM/Hrjobcontract/Upgrader.php#L1035. The reason was to hide the Contact Length Of Service  display on the contact summary details page(personal details tab) and the edit contact page. However after disabling this, updates to the `Length_Of_Service`  custom field belonging to the Contact_Length_Of_Service custom group stopped working, this resulted in a blank value for new contacts with newly created contracts and the values stopped updating for old contacts with existing contracts.
The approach to fix the issue is by adding another upgrader to make the …
=> PCHR-4148: Fix issue with blank/incorrect display of Contract length of service field

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/CreateUserRecordTaskForm.php
When creating a user account by `HR Admin`, option for assigning `Regional HR Admin` role to user account was not available. This PR fixes the issue.
Regional HR Admin was added to the list of roles that can be assigned
```
$roles = ['HR Admin', 'Manager', 'Staff', 'Regional HR Admin'];
```
---
=> PCHR-4173: Local Admin Role is not available

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestRights.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestRightsTest.php
According to the specification, admins should be able to change the Absence Type of any open Leave Request, the same way as staff members are allowed to do that to their own Leave Requests. However, the current implementation allowed only staff members to do that.
Admins could not change the Absence Type of an open Leave Request. When trying to do that, they would get a "You are not allowed to change the type of a request" error.
Admins can change the Absence Type of an open Leave Request
Before actually making the changes for this fix, on  https://github.com/compucorp/civihr/pull/2876/commits/b4355593b00f81a3ab7bbd7c49ca0c639c16095a I did a quick refactoring of the `LeaveRequestRights` class by replacing a helper method to get the Leave Request statuses with a call to …
=> PCHR-3039: Allow admins to change Absence Type of open Leave Requests

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/AbsenceType.tpl, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsenceTypeTest.php
A new field called category was introduced in a previous PR. This PR adds the the category field to leave/absence type listing page.
The categories were fetched using BAO for AbsenceType and mapped to each of the category id in absence type table.
```
private function getCategoryLabel($categoryId) {
if (empty($this->categories)) {
$this->categories = AbsenceType::getCategories();
}
$categoryLabel = array_search($categoryId, $this->categories);
if ($categoryLabel !== NULL) {
return $categoryLabel;
}
}
```
=> PCHR-4207: Add leave type category label

uk.co.compucorp.civicrm.hrcore/config/menu/main.php
As part of the Staff Menu improvements Epic, this PR removes the Search menu and its sub menu items.
The  Search menu and its sub menu items were present.
The  Search menu and its sub menu items are no longer present.
=> PCHR-4302: Remove Search Menu and Sub Items

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Menu/Config/CustomFields.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Menu/Config/Import.php, uk.co.compucorp.civicrm.hrcore/config/menu/configure.php, uk.co.compucorp.civicrm.hrcore/config/menu/import.php
As part of the changes introduced by the Staff menu improvements epic, this PR adds the import related menu items under the Configure menu. The import menu items themselves are under the menu heading 'Import'. The import menu items comprises of static menu import items and dynamic import items which are basically for custom fields and these menu items may change depending on the custom fields present on a site.
The Import related menu Items were not under 'Configure' Menu.
The Import related menu Items are now  under the 'Configure' Menu.
A new class `CRM_HRCore_Menu_Config_Import` was created to merge the static import menu items with the dynamic custom fields import menu items and return the resulting import menus.
``` php
public static function getItems() {
$importFile = …
```
=> PCHR-4304: Move Import related Items to the Configure menu.

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/BuildForm/ContactImportFieldsFilter.php, uk.co.compucorp.civicrm.hrcore/hrcore.php
As part of the changes introduced by the Staff menu improvements epic, this PR removes hides some unwanted fields and their labels from the Import Contacts page.
The contact import screen was un-modified.
The following fields were hidden from the import contacts page. In order to avoid validation issues and also prevent unexpected results, the default expected values of these fields were also set.
1. Choose Data Source data source field 
2. Contact type 
3. Dedupe options
4. Import Field Separator
Hook `hrcore_civicrm_buildForm` was used to hide freeze these fields and also hide them by injecting appropriate CSS into the form page.
A sample CSV was uploaded to create contacts and the contacts were created as expected with no errors to make sure that the functionality still works as …
=> PCHR-4305: Filter Unwanted Fields From Import Contact Screen.

com.civicrm.hrjobroles/CRM/Hrjobroles/Import/Form/DataSource.php, com.civicrm.hrjobroles/templates/CRM/Hrjobroles/Import/Form/DataSource.tpl, hrjobcontract/CRM/Hrjobcontract/Import/Form/DataSource.php, hrjobcontract/templates/CRM/Hrjobcontract/Import/Form/DataSource.tpl
As part of the changes introduced by the Staff menu improvements epic, this PR removes hides some unwanted fields and their labels from the Job contract and Job roles Import pages.
Job contract and Job roles Import pages was un-modified.
The Import Field Separator field was hidden from the Job contract and Job roles Import pages. In order to avoid validation issues and also prevent unexpected results, the default expected value for field was also set.
The core css class [here](https://github.com/civicrm/civicrm-core/blob/master/css/civicrm.css#L26-L29) was used to hide the Import Field Separator field from the view.
=> PCHR-4306: Filter Unwanted Fields From Job Roles/Job Contract Import Page

uk.co.compucorp.civicrm.hrcore/hrcore.php
This PR updates the page title of the import contact page.
The page title of the import contact page was unchanged
The page title of the import contact page was updated from 'Import Contacts' to 'Import Staff'
=> PCHR-4308: Update Import Contact Page Title

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1035.php
This PR fixes issue with absence type sql operations on existing sites whenever logging is enabled.
Carrying out SQL operations generates error as a result of log table not being synchronized appropriately with changes on `civicrm_hrleaveandabsences_absence_type` table.
SQL operations now occur without error
Log table is re-checked for newly added columns and triggers re-generated based on changes.
```
$logging->fixSchemaDifferencesFor($absenceTypeTable, [], TRUE)
```
An existing upgrader was updated because the epic is still on and not ready for testing.
=> PCHR-4217: Schema Fixes for Absence Type Log Table

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsenceTypeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/AbsenceTypeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
Absence type title is a required field and null is not allowed. If no value is specified for title and other required fields are provided, the record still get inserted into the db. This PR fixes the issue
Creating absence type with empty title works.
Creating absence type with empty title now throws an exception.
The title was checked for emptiness(after trimming), and error is thrown if title is not present or evaluates to false. 
```
private static function validateAbsenceTypeTitle($params) {
$title = trim(CRM_Utils_Array::value('title', $params));
if (empty($title) && $title !== '0') {
throw new InvalidAbsenceTypeException(
'The title is not provided'
);
}
....
}
```
This is with the exception of `0` as discussed in slack conversation.
cc @igorpavlov.
=> PCHR-4345: Improve Absence Type Title Validation

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/Search/StaffDirectory.mgd.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/Search/StaffDirectory.php, uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/SearchCriteria.tpl, uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/Selector.tpl, uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/StaffDirectory.tpl, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Form/Search/StaffDirectoryTest.php
As part of the changes introduced by the Staff Menu Improvement Epic, this PR adds the Staff Directory Page that allows the Admin view a list of users and use a form filters to refine the search results. 
- The Staff Directory Page does not exist.
The Staff Directory page was created and ships with only the `Select Staff` filter field for now. This filter field allows the admin to filter staff based on Job contract dates.
The `Select Staff` filter is a select dropdown that has the following options:
- **Current Staff**: i.e. 
Job Contract Start Date <= Todays date
Job Contract End Date >= Todays date (or is null)
- **Past Staff** i.e
Job Contract End Date < Todays date
- **Staff Joining in Future** i.e
Job Contract Start Date > Todays date
- **All Staff**
- **Relative Dates** i.e
CiviCRM …
=> PCHR-4311: Create Staff Directory Search Page

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/Search/StaffDirectory.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Form/Search/StaffDirectoryTest.php
This PR modifies the bulk actions available on the search results page for the Staff directory page.
All bulk actions provided by Civi are available for the Search directory page.
After searching only the following bulk actions are available:
* Create User Accounts
* Delete Staff (Delete Contacts)
* Delete Staff permanently (Delete Contacts permanently
* Export Staff (Export Contact)
* Print merge documents
The `buildTaskList` method of the `CRM_HRCore_Form_Search_StaffDirectory` class was modified to return the required bulk actions.
There was an issue with Export Staff bulk action yielding an empty CSV which is as a result of the function processing the export functionality [here](https://github.com/compucorp/civihr/blob/49b363e09bfb5d9fd647ba14f7672be70c686c7e/hrjobcontract/CRM/Export/B …
=> PCHR-4310: Modify Bulk Actions After Search for Staff Directory Page

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Menu/Config/StaffDirectory.php, uk.co.compucorp.civicrm.hrcore/config/menu/main.php
This PR adds the URL for the Staff Directory Page. The URL opens the page listing the current staff.
- A placeholder URL was in place
=> PCHR-4317: Add menu URL for staff directory.

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/Links/ContactCustomActions.php, uk.co.compucorp.civicrm.hrcore/hrcore.php
This PR modifies the actions available for individual contact on the Staff directory search results page for Individual contacts.
After searching the following actions are available for each staff member in the list:
* Record Leave
* Record Sickness
* Record Overtime
* Add Task
* Add Document
* Add Workflow
* Delete Staff
* Delete Staff Permanently
The `hrcore_civicrm_links` hook was used to modify the contact links for the staff directory search page.
=> PCHR-4309: Modify Search Actions for Individual Contacts on Staff Directory Page

uk.co.compucorp.civicrm.hrleaveandabsences/js/src/leave-absences/leave-type-wizard/components/fields-templates/leave-type-wizard-field-notification_receivers_ids.html
This PR fixes autocompletion for Backup Leave Approver field. The autocompletion was accidentally removed in https://github.com/compucorp/civihr/pull/2908. 
```html
<ui-select
...
<ui-select-choices repeat="contact.contact_id as contact in (form.contacts | filter: $select.search)">
{{contact.display_name}}
```
Basically `(form.contacts | filter: $select.search)` instead of just `form`.
----
⏹Jasmine Tests - not neededmended & passed
⏹JS distributive files - not needed
⏹CSS distributive files - not needed
⏹Backstop tests - not needed
⏹PHP Unit Tests - not needed
=> PCHR-4353: Fix autocompletion for Backup Leave Approver field

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1036.php
This PR updates existing sites absence type by linking the newly created category column to option group used for listing available values.
Absence type category were not initialized
Absence type category are now initialized
When the category column was created in `civicrm_hrleaveandabsences_absence_type` table, it was done with `NOT NULL` property. This implies the value will be empty for existing sites. This was used as criteria for differentiating between new and existing systems. 
All absence types were first fetched
```
private function up1036_getAbsenceTypes() {
$absenceTypes = [];
$absenceType = new AbsenceType();
$absenceType->find();
while($absenceType->fetch()) {
$absenceTypes[] = clone $absenceType;
}
return $absenceTypes;
}
```
and then updated only if category was empty.
``` …
```
=> PCHR-4249: Existing Leave Types to be Working after Upgrade

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1037.php
Due to categorization of absence types on sites, the need arise to ensure those categorized as _is_sick_ also have their leave requests properly categorized. This PR migrates existing sickness leave request for proper alignment.
Some non sickness leave requests are linked to sickness absence type
Non sickness leave requests are now correctly linked to sickness absence type
All sickness absence types were fetched
```
private function up1037_getSicknessAbsenceTypeId() {
$sicknessIds = [];
$absenceType = new AbsenceType();
$absenceType->is_sick = 1;
$absenceType->find();
while ($absenceType->fetch()) {
$sicknessIds[] = $absenceType->id;
}
return $sicknessIds;
}
```
and their ids used to match sickness leave requests whose request type is not yet `sickness`
```
private function …
```
=> PCHR-4350: Existing Sickness Leave Request Migration

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/Search/StaffDirectory.php
This PR fixes an issue with the Staff directory page not opening the results page with current staff selected by default. 
- All staff is selected rather than current staff when the Staff directory page is opened and all staff are listed in the results page.
The URL for the staff directory page looks like this: `civicrm/contact/search/custom?csid=16&force=1&reset=1&select_staff=current` and its supposed to add the URL parameters to the form parameters however this does not work as expected. This PR refactors the function responsible for adding the URL parameters to the form parameters.
Only current staff are selected and listed in the results page.
=> PCHR-4370: Fix Issue with Staff Directory Page Not Listing Current Staff By Default

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/Links/ContactCustomActions.php
This PR adds the View and Edit actions to the list of available actions for an individual contact on the Staff directory results page.
- The View and Edit actions were not in the list of available actions.
- The View and Edit actions was added to the list of available actions.
=> PCHR-4369: Add View and Edit To Individual Contact Actions on Staff Directory Page

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/BuildForm/ActivityFilterSelectFieldsModifier.php, uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/BuildForm/ActivityLinksFilter.php
#2444 , modifies the communications tab to restrict what activities can be added and what activities to filtered by.  
This PR adds the meeting activity back to the list of un-restricted activities, i.e it allows to add a meeting Activity from the communications tab and also to filter meeting activity types.
- The meeting activity can not be added neither can it be filtered by in the communications tab.
- A meeting activity (Record Meeting) can now be added, also the Meeting activity is now among the list of activity filters.
=> PCHR-4380: Allow meeting activity and filter by meeting activity.

com.civicrm.hrjobroles/CRM/Hrjobroles/Upgrader.php, com.civicrm.hrjobroles/xml/option_groups/organisation_provider_install.xml
For setting up job role funder, organisation contact records were created for such. This PR creates an option group for the purpose of managing funders list.
There were no option group for managing job role funders.
An option group is created for managing list of funders.
An XML file was created for setting up funders option groups. This was then installed by an upgrader, creating the required option group in the process.
```
if ($result['count'] === 0) {
$file = 'xml/option_groups/organisation_contact_install.xml';
$this->executeCustomDataFile($file);
}
```
=> PCHR-4328: Create Option Groups for Organization Contact in Job Role

uk.co.compucorp.civicrm.hrcore/config/menu/configure.php
New options groups were added in [#2919](https://github.com/compucorp/civihr/pull/2919) and [#2920](https://github.com/compucorp/civihr/pull/2920). This PR creates a link to each option group page in the configure menu . The option groups are Health Insurance Provider, Life Insurance Provider, Pension Provider and Funder (for job roles).
The configure file was updated with link to each of the added option groups
```
...
'Health Insurance Providers' => [
...
],
'Life Insurance Providers' => [
...
],
'Pension Providers' => [
...
],
...
'Funders' => [
...
],
```
=> PCHR-4335: Link Option Group to Configure Menu

uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Service/Stats/StatsGathererTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/sql/auto_install.sql, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsencePeriodTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsenceTypeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlementTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/PublicHolidayTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/AbsenceTypeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/EntitlementCalculationTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreationTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestDeletionTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeavePeriodEntitlementTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/PublicHolidayTest.php
On a fresh CiviHR installation, we need to create two leave periods automatically (current and next). It  works in following manner:
- Create a leave period from start of the year to the end of year. E.g. i.e. if today is 5/8/2018, it's created  for 1/1/2018 - 31/12/2018.
- Create a leave period for the next year, i.e., 1/1/2019 - 31/12/2019
- Default absence periods are not created for new CiviHR installations
- Default absence periods are now created for new CiviHR installations
=> PCHR-4366: Add Default Absence periods for New CiviHR installations.

com.civicrm.hrjobroles/xml/option_groups/organisation_provider_install.xml
Option group was created with `Job role funder` in https://github.com/compucorp/civihr/pull/2920. This PR renamed the title to `Funder`.
Option group title for Job role is "Job Role Funder"
Option group title for Job role is "Funder"
The option group title was renamed.
=> PCHR-4328: Renamed Funder Option Group API Title

hrcase/CRM/HRCase/Upgrader.php
Some clients reported they were not able to create new Workflow types. After some investigation, we discovered that this was happening because the "Open Case" activity type was missing in these sites.
The "Open Case" activity type is missing is some sites. This prevents users from creating new Workflow types.
The "Open Case" activity type is recreated in the sites where it was missing and users can create new Workflow types.
Workflow types are nothing more than Case Types. When creating a new Case Type, civi uses a harcoded template for the Case Type definition and [this template includes the "Open Case"](https://github.com/civicrm/civicrm-core/blob/ffee3b9dc3d728ae951bff8fbc106acf7ed3cbb5/ang/crmCaseType.js#L13) by default. This is the reason users cannot create new Workflow types when …
=> PCHR-4374: Recreate missing "Open Case" activity type

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/Search/StaffDirectory.php
This PR reorders the staff directory columns to match the wireframe at https://compucorp.atlassian.net/wiki/spaces/PCHR/pages/134906300/Improve+the+Staff+menu+items
- The  search results columns are not ordered according to the wireframe.
The search results columns are ordered according to the wireframe.
- Name
- Work Email
- Work Phone
- Job Title
- Manager
- Location
- Department
- Actions
=> PCHR-4383: Reorder Staff Directory Columns

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/AbsencePeriod.php
When creating a new absence period and the user is directed to proceed to the calculate entitlements page, after the entitlements calculation is saved, the user should be redirected back to the Absence period listing page.
- The user is not redirected to absence period listing page after calculating entitlements for a new absence period.
- The user is redirected to absence period listing page after calculating entitlements for a new absence period.
=> PCHR-4385: Redirect to Absence Period Listing Page After Saving Entitlements

uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/Search/StaffDirectory.php, uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Form/Search/StaffDirectoryTest.php
When the Job contract end date filter is selected on the Staff directory page without selecting the Job contract start date, it leads to unpredictable results as contacts that does not match the job contract end date filter criteria are also displayed.
Currently, the Staff directory SQL allows contacts with contract without an end date to show up in results as long as the condition for their contract start dates are met.
For example: A staff with contract start date Jan 1, 2018 and no contract end date.
If contract start date filter is Jan 1, 2018  and contract end date filter is Today, the staff will show up in the search results.
The SQL part that takes care of this logic adds the `OR (contract_details.period_end_date IS NULL)` . If no contract start date is selected, this led to …
=> PCHR-4384: Fix Job Contract End Date Filter Bug

uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/StaffDirectoryFiltersSection.tpl
This PR fixes an issue with date range filters on the Staff Directory page.
Selectors do not flush the data inside inputs on toggling:
Selectors **do** flush the data inside inputs on toggling:
We amend the function which is triggered when date range selector is changed so it also flushes date range fields:
```js
function toggleAbsoluteDateRangeFields ($dateRangeSelector) {
// ...
if (absoluteDateRangeOptionSelected) {
$absoluteDateRange.removeClass('hidden');
} else {
$absoluteDateRange.addClass('hidden');
$absoluteDateRange.find('input').val(''); // <<< here
}
```
We also do a similar thing to the contact range selector:
```js
function toggleContractDates() {
// ...
if (selectStaffValue === 'choose_date') {
$contractDates.removeClass('hidden');
} else { …
```
=> PCHR-4398: Fix the date range filters on Staff Directory page

uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/StaffDirectory.tpl
This PR fixes the issue with selectors counter after submitting filters on Staff Directory page
The counter is not reset:
This GIF was taken from the commit before styling started:
The issue was introduced here: https://github.com/compucorp/civihr/pull/2922/commits/79b3363199680d225a3658ae5202ede63c89e2ac
The problem is that earlier the submit buttons were rendered like that:
```
{include file="CRM/common/formButtons.tpl"}
```
which produces the following markup:
```html
<span class="crm-button crm-button-type-refresh crm-button_qf_Custom_refresh crm-i-button">
<i class="crm-i fa-check"></i>
<input class="crm-form-submit default validate" crm-icon="fa-check" name="_qf_Custom_refresh" value="Search" type="submit" id="_qf_Custom_refresh">
</span>
```
There were two issues with this markup …
=> PCHR-4401: Fix selector counter after submit on Staff Directory page

uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/StaffDirectory.tpl, uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/StaffDirectoryFiltersSection.tpl, uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/Search/StaffDirectoryTopBarSection.tpl
This PR fixes the issue introduced after https://github.com/compucorp/civihr/pull/2938. The solution in the https://github.com/compucorp/civihr/pull/2938 finally worked but broke Bulk Actions selector.
See https://github.com/compucorp/civihr/pull/2938.
Now everything works:
- Filter forms reset the staff counter
- Bulk actions work as expected
It was thought that the solution in https://github.com/compucorp/civihr/pull/2938 would help to submit the `_qf_Custom_refresh`, but the problem is that is should *not always* be submitted. It should be submitted only on filters applying.
So, original markup that is used by CiviCRM was used instead:
```
<input class="btn btn-sm btn-primary" name="_qf_Custom_refresh" value="Filter" type="submit"/>
```
The "Filter" button is now smaller, this looks …
=> PCHR-4401: Fix regression with bulk actions on Staff Directory

uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Service/Stats/StatsGathererTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestRights.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestStatusMatrix.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestRightsTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestStatusMatrixTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestTest.php
Currently the Admin has the highest rights regarding leave request administration for all contacts. The Admin can create/edit/cancel/delete leave requests for all contacts. This PR makes some changes regarding the Admin's privileges regarding his own requests particularly when the Admin is not own leave approver. Basically  for own request, in situations where the Admin is not own leave approver, the Admin is treated basically like a staff as the same principles that apply to a Staff applies to Admin in this regard.
The Admin has admin rights over all leave requests including own requests.
The Admin does not have admin rights over own request when not own leave approver.
The change was implemented in the major areas for leave request administration, basically:
**Status Transitions** : The …
=> PCHR-4408: Treat Admin As Staff For Own Requests When Not Own Leave Approver

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsenceTypeTest.php
This PR fixes a regression introduced in https://github.com/compucorp/civihr/pull/2864/commits/060a945806e901e08f8f2f9382518a2338989ee5. Due to the regression it was not possible to directly enable/disable absence type.
We do not validate title if we are editing an absence type and the `title` param is not passed.
```php
private static function validateAbsenceTypeTitle($params) {
$isEditing = array_key_exists('id', $params);
$titleIsPassed = array_key_exists('title', $params);
$skipTitleValidation = $isEditing && !$titleIsPassed;
if ($skipTitleValidation) {
return;
// ...
}
```
-----
⏹Jasmine Tests - not needed
⏹JS distributive files - not needed
⏹CSS distributive files - not needed
⏹Backstop tests - not needed
✅PHP Unit Tests - added and passed
=> PCHR-4412: Fix error with a direct absence type enabling

com.civicrm.hrjobroles/CRM/Hrjobroles/Upgrader.php
When creating job roles, funders list are provided from list of contacts previously created. Having created an option group in https://github.com/compucorp/civihr/pull/2920 for managing list of funders, this PR migrates funders in existing job roles by creating option value replica and replacing funder id with that of new created option value.
Existing job role funders were pointed to contact list
Existing job role funders are linked to option value for `hrjc_funder` option group.
All existing job roles were fetched and their unique funder_id extracted. 
```
private function getFunderIds($jobRoles) {
$funderIds = [];
foreach ($jobRoles as $jobRole) {
$funders = array_values(array_filter(explode('|', $jobRole['funder'])));
$funderIds = array_merge($funderIds, $funders);
}
return …
```
=> PCHR-4330: Migrate Existing Job Role Organisation Contact

com.civicrm.hrjobroles/js/src/job-roles/controllers/job-role-panel.html
Funder tool icon implementation was previously implemented in https://github.com/compucorp/civihr/pull/2951. A display issue was introduced which was fixed by this PR.
The table header had a replication of `th` tag causing issue with the display. The extra tags were removed in this PR.
=> PCHR-4334: Fixed Display Issue with Existing Job Roles Funder

hrjobcontract/CRM/Hrjobcontract/BAO/HRJobHealth.php, hrjobcontract/CRM/Hrjobcontract/DAO/HRJobHealth.php, hrjobcontract/CRM/Hrjobcontract/DAO/HRJobPension.php, hrjobcontract/CRM/Hrjobcontract/Test/Fabricator/HRJobPension.php, hrjobcontract/CRM/Hrjobcontract/Upgrader.php, hrjobcontract/sql/install.sql, hrjobcontract/tests/phpunit/CRM/Hrjobcontract/Import/Parser/ApiTest.php
Existing organisation contacts were used for health, life and pension insurance provider. Having created an option group in https://github.com/compucorp/civihr/pull/2919 for managing list of providers, this PR migrates providers in existing job roles by creating option value replica.
Providers in organisation contact were not migrated to option value for their respective option group
Providers which are previously in contact are migrated to option value for their respective option group.
The install file in [hrjobcontract](https://github.com/compucorp/civihr/blob/master/hrjobcontract/sql/install.sql) was manually modified to remove the contact constraint on `civicrm_hrjobcontract_pension` and `civicrm_hrjobcontract_health`. This was due lack of proper integration with CiviCRM GenCode …
=> PCHR-4329: Migrate existing organisation contact

hrjobcontract/CRM/Hrjobcontract/Upgrader.php
Migration of existing organisation contact was previously implemented in https://github.com/compucorp/civihr/pull/2959. A build error for existing site was introduced there which this PR fixes. 
A CIVICRM api error was generated while upgrading existing site. 
No API error was generated while upgrading site.
The upgrader initially modifies table column and then check if any column restriction exit before attempting to remove affected foreign keys. The constraint restriction check was put in place to cater for new sites which do not have the foreign keys. Due to the constraints, an API error was thrown while modifying the columns on existing sites before foreign key constraints were removed. 
The order of implementation was therefore changed to ensure restrictions were removed (if present) …
=> PCHR-4329: Fix build issue on existing sites with foreign key constraints

hrjobcontract/CRM/Hrjobcontract/Upgrader.php
Migration of contacts was previously implemented in https://github.com/compucorp/civihr/pull/2959. This PR separates removal of `pension_type_contact_id_fk` and `pension_type` column modification due to API Error.
Deployment raises db error when `pension_type_contact_id_fk` foreign key does not exist.
Deployment runs smoothly.
When running upgrade, dropping foreign key and modifying the column results in an error when foreign key does not exist on a site db. The previous implementation was therefore updated to ensure foreign key was first removed (if present) before going ahead with column modification.
=> PCHR-4329: Separated constraint checks on pension from column modification

org.civicrm.bootstrapcivihr/scss/overrides/_variables.scss
The `org.civicrm.shoreditch/base/scss/overrides/_variables.scss` partial had been removed from Shoreditch (see above PR for additional details), so we need to remove its reference in the `org.civicrm.bootstrapcivihr` sass codebase
**Note:** the `gulp sass` task had been executed on every CiviHR extension and in the SSP theme, and as expected no changes in the minified css files had been detected
**Note 2:** a different ticket to track the fork syncing was created after the branch of this PR had already been created, hence the reason the branch name is referencing a different ticket number
=> PCHR-4445: Remove reference to deleted partial

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/WorkPattern.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/ContactWorkPatternTest.php
On sites running on PHP 7.2, the following warning is displayed when accessing the Work Patterns list page:
```
Warning: A non-numeric value encountered in CRM_HRLeaveAndAbsences_BAO_WorkPattern->getNumberOfHours() (line 249 of /var/www/master-php7.civihr.net/httpdocs/sites/all/modules/civicrm/tools/extensions/civihr/uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/WorkPattern.php).
```
The error was being thrown by the method used to calculate the total number of working hours for each work pattern. It does that by summing the `number_of_hours` for each Work Day of each Work Week in the pattern. For non-working days, the `number_of_hours` field will an empty string, which is not a numeric value, hence the warning.
To fix it, the make sure of converting the values …
=> PCHR-4426: Fix warning on the Work Patterns list page

hrjobcontract/api/v3/HRJobContract.php
When accessing the My Details page, as a user with an active contract, the following warning would be displayed:
The warning was displayed on the SSP
The warning is not displayed anymore
The reason for the warning is that we were trying to use a null variable as an object. So, my first attempt to fix this was to replace the `$return = null` with a `$return = new stdClass`. 
That worked, however I realized that this API was returning an object rather than an array, which is what CiviCRM APIs usually return. This is confusing, so instead of initializing the object, I decided to change the response format to an array.
For clients using the API via JS, this change in the format won't affect anything, as both an object and an array will be converted to a JS object. However, this does affect …
=> PCHR-4396: Fix "creating default object from empty value" warning on the SSP

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/GeneralSettings.php
After the upgrade to PHP 7, some notices and errors started appearing on L&A settings page. The settings form itself would not load:
```
Notice: Array to string conversion in CRM_HRLeaveAndAbsences_Form_GeneralSettings->buildQuickForm() (line 31 of /sites/all/modules/civicrm/tools/extensions/civihr/uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/GeneralSettings.php).
Notice: Undefined property: CRM_HRLeaveAndAbsences_Form_GeneralSettings::$Array in CRM_HRLeaveAndAbsences_Form_GeneralSettings->buildQuickForm() (line 31 of /sites/all/modules/civicrm/tools/extensions/civihr/uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/GeneralSettings.php).
Error: Function name must be a string in CRM_HRLeaveAndAbsences_Form_GeneralSettings->buildQuickForm() …
```
=> PCHR-4441: Fix errors on the L&A settings page

uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/AbsenceType.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChange.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreation.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestDeletion.php, uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/PublicHolidayLeaveRequest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/AbsenceTypeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestCreationTest.php, uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/PublicHolidayLeaveRequestDeletionTest.php
Due to recent changes that allows more than one Absence type to have the MTPHL property as true (see: #2964). This PR makes changes to the background job that creates these public holiday leave requests to accommodate creating public holiday leave requests for as many absence types that have MTPHL as true.
- The scheduled job that is responsible for creating public holiday leave requests will only create public holiday leave requests for only one absence type with MTPHL as true for contacts.
- The scheduled job that is responsible for creating public holiday leave requests will create public holidays for as many absence types with MTPHL as true for contacts.
- Apart from modifying the `PublicHolidayLeaveRequestCreation` class to now fetch all absence types with MTPHL using the new …
=> PCHR-4432:  Add support for creation of Public Holiday Requests for Absence Types with MTPHL Via Background Job

uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php
When adding a new absence type or updating an existing absence type, a warning is shown on the screen after saving. 
- The error `Parameter 3 to _hrleaveandabsences_civicrm_post_absencetype() expected to be a reference, value given in hrleaveandabsences_civicrm_post()` is shown on the screen when adding a new absence type or modifying an existing absence type.
- No error is shown on the screen when adding a new absence type or modifying an existing absence type.
The `_hrleaveandabsences_civicrm_post_absencetype` function as well as the 
other`_hrleaveandabsences_civicrm_post_*`  functions expects the `$objectRef` variable passed to be passed as a reference but it was passed by value instead. This warning shows on sites running PHP versions 5.6.38 upwards as seen …
=> PCHR-4446: Fix Expected Variable Reference Warning

hrjobcontract/CRM/Hrjobcontract/Import/Parser.php, hrjobcontract/CRM/Hrjobcontract/Import/Parser/Api.php, hrjobcontract/CRM/Hrjobcontract/Import/Parser/BaseClass.php
When trying to import Job contracts on a site running PHP 7.2.X. Some warnings occur on the various stages of the import screen.
- Some errors on the various stages of the Job contract import screen.
- One of the errors was related to an error regarding using count function on a variable that does not implement the Countable interface. This warning is displayed by PHP starting from PHP 7.2.
The [here](https://github.com/compucorp/civihr/blob/fb73df3b053bec0bcbadc5f9362704cc14ab8b15/hrjobcontract/CRM/Hrjobcontract/Import/Parser/BaseClass.php#L88) returns NULL sometimes and an error is thrown when using count on the variable h[ere](https://github.com/compucorp/civihr/blob/fb73df3b053bec0bcbadc5f9362704cc14ab8b15/hrjobcontract/CRM/Hrjobcontract/Import/Parser.php#L319). This was fixed by …
=> PCHR-4448: Fix Warning and Notice Messages on Import Job Contract Wizard

uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/partials/staff-leave-report-section-header.html, uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/staff-leave-report.html
This PR fixes 2 issues for grouped Public Holidays on Staff Leave Report:
1) It now renders zero balance changes correctly
2) It now does not show action dropdown for Public Holidays for Staff (because it anyway does not have any actions inside) and hides the group view switch.
In SSP My Leave you can see an empty actions dropdown.
In CIviCRM you can see missing zero balances (see After to see the difference)
No switch and dropdown on SSP:
Zeros are rendered correctly in CiviCRM:
To render zeroes we need to compare a balance prop against `undefined`: 
```html
request.types_to_balance_changes[absenceType.id] !== undefined
```
To hide actions dropdown and the group view switch we simply check for `$root.section !== 'my-leave'"`.
-----
⏹Jasmine Tests - no changes
⏹JS …
=> PCHR-4471: Fix issues for grouped Public Holidays on Staff Leave Report

com.civicrm.hrjobroles/CRM/Hrjobroles/DAO/HrJobRoles.php, com.civicrm.hrjobroles/CRM/Hrjobroles/Upgrader.php
When making request via Contact API, response usually contains job role id if the requested contact has existing job role. This was because job role id is [exportable](https://github.com/compucorp/civihr/blob/master/com.civicrm.hrjobroles/CRM/Hrjobroles/DAO/HrJobRoles.php#L273) and its key [overrides](https://github.com/civicrm/civicrm-core/blob/master/CRM/Contact/BAO/Query.php#L487) that of contact id when loading contact details. 
This process also have effect on adding funder to individual contact type. Instead of saving contact id of the funder, funder's job role id was used in place of its contact id if contact happens to have existing job role.
Contact API request returns funder id instead of contact id when contact have an existing job role.
Contact API request returns contact id …
=> PCHR-4444: Funders of Type Individual is not saved with the correct Contact ID

hrjobcontract/CRM/Hrjobcontract/BAO/HRJobHour.php
When Importing a job contract, on the last screen after the import has completed, a notice is displayed.
When Importing a job contract, on the last screen after the import has completed, a notice is displayed : `Notice: Undefined index: role_revision_id in CRM_Hrjobcontract_BAO_HRJobHour::create() 
(line 63 of /var/www/master-php7.civihr.net/httpdocs/sites/all/modules/civicrm/tools/extensions/civihr/hrjobcontract/CRM/Hrjobcontract/BAO/HRJobHour.php)`
The call to return an [HRJobHourInstance](https://github.com/compucorp/civihr/blob/1f3ff3fdb74d768b4e97c2b8e917edb250b97d95/hrjobcontract/CRM/Hrjobcontract/BAO/HRJobHour.php#L48-L53), returns NULL because the API call is wrapped in a transaction and the details is not yet available until the API call is done. Hence, subsequent calls to get …
=> PCHR-4460: Fix 'Undefined index: role_revision_id' Error In Job Contract Import Screen
