- uk.co.compucorp.civicrm.appraisals/CRM/Appraisals/DAO/Appraisal.php
- uk.co.compucorp.civicrm.appraisals/CRM/Appraisals/DAO/AppraisalCycle.php
- uk.co.compucorp.civicrm.appraisals/CRM/Appraisals/Form/Report/Report.php
- uk.co.compucorp.civicrm.appraisals/CRM/Appraisals/Upgrader.php
Adding 'cycle_is_active' field for AppraisalCycle entity. The field can take tinyint "0" / "1" value (default is "1").
> PCHR-776 - adding 'cycle_is_active' field for AppraisalCycle entity.

- uk.co.compucorp.civicrm.appraisals/CRM/Appraisals/BAO/AppraisalCycle.php
- uk.co.compucorp.civicrm.appraisals/api/v3/AppraisalCycle.php
Adding two custom API calls for AppraisalCycle entity.
//// 1. Getting distribution of cycle's appraisals by step:
// Returns the number of appraisals belonging to the specific Appraisal Cycle ID,
// distributed by step.
// JavaScript usage example:
```javascript
CRM.api3('AppraisalCycle', 'getappraisalsperstep', {
"sequential": 1,
"appraisal_cycle_id": 1,  // required
"include_appraisals": 1   // optional, default = 0
}).done(function(result) {
// do something
});
```
// response example:
```javascript
{
"is_error":0,
"version":3,
"count":2,
"values":[{
"status_id":"1",
"status_name":"Awaiting self appraisal",
"appraisals_count":"3",
"appraisals":[{  // "appraisals" array appear only when passing "include_appraisals" = 1
// appraisal 1
},
{
// appraisal 2
},
{
// appraisal 3
}]
},
{ …
```
> Pchr 777 custom calculation api calls

- hrjobcontract/CRM/Hrjobcontract/Import/FieldsProvider.php
- hrjobcontract/CRM/Hrjobcontract/Import/FieldsProvider/Generic.php
- hrjobcontract/CRM/Hrjobcontract/Import/FieldsProvider/HRJobRole.php
- hrjobcontract/CRM/Hrjobcontract/Import/Form/MapFieldBaseClass.php
- hrjobcontract/CRM/Hrjobcontract/Import/Parser.php
- hrjobcontract/CRM/Hrjobcontract/Import/Parser/Api.php
Added headers in the selects in "MapField" step of job contract import.
> PCHR-823: differentiated fields from different entities in the UI

- hrjobcontract/CRM/Hrjobcontract/DAO/HRJobDetails.php
- hrjobcontract/CRM/Hrjobcontract/Import/Parser/Api.php
Now the required fields are checked correctly, and if they're missing an error is reported.
> PCHR-517: Fixed handling of required fields

- hrabsence/api/v3/Activity/Getabsences.php
- hrabsence/js/app.js
This PR removes the "cancelled" leaves from Calendars.
> PCHR-817: cancelled leaves on calendar

- uk.co.compucorp.civicrm.appraisals/js/karma.conf.js
- uk.co.compucorp.civicrm.appraisals/js/test/globals.js
- uk.co.compucorp.civicrm.appraisals/js/test/test-main.js
The test environments are being set up in the other angular apps, this PR standardizes the test environment of the Appraisals app, so that it matches how things are done in the other apps
> PCHR-839: Setup test environment (Appraisals)

- hrjobcontract/CRM/Hrjobcontract/BAO/HRJobContract.php
- hrjobcontract/CRM/Hrjobcontract/Import/EntityHandler/HRJobDetails.php
- hrjobcontract/CRM/Hrjobcontract/Import/Parser/Api.php
Marks contract that is current as primary
> PCHR-806: Properly handle primary contracts on import

- hrjobcontract/hrjobcontract.php
Replace location values with Location Labels in search results
> PCHR-816: Replace location values with Location Labels in search results

- com.civicrm.hrjobroles/CRM/Hrjobroles/BAO/HrJobRoles.php
When trying to import  job roles the following error appear for all the records :
> PCHR-868: Fix a bug that prevent importing any job role

- com.civicrm.hrjobroles/js/dist/job-roles.min.js
- com.civicrm.hrjobroles/js/src/job-roles/controllers/hr-job-roles-controller.js
- com.civicrm.hrjobroles/js/src/job-roles/services/hr-job-roles-service.js
> Revert "PCHR-505 Empty dates save fix"

- com.civicrm.hrjobroles/CRM/Hrjobroles/BAO/Query.php
- com.civicrm.hrjobroles/hrjobroles.php
- com.civicrm.hrjobroles/templates/CRM/Hrjobroles/Form/Search/Criteria/JobRole.tpl
A new panel was added to the Avanced Search, containing
all of the Job Role fields.
This is what the panel looks like:
> PCHR-889: Add Job Role fields in Advanced Search

- uk.co.compucorp.civicrm.appraisals/CRM/Appraisals/BAO/Appraisal.php
- uk.co.compucorp.civicrm.appraisals/CRM/Appraisals/Upgrader.php
I've created a new 'validateNewAppraisal()' static method which is executed every time we try to create new Appraisal. The method check for some requirements plus there is a new one which checks if there is already existing Appraisal for given Contact and Cycle ID.
We assume that Contact can have only single Appraisal per Cycle so if there is already current Appraisal existing for given Contact and Cycle then an exception is thrown.
> PCHR-871-creating-additional-BAO-appraisal-validation-method

- uk.co.compucorp.civicrm.hrleaveandabsences/LICENSE.txt
- uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.civix.php
- uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php
- uk.co.compucorp.civicrm.hrleaveandabsences/info.xml
This creates only the extension skeleton with basic hooks implementations
to define the extension's menu items.
None of the links/pages the menu items point to are yet implemented.
These are the new menus:
> PCHR-943: Create Leave and Absences extension

- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/AbsenceType.php
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/AbsenceType.php
- uk.co.compucorp.civicrm.hrleaveandabsences/sql/auto_install.sql
- uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/AbsenceType.tpl
- uk.co.compucorp.civicrm.hrleaveandabsences/xml/Menu/hrleaveandabsences.xml
- uk.co.compucorp.civicrm.hrleaveandabsences/xml/schema/CRM/HRLeaveAndAbsences/AbsenceType.xml
The Leave/Absences types list is accessible only by the manager and it lists all the available types. Each type may have a different set of actions available, according to if it is reserved, default and/or enabled.
> PCHR-903: Create Leaves/Absences list view

- hrjobcontract/views/modalForm.html
"Contract end reason" filed is now moved below "Contract End Date" instead of "Contract Duration" field.
> PCHR-841 - Moving input field under Contract end date field instead of Contract Duration.

- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/WorkDay.php
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/WorkPattern.php
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/WorkWeek.php
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/WorkDay.php
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/AbsenceType.php
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/WorkPattern.php
- uk.co.compucorp.civicrm.hrleaveandabsences/hrleaveandabsences.php
- uk.co.compucorp.civicrm.hrleaveandabsences/js/hrleaveandabsences.js
- uk.co.compucorp.civicrm.hrleaveandabsences/sql/auto_install.sql
- uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/AbsenceType.tpl
- uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/WorkPattern.tpl
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/WorkDayTest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/WorkPatternTest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/xml/Menu/hrleaveandabsences.xml
- uk.co.compucorp.civicrm.hrleaveandabsences/xml/schema/CRM/HRLeaveAndAbsences/WorkDay.xml
This PR adds the Work Patterns list page:
> PCHR-907: Work Patterns list page

- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/WorkPattern.php
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Form/WorkPattern.php
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/WorkPattern.php
- uk.co.compucorp.civicrm.hrleaveandabsences/css/hrleaveandabsences.css
- uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/AbsenceType.tpl
- uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/WorkPattern.tpl
- uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/WorkPattern/Details.tpl
- uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/WorkPattern.tpl
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/WorkPatternTest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/WebTest/WorkPattern/FormTest.php
This is the first part of the Work Pattern form. At this point,
it only contains the Detail tab form. 
This is how the form looks like:
> PCHR-946: Add the Work Pattern form with Detail tab

- uk.co.compucorp.civicrm.hrleaveandabsences/xml/auto_install.xml
This option list will be used by the "Leaves Days" field,
on the calendar tab of the WorkPattern form (will be
add on another PR)
> PCHR-906: Add the Leaves Days Amounts options list

- hrcase/hrcase.php
1. Detection of activity being created by tasks and assignments or not.
2. Passing component_id in api call so it returns single value only.
> PCHR-1016: Resolve conflict between hrcase and T and A

- hrjobcontract/hrjobcontract.php
**Issue:**
Contract type is an option group which has multiple options. Every options has a value and a label, eg:
```
| Value      	| Label      
|------------	|------------	
| Contractor 	| Contractor 
| 1          	| Fixed Term
```
When exporting "Contract type" of contacts, The "value" was getting exported instead of "labels".
**Solution:**
Before export, CiviCRM creates a $exportTempTable. Replace the values with respective labels in $exportTempTable using SQL UPDATE query.
> PCHR-1080: changes to export contract type labels instead of values

- hrstaffdir/xml/auto_install.xml
https://github.com/civicrm/civihr/pull/953
> PCHR-1150: installing org.civicrm.hrstaffdir throwing an error

- hrcase/hrcase.php
https://github.com/civicrm/civihr/pull/961
> PCHR-1151: Unset already exist case types in hrcase extenison

- hrjobcontract/CRM/Hrjobcontract/BAO/HRJobLeave.php
- hrjobcontract/CRM/Hrjobcontract/DAO/HRJobLeave.php
- hrjobcontract/CRM/Hrjobcontract/Upgrader.php
The future changes to the add/edit contract form will allow the admin to
control if  the number of public holidays should be added to a leave
entitlement. This information will be stored in this new field.
> PCHR-1111: Add the add_public_holidays field to the HRJobLeave

- hrcase/hrcase.php
Related to https://github.com/compucorp/civihr-tasks-assignments/pull/69
> PCHR-1191: Remove joining & exiting case types from T&A extension

- hrcase/xml/case/Appraisal.xml
- hrcase/xml/case/Exiting.xml
- hrcase/xml/case/Joining.xml
- hrcase/xml/case/Probation.xml
I've updated the standard timeline and activity types for build-in case types according to this wiki page :
https://compucorp.atlassian.net/wiki/pages/viewpage.action?pageId=75857955
> PCHR-459: Update standard timeline and activity types for built-in case types

- uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/AbsenceType.tpl
> PCHR-911: Add a label to the Actions column of the absence type list

- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/WorkPattern.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/WebTest/WorkPattern/FormHelpersTrait.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/WebTest/WorkPattern/FormTest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/WebTest/WorkPattern/ListTest.php
> PCHR-914: Show no. of hours as "Various" when work pattern has more than 1 week

- hrcase/README.md
- hrcase/hrcase.php
Original PR : https://github.com/civicrm/civihr/pull/1020
> PCHR-1263: ensure hrcase dependency on T&A

- uk.co.compucorp.civicrm.hrleaveandabsences/xml/option_groups/leave_request_status_install.xml
This PR adds a new option list that contains the valid statuses for a Leave Request (still not implemented). All the values are reserved. The available values are:
- Approved
- Admin Approved
- Waiting Approval
- More Information Requested
- Rejected
- Cancelled
> PCHR-1344: Add the Leave Request Status option list

- uk.co.compucorp.civicrm.hrleaveandabsences/xml/option_groups/leave_request_day_type_install.xml
This PR adds a new option list that contains the valid types for the from_date_type and to_date_type of the Leave Request (still not implemented). All the values are reserved. The available values are:
- All day
- 1/2 AM
- 1/2 PM
- Weekend
- Non Working Day
- Public Holiday
> PCHR-1345: Add the Leave Request Day Type option list

- hrui/hrui.php
original ticket https://github.com/civicrm/civihr/pull/1025
> PCHR-1327: Disable CiviReport

- org.civicrm.reqangular/reqangular.php
> PCHR-1278: Do not inject civihr angular in angular-based core pages

- com.civicrm.hrjobroles/CRM/Hrjobroles/BAO/HrJobRoles.php
- com.civicrm.hrjobroles/CRM/Hrjobroles/DAO/HrJobRoles.php
- com.civicrm.hrjobroles/CRM/Hrjobroles/Import/Form/DataSource.php
- com.civicrm.hrjobroles/CRM/Hrjobroles/Import/Parser/HrJobRoles.php
- com.civicrm.hrjobroles/js/src/job-roles/controllers/hr-job-roles-controller.js
- com.civicrm.hrjobroles/tests/phpunit/CRM/Hrjobroles/BAO/HrJobRolesTest.php
- com.civicrm.hrjobroles/tests/phpunit/CRM/Hrjobroles/Import/Parser/HrJobRolesTest.php
- com.civicrm.hrjobroles/tests/phpunit/HrJobRolesTestBase.php
- com.civicrm.hrjobroles/tests/phpunit/api/v3/HrJobRolesTest.php
- com.civicrm.hrjobroles/xml/schema/CRM/Hrjobroles/HrJobRoles.xml
original PRs :
https://github.com/civicrm/civihr/pull/1032
https://github.com/civicrm/civihr/pull/1052
which get reverted to by :
https://github.com/civicrm/civihr/pull/1055
https://github.com/civicrm/civihr/pull/1056
> PCHR-1340:  job role import and form errors

- hrjobcontract/CRM/Hrjobcontract/ExportImportValuesConverter.php
when exporting a job contract , the (change reason) should be exported as a label instead of as a value.
> PCHR-799: convert (change reason) options to export label instead of value

- hrjobcontract/js/src/job-contract/controllers/contract.js
https://github.com/civicrm/civihr/pull/1065
> UY-51 - Fixing of fetching Job Contract entities (pay and health).

- hrjobcontract/CRM/Hrjobcontract/BAO/Query.php
Changing two checks for past and future revisions to a single one using end of revision's effective date.
> PCHR-1080 - SQL query changing for Revision join.

- uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Form/AbsenceType.tpl
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/WebTest/AbsenceType/FormTest.php
This PR applies the changes in https://github.com/civicrm/civihr/pull/1089 to the 1.7-develop branch.  The other fixes for this ticket were already merged to the develop branch before the "deploy feature branch" workflow, hence we still need to use the old approach here.
> PCHR-898: Fix the visibility of the "Expire after certain duration" dropdown

- hrui/hrui.php
- hrui/js/hrui.js
**Before**
**After**
Also refactored the code a bit as well
> PCHR-1477: Remove Cases tab if T&A is enabled

- hrjobcontract/CRM/Hrjobcontract/Upgrader.php
- hrjobcontract/hrjobcontract.php
I created a new upgrader method to remove ( Job contract Report ) menu item if it exist , and also updated the existing upgrader ( upgrade_1017) so it doesn't get created at all for new installations .
> PCHR-1516: Remove (Job Contract Report) menu item

- hrjobcontract/js/src/job-contract/controllers/form/form-hour.js
- hrjobcontract/js/test/controllers/form/form-hour_test.js
This PR fix the issue on Job contract hours form, the `Actual hours` should always change based on the selection in the `Hours Type` dropdown.
Also it was changed the line break type from `CR` to `LF` on `hrjobcontract/js/src/job-contract/controllers/form/form-hour.js`.
***Before***
***After***
> PCHR-854: Fix actual hours

- com.civicrm.hrjobroles/info.xml
- contactaccessrights/info.xml
- contactsummary/info.xml
- hrabsence/info.xml
- hrbank/info.xml
- hrcareer/info.xml
- hrcase/info.xml
- hrdemog/info.xml
- hrident/info.xml
- hrim/info.xml
- hrjobcontract/info.xml
- hrmed/info.xml
- hrprofile/info.xml
- hrqual/info.xml
- hrrecruitment/info.xml
- hrreport/info.xml
- hrsampledata/info.xml
- hrstaffdir/info.xml
- hrui/info.xml
- hrvisa/info.xml
- org.civicrm.bootstrap/info.xml
- org.civicrm.bootstrapcivicrm/info.xml
- org.civicrm.bootstrapcivihr/info.xml
- org.civicrm.hremergency/info.xml
- org.civicrm.reqangular/info.xml
- org.civicrm.styleguide/info.xml
- uk.co.compucorp.civicrm.hrnavigation/info.xml
> PCHR-1545: Update version, compatibility and release date for all CiviHR extensions

- com.civicrm.hrjobroles/info.xml
- contactaccessrights/info.xml
- contactsummary/info.xml
- hrabsence/info.xml
- hrbank/info.xml
- hrcareer/info.xml
- hrcase/info.xml
- hrdemog/info.xml
- hrident/info.xml
- hrim/info.xml
- hrjobcontract/info.xml
- hrmed/info.xml
- hrprofile/info.xml
- hrqual/info.xml
- hrrecruitment/info.xml
- hrreport/info.xml
- hrsampledata/info.xml
- hrstaffdir/info.xml
- hrui/info.xml
- hrvisa/info.xml
- org.civicrm.bootstrapcivihr/info.xml
- org.civicrm.hremergency/info.xml
- org.civicrm.reqangular/info.xml
- uk.co.compucorp.civicrm.hrnavigation/info.xml
> PCHR-1545: Update version and release date for all CiviHR extensions

- com.civicrm.hrjobroles/info.xml
- contactaccessrights/info.xml
- contactsummary/info.xml
- hrabsence/CRM/HRAbsence/Form/AbsenceRequest.php
- hrabsence/info.xml
- hrbank/info.xml
- hrcareer/info.xml
- hrcase/info.xml
- hrdemog/info.xml
- hrident/info.xml
- hrim/info.xml
- hrjobcontract/info.xml
- hrmed/info.xml
- hrprofile/info.xml
- hrqual/info.xml
- hrrecruitment/info.xml
- hrreport/info.xml
- hrsampledata/info.xml
- hrstaffdir/info.xml
- hrui/info.xml
- hrvisa/info.xml
- org.civicrm.bootstrapcivihr/info.xml
- org.civicrm.hremergency/info.xml
- org.civicrm.reqangular/info.xml
- uk.co.compucorp.civicrm.hrnavigation/info.xml
Pull requests on this merge:
@davialexandre
- PCHR-1545: Update version and release date for all CiviHR extensions
> Sync master with staging

- org.civicrm.bootstrapcivicrm/bootstrapcivicrm.php
This PR makes the checkboxes to finish tasks visible again, on tasks and assignments dashboard.
> PCHR-1567: adding missing script

- org.civicrm.bootstrapcivicrm/js/radio-checkbox.js
**Issue**
The checkboxes in the Tasks & Assignments are missing.
This PR makes the checkboxes in the Tasks & Assignments visible again.
**before**
**after**
> PCHR-1567: fixing checkboxes

- hrjobcontract/CRM/Hrjobcontract/Import/Parser/Api.php
- hrjobcontract/tests/phpunit/CRM/Hrjobcontract/Import/Parser/ApiTest.php
When Importing a contract with end date but without contract end reason , an error should appear in the result spreadsheet and the contract should not be imported .
> PCHR-1407: Importing contract with end date but without end reason should fail

- com.civicrm.hrjobroles/info.xml
- contactaccessrights/info.xml
- contactsummary/info.xml
- hrabsence/info.xml
- hrbank/info.xml
- hrcareer/info.xml
- hrcase/info.xml
- hrdemog/info.xml
- hrident/info.xml
- hrim/info.xml
- hrjobcontract/info.xml
- hrmed/info.xml
- hrprofile/info.xml
- hrqual/info.xml
- hrrecruitment/info.xml
- hrreport/info.xml
- hrsampledata/info.xml
- hrstaffdir/info.xml
- hrui/info.xml
- hrvisa/info.xml
- org.civicrm.bootstrapcivihr/info.xml
- org.civicrm.hremergency/info.xml
- org.civicrm.reqangular/info.xml
> PCHR-1629: Update extensions' version and release date

- bin/git-release.sh
- com.civicrm.hrjobroles/info.xml
- contactaccessrights/info.xml
- contactsummary/info.xml
- hrabsence/info.xml
- hrbank/info.xml
- hrcareer/info.xml
- hrcase/info.xml
- hrdemog/info.xml
- hrident/info.xml
- hrim/info.xml
- hrjobcontract/info.xml
- hrmed/info.xml
- hrprofile/info.xml
- hrqual/info.xml
- hrrecruitment/info.xml
- hrreport/info.xml
- hrsampledata/info.xml
- hrstaffdir/info.xml
- hrui/info.xml
- hrvisa/info.xml
- org.civicrm.bootstrapcivihr/info.xml
- org.civicrm.hremergency/info.xml
- org.civicrm.reqangular/info.xml
- uk.co.compucorp.civicrm.appraisals/info.xml
- uk.co.compucorp.civicrm.hrcore/info.xml
- uk.co.compucorp.civicrm.hrleaveandabsences/info.xml
> PCHR-1701: Update extensions' version and release date

- hrabsence/CRM/HRAbsence/BAO/HRAbsenceType.php
Triggering 'delete' action on HRAbsenceType entity when deleting Absence Type.
> PCHR-1646 - Implementing post hook on deleting absence type.

- com.civicrm.hrjobroles/info.xml
- contactaccessrights/info.xml
- contactsummary/info.xml
- hrabsence/info.xml
- hrbank/info.xml
- hrcareer/info.xml
- hrcase/info.xml
- hrdemog/info.xml
- hrident/info.xml
- hrim/info.xml
- hrjobcontract/info.xml
- hrmed/info.xml
- hrprofile/info.xml
- hrqual/info.xml
- hrrecruitment/info.xml
- hrreport/info.xml
- hrsampledata/info.xml
- hrstaffdir/info.xml
- hrui/info.xml
- hrvisa/info.xml
- org.civicrm.bootstrapcivihr/info.xml
- org.civicrm.hremergency/info.xml
- org.civicrm.reqangular/info.xml
- uk.co.compucorp.civicrm.appraisals/info.xml
- uk.co.compucorp.civicrm.hrcore/info.xml
- uk.co.compucorp.civicrm.hrleaveandabsences/info.xml
> PCHR-1702: Bump version to 1.6.4

- .idea/codeStyleSettings.xml
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlement.php
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/LeavePeriodEntitlement.php
- uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeavePeriodEntitlement.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlementTest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeavePeriodEntitlementTest.php
Created the LeavePeriodEntitlement API to get the balances for one LeavePeriodEntitlement or a Set of LeavePeriodEntitlements deending on the parameters passed in i.e either  the Entitlement ID to get the balance for a singe LeaveEntitlementPeriod or a combination of the Contact ID and Absence Period ID to get the balances for one or more LeavePeriodEntitlements within the absence period.
Added Unit tests for getFutureBalance function of LeaveEntitlementBAO
> PCHR-1132 Created an API to get remainder of a LeaveEntitlement(s)

- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChange.php
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlement.php
- uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeavePeriodEntitlement.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeavePeriodEntitlementTest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeavePeriodEntitlementTest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/LeaveBalanceChangeHelpersTrait.php
**Created LeavePeriodEntitlement.getBreakdown API endpoint**
The API returns all of its leave balance changes for a LeavePeriodEntitlement when an entitlement_id is passed or leave balance changes for a set of LeavePeriodEntitlement when contact_id + period_id is passed to the API.
The API can be called from PHP like this with entitlement id: 
```php
civicrm_api3('LeavePeriodEntitlement', 'getbreakdown', array(
'entitlement_id' => 1,
));
```
**Sample Return values: **
```json
{
"is_error": 0,
"version": 3,
"count": 1,
"id": 0,
"values": [
{
"id": "1",
"breakdown": [
{
"amount": "3.50",
"expiry_date": null,
"type": {
"id": 1,
"value": "leave",
"label": "Leave"
}
},
{
"amount": "4.00",
"expiry_date": null,
"type": {
"id": 2,
"value": "brought_forward",
"label": "Brought …
```
> PCHR-1123 Created API Endpoint:  LeavePeriodEntitlement.getBreakdown

- bin/git-release.sh
- com.civicrm.hrjobroles/info.xml
- contactaccessrights/info.xml
- contactsummary/info.xml
- hrabsence/info.xml
- hrbank/info.xml
- hrcareer/info.xml
- hrcase/info.xml
- hrdemog/info.xml
- hrident/info.xml
- hrim/info.xml
- hrjobcontract/info.xml
- hrmed/info.xml
- hrprofile/info.xml
- hrqual/info.xml
- hrrecruitment/info.xml
- hrreport/info.xml
- hrsampledata/info.xml
- hrstaffdir/info.xml
- hrui/info.xml
- hrvisa/info.xml
- org.civicrm.bootstrapcivihr/info.xml
- org.civicrm.hremergency/info.xml
- org.civicrm.reqangular/info.xml
- uk.co.compucorp.civicrm.appraisals/info.xml
- uk.co.compucorp.civicrm.hrcore/info.xml
- uk.co.compucorp.civicrm.hrleaveandabsences/info.xml
> PCHR-1771: Update release date

- uk.co.compucorp.civicrm.hrleaveandabsences/xml/option_groups/sickness_reason_install.xml
This PR creates Sickness reason option groups.
The initial options are: 
- Accident
- Appointment
- Backache
- Cold/Flu
- Food Poisoning
- Gastric upset
- Headache
- Infectious disease
- Migraine
- Minor Operation
- Stress
For each option, the value is sequential, starting with 1 for Accident. The name is the option label in snake case (e.g. "Food Poisoning" -> food_poisoning)
> PCHR-1378: Created Sickness reason option group

- uk.co.compucorp.civicrm.hrleaveandabsences/xml/option_groups/leave_request_required_document_install.xml
This PR creates the Leave request required document option group.
The initial options are: 
- Self certification form required
- Back to work interview required
- Return to work form required
For each option, the value is sequential, starting with 1 for "Self certification form required". The name is the option label in snake case (e.g. self_cerification_form_required)
> PCHR-1379: Created Leave request required document option group

- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChange.php
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveBalanceChange.php
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/SicknessRequest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/LeaveRequest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Test/Fabricator/SicknessRequest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/LeaveRequest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/api/v3/SicknessRequest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveBalanceChangeTest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/SicknessRequestTest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveBalanceChangeTest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestTest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/SicknessRequestTest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/LeaveRequestTest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/SicknessRequestTest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/TOILRequestTest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/helpers/LeaveRequestHelpersTrait.php
Whenever a Leave Request gets updated, we must also update the Leave Balance Changes caused by it. This should not be the responsibility of the Leave Request BAO though. That BAO should care only about itself and its direct dependents, the Leave Request Dates. Besides that, Leave Balance Changes are also used for other purposes, like storing information about the Entitlement and expired leaves. For these reasons, it's interesting to separate this from the Leave Request BAO and try to encapsulate the logic somewhere else.
The LeaveRequest service was created to achieve this isolation. It has two methods: `create` and `delete`. The former, basically, creates the LeaveRequest using the BAO's `create` method, and then uses the `LeaveRequest::calculateBalanceChange` method in order to get the …
> PCHR-1681: Create/Delete LeaveBalanceChange related to Leave and Sickness Requests

- uk.co.compucorp.civicrm.hrleaveandabsences/views/manager-leave/components/manager-leave-requests.html
- uk.co.compucorp.civicrm.hrleaveandabsences/views/my-leave/components/my-leave-report.html
This PR (and https://github.com/compucorp/civihr-employee-portal-theme/pull/127)contains the markup for the Manager Dashboard page,
**Screencast**
**Note**: Button styles changes for My Leave Report Page to keep consistency with manager page
> PCHR-1797: Manager Dashboard Markup

- uk.co.compucorp.civicrm.hrleaveandabsences/views/manager-leave/components/manager-leave.html
- uk.co.compucorp.civicrm.hrleaveandabsences/views/my-leave/components/my-leave.html
The **Record Sickness** and **Record Overtime** has been added to the `MyLeave` and `ManagerLeave` page.
> PCHR-1797: Add Sickness and Overtime button

- uk.co.compucorp.civicrm.hrcomments/LICENSE.txt
- uk.co.compucorp.civicrm.hrcomments/README.md
- uk.co.compucorp.civicrm.hrcomments/hrcomments.civix.php
- uk.co.compucorp.civicrm.hrcomments/hrcomments.php
- uk.co.compucorp.civicrm.hrcomments/info.xml
This PR creates the uk.co.compucorp.civicrm.hrcomments extension. This is just the first commit for this extension and it only contains the basic skeletal extension structure.
This extension will provide commenting functionality for any CiviHR entity. It will eventually provide some API's that other entities can use to access the commenting functionality
> PCHR-1866:  Create HR Comments extension

- com.civicrm.hrjobroles/info.xml
- contactaccessrights/info.xml
- contactsummary/info.xml
- hrabsence/info.xml
- hrbank/info.xml
- hrcareer/info.xml
- hrcase/info.xml
- hrdemog/info.xml
- hrident/info.xml
- hrim/info.xml
- hrjobcontract/info.xml
- hrmed/info.xml
- hrprofile/info.xml
- hrqual/info.xml
- hrrecruitment/info.xml
- hrreport/info.xml
- hrstaffdir/info.xml
- hrui/info.xml
- hrvisa/info.xml
- org.civicrm.bootstrapcivihr/info.xml
- org.civicrm.hremergency/info.xml
- org.civicrm.reqangular/info.xml
- uk.co.compucorp.civicrm.appraisals/info.xml
- uk.co.compucorp.civicrm.hrcore/info.xml
- uk.co.compucorp.civicrm.hrleaveandabsences/info.xml
- uk.co.compucorp.civicrm.hrsampledata/info.xml
> PCHR-1772: Bump version to 1.6.5

- com.civicrm.hrjobroles/info.xml
- contactaccessrights/info.xml
- contactsummary/info.xml
- hrabsence/info.xml
- hrbank/info.xml
- hrcareer/info.xml
- hrcase/info.xml
- hrdemog/info.xml
- hrident/info.xml
- hrim/info.xml
- hrjobcontract/info.xml
- hrmed/info.xml
- hrprofile/info.xml
- hrqual/info.xml
- hrrecruitment/info.xml
- hrreport/info.xml
- hrstaffdir/info.xml
- hrui/info.xml
- hrvisa/info.xml
- org.civicrm.bootstrapcivihr/info.xml
- org.civicrm.hremergency/info.xml
- org.civicrm.reqangular/info.xml
- uk.co.compucorp.civicrm.appraisals/info.xml
- uk.co.compucorp.civicrm.hrcore/info.xml
- uk.co.compucorp.civicrm.hrleaveandabsences/info.xml
- uk.co.compucorp.civicrm.hrsampledata/info.xml
To the 1.6.5 release date, 2017-01-16
> PCHR-1874: Update release date

- hrjobcontract/CRM/Hrjobcontract/Import/Parser/Api.php
- hrjobcontract/tests/phpunit/CRM/Hrjobcontract/Import/Parser/ApiTest.php
On import, use of empty hours amount or "casual" hours type was causing FTE values to be calculated as 1/1.  Expected result for wither empty hours or Casual hours type is 0/0 FTE.
As it turned out, default values for FTE values in database are 1.  On import, if hours amount was empty (""), no values were being set on insert query, thus using default values of 1 and hence calculating a 1/1 FTE.
Added check to see if "Casual" hours type is being used on job contract import.  If either "Casual" type  or empty "Hours Amount" is used on import, FTE values are set to 0.
> PCHR-1412: Set FTE Values as 0 when Casual Type is Used on Import

- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/api/v3/ApiPermissionTest.php
This PR removes unnecessary code in the API Permissions test.
> PCHR-1895: Code Optimization

- com.civicrm.hrjobroles/info.xml
- contactaccessrights/info.xml
- contactsummary/info.xml
- hrabsence/info.xml
- hrbank/info.xml
- hrcareer/info.xml
- hrcase/info.xml
- hrdemog/info.xml
- hrident/info.xml
- hrim/info.xml
- hrjobcontract/info.xml
- hrmed/info.xml
- hrprofile/info.xml
- hrqual/info.xml
- hrrecruitment/info.xml
- hrreport/info.xml
- hrstaffdir/info.xml
- hrui/info.xml
- hrvisa/info.xml
- org.civicrm.bootstrapcivihr/info.xml
- org.civicrm.hremergency/info.xml
- org.civicrm.reqangular/info.xml
- uk.co.compucorp.civicrm.appraisals/info.xml
- uk.co.compucorp.civicrm.hrcore/info.xml
- uk.co.compucorp.civicrm.hrleaveandabsences/info.xml
- uk.co.compucorp.civicrm.hrsampledata/info.xml
> PCHR-1947: Bump version

- org.civicrm.bootstrapcivicrm/scss/civicrm/contact/_contact.scss
- org.civicrm.bootstrapcivicrm/scss/civicrm/contact/pages/_memberships.scss
Style contact memberships page 
BEFORE: 
AFTER:
> Ai-23: Contacts membership tabs

- uk.co.compucorp.civicrm.hrleaveandabsences/views/manager-leave/components/manager-leave-calendar.html
This PR contains the static HTML for the Manager Calendar page.
> PCHR-1800: Manager calendar static page

- org.civicrm.bootstrapcivicrm/bootstrapcivicrm.php
Remove the `enable-select2.js` file from the statement to works on every page.
> AI-18: Style select fields

- uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/directives/leave-request-popup.html
This PR(and https://github.com/compucorp/civihr-employee-portal-theme/pull/143) contains the HTML for comments section
**Mock:** https://projects.invisionapp.com/share/WX71LBMPJ#/screens/160513467
**Additions**
`leave-request-comment` component created with the following subcomponents
- `chr_leave-request-comment__meta`
- `chr_leave-request-comment__author`
- `chr_leave-request-comment__date`
- `chr_leave-request-comment__text`
**Screenshot**
> PCHR-1420: Comments Static Html

- hrcase/CRM/HRCase/Upgrader.php
- hrcase/CRM/HRCase/Upgrader/Base.php
- hrcase/hrcase.civix.php
- hrcase/hrcase.php
installing hrcase extension causing an error because the maanged entity handler was trying to create (Exiting) case type which is an already existing case type created by 1402 upgrader .
I've moved running upgraders to postInstall method where I can control weather to create or update the case type .. since the managed entity handler runs before postInstall method and 'Exiting' case type will not be there .
> PCHR-459: Fixing hrcase installation error

- hrjobcontract/CRM/Hrjobcontract/BAO/HRJobContract.php
- hrjobcontract/CRM/Hrjobcontract/BAO/HRJobContractRevision.php
- hrjobcontract/CRM/Hrjobcontract/DAO/HRJobHealth.php
- hrjobcontract/CRM/Hrjobcontract/ExportImportValuesConverter.php
- hrjobcontract/CRM/Hrjobcontract/Import/Parser/Api.php
- hrjobcontract/CRM/Hrjobcontract/Import/Parser/BaseClass.php
- hrjobcontract/CRM/Hrjobcontract/Report/Form/Summary.php
- hrjobcontract/CRM/Hrjobcontract/SelectValues.php
- hrjobcontract/CRM/Hrjobcontract/Upgrader.php
- hrjobcontract/tests/phpunit/CRM/Hrjobcontract/Import/Parser/ApiTest.php
- hrjobcontract/views/contractSummary.html
- uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Test/Fabricator/OptionValue.php
Insurance plan types were hardcoded and were not manageable from UI.
Included ugrade to create option group and option values for insurance plan types. Also, changed implementation of CRM_Hrjobcontract_SelectValues::planType() method to obtain values from option values in database.
> PCHR-1858: Implement Management of Insurance Plan Types

- com.civicrm.hrjobroles/info.xml
- contactaccessrights/info.xml
- contactsummary/info.xml
- hrabsence/info.xml
- hrbank/info.xml
- hrcareer/info.xml
- hrcase/info.xml
- hrdemog/info.xml
- hrident/info.xml
- hrim/info.xml
- hrjobcontract/info.xml
- hrmed/info.xml
- hrprofile/info.xml
- hrqual/info.xml
- hrrecruitment/info.xml
- hrreport/info.xml
- hrstaffdir/info.xml
- hrui/info.xml
- hrvisa/info.xml
- org.civicrm.bootstrapcivihr/info.xml
- org.civicrm.hremergency/info.xml
- org.civicrm.reqangular/info.xml
- uk.co.compucorp.civicrm.appraisals/info.xml
- uk.co.compucorp.civicrm.hrcore/info.xml
- uk.co.compucorp.civicrm.hrleaveandabsences/info.xml
- uk.co.compucorp.civicrm.hrsampledata/info.xml
> PCHR-1958: Bump version

- uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/directives/leave-request-popup.html
The html is implemented for the files tab of leave request popup. 
Attached is the screenshot of the same
> PCHR-1425: Implement html for files tab

- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/DAO/ContactWorkPattern.php
- uk.co.compucorp.civicrm.hrleaveandabsences/sql/auto_install.sql
- uk.co.compucorp.civicrm.hrleaveandabsences/xml/schema/CRM/HRLeaveAndAbsences/ContactWorkPattern.xml
This PR adds the change_reason field to the ContactWorkPattern Entity. 
The change_reason field has a pseudoconstant to the "Job Contract Revision Change Reason" Option Group.
> PCHR-2013: Add change_reason field to ContactWorkPattern Entity.

- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Page/Dashboard.php
- uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/Dashboard.tpl
- uk.co.compucorp.civicrm.hrleaveandabsences/xml/Menu/hrleaveandabsences.xml
This PR adds the Dashboard page to L&A extension.
> PCHR-2029: Add dashboard page

- com.civicrm.hrjobroles/info.xml
- contactaccessrights/info.xml
- contactsummary/info.xml
- hrabsence/info.xml
- hrbank/info.xml
- hrcareer/info.xml
- hrcase/info.xml
- hrdemog/info.xml
- hrident/info.xml
- hrim/info.xml
- hrjobcontract/info.xml
- hrmed/info.xml
- hrprofile/info.xml
- hrqual/info.xml
- hrrecruitment/info.xml
- hrreport/info.xml
- hrstaffdir/info.xml
- hrui/info.xml
- hrvisa/info.xml
- org.civicrm.bootstrapcivihr/info.xml
- org.civicrm.hremergency/info.xml
- org.civicrm.reqangular/info.xml
- uk.co.compucorp.civicrm.appraisals/info.xml
- uk.co.compucorp.civicrm.hrcore/info.xml
- uk.co.compucorp.civicrm.hrleaveandabsences/info.xml
- uk.co.compucorp.civicrm.hrsampledata/info.xml
> PCHR-2043: Bump version

- uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/request-modal/details/sickness.html
As part of this PR style fixes has been done to the Sickness Modal,
**Improvements**
1. HTML optimized
**Screenshot**
> PCHR-1841: Styles fixes for document

- hrjobcontract/CRM/Hrjobcontract/BAO/HRJobDetails.php
- hrjobcontract/CRM/Hrjobcontract/DAO/Base.php
When a new contract is created for a contact and there is an Absence Type with 'Must take public Holiday As Leave' set to true, The Public Holiday Leave requests for Public holidays in the future are created for that contact for the absence Type. 
The problem is that the Public Holiday Leave Requests are all being created with zero balance change amounts rather than the amount being derived from the work pattern that is being used by the contact. This issue is observed for contacts using the default Work Pattern.
To calculate the amount to be deducted for the public holiday leave requests, The work pattern used by the contact and the effective start date of the Work pattern or start date of the job contract revision of the contact in the case of the contact using the default work pattern …
> PCHR-1197: Fix issues with Public Holiday Leave Request Balance changes when a new Contract is created

- uk.co.compucorp.civicrm.hrcore/backstop_data/casper_scripts/ssp-leave-absences/manager/leave-requests-of-staff-edit-sickness.js
- uk.co.compucorp.civicrm.hrcore/backstop_data/scenarios/ssp-la-manager-leave-requests.json
- uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/controllers/request-ctrl.js
- uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/request-modal/details/leave.html
- uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/request-modal/details/sickness.html
Allow manager to edit all in sickness requests
Backstopjs test case is added to display sickness request by manager
---
> PCHR-2167: Allow manager to edit all in sickness requests

- uk.co.compucorp.civicrm.hrleaveandabsences/managed_entities/EmailTemplate.mgd.php
> PCHR-2198: Fix syntax error

- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php
If you accrue TOIL as a staff and your manager approves it and saves it. Then maybe the manager thinks he made a mistake and changes the status back to 'Information Requested' and tries updating the TOIL request or even tries to update the value of the TOIL accrued, An error appears that 'The TOIL amount plus all approved TOIL for current period is greater than the maximum for this Absence Type'.
To illustrate the Bug, consider the following table showing TOIL accrued for a contact in a given period for a particular Absence Type with max_leave_accrual of 9.
| TOIL Name  | Status | Amount Accrued |
| ------------- | ------------- | ------------- |
| TOIL A  | Approved  |4|
| TOIL B  | Approved  |3|
To accrue another TOIL called TOIL C with amount 3, the validation goes like this:
**Total …
> PCHR-2209:  Fix Issues with updating An Already Approved TOIL

- uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/directives/leave-request-popup.html
Change accure to accrue in toil request.
accrue was accure in toil request.
Fixed typo.
Changed text in html.
> PCHR-2250: Change accure to accrue

- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/PublicHoliday.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/PublicHolidayTest.php
When a Public Holiday is disabled, the Public Holiday leave requests associated with the Public Holiday remain visible in the SSP my reports page for staff.
The Public Holiday leave requests remain visible in SSP my report page for staff even after the Public Holiday has been disabled and the scheduled job ran.
The Public Holiday leave requests are removed from the SSP my report page for staff after when the Public Holiday has been disabled and the scheduled job ran.
Before only the following Public Holiday related actions add jobs to the Public Holiday Leave Requests Queue:
- Creating a Public Holiday
- Changing the dates of a Public Holiday
In this PR, toggling the status of a Public Holiday also adds a task to the Public Holiday Leave Requests Queue
> PCHR-2245: Fix issues with A Public Holiday being visible in SSP My Report when it is disabled

- uk.co.compucorp.civicrm.hrleaveandabsences/views/my-leave/components/my-leave-report.html
Hide Export to csv
Removed HTML of "Export to csv".
> PCHR-2193 Hide Export to csv

- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/WorkPattern.php
The `WorkPattern::getValuesArray` method is used internally by a few important methods in L&A (For example, the` WorkPattern::getWeeks` and, indirectly, by the `WorkPatternCalendar::get` methods). This PR optimizes the implementation of this method, and consequentially also optimizes any of the methods that use it.
The method uses a chained API call to get a WorkPattern, together with its weeks and days. Chained API calls are just a way to make multiple API calls with a single request. Internally, the 3 calls will be executed separately (i.e. One call/query to get the Work Pattern, one call/query to get the WorkWeeks and one call/query to get the WorkDays).
Besides, API calls add some overhead, as each of call has to go through the whole API layer, which does a lot of things, including …
> PCHR-2240: WorkPattern::getValuesArray optimizations

- hrui/CRM/HRUI/Upgrader.php
- hrui/CRM/HRUI/Upgrader/Steps/4704.php
Reference: https://github.com/civicrm/civihr/pull/1940
> PCHR-1687: Hotfix to fix the absolute URL problem of the Custom CSS URL

- hrjobcontract/js/test/services/contract-details_test.js
- hrjobcontract/js/test/services/contract-health_test.js
- hrjobcontract/js/test/services/contract-hour_test.js
- hrjobcontract/js/test/services/contract-leave_test.js
- hrjobcontract/js/test/services/contract-pay_test.js
- hrjobcontract/js/test/services/contract-pension_test.js
- hrjobcontract/js/test/services/contract-revision-list_test.js
As part of this PR, some test cases of services in `hrjobcontract` extension, were unnecessary form previous changes. Those test cases have been removed, and tests have been renamed for better readability.
> PCHR-2317: Remove unnecessary test cases for hrjobcontract services

- uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/models/instances/work-pattern-instance.js
- uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/shared/models/work-pattern-model.js
- uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/mocks/apis/work-pattern-api-mock.js
- uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/models/instances/work-pattern-instance_test.js
- uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/test/shared/models/work-pattern-model_test.js
As part of this PR the following `WorkPattern` Model and `WorkPatternInstance`is created.
1. `WorkPattern`Model Usage
**assignWorkPattern()**
```javascript
WorkPattern.assignWorkPattern(<contactId>, <workPatternID>, <effectiveDate>, <effectiveEndDate>, <changeReason>, <params>);
```
**default()**
```javascript
WorkPattern.default(<params>);
```
**workPatternsOf()**
```javascript
WorkPattern.workPatternsOf(< contactId >, <params>);
```
2. `WorkPatternInstance` - Its an extension of the `ModelInstance`.
---
> PCHR-2014: Work Pattern Model+Instance

- hrreport/CRM/HRReport/Form/Activity/HRAbsenceDates.php
We need to add more columns to a the Absence dates report so that a leave request can be created from single row rather than aggregating the information for creating the request from all the child activities.
Also Fixed an issue with the Report not displaying the Contact ID of the Absence Request in the case where an Admin creates a Request on behalf of the contact, It displays the Contact ID of the Admin rather than that of the Contact.
Start Date, End Date and Total Qty columns were added.
The Contact ID is correctly displayed when an Admin creates an Absence request on behalf of a contact.
> PCHR-2336: Modify Absence Dates Report

- uk.co.compucorp.civicrm.hrcore/backstop_data/casper_scripts/ssp/dashboard-open-calendar.js
- uk.co.compucorp.civicrm.hrcore/backstop_data/casper_scripts/ssp/dashboard-request-toil-date.js
- uk.co.compucorp.civicrm.hrcore/backstop_data/casper_scripts/ssp/dashboard-request-toil.js
- uk.co.compucorp.civicrm.hrcore/backstop_data/casper_scripts/ssp/hr-resources-see-resources.js
- uk.co.compucorp.civicrm.hrcore/backstop_data/casper_scripts/ssp/vacancies-more-details.js
- uk.co.compucorp.civicrm.hrcore/backstop_data/page-objects/ssp/dashboard.js
- uk.co.compucorp.civicrm.hrcore/backstop_data/page-objects/ssp/hr-resources.js
- uk.co.compucorp.civicrm.hrcore/backstop_data/page-objects/ssp/vacancies.js
- uk.co.compucorp.civicrm.hrcore/backstop_data/scenarios/ssp-dashboard.json
- uk.co.compucorp.civicrm.hrcore/backstop_data/scenarios/ssp-hr-resources.json
- uk.co.compucorp.civicrm.hrcore/backstop_data/scenarios/ssp-hr-vacancies.json
- uk.co.compucorp.civicrm.hrcore/backstop_data/scenarios/ssp-manager-absence-approval.json
As part of this PR, few more Backstop JS tests for SSP has been added.
Backstop tests for the Pivot table of the Report section is pending as casper script is not registering the click event for the tab.
**SSP - Manager Absence Approval**
**SSP - HR Vacancies - More Details**
**SSP - HR Resources - See Resources**
**SSP - Dashboard- Request TOIL**
**SSP - Dashboard- Request TOIL Date**
**SSP - Dashboard- Open Calendar**
> PCHR-2417: More SSP backstop tests

- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Import/Parser/Base.php
When Importing Leave Requests and the date format in the CSV is modified to another format apart from `Y-m-d` e.g `d/m/Y` , There are some inconsistencies in the date validation function and an error is reported for some of the Leave requests saying that the dates are Invalid.
The core PHP DateTime class is used to validate dates in the CSV to be imported but for one reason or the other, a parse error is thrown for some dates e.g `20/09/2016` cannot be parsed while `03/11/2016` can be parsed by DateTime. `Caught exception: DateTime::__construct(): Failed to parse time string (20/09/2016)`
This PR switches to using the Date Format radio button field on the Upload Data page so as to allow the user uploading the CSV to specify the date format in the CSV. If the date format does not match …
> PCHR-2437: Fix error When importing Leave Request with some Date Formats

- hrui/hrui.civix.php
- hrui/hrui.php
- hrui/templates/CRM/common/footer.tpl
Update the footer details, and create new "Help" and "Developer" menu in CiviCRM and hide the support menu.
Support is not hidden and Help and Developer menu are absent.
Footer has more info with links:
Support is hidden and Help and Developer menu are present.
Footer has less links and information:
Modify "/civihr/hrui/hrui.php" file to Hide "Suppot" menu and "Help" and "developer" Menu
1. Disable "Support menu"
```php
/**
* Changes to some core menu items
*
*/
function _hrui_coreMenuChanges(&$params) {
...
$supportNavId = CRM_Core_DAO::getFieldValue('CRM_Core_DAO_Navigation', 'Support', 'id', 'name');
unset($params[$supportNavId]);
...
}
```
2.Add help and Developer menu using _navigationMenu hook.
```php
function hrui_civicrm_navigationMenu(&$menu) {
...
_createHelpMenu($menu); …
```
> PCHR-2358: Update help links

- hrjobcontract/views/modalForm.html
After merge https://github.com/civicrm/civihr/commit/f64016f48fa3bc4de9ba240d77fcccd842ca0aad Job Contract Modal broke. This PR fixes this issue.
After merge https://github.com/civicrm/civihr/commit/f64016f48fa3bc4de9ba240d77fcccd842ca0aad conflicts for the Job Contract Modal were not resolved. That caused it to break.
This commit was also considered in this PR https://github.com/civicrm/civihr/commits/la-milestone-3/hrjobcontract/views/modalForm.html
Only manual testing was performed.
It was checked that there are no left conflicts:
---
> PCHR-2353: Fix conflicts that were not resolved after merge

- hrjobcontract/js/test/controllers/contract_test.js
- hrjobcontract/js/test/services/contract-details_test.js
- hrjobcontract/js/test/services/contract-health_test.js
- hrjobcontract/js/test/services/contract-hour_test.js
- hrjobcontract/js/test/services/contract-leave_test.js
- hrjobcontract/js/test/services/contract-pay_test.js
- hrjobcontract/js/test/services/contract-pension_test.js
This PR fixes a few issues with HR Job Contracts tests. Some tests were passing without actually running their expectations.
This PR is part of a series of fixes first introduced in [https://github.com/civicrm/civihr/pull/2089](https://github.com/civicrm/civihr/pull/2089) for staging. These fixes are specifics to 1.7.
Naming conventions were not applied as to keep the PR short and simple.
---
> PCHR-2478: Fix HR Job Contracts tests

- hrreport/CRM/HRReport/Form/Activity/HRAbsenceDates.php
Sometimes for one reason or the other, The status of an absence request on the Absence dates report is different from the status of that same absence request on the Absence list view for a contact. For example the absence dates of an absence request can have the status Rejected while the Absence itself on the absences view has the status Cancelled.
- The status of an absence request on the Absence Dates report does not match that which is displayed for the absence request on the Absence list page for the contact.
The status of the parent Absence/Activity sometimes differs from the status on the child activities, but it is the parent activity status that is most reliable as it is the one used in Absence list view.
- The PR changes the query for the Absence dates report to join to the …
> PCHR-2469: Fix issue with incorrect display of status on Absence Dates Report.

- hrcase/hrcase.php
From an old ticket it was decide that to set the date for certain "exiting" assignment activities based on a contact's notice period for a contact. The code that did this assumed that activity types "Revoke access to databases" and "Block work email ID" would always exist. 
"Revoke access to databases" does not exist in current new installations (although "Revoke access to Database" _does_) and "Block work email ID" does exist, but for the CiviTask component, instead of the expected Civicase. This leads to an exception since the call to fetch them uses `getsingle`.
From a discussion with Ruchi it was decided these activities should instead use an offset from the key date, instead of being calculated based on notice period.
A hook would try to set the activity date for certain tasks if the …
> PCHR-2136: Remove hook to set activity time based on notice period

- hrrecruitment/CRM/HRRecruitment/Upgrader.php
- hrui/CRM/Core/BAO/Navigation.php
- hrui/CRM/HRUI/Upgrader.php
- hrui/CRM/HRUI/Upgrader/Steps/4706.php
- hrui/hrui.php
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1008.php
We need to add icons top level menu items so they look like this at the end : 
as shown in this invisionapp mockup: https://projects.invisionapp.com/d/main#/console/11433802/251312455/preview
No icons for top-level menu items
icons added to top-level menu items
We decided to use upgraders to set the icon values in database instead of altering them via **hook_civicrm_navigationMenu**, since using **hook_civicrm_navigationMenu** will be confusing to users if they tried to change the icons from UI since the **hook_civicrm_navigationMenu** will keep reverting them each time the cache get cleared.
1- **Search**, **Staff** (Contacts), and **Configs** (Administer ) icons are added by defining a new upgrader inside hrui extension.
2- **Help**, and **Developer** are exceptions and their icons are …
> PCHR-2830: Adding icons to top-level menu items

- uk.co.compucorp.civicrm.hrleaveandabsences/templates/CRM/HRLeaveAndAbsences/Page/WorkPattern.hlp
This PR simply improved the text of the help message on the Work Pattern page.
----
✅ Manual Tests - passed
⏹ Jasmine Tests - omitted
⏹ JS distributive files - not needed
⏹ Backstop Tests - omitted
⏹ PHP Unit Tests - omitted
⏹ CSS distributive files - not needed
> PCHR-2812: Change help text on Work Pattern page

- hrcase/CRM/HRCase/HRCase.mgd.php
This PR changes the original word replacement of "Cases(s) -> Assignment(s)" to Cases(s) -> Workflow(s)" and does a bit of a clean up of the word replacement file
> PCHR-2638: Word replacement, Case(s) -> Workflow(s)

- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Import/Parser/Base.php
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Mail/Template/BaseRequestNotification.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Import/Parser/BaseTest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Mail/Template/LeaveRequestNotificationTemplateTest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Mail/Template/SicknessRequestNotificationTemplateTest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Mail/Template/TOILRequestNotificationTemplateTest.php
Since Leave requests can now be created in hours or in days, Some changes need to be made to the Leave request import functionality to allow leave to be imported in hours.
- Leave in hours cannot be imported
- Leave in hours can be imported
- When leave requests in hours are to be imported, the `from_date_amount` and `to_date_amount` fields required by the LeaveRequest BAO create method are set to zero. 
- The start time is set to 00:00 and end time to be 23:59 when importing leave in days.
- The validation error message for validateEntitlementAndBalanceChange is modified to indicate whether it is in days or hours based on the Absence Type calculation unit in `validateEntitlementAndBalanceChange` method of the `CRM_HRLeaveAndAbsences_Import_Parser_Base` class.
- The …
> PCHR-2888: Modify Leave Request Import Functionality For Leave in Hours

- uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
- uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1005.php
- uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1006.php
A new scheduled job to send statistics will be added.
There was no scheduled job for "CiviHR Update Check"
A new job will be added with the name "CiviHR Update Check". It will make an API call to `Job.check_civihr_version`
`civilint` errors in the Upgrader.php file were also fixed in this PR
> PCHR-3030: Scheduled Job to Send Statistics

- uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1006.php
This PR fixes issues that came up during the testing of the ping back feature.
The description had a mistake, "to to", and was out-of-date
The description mistake was corrected, and it was updated to match the description in the specs
> PCHR-3201: QA Fixes

- uk.co.compucorp.civicrm.hrcore/backstop_data/casper_scripts/ssp/tasks-create-new-task.js
- uk.co.compucorp.civicrm.hrcore/backstop_data/casper_scripts/ssp/tasks-show-completed-tasks.js
- uk.co.compucorp.civicrm.hrcore/backstop_data/page-objects/ssp/tasks.js
- uk.co.compucorp.civicrm.hrcore/backstop_data/scenarios/ssp-tasks.json
This PR adds missing Backstop tests for SSP tasks page.
> PCHR-3202: SSP Tasks backstop tests

- com.civicrm.hrjobroles/info.xml
- contactaccessrights/info.xml
- contactsummary/info.xml
- hrabsence/info.xml
- hrbank/info.xml
- hrcareer/info.xml
- hrcase/info.xml
- hrdemog/info.xml
- hrim/info.xml
- hrjobcontract/info.xml
- hrmed/info.xml
- hrprofile/info.xml
- hrqual/info.xml
- hrrecruitment/info.xml
- hrreport/info.xml
- hrstaffdir/info.xml
- hrui/info.xml
- org.civicrm.bootstrapcivihr/info.xml
- org.civicrm.hremergency/info.xml
- org.civicrm.reqangular/info.xml
- uk.co.compucorp.civicrm.appraisals/info.xml
- uk.co.compucorp.civicrm.hrcomments/info.xml
- uk.co.compucorp.civicrm.hrcore/info.xml
- uk.co.compucorp.civicrm.hremails/info.xml
- uk.co.compucorp.civicrm.hrleaveandabsences/info.xml
- uk.co.compucorp.civicrm.hrsampledata/info.xml
Bump the version number to 1.7.3
> PCHR-3232: Bump version number

- uk.co.compucorp.civicrm.hrcore/backstop_data/casper_scripts/ssp/tasks-create-new-task.js
- uk.co.compucorp.civicrm.hrcore/backstop_data/casper_scripts/ssp/tasks-show-completed-tasks.js
- uk.co.compucorp.civicrm.hrcore/backstop_data/page-objects/ssp/tasks.js
- uk.co.compucorp.civicrm.hrcore/backstop_data/scenarios/ssp-tasks.json
- uk.co.compucorp.civicrm.hrcore/gulp/tasks/backstopjs.js
This PR is a combination of
https://github.com/civicrm/civihr/pull/2426
The content of this PR has been already approved.
Support for Super admin credentials has been added to Backstop, and as `SSP - Tasks - Create new tasks` scenario updated with `super-admin` credential as the Create New button is visible only for Super Admin.
> PCHR-3062: SSP Tasks Backstop Scenarios

- uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Form/CreateUserRecordTaskForm.php
This PR updates the role names to the new names after the changes made in [ #435](https://github.com/compucorp/civihr-employee-portal/pull/435)
The role names were not updated.
The role names are updated in files that are still using the old name for the updated roles.
> PCHR-3071: Update Role names

- contactaccessrights/views/access-rights-modal.html
This PR simply updates the text of the Manage Rights modal
> PCHR-3134: Update Manage Rights modal text

- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1018.php
- uk.co.compucorp.civicrm.hrleaveandabsences/views/shared/components/leave-calendar-day.html
https://github.com/civicrm/civihr/pull/2451 was accidentally merged (then Staging was reverted). This PR contains same changes as https://github.com/civicrm/civihr/pull/2451.
> PCHR-3251: Upgrader for single day requests in hours

- uk.co.compucorp.civicrm.hrleaveandabsences/views/absence-tab/components/absence-tab-custom-work-pattern-modal.html
This PR fixes the spelling error on create work pattern form.
> PCHR-3264: Fix work pattern modal spelling

- uk.co.compucorp.civicrm.hrcore/CRM/HRCore/CMSData/Role/DrupalRoleService.php
When sending stats to civihr.org we send most recent login data. This data uses the role name as an index. When role name is changed, as they were in https://github.com/compucorp/civihr-employee-portal/pull/435, the server does not know which roles are the "base" roles (civihr_admin, civihr_staff, civihr_manager & civihr_local_admin). To avoid problems like this when role name is changes we will use role machine name.
The stats request used role names as an index for most recent login data
```json
{
"siteUrl": "https://civihr-staging.civihrhosting.co.uk/",
"siteName": "CiviHR Staging site",
"generationDate": "2018-03-28T13:05:17+0000",
"lastLoginByRole": {
"administrator": "2018-03-28T13:03:44+0000",
"HR Admin": "2018-03-28T12:55:13+0000",
"Staff": "2018-03-28T06:46:23+0000",
"Manager": …
```
> PCHR-3509: Use Role Machine Names Instead of Role Names

- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Service/LeaveRequestRights.php
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader.php
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1020.php
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1021.php
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1022.php
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1023.php
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1024.php
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Upgrader/Step/1025.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestRightsTest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Service/LeaveRequestTest.php
After merging staging into the PCHR-3162 epic branch one upgrader had the same name. To accommodate this upgrader all those added in this feature were renamed with an incremented version number.
Staging and the epic branch were out of sync. There was a conflict of upgrader number.
Staging is merged into the epic branch. There is no upgrader conflict.
> PCHR-3162: Resolve Merge Conflict

- Jenkinsfile
This PR updates the `Jenkinsfile` to add support for sending notifications to Slack channels, in preparation for our migration from HipChat to slack
HipChat notifications support is kept so that this PR can be safely merged even before the migration
The [HipChat Plugin](https://wiki.jenkins.io/display/JENKINS/HipChat+Plugin) for Jenkins allowed the use of several tokens that the notifications relied on. As those tokens were not available in the [Slack Plugin](https://github.com/jenkinsci/slack-plugin), replacements had to be found when possible
Thanks to the [BlueOcean Display Url Plugin](https://wiki.jenkins.io/display/JENKINS/BlueOcean+Display+URL+Plugin), a `RUN_DISPLAY_URL` env variable is available, which does the same job as the `BLUE_OCEAN_URL` token
**HipChat**
```groovy
'Click <a …
```
> PCHR-3592: Add slack notifications to Jenkins

- uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
- uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1016.php
This PR is a compilation of the following changes:
* PCHR-3411: https://github.com/civicrm/civihr/pull/2554
This PR is the same as https://github.com/civicrm/civihr/pull/2591 but it removes commits from PCHR-3469 (https://github.com/civicrm/civihr/pull/2563 and https://github.com/civicrm/civihr/pull/2583). Please refer to https://github.com/compucorp/civihr-tasks-assignments/pull/354 for more information.
> PCHR-3369: Tasks and Workflows UX improvements

- com.civicrm.hrjobroles/info.xml
- contactaccessrights/info.xml
- contactsummary/info.xml
- hrbank/info.xml
- hrcareer/info.xml
- hrcase/info.xml
- hrdemog/info.xml
- hrim/info.xml
- hrjobcontract/info.xml
- hrmed/info.xml
- hrprofile/info.xml
- hrqual/info.xml
- hrrecruitment/info.xml
- hrreport/info.xml
- hrstaffdir/info.xml
- hrui/info.xml
- org.civicrm.bootstrapcivihr/info.xml
- org.civicrm.hremergency/info.xml
- org.civicrm.reqangular/info.xml
- uk.co.compucorp.civicrm.hrcomments/info.xml
- uk.co.compucorp.civicrm.hrcontactactionsmenu/info.xml
- uk.co.compucorp.civicrm.hrcore/info.xml
- uk.co.compucorp.civicrm.hremails/info.xml
- uk.co.compucorp.civicrm.hrleaveandabsences/info.xml
- uk.co.compucorp.civicrm.hrsampledata/info.xml
Update release date and bump version to 1.7.6
> PCHR-3638: Bump ext version

- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/BAO/LeaveRequest.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/BAO/LeaveRequestTest.php
This PR fixes the following issues:
1) You should NOT be able to add a leave request in Hours and then add a leave request in days for the same day.
2) You should be able to create Hours TOIL Accrual after Days TOIL Accrual
When checking for existing AM/PM it should not care about requests in hours.
TOIL should not care about neither requests types, not units. It should care only about dates/times of TOIL requests.
----
PHP tests augmented and passed
> PCHR-3580: Fix bugs for multimple request per day

- uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader.php
- uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1021.php
Changed the order of default gender options
> PCHR-3604: Change Order Of Gender Options

- uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/link-modal/components/calendar-feeds-link-modal.html
- uk.co.compucorp.civicrm.hrleaveandabsences/js/angular/src/leave-absences/calendar-feeds/link-modal/directives/input-with-copy-button.html
This PR makes the Feed Link Modal mobile friendly.
`col-xs-*` -> `col-sm-*`
And `form-group` classes for gaps.
----
Tested manually.
> PCHR-3947: Make Feed Link Modal mobile friendly

- uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/PageRun/RelationshipTypesFilter.php
- uk.co.compucorp.civicrm.hrcore/hrcore.php
Hides disabled relationship types from non-root admins.
> PCHR-3602 Hides disabled relationship Types from non-root admins

- org.civicrm.bootstrapcivihr/scss/mixins/_spinner.scss
This PR simply applies the new variable from https://github.com/compucorp/org.civicrm.shoreditch/pull/118
---
> PCHR-3424: Apply images path variable

- hrui/hrui.php
PR is a copy of https://github.com/compucorp/civihr/pull/2809. Only changed the base forked to compucorp/civihr.
> SHOR-22: Remove extra PHP code for appending contact image - covered under shoreditch

- com.civicrm.hrjobroles/CRM/Hrjobroles/BAO/Query.php
Filtering contacts in advanced search by `Job Role`, without specifying any date result in contacts whose job role is no longer active. This PR fixes the issue by ensuring the job role start date is less or equal to current date while the end date is greater or equal to current date or NULL.
Filtering contact by job role returns record whose job role is inactive with reference to its start and end date whenever start and or end date range criteria is not specified.
Filtering contact by job role without specifying any date filter now returns contacts whose job role is active
When searching contacts record, check was carried out to see if job role filtering was used and if job roles start and end date are put into consideration.
```
if (!$filterJobRoleByDate && strpos($param[0], 'date')) { …
```
> PCHR-4075: Fix Filters on Admin - Advanced Search - Job Role Filters

- uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Upgrader/Steps/1031.php
This PR fixes the upgraders for case type categorization. It adds back an upgrader that was removed by mistake and removes another that has been moved to Tasks and Assignment. The reason for the later is explained here:
https://github.com/compucorp/civihr-tasks-assignments/pull/407
There are two relevant upgraders on this PR:
* The upgrader to add default assignee options: was removed by mistake
* The upgrader to create a custom category field for workflow types: which should be removed from HRCore and moved back to Tasks and Workflows.
Removing the default assignee options upgrader was caused by syncing with staging and not fixing the conflicts the right way. The upgrader was added back as the last upgrader for HRCore, `CRM_HRCore_Upgrader_Steps_1031`. This upgrader was being used for …
> PCHR-4050: Fix Case Type Category upgraders

- com.civicrm.hrjobroles/CRM/Hrjobroles/BAO/Query.php
- hrjobcontract/CRM/Hrjobcontract/BAO/Query.php
This PR changes the multiple select fields from Job Contract and Job Roles to use select2 plugin on Advanced Search(Staff Directory)
These fields used normal Multiple select box field
These fields are using select2 in multiple select box fields
> PCHR-4068: Improve Job Contract and Job Roles Filter Fields

- uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Hook/PreProcess/ContactForm.php
- uk.co.compucorp.civicrm.hrcore/config/menu/main.php
- uk.co.compucorp.civicrm.hrcore/hrcore.php
As part of the requirements of the Staff Menu Improvements epic, this PR modifies the Staff menu sub Items.
- The staff menu sub Items was not changed.
- The page title of the Add New Individual Page is 'New Individual'
After the changes, the staff menu has the following sub menu Items:
- Add New Staff Member (url: /civicrm/contact/add?reset=1&ct=Individual)
- Staff Directory (url: /civicrm/contact/search/advanced?reset=1)
**Record Communication (section heading)**
- New email (url: civicrm/activity/email/add?atype=3&action=add&reset=1&context=standalone)
- New meeting (url: civicrm/activity?reset=1&action=add&context=standalone)
The page title of the Add New Staff Member was also modified from 'New Individual' to 'New Staff'
The `hrcore_civicrm_alterMenu` hook should have sufficed to …
> PCHR-4303: Modify Staff Menu Items

- com.civicrm.hrjobroles/info.xml
- contactaccessrights/info.xml
- contactsummary/info.xml
- hrbank/info.xml
- hrcareer/info.xml
- hrcase/info.xml
- hrim/info.xml
- hrjobcontract/info.xml
- hrmed/info.xml
- hrprofile/info.xml
- hrqual/info.xml
- hrreport/info.xml
- hrstaffdir/info.xml
- hrui/info.xml
- org.civicrm.bootstrapcivihr/info.xml
- org.civicrm.hremergency/info.xml
- org.civicrm.reqangular/info.xml
- uk.co.compucorp.civicrm.hrcomments/info.xml
- uk.co.compucorp.civicrm.hrcontactactionsmenu/info.xml
- uk.co.compucorp.civicrm.hrcore/info.xml
- uk.co.compucorp.civicrm.hremails/info.xml
- uk.co.compucorp.civicrm.hrleaveandabsences/info.xml
- uk.co.compucorp.civicrm.hrsampledata/info.xml
> CiviHR 1.7.12

- com.civicrm.hrjobroles/info.xml
- contactaccessrights/info.xml
- contactsummary/info.xml
- hrbank/info.xml
- hrcareer/info.xml
- hrcase/info.xml
- hrim/info.xml
- hrjobcontract/info.xml
- hrmed/info.xml
- hrprofile/info.xml
- hrqual/info.xml
- hrreport/info.xml
- hrstaffdir/info.xml
- hrui/info.xml
- org.civicrm.bootstrapcivihr/info.xml
- org.civicrm.hremergency/info.xml
- org.civicrm.reqangular/info.xml
- uk.co.compucorp.civicrm.hrcomments/info.xml
- uk.co.compucorp.civicrm.hrcontactactionsmenu/info.xml
- uk.co.compucorp.civicrm.hrcore/info.xml
- uk.co.compucorp.civicrm.hremails/info.xml
- uk.co.compucorp.civicrm.hrleaveandabsences/info.xml
- uk.co.compucorp.civicrm.hrsampledata/info.xml
> CiviHR 1.7.13

- uk.co.compucorp.civicrm.hrcore/CRM/HRCore/Helper/ContactActionsMenu/WorkflowActionGroup.php
- uk.co.compucorp.civicrm.hrcore/config/menu/main.php
- uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/CreateUserRecordSingleTaskForm.tpl
- uk.co.compucorp.civicrm.hrcore/templates/CRM/HRCore/Form/CreateUserRecordTaskForm.tpl
- uk.co.compucorp.civicrm.hrcore/tests/phpunit/CRM/HRCore/Files/sample_navigation_menu.json
- uk.co.compucorp.civicrm.hrleaveandabsences/CRM/HRLeaveAndAbsences/Mail/Message.php
- uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/CRM/HRLeaveAndAbsences/Mail/MessageTest.php
This PR fixes all links in CiviHR that include AngularJS routing parameters.
This PR is related to https://github.com/compucorp/civihr-tasks-assignments/pull/435, please reall all the information there.
-----
⏹Jasmine Tests - not needed
⏹JS distributive files - not needed
⏹CSS distributive files - not needed
⏹Backstop tests - not needed
⏹PHP Unit Tests - not needed
> PCHR-4243: Fix AngularJS 1.6 router links

- package-lock.json
- uk.co.compucorp.civicrm.hrcore/package-lock.json
- uk.co.compucorp.civicrm.hrcore/package.json
> PCHR-4494: Update dependencies
